import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";

const WorkforceUiContext = createContext(null);

const EN = {
  "Canlı Operasyon":"Live Operations","Puantaj":"Attendance","Puantaj Çıktısı":"Timesheet Output","Dönem Kapanışı":"Period Close","OPEX Roster Lab":"OPEX Roster Lab","Vardiya Planı":"Shift Plan","Onay Bekleyenler":"Pending Approvals","İzin Yönetimi":"Leave Management","Depo ve Konum":"Warehouse & Location","Kural ve Tatiller":"Rules & Holidays","Cihaz Yönetimi":"Device Management","Picker Uygulaması":"Picker App",
  "Control Center":"Control Center","Yetki kontrollü":"Permission controlled","Manuel düzeltme açık":"Manual correction enabled","Müdür operasyon modu":"Manager operations mode","Dil":"Language","Tema":"Theme","Açık tema":"Light theme","Koyu tema":"Dark theme",
  "Canlı durum":"Live status","Bugünün vardiyaları":"Today's shifts","Tümünü gör":"View all","Hesaplanan puantaj":"Calculated attendance","Normal, gece ve resmî tatil saatleri":"Normal, night and public holiday hours","Excel/CSV":"Excel/CSV","Tüm depolar":"All warehouses","Manuel düzeltme yalnız Admin veya özel yetkili kullanıcı içindir.":"Manual correction is available only to Admin or explicitly authorized users.",
  "Onay akışı":"Approval flow","Onay bekleyen kayıtlar":"Records pending approval","Satır seç, sayfadakileri seç veya toplu onayla.":"Select rows, select the page or approve in bulk.","Seçilenleri onayla":"Approve selected","Tümünü onayla":"Approve all","seçili":"selected",
  "Planlama":"Planning","Vardiya planı ve toplu yükleme":"Shift plan and bulk upload","Atanmış vardiya yoksa mobil check-in endpoint’i işlemi reddeder.":"Mobile check-in is rejected when no shift is assigned.","Şablon indir":"Download template","Toplu vardiya yükle":"Bulk shift upload","Vardiya oluştur":"Create shift",
  "İzin işlemleri":"Leave operations","Çalışan izin girişleri":"Employee leave entries","Müdür izin girer; izin türünün puantaj etkisi otomatik uygulanır.":"The manager records leave; its attendance impact is applied automatically.","Time Off toplu yükle":"Bulk Time Off upload","İzin gir":"Add leave",
  "Geofence":"Geofence","Depo ve konum doğrulama":"Warehouse and location verification","Koordinat, yarıçap, GPS sapması ve opsiyonel QR ayarları.":"Coordinates, radius, GPS tolerance and optional QR settings.","Depo ekle":"Add warehouse","Toplu düzenle":"Bulk edit","Seçilen depoları düzenle":"Edit selected warehouses","Depo seç":"Select warehouse","Tümünü seç":"Select all","Seçimi temizle":"Clear selection",
  "Sürümlü yönetim":"Versioned management","Kural setleri, resmî tatiller ve izin türleri":"Rule sets, public holidays and leave types","Tüm etkiler tarihli ve değiştirilebilir.":"All effects are dated and editable.","Çalışma Kuralları":"Work Rules","Resmî Tatiller":"Public Holidays","İzin Türleri":"Leave Types","Resmî tatil ekle":"Add public holiday","İzin türü ekle":"Add leave type","Düzenle":"Edit","Aktif":"Active","Pasif":"Inactive","Resmî":"Official","Doğrulama gerekli":"Verification required",
  "Cihaz güvenliği":"Device security","Picker cihaz eşleşmeleri":"Picker device pairings","Son görülme":"Last seen","Picker mobile experience":"Picker mobile experience","Vardiya yoksa check-in yok.":"No shift, no check-in.","Picker uygulamasını aç":"Open picker app",
  "İK ve bordro":"HR and payroll","Kümülatif dönem yönetimi":"Cumulative period management","Beklenen süre yalnız atanmış vardiyalardan ve çalışanın işe giriş-çıkış aralığından hesaplanır; boş güne otomatik saat yazılmaz.":"Expected time is calculated only from assigned shifts within employment dates; blank days receive no automatic hours.","Personel Ana Veri":"Employee Master Data","Toplu İzin":"Bulk Leave","Başlangıç":"Start","Kesim tarihi":"Cutoff date","Tüm kişiler":"All employees","İK CSV":"HR CSV","Yazdır / PDF":"Print / PDF","Kapanış taslağı":"Close draft","Planlanan":"Planned","Fiili Çalışma":"Actual Work","Normal":"Normal","Resmî Tatil":"Public Holiday","Fazla Mesai":"Overtime","Gece":"Night","Eksik":"Missing","İzin":"Leave","Personel ana verisi":"Employee master data","CSV/XLSX yükle":"Upload CSV/XLSX","Time Off Used toplu yükleme":"Bulk Time Off Used upload","Time Off Excel yükle":"Upload Time Off Excel",
  "OPEX özel alan":"OPEX private area","Roster laboratuvarı ve norm analizi":"Roster lab and norm analysis","Ham kaynak değişmez. 11 saat üstü kayıtlar, izin çakışmaları ve 7,5 saat önerileri yalnız simülasyon katmanında incelenir.":"Raw source remains unchanged. Records over 11 hours, leave conflicts and 7.5-hour proposals are reviewed only in simulation.","Roster CSV yükle":"Upload roster CSV","Simülasyon CSV":"Simulation CSV","11 Saat Kontrolü":"11-Hour Check","BY / Norm Raporu":"RE / Norm Report","Regional Manager":"Regional Manager","BY / Regional Executive":"RE / Regional Executive","11 Saat Üstü":"Over 11 Hours","İzin Çakışması":"Leave Conflict","Simülasyon Düzeltmesi":"Simulation Overrides","11 saat üstü kayıtlar":"Records over 11 hours","Tümüne 7,5 saat simülasyonu":"Apply 7.5-hour simulation to all","Norm yeterli / mesai var":"Norm met / overtime exists","Norm altı":"Below norm","Dengeli":"Balanced",
  "Personel":"Employee","Depo":"Warehouse","Tarih":"Date","Saat":"Time","Durum":"Status","İşlem":"Action","Kaynak":"Source","Giriş":"Check-in","Çıkış":"Check-out","Giriş–Çıkış":"Check-in–out","Eksik / Fazla":"Missing / Overtime","Durum / Onay":"Status / Approval","Net plan":"Net plan","Ücretli":"Paid","Ücretsiz":"Unpaid","Açık":"On","Kapalı":"Off","Vazgeç":"Cancel","Kaydet":"Save","Güncelle":"Update","Şablon":"Template","Toplam":"Total","Çalışan":"Employee","Ad Soyad":"Full Name","Unvan":"Title","İşe Giriş":"Hire Date","İşe Giriş / Çıkış":"Hire / Termination","Onay":"Approval","Süre":"Duration","Yorum":"Comment","Fark":"Gap","Satır":"Rows","Fiili":"Actual","Plan":"Plan",
  "Ana Sayfa":"Home","Vardiyalarım":"My Shifts","Bildirimler":"Notifications","Profil":"Profile","Arşiv":"Archive","Bugünkü vardiya":"Today's shift","Plan ve geçmiş":"Plan and history","Tümü":"All","Tamamlandı":"Completed","Gelmedi":"Absent","Fazla":"Overtime","Vardiyayı Yönet":"Manage Shift","Vardiya Detayı":"Shift Detail","Vardiyayı Bitir":"End Shift","Molaya Çık":"Start Break","Molayı Bitir":"End Break","İtiraz / Düzeltme Talebi":"Dispute / Correction Request","Yeni bildirim yok":"No new notifications","Asıl depo":"Home warehouse","Cihaz doğrulama":"Device verification","Kayıtlı cihaz":"Registered device"
};

const DE = {
  ...EN,
  "Canlı Operasyon":"Live-Betrieb","Puantaj":"Zeiterfassung","Puantaj Çıktısı":"Stundennachweis","Dönem Kapanışı":"Periodenabschluss","Vardiya Planı":"Schichtplan","Onay Bekleyenler":"Ausstehende Freigaben","İzin Yönetimi":"Abwesenheiten","Depo ve Konum":"Lager & Standort","Kural ve Tatiller":"Regeln & Feiertage","Cihaz Yönetimi":"Geräteverwaltung","Picker Uygulaması":"Picker-App","Yetki kontrollü":"Berechtigungsgesteuert","Dil":"Sprache","Tema":"Design","Açık tema":"Helles Design","Koyu tema":"Dunkles Design",
  "Canlı durum":"Live-Status","Bugünün vardiyaları":"Heutige Schichten","Tümünü gör":"Alle anzeigen","Onay akışı":"Freigabeprozess","Seçilenleri onayla":"Auswahl freigeben","Tümünü onayla":"Alle freigeben","Planlama":"Planung","Şablon indir":"Vorlage herunterladen","Toplu vardiya yükle":"Schichten gesammelt laden","Vardiya oluştur":"Schicht erstellen","İzin işlemleri":"Abwesenheiten","İzin gir":"Abwesenheit eintragen","Depo ekle":"Lager hinzufügen","Toplu düzenle":"Stapelbearbeitung","Seçilen depoları düzenle":"Ausgewählte Lager bearbeiten","Tümünü seç":"Alle auswählen","Seçimi temizle":"Auswahl löschen","Çalışma Kuralları":"Arbeitsregeln","Resmî Tatiller":"Feiertage","İzin Türleri":"Abwesenheitsarten","Düzenle":"Bearbeiten","Aktif":"Aktiv","Pasif":"Inaktiv","Doğrulama gerekli":"Prüfung erforderlich",
  "İK ve bordro":"Personal & Entgelt","Kümülatif dönem yönetimi":"Kumulative Periodenverwaltung","Personel Ana Veri":"Mitarbeiterstammdaten","Toplu İzin":"Abwesenheiten importieren","Başlangıç":"Beginn","Kesim tarihi":"Stichtag","Tüm kişiler":"Alle Mitarbeiter","İK CSV":"HR-CSV","Yazdır / PDF":"Drucken / PDF","Kapanış taslağı":"Abschlussentwurf","Planlanan":"Geplant","Fiili Çalışma":"Ist-Arbeit","Resmî Tatil":"Feiertag","Fazla Mesai":"Überstunden","Gece":"Nacht","Eksik":"Fehlzeit","İzin":"Abwesenheit","Personel ana verisi":"Mitarbeiterstammdaten",
  "OPEX özel alan":"OPEX-Sonderbereich","Roster laboratuvarı ve norm analizi":"Roster-Labor und Sollanalyse","11 Saat Kontrolü":"11-Stunden-Prüfung","BY / Norm Raporu":"RE-/Soll-Bericht","11 Saat Üstü":"Über 11 Stunden","İzin Çakışması":"Abwesenheitskonflikt","Norm altı":"Unter Soll","Dengeli":"Ausgeglichen",
  "Personel":"Mitarbeiter","Depo":"Lager","Tarih":"Datum","Saat":"Zeit","Durum":"Status","İşlem":"Aktion","Kaynak":"Quelle","Giriş":"Kommen","Çıkış":"Gehen","Eksik / Fazla":"Fehlzeit / Mehrarbeit","Ücretli":"Bezahlt","Ücretsiz":"Unbezahlt","Vazgeç":"Abbrechen","Kaydet":"Speichern","Güncelle":"Aktualisieren","Toplam":"Gesamt","Çalışan":"Mitarbeiter","Ad Soyad":"Vor- und Nachname","Unvan":"Position","İşe Giriş":"Eintritt","Onay":"Freigabe","Süre":"Dauer","Yorum":"Kommentar","Fark":"Differenz","Fiili":"Ist","Plan":"Plan",
  "Ana Sayfa":"Start","Vardiyalarım":"Meine Schichten","Bildirimler":"Benachrichtigungen","Profil":"Profil","Arşiv":"Archiv","Bugünkü vardiya":"Heutige Schicht","Tümü":"Alle","Tamamlandı":"Abgeschlossen","Gelmedi":"Abwesend","Fazla":"Mehrarbeit","Vardiyayı Yönet":"Schicht verwalten","Vardiya Detayı":"Schichtdetails","Vardiyayı Bitir":"Schicht beenden","Yeni bildirim yok":"Keine neuen Benachrichtigungen","Asıl depo":"Stammlager","Kayıtlı cihaz":"Registriertes Gerät"
};

const AR = {
  ...EN,
  "Canlı Operasyon":"العمليات المباشرة","Puantaj":"الحضور","Puantaj Çıktısı":"كشف الدوام","Dönem Kapanışı":"إغلاق الفترة","Vardiya Planı":"خطة المناوبات","Onay Bekleyenler":"الموافقات المعلقة","İzin Yönetimi":"إدارة الإجازات","Depo ve Konum":"المستودع والموقع","Kural ve Tatiller":"القواعد والعطلات","Cihaz Yönetimi":"إدارة الأجهزة","Picker Uygulaması":"تطبيق العامل","Yetki kontrollü":"محكوم بالصلاحيات","Dil":"اللغة","Tema":"المظهر","Açık tema":"المظهر الفاتح","Koyu tema":"المظهر الداكن",
  "Canlı durum":"الحالة المباشرة","Bugünün vardiyaları":"مناوبات اليوم","Tümünü gör":"عرض الكل","Onay akışı":"مسار الموافقة","Seçilenleri onayla":"اعتماد المحدد","Tümünü onayla":"اعتماد الكل","Planlama":"التخطيط","Şablon indir":"تنزيل النموذج","Toplu vardiya yükle":"رفع المناوبات بالجملة","Vardiya oluştur":"إنشاء مناوبة","İzin işlemleri":"عمليات الإجازة","İzin gir":"إضافة إجازة","Depo ekle":"إضافة مستودع","Toplu düzenle":"تعديل جماعي","Seçilen depoları düzenle":"تعديل المستودعات المحددة","Tümünü seç":"تحديد الكل","Seçimi temizle":"مسح التحديد","Çalışma Kuralları":"قواعد العمل","Resmî Tatiller":"العطلات الرسمية","İzin Türleri":"أنواع الإجازات","Düzenle":"تعديل","Aktif":"نشط","Pasif":"غير نشط","Doğrulama gerekli":"يتطلب التحقق",
  "İK ve bordro":"الموارد البشرية والرواتب","Kümülatif dönem yönetimi":"إدارة الفترة التراكمية","Personel Ana Veri":"البيانات الأساسية للموظفين","Toplu İzin":"رفع الإجازات","Başlangıç":"البداية","Kesim tarihi":"تاريخ الإقفال","Tüm kişiler":"كل الموظفين","İK CSV":"ملف الموارد البشرية","Yazdır / PDF":"طباعة / PDF","Kapanış taslağı":"مسودة الإغلاق","Planlanan":"المخطط","Fiili Çalışma":"العمل الفعلي","Resmî Tatil":"عطلة رسمية","Fazla Mesai":"عمل إضافي","Gece":"ليلي","Eksik":"نقص","İzin":"إجازة","Personel ana verisi":"البيانات الأساسية للموظفين",
  "OPEX özel alan":"منطقة OPEX الخاصة","Roster laboratuvarı ve norm analizi":"مختبر الجدول وتحليل المعيار","11 Saat Kontrolü":"فحص 11 ساعة","BY / Norm Raporu":"تقرير المسؤول / المعيار","11 Saat Üstü":"أكثر من 11 ساعة","İzin Çakışması":"تعارض إجازة","Norm altı":"أقل من المعيار","Dengeli":"متوازن",
  "Personel":"الموظف","Depo":"المستودع","Tarih":"التاريخ","Saat":"الوقت","Durum":"الحالة","İşlem":"الإجراء","Kaynak":"المصدر","Giriş":"الدخول","Çıkış":"الخروج","Eksik / Fazla":"نقص / إضافي","Ücretli":"مدفوع","Ücretsiz":"غير مدفوع","Vazgeç":"إلغاء","Kaydet":"حفظ","Güncelle":"تحديث","Toplam":"الإجمالي","Çalışan":"الموظف","Ad Soyad":"الاسم الكامل","Unvan":"المسمى","İşe Giriş":"تاريخ التعيين","Onay":"الموافقة","Süre":"المدة","Yorum":"التعليق","Fark":"الفرق","Fiili":"فعلي","Plan":"الخطة",
  "Ana Sayfa":"الرئيسية","Vardiyalarım":"مناوباتي","Bildirimler":"الإشعارات","Profil":"الملف الشخصي","Arşiv":"الأرشيف","Bugünkü vardiya":"مناوبة اليوم","Tümü":"الكل","Tamamlandı":"مكتمل","Gelmedi":"غائب","Fazla":"إضافي","Vardiyayı Yönet":"إدارة المناوبة","Vardiya Detayı":"تفاصيل المناوبة","Vardiyayı Bitir":"إنهاء المناوبة","Yeni bildirim yok":"لا توجد إشعارات جديدة","Asıl depo":"المستودع الأساسي","Kayıtlı cihaz":"جهاز مسجل"
};

Object.assign(EN, {
  "Depoyu düzenle":"Edit warehouse","Yeni depo ekle":"Add new warehouse","Depo ve geofence":"Warehouse and geofence","Depo adı":"Warehouse name","Depo kodu":"Warehouse code","Bölge":"Region","Enlem":"Latitude","Boylam":"Longitude","Geofence yarıçapı (m)":"Geofence radius (m)","Maks. GPS sapması (m)":"Max. GPS tolerance (m)","Doğrulama":"Verification","QR opsiyonu":"QR option","Adres":"Address","Konum + cihaz":"Location + device","Konum + cihaz + QR":"Location + device + QR","Yönetici onayı":"Manager approval","Değiştirme":"No change","Toplu güncelle":"Bulk update","Boş bıraktığınız alanlar değiştirilmez. Değişiklik tüm seçili depolara audit kaydıyla uygulanır.":"Blank fields remain unchanged. Changes are applied to every selected warehouse with an audit record.",
  "Vardiyayı düzenle":"Edit shift","Yeni vardiya oluştur":"Create new shift","Vardiya planı":"Shift planning","Personel seç":"Select employee","Başlangıç":"Start","Bitiş":"End","Planlanan mola (dk)":"Planned break (min)","Görev":"Role","Bu vardiya oluşmadan ilgili gün için check-in kabul edilmez.":"Check-in is not accepted for that day until this shift exists.","Kuralı düzenle":"Edit rule","Kural adı":"Rule name","Değer (dakika)":"Value (minutes)","Seviye":"Level","Başlangıç tarihi":"Effective date","Açıklama":"Description","Resmî tatili düzenle":"Edit public holiday","Saat bazlı tatil":"Hourly holiday","Tatil adı":"Holiday name","Başlangıç saati":"Start time","Bitiş tarihi":"End date","Bitiş saati":"End time","Kapsam":"Scope","Çalışana izin gir":"Add employee leave","İzin türü":"Leave type","Süre (dakika)":"Duration (minutes)","İzin türünü düzenle":"Edit leave type","İzin adı":"Leave name","Bordro kodu":"Payroll code","Ücret durumu":"Pay status","Planlanan süreyi karşılar mı?":"Does it cover planned time?","Haftalık toplama girer mi?":"Counts toward weekly total?","Yıllık bakiyeden düşer mi?":"Deduct from annual balance?","Belge zorunlu mu?":"Document required?","Puantajı manuel düzelt":"Correct attendance manually","Yetkili işlem":"Authorized action","Düzeltme gerekçesi":"Correction reason"
});
Object.assign(DE, {
  "Depoyu düzenle":"Lager bearbeiten","Yeni depo ekle":"Neues Lager hinzufügen","Depo ve geofence":"Lager und Geofence","Depo adı":"Lagername","Depo kodu":"Lagercode","Bölge":"Region","Enlem":"Breitengrad","Boylam":"Längengrad","Geofence yarıçapı (m)":"Geofence-Radius (m)","Maks. GPS sapması (m)":"Max. GPS-Toleranz (m)","Doğrulama":"Verifizierung","QR opsiyonu":"QR-Option","Adres":"Adresse","Konum + cihaz":"Standort + Gerät","Konum + cihaz + QR":"Standort + Gerät + QR","Yönetici onayı":"Managerfreigabe","Değiştirme":"Nicht ändern","Toplu güncelle":"Stapel aktualisieren","Vardiyayı düzenle":"Schicht bearbeiten","Yeni vardiya oluştur":"Neue Schicht erstellen","Personel seç":"Mitarbeiter wählen","Başlangıç":"Beginn","Bitiş":"Ende","Planlanan mola (dk)":"Geplante Pause (Min.)","Görev":"Rolle","Kuralı düzenle":"Regel bearbeiten","Kural adı":"Regelname","Değer (dakika)":"Wert (Minuten)","Seviye":"Stufe","Başlangıç tarihi":"Gültig ab","Açıklama":"Beschreibung","Resmî tatili düzenle":"Feiertag bearbeiten","Tatil adı":"Name des Feiertags","Başlangıç saati":"Startzeit","Bitiş tarihi":"Enddatum","Bitiş saati":"Endzeit","Kapsam":"Geltungsbereich","Çalışana izin gir":"Abwesenheit eintragen","İzin türü":"Abwesenheitsart","Süre (dakika)":"Dauer (Minuten)","Ücret durumu":"Vergütung","Düzeltme gerekçesi":"Korrekturgrund"
});
Object.assign(AR, {
  "Depoyu düzenle":"تعديل المستودع","Yeni depo ekle":"إضافة مستودع جديد","Depo ve geofence":"المستودع والنطاق الجغرافي","Depo adı":"اسم المستودع","Depo kodu":"رمز المستودع","Bölge":"المنطقة","Enlem":"خط العرض","Boylam":"خط الطول","Geofence yarıçapı (m)":"نصف قطر النطاق (م)","Maks. GPS sapması (m)":"أقصى سماح GPS (م)","Doğrulama":"التحقق","QR opsiyonu":"خيار QR","Adres":"العنوان","Konum + cihaz":"الموقع + الجهاز","Konum + cihaz + QR":"الموقع + الجهاز + QR","Yönetici onayı":"موافقة المدير","Değiştirme":"دون تغيير","Toplu güncelle":"تحديث جماعي","Vardiyayı düzenle":"تعديل المناوبة","Yeni vardiya oluştur":"إنشاء مناوبة جديدة","Personel seç":"اختر الموظف","Başlangıç":"البداية","Bitiş":"النهاية","Planlanan mola (dk)":"الاستراحة المخططة (د)","Görev":"الدور","Kuralı düzenle":"تعديل القاعدة","Kural adı":"اسم القاعدة","Değer (dakika)":"القيمة (دقائق)","Seviye":"المستوى","Başlangıç tarihi":"تاريخ السريان","Açıklama":"الوصف","Resmî tatili düzenle":"تعديل العطلة الرسمية","Tatil adı":"اسم العطلة","Başlangıç saati":"وقت البدء","Bitiş tarihi":"تاريخ الانتهاء","Bitiş saati":"وقت الانتهاء","Kapsam":"النطاق","Çalışana izin gir":"إضافة إجازة للموظف","İzin türü":"نوع الإجازة","Süre (dakika)":"المدة (دقائق)","Ücret durumu":"حالة الأجر","Düzeltme gerekçesi":"سبب التصحيح"
});
Object.assign(EN, {
  "2026–2050 yenile":"Refresh 2026–2050","Atanmış vardiya doğrulandı":"Assigned shift verified","Bordro":"Payroll","Check-in yapabilir":"Check-in available","Çalışan İmzası":"Employee Signature","Depo bazlı":"By warehouse","Depo Müdürü":"Warehouse Manager","Evet":"Yes","Evet, eksik mesai üretmez":"Yes, does not create missing time","GPS sapması":"GPS tolerance","Ham mobil kayıt silinmez; öncesi/sonrası ve gerekçe audit kaydında tutulur.":"Raw mobile records are retained; before/after values and the reason are kept in the audit log.","Hayır":"No","Hayır, çalışmaya eklenmez":"No, not added to working time","İK / Bordro":"HR / Payroll","İmzaya hazır rapor":"Signature-ready report","Kişi bazlı":"By employee","Kişi seç":"Select employee","Kişi veya depo bazlı puantaj":"Attendance by employee or warehouse","Koordinat":"Coordinates","Kritik":"Critical","Mobil uygulama aktif vardiyayı sunucudan doğrular. Vardiyalarım, arşiv, mola, check-in/out ve itiraz akışı hazır.":"The mobile app verifies the active shift with the server. My Shifts, archive, breaks, check-in/out and dispute flow are available.","Mola aralığı resmî tatil/gece kesişiminden doğru şekilde düşülür.":"Break intervals are correctly deducted from public holiday and night overlaps.","Operasyon":"Operations","Otomatik":"Automatic","PUANTAJ ÇİZELGESİ":"ATTENDANCE SHEET","Resmî tatil":"Public holiday","Sert blok":"Hard block","Tarih / Plan":"Date / Plan","Vardiyanın yalnız bu zaman aralığıyla kesişen fiili çalışma dakikaları resmî tatil sayılır.":"Only actual working minutes overlapping this interval count as public holiday work.","Yarıçap":"Radius",
  "11 Saat":"11 Hours","20 saat gibi şüpheli kayıtlar otomatik olarak bordrodan silinmez. Aşağıdaki 7,5 saat işlemi yalnız test/simülasyondur ve audit kaydı üretir.":"Suspicious records such as 20 hours are not silently removed from payroll. The 7.5-hour action below is simulation-only and creates an audit record.","Aylık Puantaj CSV’sini yüklediğinde ham kayıtlar tarayıcı veritabanında tutulur ve 11 saat kontrolleri burada açılır.":"After uploading the monthly attendance CSV, raw rows are kept in the browser database and 11-hour checks appear here.","Depo / Tarih":"Warehouse / Date","Depo müdürü ve rider captain norm/headcount hesabına dahil edilmez. “Gereksiz mesai” sinyali, roster döneminde norm kadar picker görülmesine rağmen fazla mesai oluşmasıdır; nihai karar değildir.":"Warehouse managers and rider captains are excluded from norm/headcount. The unnecessary-overtime signal means overtime exists despite norm-level picker staffing; it is not a final decision.","Employee ID, TC, depo, unvan, işe giriş ve çıkış tarihleri":"Employee ID, national ID, warehouse, title, hire and termination dates","Employee Number + tarih üzerinden eşleşir; müdürün girdiği aynı kişi/gün ikinci kez eklenmez.":"Matched by Employee Number + date; a manager-entered employee/day is not duplicated.","Ham Net":"Raw Net","Hazırlayan":"Prepared by","İzin çakışması":"Leave conflict","KÜMÜLATİF DÖNEM PUANTAJI":"CUMULATIVE PERIOD ATTENDANCE","Norm":"Norm","Operasyon Onayı":"Operations Approval","Roster laboratuvarı boş":"Roster lab is empty","Roster okunuyor…":"Loading roster…","Simülasyon":"Simulation","TC kimlik numarası yetkiniz nedeniyle ilk iki ve son iki hane olarak maskeleniyor.":"The national ID is masked to the first two and last two digits due to your permissions.",
  "Aç":"Open","Atanmış depo":"Assigned warehouse","Bu ay":"This month","Bu yıla ait kayıt bulunmuyor.":"No records found for this year.","Bugünkü vardiyan ve puantaj durumun burada.":"Your shift and attendance status for today are shown here.","Çalışma":"Work","Giriş, mola ve çıkış":"Check-in, break and check-out","Görev Yeri":"Work Location","İyi günler, Erdi":"Hello, Erdi","Kişisel ve hassas bilgiler yalnız yetkili roller tarafından görüntülenir.":"Personal and sensitive information is visible only to authorized roles.","Puantaj Sonucu":"Attendance Result","Vardiya atandığında veya güncellendiğinde burada görünecek.":"It will appear here when a shift is assigned or updated.","Vardiya ve sistem bildirimleri":"Shift and system notifications","Vardiya, puantaj ve duyurularının özeti.":"Summary of shifts, attendance and announcements."
});
Object.assign(DE, {
  "Bordro":"Entgeltabrechnung","Depo bazlı":"Nach Lager","Depo Müdürü":"Lagerleiter","Evet":"Ja","Hayır":"Nein","İK / Bordro":"Personal / Entgelt","Kişi bazlı":"Nach Mitarbeiter","Kişi seç":"Mitarbeiter wählen","Koordinat":"Koordinaten","Kritik":"Kritisch","Operasyon":"Betrieb","Otomatik":"Automatisch","Resmî tatil":"Feiertag","Sert blok":"Harte Sperre","Tarih / Plan":"Datum / Plan","Yarıçap":"Radius","11 Saat":"11 Stunden","Depo / Tarih":"Lager / Datum","Ham Net":"Roh-Netto","Hazırlayan":"Erstellt von","İzin çakışması":"Abwesenheitskonflikt","Norm":"Soll","Operasyon Onayı":"Betriebsfreigabe","Roster laboratuvarı boş":"Roster-Labor ist leer","Roster okunuyor…":"Roster wird geladen…","Simülasyon":"Simulation","Aç":"Öffnen","Atanmış depo":"Zugewiesenes Lager","Bu ay":"Dieser Monat","Çalışma":"Arbeit","Görev Yeri":"Arbeitsort","Puantaj Sonucu":"Zeitergebnis","Vardiya ve sistem bildirimleri":"Schicht- und Systemmeldungen"
});
Object.assign(AR, {
  "Bordro":"الرواتب","Depo bazlı":"حسب المستودع","Depo Müdürü":"مدير المستودع","Evet":"نعم","Hayır":"لا","İK / Bordro":"الموارد البشرية / الرواتب","Kişi bazlı":"حسب الموظف","Kişi seç":"اختر الموظف","Koordinat":"الإحداثيات","Kritik":"حرج","Operasyon":"العمليات","Otomatik":"تلقائي","Resmî tatil":"عطلة رسمية","Sert blok":"حظر صارم","Tarih / Plan":"التاريخ / الخطة","Yarıçap":"نصف القطر","11 Saat":"11 ساعة","Depo / Tarih":"المستودع / التاريخ","Ham Net":"الصافي الخام","Hazırlayan":"أعدّه","İzin çakışması":"تعارض إجازة","Norm":"المعيار","Operasyon Onayı":"موافقة العمليات","Roster laboratuvarı boş":"مختبر الجدول فارغ","Roster okunuyor…":"جارٍ تحميل الجدول…","Simülasyon":"المحاكاة","Aç":"فتح","Atanmış depo":"المستودع المعيّن","Bu ay":"هذا الشهر","Çalışma":"العمل","Görev Yeri":"مكان العمل","Puantaj Sonucu":"نتيجة الحضور","Vardiya ve sistem bildirimleri":"إشعارات المناوبات والنظام"
});
Object.assign(EN, { "2026 özeti":"2026 summary", "İşe giriş":"Hire date" });
Object.assign(DE, { "2026 özeti":"Übersicht 2026", "İşe giriş":"Eintrittsdatum" });
Object.assign(AR, { "2026 özeti":"ملخص 2026", "İşe giriş":"تاريخ التعيين" });
Object.assign(EN, {
  "Roster laboratuvarı, dönem mesaisi ve norm analizi":"Roster lab, period overtime and norm analysis",
  "Ham kaynak değişmez. Tüm çalışanların dönem hesabı, yüklenen izinler ve roster birlikte değerlendirilerek ayrı simülasyon katmanında üretilir.":"The raw source remains unchanged. Period calculations for all employees combine uploaded leave and roster data in a separate simulation layer.",
  "Dönem Mesai Hesabı":"Period Overtime Calculation","Kişi Bazlı Mesai Excel":"Employee Overtime Excel","Tüm unvanlar":"All titles","Vardiya / Gün":"Shifts / Days","Hesaba Esas":"Calculation Basis","Depo / Unvan":"Warehouse / Title","Kontroller":"Checks","İnceleme":"Review","Temiz":"Clear","izin günü":"leave days","izin çakışması":"leave conflicts","adet 11 saat":"over 11 hours","simülasyon":"simulation",
  "Bu tablo yalnız 11 saat üstünü değil, seçilen dönemde roster veya izin kaydı bulunan herkesi kapsar. Fazla mesai kişi/gün bazında resmî tatil hariç 7,5 saatin üstünden hesaplanır; roster ile çakışan izin günü OPEX hesabında çalışmadan düşer, ham net ayrıca korunur. Gece süresi mola zamanları bilinmediği için oransal yaklaşıktır.":"This table includes everyone with a roster or leave record in the selected period, not only records over 11 hours. Overtime is calculated per employee/day above 7.5 non-holiday hours; a leave day conflicting with roster is excluded from OPEX work while raw net time is retained. Night time is proportional because break times are unknown."
});
Object.assign(DE, {
  "Roster laboratuvarı, dönem mesaisi ve norm analizi":"Roster-Labor, Periodenmehrarbeit und Sollanalyse",
  "Ham kaynak değişmez. Tüm çalışanların dönem hesabı, yüklenen izinler ve roster birlikte değerlendirilerek ayrı simülasyon katmanında üretilir.":"Die Rohquelle bleibt unverändert. Die Periodenberechnung aller Mitarbeiter kombiniert importierte Abwesenheiten und Roster in einer separaten Simulationsebene.",
  "Dönem Mesai Hesabı":"Mehrarbeitsberechnung der Periode","Kişi Bazlı Mesai Excel":"Mehrarbeit je Mitarbeiter (Excel)","Tüm unvanlar":"Alle Positionen","Vardiya / Gün":"Schichten / Tage","Hesaba Esas":"Berechnungsbasis","Depo / Unvan":"Lager / Position","Kontroller":"Prüfungen","İnceleme":"Prüfen","Temiz":"Sauber","izin günü":"Abwesenheitstage","izin çakışması":"Abwesenheitskonflikte","adet 11 saat":"über 11 Stunden","simülasyon":"Simulation",
  "Bu tablo yalnız 11 saat üstünü değil, seçilen dönemde roster veya izin kaydı bulunan herkesi kapsar. Fazla mesai kişi/gün bazında resmî tatil hariç 7,5 saatin üstünden hesaplanır; roster ile çakışan izin günü OPEX hesabında çalışmadan düşer, ham net ayrıca korunur. Gece süresi mola zamanları bilinmediği için oransal yaklaşıktır.":"Die Tabelle umfasst alle Personen mit Roster- oder Abwesenheitseintrag im Zeitraum. Mehrarbeit wird je Mitarbeiter und Tag über 7,5 Nicht-Feiertagsstunden berechnet; kollidierende Abwesenheit wird aus der OPEX-Arbeit entfernt, der Rohwert bleibt erhalten. Nachtzeit ist wegen unbekannter Pausenzeiten proportional."
});
Object.assign(AR, {
  "Roster laboratuvarı, dönem mesaisi ve norm analizi":"مختبر الجدول وحساب العمل الإضافي وتحليل المعيار",
  "Ham kaynak değişmez. Tüm çalışanların dönem hesabı, yüklenen izinler ve roster birlikte değerlendirilerek ayrı simülasyon katmanında üretilir.":"يبقى المصدر الخام دون تغيير. يجمع حساب الفترة لجميع الموظفين بين الإجازات المرفوعة والجدول في طبقة محاكاة منفصلة.",
  "Dönem Mesai Hesabı":"حساب العمل الإضافي للفترة","Kişi Bazlı Mesai Excel":"Excel للعمل الإضافي حسب الموظف","Tüm unvanlar":"كل المسميات","Vardiya / Gün":"المناوبات / الأيام","Hesaba Esas":"أساس الحساب","Depo / Unvan":"المستودع / المسمى","Kontroller":"الفحوصات","İnceleme":"مراجعة","Temiz":"سليم","izin günü":"أيام الإجازة","izin çakışması":"تعارضات الإجازة","adet 11 saat":"أكثر من 11 ساعة","simülasyon":"محاكاة",
  "Bu tablo yalnız 11 saat üstünü değil, seçilen dönemde roster veya izin kaydı bulunan herkesi kapsar. Fazla mesai kişi/gün bazında resmî tatil hariç 7,5 saatin üstünden hesaplanır; roster ile çakışan izin günü OPEX hesabında çalışmadan düşer, ham net ayrıca korunur. Gece süresi mola zamanları bilinmediği için oransal yaklaşıktır.":"يشمل الجدول كل من لديه سجل مناوبة أو إجازة في الفترة المحددة، وليس فقط ما يتجاوز 11 ساعة. يُحسب العمل الإضافي لكل موظف ويوم فوق 7.5 ساعة غير العطلات؛ وتُستبعد الإجازة المتعارضة من عمل OPEX مع الاحتفاظ بالصافي الخام. الوقت الليلي تقريبي لعدم معرفة أوقات الاستراحة."
});
Object.assign(EN, {
  "Yöneticisine görev ata":"Assign task to manager","Seçilenleri 7,5 saate çek":"Set selected to 7.5 hours","Yönetici düzeltme görevleri":"Manager correction tasks","Atanan Yönetici":"Assigned Manager","Görev":"Task","Kayıt":"Records","Dönem":"Period","Açık":"Open","açık":"open","Tamamlandı işaretle":"Mark completed","Henüz yönetici görevi oluşturulmadı.":"No manager task has been created yet.","Yüksek":"High","11 saat üstü roster düzeltmesi":"Roster correction over 11 hours","Tümünü seç":"Select all","Seçimi temizle":"Clear selection"
});
Object.assign(DE, {
  "Yöneticisine görev ata":"Aufgabe an Leitung zuweisen","Seçilenleri 7,5 saate çek":"Auswahl auf 7,5 Stunden setzen","Yönetici düzeltme görevleri":"Korrekturaufgaben der Leitung","Atanan Yönetici":"Zugewiesene Leitung","Görev":"Aufgabe","Kayıt":"Datensätze","Dönem":"Zeitraum","Açık":"Offen","açık":"offen","Tamamlandı işaretle":"Als erledigt markieren","Henüz yönetici görevi oluşturulmadı.":"Noch keine Leitungsaufgabe erstellt.","Yüksek":"Hoch","11 saat üstü roster düzeltmesi":"Roster-Korrektur über 11 Stunden"
});
Object.assign(AR, {
  "Yöneticisine görev ata":"إسناد مهمة إلى المدير","Seçilenleri 7,5 saate çek":"ضبط المحدد على 7.5 ساعة","Yönetici düzeltme görevleri":"مهام تصحيح المدير","Atanan Yönetici":"المدير المعيّن","Görev":"المهمة","Kayıt":"السجلات","Dönem":"الفترة","Açık":"مفتوحة","açık":"مفتوحة","Tamamlandı işaretle":"تحديد كمكتملة","Henüz yönetici görevi oluşturulmadı.":"لم يتم إنشاء مهمة مدير بعد.","Yüksek":"عالية","11 saat üstü roster düzeltmesi":"تصحيح جدول يتجاوز 11 ساعة"
});
Object.assign(EN, {
  "Employee ID tekil anahtardır. Aynı kişi tekrar yüklenirse yeni kayıt açılmaz; TC, ad, Actual Warehouse, İK depo kodu, işe giriş ve çıkış bilgileri güncellenir.":"Employee ID is the unique key. Re-uploading the same employee updates national ID, name, Actual Warehouse, HR warehouse code, hire and termination data without creating a duplicate.",
  "Excel şablonu":"Excel template","Personel CSV/XLSX yükle":"Upload employee CSV/XLSX","Son dosya":"Last file","Yeni kişi":"New employees","Güncellenen":"Updated","Yeni çıkış":"New terminations","Eşleşmeyen depo":"Unmatched warehouses","Actual Warehouse":"Actual Warehouse","İK Depo Kodu":"HR Warehouse Code","İşten Çıkış":"Termination","Kaynak":"Source"
});
Object.assign(DE, {
  "Employee ID tekil anahtardır. Aynı kişi tekrar yüklenirse yeni kayıt açılmaz; TC, ad, Actual Warehouse, İK depo kodu, işe giriş ve çıkış bilgileri güncellenir.":"Die Employee ID ist der eindeutige Schlüssel. Ein erneuter Import aktualisiert Ausweis, Name, Actual Warehouse, HR-Lagercode, Eintritt und Austritt ohne Dublette.",
  "Excel şablonu":"Excel-Vorlage","Personel CSV/XLSX yükle":"Mitarbeiter-CSV/XLSX laden","Son dosya":"Letzte Datei","Yeni kişi":"Neue Mitarbeiter","Güncellenen":"Aktualisiert","Yeni çıkış":"Neue Austritte","Eşleşmeyen depo":"Nicht zugeordnete Lager","Actual Warehouse":"Tatsächliches Lager","İK Depo Kodu":"HR-Lagercode","İşten Çıkış":"Austritt"
});
Object.assign(AR, {
  "Employee ID tekil anahtardır. Aynı kişi tekrar yüklenirse yeni kayıt açılmaz; TC, ad, Actual Warehouse, İK depo kodu, işe giriş ve çıkış bilgileri güncellenir.":"معرّف الموظف هو المفتاح الفريد. عند رفع الموظف نفسه مجدداً يتم تحديث الهوية والاسم والمستودع الفعلي ورمز مستودع الموارد البشرية وتواريخ التعيين والمغادرة دون إنشاء نسخة مكررة.",
  "Excel şablonu":"نموذج Excel","Personel CSV/XLSX yükle":"رفع موظفين CSV/XLSX","Son dosya":"آخر ملف","Yeni kişi":"موظفون جدد","Güncellenen":"تم التحديث","Yeni çıkış":"مغادرات جديدة","Eşleşmeyen depo":"مستودعات غير مطابقة","Actual Warehouse":"المستودع الفعلي","İK Depo Kodu":"رمز مستودع الموارد البشرية","İşten Çıkış":"تاريخ المغادرة"
});
Object.assign(EN, {
  "Geçici OPEX Roster Lab":"Temporary OPEX Roster Lab","OPEX geçiş alanı":"OPEX transition area","Geçici Roster Lab, dönem mesaisi ve norm analizi":"Temporary Roster Lab, period overtime and norm analysis","Geçici roster yükle":"Upload temporary roster","Geçici analiz kaynağı: Roster":"Temporary analytics source: Roster","Ana analiz kaynağı: Check-in / Check-out":"Primary analytics source: Check-in / Check-out","Geçici aktif":"Temporary active","Ana sistem":"Primary system","Check-in/out’a dön":"Return to check-in/out","Roster’ı geçici kaynak yap":"Use roster as temporary source","Geçici verileri sil":"Delete temporary data","Roster ID şablonunu indir":"Download Roster ID template","Toplu Roster ID eşleştir":"Match Roster IDs in bulk"
});
Object.assign(DE, {
  "Geçici OPEX Roster Lab":"Temporäres OPEX Roster-Labor","OPEX geçiş alanı":"OPEX-Übergangsbereich","Geçici Roster Lab, dönem mesaisi ve norm analizi":"Temporäres Roster-Labor, Periodenmehrarbeit und Sollanalyse","Geçici roster yükle":"Temporären Roster laden","Geçici analiz kaynağı: Roster":"Temporäre Analysequelle: Roster","Ana analiz kaynağı: Check-in / Check-out":"Hauptanalysequelle: Check-in / Check-out","Geçici aktif":"Temporär aktiv","Ana sistem":"Hauptsystem","Check-in/out’a dön":"Zu Check-in/out wechseln","Roster’ı geçici kaynak yap":"Roster als temporäre Quelle nutzen","Geçici verileri sil":"Temporäre Daten löschen","Roster ID şablonunu indir":"Roster-ID-Vorlage herunterladen","Toplu Roster ID eşleştir":"Roster-IDs gesammelt zuordnen"
});
Object.assign(AR, {
  "Geçici OPEX Roster Lab":"مختبر OPEX المؤقت للجداول","OPEX geçiş alanı":"منطقة انتقال OPEX","Geçici Roster Lab, dönem mesaisi ve norm analizi":"مختبر الجدول المؤقت وحساب الإضافي وتحليل المعيار","Geçici roster yükle":"رفع جدول مؤقت","Geçici analiz kaynağı: Roster":"مصدر التحليل المؤقت: الجدول","Ana analiz kaynağı: Check-in / Check-out":"مصدر التحليل الرئيسي: تسجيل الدخول والخروج","Geçici aktif":"المؤقت نشط","Ana sistem":"النظام الرئيسي","Check-in/out’a dön":"العودة إلى الدخول والخروج","Roster’ı geçici kaynak yap":"استخدام الجدول كمصدر مؤقت","Geçici verileri sil":"حذف البيانات المؤقتة","Roster ID şablonunu indir":"تنزيل نموذج معرّف الجدول","Toplu Roster ID eşleştir":"مطابقة معرّفات الجدول بالجملة"
});
Object.assign(EN, {
  "Audit Log":"Audit Log","Workforce Audit Log":"Workforce Audit Log","Adli iz ve hesap verebilirlik":"Forensic trace and accountability","Audit CSV indir":"Download audit CSV","Tüm işlemler":"All actions","İşlem ayrıntısı":"Action details","Yeni çalışma kuralı":"New work rule","Yeni sürüm":"New version","Kuralın yeni sürümünü oluştur":"Create a new rule version","Hesap motoruna bağla":"Connect to calculation engine","Hesap motoru kural türü":"Calculation engine rule type","Cihazı sıfırla":"Reset device","Cihaz eşleşmesini sıfırla":"Reset device binding","Eski cihazı iptal et":"Revoke old device","Sıfırlama gerekçesi":"Reset reason","11 Saat Kayıtları Excel":"11-Hour Records Excel","Tüm Dönem Mesai Excel":"Full Period Overtime Excel"
});
Object.assign(DE, {
  "Audit Log":"Audit-Protokoll","Workforce Audit Log":"Workforce Audit-Protokoll","Adli iz ve hesap verebilirlik":"Forensische Spur und Verantwortlichkeit","Audit CSV indir":"Audit-CSV herunterladen","Tüm işlemler":"Alle Vorgänge","İşlem ayrıntısı":"Vorgangsdetails","Yeni çalışma kuralı":"Neue Arbeitsregel","Yeni sürüm":"Neue Version","Kuralın yeni sürümünü oluştur":"Neue Regelversion erstellen","Hesap motoruna bağla":"Mit Berechnungsmodul verbinden","Hesap motoru kural türü":"Regeltyp des Berechnungsmoduls","Cihazı sıfırla":"Gerät zurücksetzen","Cihaz eşleşmesini sıfırla":"Gerätebindung zurücksetzen","Eski cihazı iptal et":"Altes Gerät sperren","Sıfırlama gerekçesi":"Grund der Rücksetzung","11 Saat Kayıtları Excel":"11-Stunden-Datensätze Excel","Tüm Dönem Mesai Excel":"Gesamte Periodenmehrarbeit Excel"
});
Object.assign(AR, {
  "Audit Log":"سجل التدقيق","Workforce Audit Log":"سجل تدقيق القوى العاملة","Adli iz ve hesap verebilirlik":"الأثر الجنائي والمساءلة","Audit CSV indir":"تنزيل سجل التدقيق CSV","Tüm işlemler":"كل العمليات","İşlem ayrıntısı":"تفاصيل العملية","Yeni çalışma kuralı":"قاعدة عمل جديدة","Yeni sürüm":"إصدار جديد","Kuralın yeni sürümünü oluştur":"إنشاء إصدار جديد للقاعدة","Hesap motoruna bağla":"ربط بمحرك الحساب","Hesap motoru kural türü":"نوع قاعدة محرك الحساب","Cihazı sıfırla":"إعادة ضبط الجهاز","Cihaz eşleşmesini sıfırla":"إعادة ضبط ربط الجهاز","Eski cihazı iptal et":"إلغاء الجهاز القديم","Sıfırlama gerekçesi":"سبب إعادة الضبط","11 Saat Kayıtları Excel":"سجلات 11 ساعة Excel","Tüm Dönem Mesai Excel":"ساعات الفترة الكاملة Excel"
});
Object.assign(EN, {
  "Yönetici Görevleri":"Manager Tasks","Duyuru ve Bildirimler":"Announcements & Notifications","İtiraz / Düzeltme Talebi":"Appeal / Correction Request","İtiraz / düzeltme talebi oluştur":"Create appeal / correction request","Yöneticiye gönder":"Send to manager","Görevler":"Tasks","Yönetici iş merkezi":"Manager work center","11 saat görevleri ve picker düzeltme talepleri":"11-hour tasks and picker correction requests","İncele ve düzelt":"Review and correct","Düzeltmeyi kaydet":"Save correction","İletişim merkezi":"Communications center","Duyurular ve vardiya bildirimleri":"Announcements and shift notifications","Hatırlatma ayarları":"Reminder settings","Yeni duyuru yayınla":"Publish announcement","Vardiyanız yayınlandı":"Your shift has been published","Check-in yapmayı unutmayın":"Remember to check in","Check-out yapmayı unutmayın":"Remember to check out","Duyuruyu yayınla":"Publish announcement","Personeli güncelle":"Update employee","Yönetici açıklaması":"Manager note"
});
Object.assign(DE, {
  "Yönetici Görevleri":"Leitungsaufgaben","Duyuru ve Bildirimler":"Mitteilungen & Benachrichtigungen","İtiraz / Düzeltme Talebi":"Einspruch / Korrekturantrag","İtiraz / düzeltme talebi oluştur":"Einspruch / Korrekturantrag erstellen","Yöneticiye gönder":"An Leitung senden","Görevler":"Aufgaben","Yönetici iş merkezi":"Arbeitsbereich der Leitung","11 saat görevleri ve picker düzeltme talepleri":"11-Stunden-Aufgaben und Korrekturanträge","İncele ve düzelt":"Prüfen und korrigieren","Düzeltmeyi kaydet":"Korrektur speichern","İletişim merkezi":"Kommunikationszentrale","Duyurular ve vardiya bildirimleri":"Mitteilungen und Schichtbenachrichtigungen","Hatırlatma ayarları":"Erinnerungseinstellungen","Yeni duyuru yayınla":"Neue Mitteilung veröffentlichen","Vardiyanız yayınlandı":"Ihre Schicht wurde veröffentlicht","Check-in yapmayı unutmayın":"Check-in nicht vergessen","Check-out yapmayı unutmayın":"Check-out nicht vergessen","Duyuruyu yayınla":"Mitteilung veröffentlichen","Personeli güncelle":"Mitarbeiter aktualisieren","Yönetici açıklaması":"Anmerkung der Leitung"
});
Object.assign(AR, {
  "Yönetici Görevleri":"مهام المدير","Duyuru ve Bildirimler":"الإعلانات والإشعارات","İtiraz / Düzeltme Talebi":"اعتراض / طلب تصحيح","İtiraz / düzeltme talebi oluştur":"إنشاء اعتراض / طلب تصحيح","Yöneticiye gönder":"إرسال إلى المدير","Görevler":"المهام","Yönetici iş merkezi":"مركز عمل المدير","11 saat görevleri ve picker düzeltme talepleri":"مهام 11 ساعة وطلبات تصحيح العامل","İncele ve düzelt":"مراجعة وتصحيح","Düzeltmeyi kaydet":"حفظ التصحيح","İletişim merkezi":"مركز الاتصالات","Duyurular ve vardiya bildirimleri":"الإعلانات وإشعارات المناوبات","Hatırlatma ayarları":"إعدادات التذكير","Yeni duyuru yayınla":"نشر إعلان جديد","Vardiyanız yayınlandı":"تم نشر مناوبتك","Check-in yapmayı unutmayın":"لا تنس تسجيل الدخول","Check-out yapmayı unutmayın":"لا تنس تسجيل الخروج","Duyuruyu yayınla":"نشر الإعلان","Personeli güncelle":"تحديث الموظف","Yönetici açıklaması":"ملاحظة المدير"
});
Object.assign(EN, {
  "Sistem Konfigürasyonu":"System Configuration","Şirket özellikleri ve mobil modüller":"Company features and mobile modules","Admin kontrolü":"Admin controlled","Mobil mola yönetimi":"Mobile break management","Picker izin talepleri":"Picker leave requests","İtiraz / düzeltme talepleri":"Appeal / correction requests","Mobil duyurular":"Mobile announcements","Bildirim merkezi":"Notification center","Vardiya arşivi":"Shift archive","QR ile check-in":"QR check-in","Tümünü okundu yap":"Mark all read","Tümünü sil":"Delete all","Okudum, kapat":"Read and dismiss","İzin talebi oluştur":"Create leave request","Haftalık izin":"Weekly day off","Yıllık izin":"Annual leave","Talep":"Request","İzin talebini incele":"Review leave request","Kararı kaydet":"Save decision","Açık":"Enabled","Kapalı":"Disabled"
});
Object.assign(DE, {
  "Sistem Konfigürasyonu":"Systemkonfiguration","Şirket özellikleri ve mobil modüller":"Unternehmensfunktionen und mobile Module","Admin kontrolü":"Admin-gesteuert","Mobil mola yönetimi":"Mobile Pausenverwaltung","Picker izin talepleri":"Urlaubsanträge der Picker","İtiraz / düzeltme talepleri":"Einspruchs- / Korrekturanträge","Mobil duyurular":"Mobile Mitteilungen","Bildirim merkezi":"Benachrichtigungszentrale","Vardiya arşivi":"Schichtarchiv","QR ile check-in":"Check-in per QR","Tümünü okundu yap":"Alle als gelesen markieren","Tümünü sil":"Alle löschen","Okudum, kapat":"Gelesen und schließen","İzin talebi oluştur":"Urlaubsantrag erstellen","Haftalık izin":"Wöchentlicher Ruhetag","Yıllık izin":"Jahresurlaub","Talep":"Antrag","İzin talebini incele":"Urlaubsantrag prüfen","Kararı kaydet":"Entscheidung speichern"
});
Object.assign(AR, {
  "Sistem Konfigürasyonu":"تهيئة النظام","Şirket özellikleri ve mobil modüller":"ميزات الشركة والوحدات المحمولة","Admin kontrolü":"تحكم المسؤول","Mobil mola yönetimi":"إدارة الاستراحة عبر الجوال","Picker izin talepleri":"طلبات إجازة العامل","İtiraz / düzeltme talepleri":"طلبات الاعتراض / التصحيح","Mobil duyurular":"الإعلانات المحمولة","Bildirim merkezi":"مركز الإشعارات","Vardiya arşivi":"أرشيف المناوبات","QR ile check-in":"تسجيل الدخول عبر QR","Tümünü okundu yap":"تحديد الكل كمقروء","Tümünü sil":"حذف الكل","Okudum, kapat":"تمت القراءة والإغلاق","İzin talebi oluştur":"إنشاء طلب إجازة","Haftalık izin":"راحة أسبوعية","Yıllık izin":"إجازة سنوية","Talep":"طلب","İzin talebini incele":"مراجعة طلب الإجازة","Kararı kaydet":"حفظ القرار"
});
Object.assign(EN, {
  "Moladasın":"You are on break","Aktif mola":"Active break","Molayı yönet":"Manage break","İzin talebin gönderildi":"Leave request sent","Açıklama boş bırakılamaz.":"Description cannot be empty.","Mola canlı aktivitesi":"Live break activity","İzin talebin yöneticine gönderildi. Durumu Görevler ekranından izleyebilirsin.":"Your leave request was sent to your manager. You can track it on the Tasks screen.","Bugünkü operasyon durumun hazır.":"Today's operation status is ready.","Plan bekleniyor":"Waiting for plan","Molada":"On break","Görev yeri":"Work location","Kayıtlı cihaz":"Registered device","Hızlı işlemler":"Quick actions","Tek dokunuşla":"One tap","Vardiya arşivi":"Shift archive","İzin talebi":"Leave request","Görevler ve talepler":"Tasks and requests","Güncel durumu izle":"Track current status","Bu ay vardiya":"Shifts this month","Tamamlanan":"Completed","Açık talep":"Open requests"
});
Object.assign(DE, {
  "Moladasın":"Du bist in der Pause","Aktif mola":"Aktive Pause","Molayı yönet":"Pause verwalten","İzin talebin gönderildi":"Urlaubsantrag gesendet","Açıklama boş bırakılamaz.":"Die Beschreibung darf nicht leer sein.","Mola canlı aktivitesi":"Live-Pausenaktivität","İzin talebin yöneticine gönderildi. Durumu Görevler ekranından izleyebilirsin.":"Dein Urlaubsantrag wurde an deine Führungskraft gesendet. Den Status siehst du unter Aufgaben.","Bugünkü operasyon durumun hazır.":"Dein heutiger Betriebsstatus ist bereit.","Plan bekleniyor":"Plan ausstehend","Molada":"In Pause","Görev yeri":"Einsatzort","Kayıtlı cihaz":"Registriertes Gerät","Hızlı işlemler":"Schnellaktionen","Tek dokunuşla":"Mit einem Tipp","Vardiya arşivi":"Schichtarchiv","İzin talebi":"Urlaubsantrag","Görevler ve talepler":"Aufgaben und Anträge","Güncel durumu izle":"Aktuellen Status verfolgen","Bu ay vardiya":"Schichten diesen Monat","Tamamlanan":"Abgeschlossen","Açık talep":"Offene Anträge"
});
Object.assign(AR, {
  "Moladasın":"أنت في استراحة","Aktif mola":"استراحة نشطة","Molayı yönet":"إدارة الاستراحة","İzin talebin gönderildi":"تم إرسال طلب الإجازة","Açıklama boş bırakılamaz.":"لا يمكن ترك الوصف فارغًا.","Mola canlı aktivitesi":"نشاط الاستراحة المباشر","İzin talebin yöneticine gönderildi. Durumu Görevler ekranından izleyebilirsin.":"تم إرسال طلب الإجازة إلى مديرك. يمكنك متابعة حالته من شاشة المهام.","Bugünkü operasyon durumun hazır.":"حالة عمليات اليوم جاهزة.","Plan bekleniyor":"بانتظار الخطة","Molada":"في استراحة","Görev yeri":"موقع العمل","Kayıtlı cihaz":"جهاز مسجل","Hızlı işlemler":"إجراءات سريعة","Tek dokunuşla":"بلمسة واحدة","Vardiya arşivi":"أرشيف المناوبات","İzin talebi":"طلب إجازة","Görevler ve talepler":"المهام والطلبات","Güncel durumu izle":"متابعة الحالة الحالية","Bu ay vardiya":"مناوبات هذا الشهر","Tamamlanan":"مكتمل","Açık talep":"طلبات مفتوحة"
});

const DICTIONARIES = { en: EN, de: DE, ar: AR };
const LOCALE_CODES = { tr: "tr-TR", en: "en-US", de: "de-DE", ar: "ar-SA" };

function translateText(raw, locale) {
  if (locale === "tr") return raw;
  const match = String(raw).match(/^(\s*)(.*?)(\s*)$/s);
  const core = match?.[2] || raw;
  return `${match?.[1] || ""}${DICTIONARIES[locale]?.[core] || EN[core] || core}${match?.[3] || ""}`;
}

function useDomLocalization(rootRef, locale) {
  const originals = useRef(new WeakMap());
  const rendered = useRef(new WeakMap());
  useEffect(() => {
    const root = rootRef.current; if (!root) return undefined;
    let applying = false;
    const localize = (node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        const lastRendered = rendered.current.get(node);
        // React can reuse the same Text node when a live label changes (for
        // example "Molaya Çık" -> "Molayı Bitir"). Treat a value that differs
        // from our last translated output as a new source value; otherwise the
        // localization observer would restore the stale label until remount.
        if (!originals.current.has(node) || (lastRendered !== undefined && node.nodeValue !== lastRendered)) {
          originals.current.set(node, node.nodeValue);
        }
        const next = translateText(originals.current.get(node), locale);
        rendered.current.set(node, next);
        if (node.nodeValue !== next) node.nodeValue = next;
        return;
      }
      if (node.nodeType !== Node.ELEMENT_NODE) return;
      ["placeholder", "title", "aria-label"].forEach((attr) => {
        if (!node.hasAttribute?.(attr)) return;
        const dataKey = `wfxOriginal${attr.replace(/-([a-z])/g, (_, value) => value.toUpperCase()).replace(/^./, (value) => value.toUpperCase())}`;
        if (!node.dataset[dataKey]) node.dataset[dataKey] = node.getAttribute(attr);
        node.setAttribute(attr, translateText(node.dataset[dataKey], locale));
      });
      node.childNodes.forEach(localize);
    };
    applying = true; localize(root); applying = false;
    const observer = new MutationObserver((mutations) => {
      if (applying) return;
      applying = true;
      mutations.forEach((mutation) => mutation.type === "characterData" ? localize(mutation.target) : mutation.addedNodes.forEach(localize));
      applying = false;
    });
    observer.observe(root, { subtree: true, childList: true, characterData: true });
    return () => observer.disconnect();
  }, [rootRef, locale]);
}

export function WorkforceUiProvider({ children }) {
  const [theme, setThemeState] = useState(() => localStorage.getItem("opex_theme") === "dark" ? "dark" : "light");
  const [locale, setLocaleState] = useState(() => ["tr", "en", "de", "ar"].includes(localStorage.getItem("opex_workforce_locale")) ? localStorage.getItem("opex_workforce_locale") : "tr");
  const setTheme = (value) => { localStorage.setItem("opex_theme", value); setThemeState(value); };
  const setLocale = (value) => { localStorage.setItem("opex_workforce_locale", value); setLocaleState(value); };
  const value = useMemo(() => ({ theme, setTheme, locale, setLocale, dir: locale === "ar" ? "rtl" : "ltr", localeCode: LOCALE_CODES[locale], t: (text) => translateText(text, locale), useDomLocalization }), [theme, locale]);
  return <WorkforceUiContext.Provider value={value}>{children}</WorkforceUiContext.Provider>;
}

export function useWorkforceUi() {
  const value = useContext(WorkforceUiContext);
  if (!value) throw new Error("useWorkforceUi must be used inside WorkforceUiProvider");
  return value;
}
