
import React, { useMemo, useRef, useState } from "react";
import "./App.css";
import { api } from "./services/api";
import PremiumLoader from "./components/PremiumLoader";

const STORE_OPTIONS = [
  { code: "FULYA", name: "Fulya (İstanbul)" },
  { code: "ANKA", name: "Anka (İstanbul)" },
  { code: "ACIBADEM", name: "Acıbadem" },
];

const I18N = {
  TR: { command:"Komuta Merkezi", live3d:"Canlı 3D", architect:"Mimari Düzenleyici", placement:"Ürün Yerleşimi", planogram:"Planogram", rules:"Kural Motoru", reports:"Raporlar", uploadSku:"SKU yükle", uploadLayout:"Layout yükle", generate:"Optimum plan üret" },
  EN: { command:"Command Center", live3d:"Live 3D", architect:"Layout Architect", placement:"Product Placement", planogram:"Planogram", rules:"Rule Engine", reports:"Reports", uploadSku:"Upload SKUs", uploadLayout:"Upload Layout", generate:"Generate Optimal Plan" },
};

function cls(...xs){ return xs.filter(Boolean).join(" "); }
function n(v,d=0){ const x=Number(String(v??"").replace(",",".")); return Number.isFinite(x)?x:d; }
function storePayload(storeName){ const f = String(storeName).toLowerCase().includes("fulya"); return f ? { store_code:"FULYA", store_name:"Fulya (İstanbul)", active_depot:"Fulya (İstanbul)", dmart:"Fulya (İstanbul)", depot:"Fulya (İstanbul)" } : { store_code:String(storeName).split(" ")[0].toUpperCase(), store_name:storeName, active_depot:storeName, dmart:storeName, depot:storeName }; }
function imageOf(p){ return p?.image_url || p?.product_image_url || p?.catalog_image_url || p?.pim_image_url || p?.image || ""; }
function titleOf(p){ return p?.product_name || p?.name || p?.sku || "Ürün"; }
function storageOf(x){ const s=String(x?.storage_type||x?.allowed_storage_type||x||"AMBIENT").toUpperCase(); if(s.includes("FROZEN")) return "FROZEN"; if(s.includes("CHILLED")) return "CHILLED"; return "AMBIENT"; }
function storageTr(s){ s=storageOf(s); return s==="FROZEN"?"-18 Donuk":s==="CHILLED"?"+4 Soğuk":"Kuru"; }
function moduleTitle(a,m,idx){ const side=String(m.side||"").toUpperCase(); const sideText= side==="L"?"Sol":side==="R"?"Sağ":side==="INTERNAL"?"İç":side==="DOOR"?"Dolap":side||"Modül"; return `${a.aisle_id} / ${sideText} / Modül ${m.module_no||m.module_id||idx+1}`; }
function shelfProducts(s){ return Array.isArray(s?.products)?s.products:[]; }
function planStats(plan){ const aisles=plan?.aisles||[]; const modules=aisles.flatMap(a=>a.modules||[]); const shelves=modules.flatMap(m=>m.shelves||[]); const products=shelves.flatMap(s=>s.products||[]); return { aisles:aisles.length, modules:modules.length, shelves:shelves.length, products:products.length }; }
function normalizePlan(raw, fallback){ if(!raw) return fallback; if(Array.isArray(raw.aisles)) return raw; if(Array.isArray(raw.modules)){ const groups={}; raw.modules.forEach(m=>{ const k=m.aisle||m.aisle_id||m.zone_id||"MISC"; (groups[k]??=[]).push(m); }); return { ...raw, aisles:Object.entries(groups).map(([k,mods],i)=>({ aisle_id:k,row:Math.floor(i/4)+1,position:i%4+1,modules:mods.map((m,j)=>({ ...m, module_id:m.module_id||j+1, module_width_cm:m.width_cm||m.module_width_cm||100, module_depth_cm:m.depth_cm||m.module_depth_cm||50, module_height_cm:m.height_cm||m.module_height_cm||210, shelves:(m.shelves||[]).map((s,si)=>({ shelf_no:s.shelf_no||s.shelf||si+1, shelf_width_cm:s.shelf_width_cm||s.width_cm||m.width_cm||100, shelf_height_cm:s.shelf_height_cm||s.height_cm||35, shelf_depth_cm:s.shelf_depth_cm||s.depth_cm||m.depth_cm||50, allowed_storage_type:s.allowed_storage_type||s.storage_type||m.storage_type||"AMBIENT", products:s.products||[], used_width_cm:s.used_width_cm||s.used_cm||s.used||0 })) })) }))}; } return raw; }
function parseCsvLocal(text){ const lines=text.split(/\r?\n/).filter(Boolean); if(lines.length<2) return []; const headers=lines[0].split(",").map(x=>x.trim().replace(/^"|"$/g,"")); return lines.slice(1).map(line=>{ const cells=line.match(/("[^"]*"|[^,]+)/g)||[]; const o={}; headers.forEach((h,i)=>o[h]=String(cells[i]||"").trim().replace(/^"|"$/g,"")); return o; }); }

function ProductImage({p,size=42}){ const [bad,setBad]=useState(false); const src=imageOf(p); if(src&&!bad) return <img className="po-product-img" style={{width:size,height:size}} src={src} onError={()=>setBad(true)} />; return <div className="po-product-img po-img-fallback" style={{width:size,height:size}}>{String(titleOf(p)).slice(0,2).toUpperCase()}</div>; }

function Shell({active,setActive,t,children,userName="Erdi A."}){ const items=[['command',t.command],['live3d',t.live3d],['architect',t.architect],['placement',t.placement],['planogram',t.planogram],['rules',t.rules],['reports',t.reports]]; return <div className="po-app"><aside className="po-sidebar"><div className="po-logo"><div className="po-mark">P</div><div><b>PLONAGRAM</b><span>OS</span></div></div><nav>{items.map(([k,l])=><button key={k} className={cls(active===k&&'active')} onClick={()=>setActive(k)}><i/> {l}</button>)}</nav><div className="po-user"><div>EA</div><b>{userName}</b><span>ADMIN</span></div></aside><section className="po-content">{children}</section></div> }

function TopBar({store,setStore,lang,setLang,t,onUpload,onGenerate,onLayout}){ return <header className="po-topbar"><div><div className="po-kicker">PLONAGRAM OS · COMMAND LAYER</div><h1>{t.command}</h1><p>Backend bağlantısı hazır. Aktif depo: {store}</p></div><div className="po-top-actions"><span className="po-online">● Sistem Durumu Çevrimiçi</span><select value={store} onChange={e=>setStore(e.target.value)}>{STORE_OPTIONS.map(s=><option key={s.code} value={s.name}>{s.name}</option>)}</select><select value={lang} onChange={e=>setLang(e.target.value)}><option>TR</option><option>EN</option></select><button onClick={onUpload}>{t.uploadSku}</button><button onClick={onLayout}>{t.uploadLayout}</button><button className="po-primary" onClick={onGenerate}>✦ {t.generate}</button></div></header> }

function CommandCenter({stats,onGenerate,setActive}){ return <main className="po-main"><section className="po-hero"><div><div className="po-kicker">WELCOME TO PLONAGRAM OS</div><h2>Warehouse intelligence,<br/>beautifully orchestrated<span>.</span></h2><p>Planogram, raf, fixture, soğuk zincir, refill riski ve picker rotasını tek komuta ekranında yönet.</p><div><button className="po-primary" onClick={onGenerate}>✦ Optimum plan üret</button><button onClick={()=>setActive('live3d')}>⌑ 3D Studio aç</button></div></div><MiniTwin /></section><KpiGrid stats={stats}/><div className="po-two"><section className="po-card"><div className="po-kicker">LIVE DIGITAL TWIN</div><h3>Okunabilir 3D operasyon alanı</h3><MiniTwin compact /><button onClick={()=>setActive('live3d')}>Open 3D Studio →</button></section><section className="po-card"><div className="po-kicker">AI INSIGHTS</div><h3>AI içgörüler</h3>{['Space Optimization Opportunity','Refill Recommendation','Overstock Alert','Planogram Performance'].map((x,i)=><div className="po-insight" key={x}><b>{x}</b><span>{i<2?'High Impact':'Positive'}</span></div>)}</section></div></main> }
function KpiGrid({stats}){ const cards=[['Planogram Score','92','↑ 8 vs last 7 days'],['Space Utilization',`${Math.max(1,Math.round(stats.products/Math.max(stats.shelves,1)*20))}%`,'healthy'],['Active SKU',stats.activeSku||0,'master products'],['Placed Products',stats.products||0,'raf üzerinde'],['Modules',stats.modules||0,'Store DNA'],['Shelves',stats.shelves||0,'capacity']]; return <div className="po-kpis">{cards.map(c=><div className="po-kpi" key={c[0]}><span>{c[0]}</span><b>{c[1]}</b><em>{c[2]}</em></div>)}</div> }
function MiniTwin({compact=false}){ return <div className={cls('po-mini-twin',compact&&'compact')}>{['A','B','C','D','E','F','G','H','I'].map((a,i)=><div key={a} className="po-mini-rack" style={{left:`${8+(i%3)*28}%`,top:`${18+Math.floor(i/3)*26}%`}}><b>{a}</b></div>)}<svg viewBox="0 0 500 260"><path d="M40 235 C120 160 150 210 210 120 S330 70 390 25" /></svg><span className="tag tag-refill">Refill Risk</span><span className="tag tag-dispatch">Dispatch</span></div> }

function Live3D({plan,setSelectedShelf}){ const aisles=plan?.aisles||[]; const [camera,setCamera]=useState('Overview'); const [layer,setLayer]=useState('Utilization'); const stats=planStats(plan); return <main className="po-main po-live"><div className="po-page-head"><div><div className="po-kicker">CANLI 3D</div><h2>Canlı Dijital İkiz</h2><p>Katmanlar, hız, görünüm, picker rotası, refill riski ve cold chain aynı sahnede.</p></div><div className="po-tabs"><button className="active">3D View</button><button>2D Plan</button><button>Heatmap</button></div></div><div className="po-live-grid"><section className="po-scene-card"><div className="po-scene-toolbar"><span>AMBIENT +22°C</span><span>CHILLED +4°C</span><span>FROZEN -18°C</span><select value={layer} onChange={e=>setLayer(e.target.value)}><option>Utilization</option><option>Refill Risk</option><option>Cold Chain</option><option>Congestion</option></select></div><div className="po-warehouse3d">{aisles.slice(0,18).map((a,i)=><div className={cls('po-aisle3d', i%5===0&&'hot', String(a.zone_type).includes('COLD')&&'cold', String(a.zone_type).includes('FROZEN')&&'frozen')} style={{left:`${8+(i%6)*14}%`,top:`${18+Math.floor(i/6)*22}%`}} key={a.aisle_id} onClick={()=>{ const m=a.modules?.[0]; const s=m?.shelves?.[0]; if(m&&s) setSelectedShelf({aisle:a,module:m,shelf:s}); }}><b>{a.aisle_id}</b><span>{a.modules?.length||0} modül</span></div>)}<svg viewBox="0 0 900 500" className="po-route"><path d="M60 430 C210 310 250 380 360 250 S610 180 760 70" /></svg><div className="po-risk-badge">CONGESTION<br/><b>Aisle 07</b></div><div className="po-refill-badge">REFILL RISK<br/><b>23 SKU</b></div></div><div className="po-scene-bottom"><button>Katmanlar</button><button>Hız 1x</button><button>Görünüm Perspektif</button><button>⛶</button></div></section><aside className="po-right-panel"><Panel title="Kamera Ön Ayarları">{['Overview','Top View','Chilled Zone','Frozen Zone','Dispatch','Kat 1','Kat 2'].map(x=><button key={x} onClick={()=>setCamera(x)} className={camera===x?'active':''}>{x}</button>)}</Panel><Panel title="SKU Ara"><input placeholder="SKU kodu veya ürün adı..."/><button>Fly to Location</button></Panel><Panel title="AI İçgörüler">{['Yoğunluk yüksek','Refill riski tespit edildi','Soğuk zincir sağlıklı','Verimli rota önerisi'].map(x=><div className="po-mini-alert" key={x}>{x}</div>)}</Panel><Panel title="Hızlı Atlama">{aisles.slice(0,12).map(a=><button key={a.aisle_id}>{a.aisle_id}</button>)}</Panel></aside></div><KpiGrid stats={{...stats,activeSku:stats.products}}/></main> }
function Panel({title,children}){ return <section className="po-panel"><h4>{title}</h4><div className="po-panel-body">{children}</div></section> }

function PlanogramWorkspace({plan,setPlan,selectedShelf,setSelectedShelf,products}){ const stats=planStats(plan); const aisles=plan?.aisles||[]; const [filter,setFilter]=useState(aisles[0]?.aisle_id||''); const activeAisle=aisles.find(a=>a.aisle_id===filter)||aisles[0]; return <main className="po-main"><div className="po-page-head"><div><div className="po-kicker">2D PLANOGRAM</div><h2>Raf raf operasyon planı<span>.</span></h2><p>Ürün görseli, facing/depth, raf ölçüsü, yazdırma ve AI önerileri tek ekranda.</p></div><div className="po-tabs"><button>3D View</button><button className="active">2D Plan</button><button>Heatmap</button></div></div><div className="po-toolbar"><Stat label="Koridor" value={stats.aisles}/><Stat label="Modül" value={stats.modules}/><Stat label="Raf" value={stats.shelves}/><Stat label="Yerleşen SKU" value={stats.products}/><select value={activeAisle?.aisle_id||''} onChange={e=>setFilter(e.target.value)}>{aisles.map(a=><option key={a.aisle_id}>{a.aisle_id}</option>)}</select><input placeholder="Ürün / SKU ara"/><button>Ürün ekle</button><button>AI önerileri</button></div><div className="po-plan-grid"><section className="po-modules"><h3>Koridor {activeAisle?.aisle_id}</h3><p>{activeAisle?.modules?.length||0} modül · gerçek raf operasyon görünümü</p><div className="po-module-row">{(activeAisle?.modules||[]).map((m,mi)=><ModuleCard key={m.module_id||mi} aisle={activeAisle} module={m} idx={mi} onShelf={(s)=>setSelectedShelf({aisle:activeAisle,module:m,shelf:s})}/>)}</div></section><aside className="po-detail"><h4>SEÇİLİ DETAY</h4>{selectedShelf?<><h3>{moduleTitle(selectedShelf.aisle,selectedShelf.module,0)}</h3><Stat label="Raf" value={selectedShelf.module.shelves?.length}/><Stat label="Ürün" value={(selectedShelf.module.shelves||[]).flatMap(s=>s.products||[]).length}/><button onClick={()=>window.print()}>Modülü yazdır</button><button onClick={()=>setSelectedShelf({...selectedShelf,print:true})}>Görsel çıktı</button></>:<p>Modül veya raf seç.</p>}<div className="po-ai-box"><b>AI Ek Öneriler</b><ul><li>Facing/depth: hızlı SKU’larda minimum 2 ön yüz öner.</li><li>Refill labor: günlük 2+ refill üreten ürünleri aynı blokta topla.</li><li>Soğuk zincir: +4 / -18 ürünleri ambient modüle taşıma.</li></ul></div></aside></div>{selectedShelf&&<ShelfModal target={selectedShelf} onClose={()=>setSelectedShelf(null)} products={products}/>}</main> }
function Stat({label,value}){ return <div className="po-stat"><b>{value}</b><span>{label}</span></div> }
function ModuleCard({aisle,module,idx,onShelf}){ const products=(module.shelves||[]).flatMap(s=>s.products||[]); const util=Math.round((module.shelves||[]).reduce((a,s)=>a+n(s.used_width_cm||s.used,0),0)/Math.max(1,(module.shelves||[]).reduce((a,s)=>a+n(s.shelf_width_cm,100),0))*100); return <article className="po-module"><header><div><small>KORİDOR / TARAF / MODÜL</small><h4>{moduleTitle(aisle,module,idx)}</h4><p>{module.module_width_cm||100}×{module.module_depth_cm||50}×{module.module_height_cm||210}cm · {module.module_type||'fixture'}</p></div><b>{util}%</b></header><div className="po-module-actions"><button>+ Raf</button><button>Modül ölçü</button><button>Modül kuralı</button><button>Yazdır</button></div>{(module.shelves||[]).map(s=><div key={s.shelf_no} className="po-shelf" onClick={()=>onShelf(s)}><div><b>Raf {s.shelf_no}</b><span>{storageTr(s)} · {shelfProducts(s).length} ürün · {Math.round(n(s.used_width_cm||s.used,0))}/{n(s.shelf_width_cm,100)}cm</span></div><div className="po-products-strip">{shelfProducts(s).slice(0,9).map((p,i)=><ProductImage key={(p.sku||i)+i} p={p} size={36}/>)}</div></div>)}</article> }

function ShelfModal({target,onClose,products}){ const {aisle,module,shelf}=target; const ps=shelfProducts(shelf); const used=n(shelf.used_width_cm||shelf.used,0), width=n(shelf.shelf_width_cm,100); return <div className="po-modal"><div className="po-shelf-dialog"><button className="po-close" onClick={onClose}>Kapat</button><small>Büyük raf görünümü</small><h2>Raf {shelf.shelf_no} · {shelf.zone_type||'mid'} · {storageTr(shelf)}</h2><p>Ölçü: {width}cm genişlik · {shelf.shelf_depth_cm||50}cm derinlik · {shelf.shelf_height_cm||35}cm yükseklik</p><div className="po-big-stats"><Stat label="Doluluk" value={`${Math.round(used/Math.max(width,1)*100)}%`}/><Stat label="Kullanılan" value={`${Math.round(used)} cm`}/><Stat label="Kalan" value={`${Math.round(width-used)} cm`}/><Stat label="Ürün / Ön yüz" value={`${ps.length} / ${ps.reduce((a,p)=>a+n(p.facing_count||p.facing,1),0)}`}/></div><div className="po-capacity"><span style={{width:`${Math.min(100,used/Math.max(width,1)*100)}%`}} /></div><div className="po-real-shelf"><b>Gerçek raf ölçeği</b><div className="po-real-products">{ps.map((p,i)=><div className="po-real-product" key={(p.sku||i)+i}><ProductImage p={p} size={62}/><strong>{titleOf(p)}</strong><span>F:{p.facing_count||p.facing||1} · W:{p.width_cm||'-'}</span></div>)}<div className="po-empty-slot">Boş {Math.max(0,Math.round(width-used))}cm<br/>Ürünü buraya sürükle</div></div></div><div className="po-suggest"><h3>Boş alan ürün önerileri</h3>{(products||[]).slice(0,8).map((p,i)=><div className="po-suggest-card" key={p.sku||i}><ProductImage p={p} size={40}/><b>{titleOf(p)}</b><button>Boş alana ekle</button></div>)}</div><table className="po-print-table"><tbody>{ps.map((p,i)=><tr key={p.sku||i}><td>{i+1}</td><td>{p.sku}</td><td>{titleOf(p)}</td><td>F:{p.facing_count||p.facing||1}</td><td>{p.used_width_cm||'-'}cm</td></tr>)}</tbody></table></div></div> }

function RuleEngine({onGenerate}){ const [open,setOpen]=useState(true); return <main className="po-main"><div className="po-page-head"><div><div className="po-kicker">AI OPTIMIZATION CENTER</div><h2>Operasyonel Planogram Motoru</h2><p>Yüklenen SKU, yerleşen/yerleşmeyen ürün, ileri kural setleri ve skor motoru tek merkezden yönetilir.</p></div><button className="po-primary" onClick={onGenerate}>⚡ Planogram üret</button></div><button onClick={()=>setOpen(!open)}>{open?'Gizle':'Göster'}</button>{open&&<><div className="po-rule-grid"><Panel title="Dosya durumu"><div className="po-chip">✓ SKU yüklendi</div><div className="po-chip">✓ yerleşti</div><div className="po-chip">✓ yerleşmedi</div></Panel><Panel title="Optimizasyon modu"><select><option>Darkstore AI v2</option><option>Fulya Store DNA</option></select><p>AI hedeflerinize göre en iyi planı üretir.</p></Panel><Panel title="Skor Motoru">{['sales','picking','ergonomics','refill','risk','fixture'].map((x,i)=><label className="po-range" key={x}>{x}<input type="range" defaultValue={60+i*5}/></label>)}</Panel><Panel title="Admin Toplama Akışı"><select><option>Kuru</option></select><select><option>Soğuk</option></select><select><option>Donuk</option></select><select><option>Ağır ürün en son</option></select></Panel></div><section className="po-card"><h3>İleri Seviye Planogram Kural Setleri</h3><div className="po-form-row"><select><option>Marka</option><option>Kategori</option><option>Storage</option></select><input placeholder="Örn: Ülker / Water / MRK..."/><select><option>Kuru zone</option><option>+4 zone</option><option>-18 zone</option></select><select><option>Fark etmez</option><option>Sol</option><option>Sağ</option></select><button className="po-primary">Kural ekle ve uygula</button></div></section></>}</main> }

function Placeholder({title}){ return <main className="po-main"><section className="po-card big"><div className="po-kicker">PLONAGRAM OS</div><h2>{title}</h2><p>Bu modül Engine v2 mimarisine bağlıdır. Sonraki sprintte kalıcı DB ve yayın/onay akışıyla genişletilecek.</p></section></main> }

export default function App(){ const [active,setActive]=useState('command'); const [store,setStore]=useState('Fulya (İstanbul)'); const [lang,setLang]=useState('TR'); const [products,setProducts]=useState([]); const [planogram,setPlanogram]=useState({aisles:[]}); const [selectedShelf,setSelectedShelf]=useState(null); const [busy,setBusy]=useState(null); const [toast,setToast]=useState(''); const fileRef=useRef(null); const layoutRef=useRef(null); const t=I18N[lang]||I18N.TR; const stats=useMemo(()=>({...planStats(planogram),activeSku:products.length}),[planogram,products]);
  async function handleUploadFile(file){ if(!file) return; setBusy({title:'SKU yükleniyor',subtitle:'CSV başlıkları ve ürün ölçüleri kontrol ediliyor.',steps:['Reading CSV','Validating Headers','Enriching Master Data','Image Mapping']}); try{ let data; try{ data=await api.uploadProductsCsv(file); setProducts(data.products||[]); setToast(`${data.row_count||0} SKU yüklendi.`); }catch(e){ const text=await file.text(); const rows=parseCsvLocal(text); if(!rows.length) throw new Error('CSV okunamadı. Başlıklar veya ayraç yapısı hatalı.'); setProducts(rows); setToast(`${rows.length} SKU lokal yüklendi. Backend uyarısı: ${e.message}`); } }catch(e){ downloadErrorReport(file.name,e.message); setToast(`Yükleme hatası: ${e.message}`); }finally{ setBusy(null); } }
  function downloadErrorReport(fileName,message){ const content=`PLONAGRAM OS CSV ERROR REPORT\nFile: ${fileName}\nReason: ${message}\nRequired minimum columns: sku, product_name, brand, storage_type, width_cm, height_cm, depth_cm, image_url\n`; const blob=new Blob([content],{type:'text/plain'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='plonagram_csv_error_report.txt'; a.click(); URL.revokeObjectURL(a.href); }
  async function generate(){ setBusy({title:'Planogram üretiliyor',subtitle:'Fulya Store DNA, fixture kapasitesi ve SKU grafiği hesaplanıyor.',steps:['Reading Store DNA','Mapping Fixtures','Building SKU Graph','Calculating Refill Risk','Generating Planogram'],onCancel:()=>setBusy(null)}); try{ const payload={ products, mode:'HYBRID', layout:{...storePayload(store)} }; const res=await api.generatePlanogram(payload); const next=normalizePlan(res.planogram||res.layout,planogram); setPlanogram(next); const s=planStats(next); setToast(`Plan üretildi: ${res.summary?.placed_products||s.products} ürün yerleşti. ${s.aisles} koridor / ${s.modules} modül / ${s.shelves} raf yüklendi. ${res.store_dna?.fulya_store_dna_v1?'Fulya Store DNA aktif.':'Store DNA kontrol edilmeli.'}`); setActive('planogram'); }catch(e){ setToast(`Plan üretimi başarısız: ${e.message}`); }finally{ setBusy(null); } }
  const page = active==='command'?<CommandCenter stats={stats} onGenerate={generate} setActive={setActive}/>:active==='live3d'?<Live3D plan={planogram} setSelectedShelf={setSelectedShelf}/>:active==='planogram'||active==='placement'?<PlanogramWorkspace plan={planogram} setPlan={setPlanogram} selectedShelf={selectedShelf} setSelectedShelf={setSelectedShelf} products={products}/>:active==='rules'?<RuleEngine onGenerate={generate}/>:<Placeholder title={t[active]||active}/>;
  return <Shell active={active} setActive={setActive} t={t}><TopBar store={store} setStore={setStore} lang={lang} setLang={setLang} t={t} onUpload={()=>fileRef.current?.click()} onLayout={()=>layoutRef.current?.click()} onGenerate={generate}/>{page}<input hidden ref={fileRef} type="file" accept=".csv,.xlsx" onChange={e=>handleUploadFile(e.target.files?.[0])}/><input hidden ref={layoutRef} type="file" accept=".json,.dxf" onChange={e=>setToast('Layout yükleme bir sonraki modülde parse edilecek.')}/>{busy&&<PremiumLoader {...busy}/>} {toast&&<div className="po-toast" onClick={()=>setToast('')}>{toast}</div>}</Shell> }
