const catalogs = {
  tr: {
    title: "Field Yönetişim Merkezi", subtitle: "Tekrarlama, muafiyet, hedefleme, dışa aktarma ve modül promosyonlarını yönetin.",
    back: "Field ana ekranına dön", mission: "Görev", refresh: "Yenile", targeting: "Yönetilen hedefleme", criterion: "Kriter", preview: "Hedefleri önizle",
    targetCount: "Hedef sayısı", recurrence: "Tekrarlama", cadence: "Sıklık", daily: "Günlük", weekly: "Haftalık", monthly: "Aylık", interval: "Aralık", timezone: "Saat dilimi", window: "Tamamlama penceresi (dk)", effectiveFrom: "Başlangıç", effectiveUntil: "Bitiş (opsiyonel)", saveRecurrence: "Tekrarlamayı kaydet",
    exemption: "Hedef muafiyeti", location: "Lokasyon", reasonCode: "Neden kodu", reason: "Açıklama", evidenceRef: "Kanıt referansı (opsiyonel)", exempt: "Muaf tut",
    export: "Yönetilen dışa aktarma", format: "Format", requestExport: "Dışa aktarma talebi oluştur", pendingApproval: "Onay bekleyen talep oluşturuldu", promotions: "Modül promosyonları", noPromotions: "Promosyon talebi yok", truthBoundary: "Field kanıtı doğrudan Inventory, Planogram veya Budget gerçeği değildir.",
    loading: "Yükleniyor…", error: "İşlem tamamlanamadı.", saved: "Kaydedildi.", noMission: "Uygun görev yok.", overdue: "Geciken", rework: "Yeniden çalışma", unseen: "Görülmemiş",
  },
  en: {
    title: "Field Governance Center", subtitle: "Govern recurrence, exemptions, targeting, exports and module promotions.",
    back: "Back to Field workspace", mission: "Mission", refresh: "Refresh", targeting: "Governed targeting", criterion: "Criterion", preview: "Preview targets",
    targetCount: "Target count", recurrence: "Recurrence", cadence: "Cadence", daily: "Daily", weekly: "Weekly", monthly: "Monthly", interval: "Interval", timezone: "Timezone", window: "Completion window (min)", effectiveFrom: "Effective from", effectiveUntil: "Effective until (optional)", saveRecurrence: "Save recurrence",
    exemption: "Target exemption", location: "Location", reasonCode: "Reason code", reason: "Reason", evidenceRef: "Evidence reference (optional)", exempt: "Exempt target",
    export: "Governed export", format: "Format", requestExport: "Create export request", pendingApproval: "Export request is pending approval", promotions: "Module promotions", noPromotions: "No promotion requests", truthBoundary: "Field evidence is not direct Inventory, Planogram or Budget truth.",
    loading: "Loading…", error: "The operation could not be completed.", saved: "Saved.", noMission: "No eligible mission.", overdue: "Overdue", rework: "Rework", unseen: "Unseen",
  },
  de: {
    title: "Field-Governance-Zentrum", subtitle: "Wiederholung, Ausnahmen, Zielgruppen, Exporte und Modul-Promotions steuern.", back: "Zurück zum Field-Arbeitsbereich", mission: "Mission", refresh: "Aktualisieren", targeting: "Governed Targeting", criterion: "Kriterium", preview: "Ziele anzeigen", targetCount: "Anzahl Ziele", recurrence: "Wiederholung", cadence: "Rhythmus", daily: "Täglich", weekly: "Wöchentlich", monthly: "Monatlich", interval: "Intervall", timezone: "Zeitzone", window: "Zeitfenster (Min.)", effectiveFrom: "Gültig ab", effectiveUntil: "Gültig bis (optional)", saveRecurrence: "Wiederholung speichern", exemption: "Zielausnahme", location: "Standort", reasonCode: "Grundcode", reason: "Grund", evidenceRef: "Nachweisreferenz (optional)", exempt: "Ziel ausnehmen", export: "Governed Export", format: "Format", requestExport: "Exportanfrage erstellen", pendingApproval: "Exportanfrage wartet auf Freigabe", promotions: "Modul-Promotions", noPromotions: "Keine Promotion-Anfragen", truthBoundary: "Field-Nachweise sind nicht direkt Inventory-, Planogram- oder Budget-Wahrheit.", loading: "Wird geladen…", error: "Vorgang konnte nicht abgeschlossen werden.", saved: "Gespeichert.", noMission: "Keine geeignete Mission.", overdue: "Überfällig", rework: "Nacharbeit", unseen: "Ungesehen",
  },
  ar: {
    title: "مركز حوكمة الميدان", subtitle: "إدارة التكرار والاستثناءات والاستهداف والتصدير والترقية بين الوحدات.", back: "العودة إلى مساحة الميدان", mission: "المهمة", refresh: "تحديث", targeting: "الاستهداف المحكوم", criterion: "المعيار", preview: "معاينة الأهداف", targetCount: "عدد الأهداف", recurrence: "التكرار", cadence: "الدورية", daily: "يومي", weekly: "أسبوعي", monthly: "شهري", interval: "الفاصل", timezone: "المنطقة الزمنية", window: "نافذة الإكمال (دقيقة)", effectiveFrom: "ساري من", effectiveUntil: "ساري حتى (اختياري)", saveRecurrence: "حفظ التكرار", exemption: "استثناء الهدف", location: "الموقع", reasonCode: "رمز السبب", reason: "السبب", evidenceRef: "مرجع الدليل (اختياري)", exempt: "استثناء الهدف", export: "تصدير محكوم", format: "التنسيق", requestExport: "إنشاء طلب تصدير", pendingApproval: "طلب التصدير بانتظار الموافقة", promotions: "ترقيات الوحدات", noPromotions: "لا توجد طلبات ترقية", truthBoundary: "دليل الميدان ليس حقيقة مباشرة للمخزون أو المخطط أو الميزانية.", loading: "جارٍ التحميل…", error: "تعذر إكمال العملية.", saved: "تم الحفظ.", noMission: "لا توجد مهمة مؤهلة.", overdue: "متأخر", rework: "إعادة عمل", unseen: "غير مرئي",
  },
  fr: {
    title: "Centre de gouvernance Field", subtitle: "Gérez récurrence, exemptions, ciblage, exports et promotions de modules.", back: "Retour à l’espace Field", mission: "Mission", refresh: "Actualiser", targeting: "Ciblage gouverné", criterion: "Critère", preview: "Prévisualiser les cibles", targetCount: "Nombre de cibles", recurrence: "Récurrence", cadence: "Cadence", daily: "Quotidien", weekly: "Hebdomadaire", monthly: "Mensuel", interval: "Intervalle", timezone: "Fuseau horaire", window: "Fenêtre d’exécution (min)", effectiveFrom: "Effectif à partir de", effectiveUntil: "Effectif jusqu’à (optionnel)", saveRecurrence: "Enregistrer la récurrence", exemption: "Exemption de cible", location: "Emplacement", reasonCode: "Code motif", reason: "Motif", evidenceRef: "Référence de preuve (optionnel)", exempt: "Exempter la cible", export: "Export gouverné", format: "Format", requestExport: "Créer une demande d’export", pendingApproval: "La demande d’export attend une approbation", promotions: "Promotions de modules", noPromotions: "Aucune demande de promotion", truthBoundary: "La preuve Field n’est pas directement la vérité Inventory, Planogram ou Budget.", loading: "Chargement…", error: "L’opération n’a pas pu être terminée.", saved: "Enregistré.", noMission: "Aucune mission éligible.", overdue: "En retard", rework: "À refaire", unseen: "Non vu",
  },
  es: {
    title: "Centro de gobernanza Field", subtitle: "Gestione recurrencia, exenciones, segmentación, exportaciones y promociones de módulos.", back: "Volver al espacio Field", mission: "Misión", refresh: "Actualizar", targeting: "Segmentación gobernada", criterion: "Criterio", preview: "Previsualizar objetivos", targetCount: "Número de objetivos", recurrence: "Recurrencia", cadence: "Cadencia", daily: "Diario", weekly: "Semanal", monthly: "Mensual", interval: "Intervalo", timezone: "Zona horaria", window: "Ventana de finalización (min)", effectiveFrom: "Vigente desde", effectiveUntil: "Vigente hasta (opcional)", saveRecurrence: "Guardar recurrencia", exemption: "Exención de objetivo", location: "Ubicación", reasonCode: "Código de motivo", reason: "Motivo", evidenceRef: "Referencia de evidencia (opcional)", exempt: "Eximir objetivo", export: "Exportación gobernada", format: "Formato", requestExport: "Crear solicitud de exportación", pendingApproval: "La solicitud espera aprobación", promotions: "Promociones de módulos", noPromotions: "No hay solicitudes de promoción", truthBoundary: "La evidencia Field no es verdad directa de Inventory, Planogram o Budget.", loading: "Cargando…", error: "No se pudo completar la operación.", saved: "Guardado.", noMission: "No hay misión elegible.", overdue: "Vencido", rework: "Rehacer", unseen: "No visto",
  },
  it: {
    title: "Centro governance Field", subtitle: "Gestisci ricorrenze, esenzioni, targeting, esportazioni e promozioni dei moduli.", back: "Torna allo spazio Field", mission: "Missione", refresh: "Aggiorna", targeting: "Targeting governato", criterion: "Criterio", preview: "Anteprima target", targetCount: "Numero target", recurrence: "Ricorrenza", cadence: "Cadenza", daily: "Giornaliero", weekly: "Settimanale", monthly: "Mensile", interval: "Intervallo", timezone: "Fuso orario", window: "Finestra completamento (min)", effectiveFrom: "Valido da", effectiveUntil: "Valido fino a (opzionale)", saveRecurrence: "Salva ricorrenza", exemption: "Esenzione target", location: "Sede", reasonCode: "Codice motivo", reason: "Motivo", evidenceRef: "Riferimento evidenza (opzionale)", exempt: "Esenta target", export: "Esportazione governata", format: "Formato", requestExport: "Crea richiesta export", pendingApproval: "La richiesta export attende approvazione", promotions: "Promozioni moduli", noPromotions: "Nessuna richiesta di promozione", truthBoundary: "L’evidenza Field non è verità diretta di Inventory, Planogram o Budget.", loading: "Caricamento…", error: "Impossibile completare l’operazione.", saved: "Salvato.", noMission: "Nessuna missione idonea.", overdue: "Scaduto", rework: "Da rifare", unseen: "Non visto",
  },
  nl: {
    title: "Field Governance Center", subtitle: "Beheer herhaling, vrijstellingen, targeting, exports en modulepromoties.", back: "Terug naar Field-werkruimte", mission: "Missie", refresh: "Vernieuwen", targeting: "Beheerde targeting", criterion: "Criterium", preview: "Doelen bekijken", targetCount: "Aantal doelen", recurrence: "Herhaling", cadence: "Frequentie", daily: "Dagelijks", weekly: "Wekelijks", monthly: "Maandelijks", interval: "Interval", timezone: "Tijdzone", window: "Voltooiingsvenster (min)", effectiveFrom: "Geldig vanaf", effectiveUntil: "Geldig tot (optioneel)", saveRecurrence: "Herhaling opslaan", exemption: "Doelvrijstelling", location: "Locatie", reasonCode: "Redencode", reason: "Reden", evidenceRef: "Bewijsreferentie (optioneel)", exempt: "Doel vrijstellen", export: "Beheerde export", format: "Formaat", requestExport: "Exportaanvraag maken", pendingApproval: "Exportaanvraag wacht op goedkeuring", promotions: "Modulepromoties", noPromotions: "Geen promotieaanvragen", truthBoundary: "Field-bewijs is niet direct de waarheid van Inventory, Planogram of Budget.", loading: "Laden…", error: "De bewerking kon niet worden voltooid.", saved: "Opgeslagen.", noMission: "Geen geschikte missie.", overdue: "Te laat", rework: "Herwerk", unseen: "Ongezien",
  },
  pl: {
    title: "Centrum zarządzania Field", subtitle: "Zarządzaj cyklicznością, wyjątkami, targetowaniem, eksportami i promocjami modułów.", back: "Wróć do przestrzeni Field", mission: "Misja", refresh: "Odśwież", targeting: "Kontrolowane targetowanie", criterion: "Kryterium", preview: "Podgląd celów", targetCount: "Liczba celów", recurrence: "Cykliczność", cadence: "Częstotliwość", daily: "Codziennie", weekly: "Co tydzień", monthly: "Co miesiąc", interval: "Interwał", timezone: "Strefa czasowa", window: "Okno realizacji (min)", effectiveFrom: "Obowiązuje od", effectiveUntil: "Obowiązuje do (opcjonalnie)", saveRecurrence: "Zapisz cykliczność", exemption: "Wyjątek celu", location: "Lokalizacja", reasonCode: "Kod powodu", reason: "Powód", evidenceRef: "Referencja dowodu (opcjonalnie)", exempt: "Zwolnij cel", export: "Kontrolowany eksport", format: "Format", requestExport: "Utwórz wniosek eksportu", pendingApproval: "Wniosek eksportu czeka na zatwierdzenie", promotions: "Promocje modułów", noPromotions: "Brak wniosków o promocję", truthBoundary: "Dowód Field nie jest bezpośrednią prawdą Inventory, Planogram ani Budget.", loading: "Ładowanie…", error: "Nie udało się ukończyć operacji.", saved: "Zapisano.", noMission: "Brak odpowiedniej misji.", overdue: "Po terminie", rework: "Do poprawy", unseen: "Niewidziane",
  },
  "pt-BR": {
    title: "Central de Governança Field", subtitle: "Gerencie recorrência, exceções, direcionamento, exportações e promoções de módulos.", back: "Voltar ao espaço Field", mission: "Missão", refresh: "Atualizar", targeting: "Direcionamento governado", criterion: "Critério", preview: "Visualizar alvos", targetCount: "Quantidade de alvos", recurrence: "Recorrência", cadence: "Cadência", daily: "Diário", weekly: "Semanal", monthly: "Mensal", interval: "Intervalo", timezone: "Fuso horário", window: "Janela de conclusão (min)", effectiveFrom: "Vigente a partir de", effectiveUntil: "Vigente até (opcional)", saveRecurrence: "Salvar recorrência", exemption: "Exceção de alvo", location: "Local", reasonCode: "Código do motivo", reason: "Motivo", evidenceRef: "Referência de evidência (opcional)", exempt: "Isentar alvo", export: "Exportação governada", format: "Formato", requestExport: "Criar solicitação de exportação", pendingApproval: "Solicitação aguardando aprovação", promotions: "Promoções de módulos", noPromotions: "Nenhuma solicitação de promoção", truthBoundary: "A evidência Field não é verdade direta de Inventory, Planogram ou Budget.", loading: "Carregando…", error: "Não foi possível concluir a operação.", saved: "Salvo.", noMission: "Nenhuma missão elegível.", overdue: "Atrasado", rework: "Refazer", unseen: "Não visto",
  },
};

export function translateFieldGovernance(locale, key) {
  return catalogs[locale]?.[key] || catalogs.en[key] || key;
}

export const FIELD_GOVERNANCE_LOCALES = Object.freeze(Object.keys(catalogs));
