const en = {
  moduleTitle: "Field Intelligence", moduleDescription: "Create governed missions, collect physical evidence, review rework and monitor completion from server authority.",
  commandCenter: "Command Center", missions: "Missions", missionBuilder: "Mission Builder", templates: "Templates", capture: "Fast Capture", evidenceReview: "Evidence Review", analytics: "Analytics",
  loading: "Loading Field Intelligence…", loadError: "Field Intelligence could not be loaded from the authoritative service.", offline: "You are offline. Field mutations are disabled until connectivity returns.", empty: "No Field records are available in your authorized scope.", refresh: "Refresh",
  activeMissions: "Active missions", targetCount: "Targets", completion: "Completion", overdueTargets: "Overdue targets", statusDistribution: "Target status distribution",
  missionTitle: "Mission title", instructions: "Instructions", priority: "Priority", normal: "Normal", high: "High", critical: "Critical", template: "Template", assignedAt: "Assigned at", deadlineAt: "Deadline", activateImmediately: "Activate immediately", allActiveLocations: "All active authorized locations", selectedLocations: "Selected locations", targetingPreview: "Target preview", serverTargetAuthority: "Preview is informational. The server resolves and freezes the authoritative target snapshot on creation.", createMission: "Create mission", missionCreated: "Mission created", targetFingerprint: "Target fingerprint", cancelMission: "Cancel mission", activateMission: "Activate mission",
  templateEditor: "Template editor", templateId: "Template ID", version: "Version", templateName: "Template name", templateStatus: "Template status", draft: "Draft", active: "Active", addField: "Add field", removeField: "Remove field", fieldKey: "Field key", fieldLabel: "Field label", fieldType: "Field type", required: "Required", saveTemplate: "Save template", templateCreated: "Template created",
  typeText: "Text", typeNumber: "Number", typeSelect: "Select", typeBarcode: "Barcode", typeQr: "QR", typePhoto: "Photo", typeLot: "Lot", typeBatch: "Batch", typeExpiry: "Expiry", typeQuantity: "Quantity", typeMeasurement: "Measurement", typeGps: "GPS", typeYesNo: "Yes / No", typeMultiRow: "Multi-row",
  quickCapture: "Fast warehouse capture", chooseMission: "Choose mission", chooseLocation: "Choose target location", submitEvidence: "Submit evidence", evidenceSubmitted: "Evidence submitted", noCaptureTargets: "No actionable mission target is available in your scope.", gpsCapture: "Capture GPS observation", gpsObserved: "GPS observation captured", photoUnavailable: "Photo requires the private evidence transport. Raw files, base64 and public URLs are rejected.", addRow: "Add row", removeRow: "Remove row",
  review: "Review", accept: "Accept", rework: "Rework", reject: "Reject", reason: "Reason", noEvidence: "No submitted evidence is awaiting review.", sendReminder: "Queue reminder", escalate: "Queue escalation", queuedNotSent: "Notification intent queued. Delivery is not claimed until the shared notification service dispatches it.",
  missionDetail: "Mission detail", noMissions: "No missions are available.", noTemplates: "No templates are available.", selectedTargets: "Selected targets", evidenceFingerprint: "Evidence fingerprint", reviewDecision: "Review decision", providerBoundary: "Shared notification provider required", clientDeviceUnverified: "Client device ID is observation metadata, not trusted-device proof.", location: "Location", createdBy: "Created by", deadlineOverdue: "Deadline overdue", permissionDenied: "Your current server-authorized permissions do not allow this Field action.",
};

const tr = {
  moduleTitle: "Field Intelligence", moduleDescription: "Yönetilen görevler oluşturun, fiziksel kanıt toplayın, yeniden çalışma inceleyin ve tamamlanmayı sunucu otoritesinden izleyin.",
  commandCenter: "Komuta Merkezi", missions: "Görevler", missionBuilder: "Görev Oluşturucu", templates: "Şablonlar", capture: "Hızlı Toplama", evidenceReview: "Kanıt İnceleme", analytics: "Analitik",
  loading: "Field Intelligence yükleniyor…", loadError: "Field Intelligence yetkili servisten yüklenemedi.", offline: "Çevrimdışısınız. Bağlantı geri gelene kadar Field değişiklikleri kapalıdır.", empty: "Yetkili kapsamınızda Field kaydı yok.", refresh: "Yenile",
  activeMissions: "Aktif görevler", targetCount: "Hedefler", completion: "Tamamlanma", overdueTargets: "Geciken hedefler", statusDistribution: "Hedef durum dağılımı",
  missionTitle: "Görev başlığı", instructions: "Talimatlar", priority: "Öncelik", normal: "Normal", high: "Yüksek", critical: "Kritik", template: "Şablon", assignedAt: "Atama zamanı", deadlineAt: "Son tarih", activateImmediately: "Hemen aktifleştir", allActiveLocations: "Tüm aktif yetkili lokasyonlar", selectedLocations: "Seçili lokasyonlar", targetingPreview: "Hedef önizleme", serverTargetAuthority: "Önizleme bilgilendirme amaçlıdır. Otoritatif hedef snapshot'ını oluştururken sunucu çözer ve dondurur.", createMission: "Görev oluştur", missionCreated: "Görev oluşturuldu", targetFingerprint: "Hedef parmak izi", cancelMission: "Görevi iptal et", activateMission: "Görevi aktifleştir",
  templateEditor: "Şablon editörü", templateId: "Şablon kimliği", version: "Versiyon", templateName: "Şablon adı", templateStatus: "Şablon durumu", draft: "Taslak", active: "Aktif", addField: "Alan ekle", removeField: "Alanı kaldır", fieldKey: "Alan anahtarı", fieldLabel: "Alan etiketi", fieldType: "Alan tipi", required: "Zorunlu", saveTemplate: "Şablonu kaydet", templateCreated: "Şablon oluşturuldu",
  typeText: "Metin", typeNumber: "Sayı", typeSelect: "Seçim", typeBarcode: "Barkod", typeQr: "QR", typePhoto: "Fotoğraf", typeLot: "Lot", typeBatch: "Batch", typeExpiry: "SKT", typeQuantity: "Miktar", typeMeasurement: "Ölçüm", typeGps: "GPS", typeYesNo: "Evet / Hayır", typeMultiRow: "Çok satır",
  quickCapture: "Hızlı depo toplama", chooseMission: "Görev seç", chooseLocation: "Hedef lokasyon seç", submitEvidence: "Kanıtı gönder", evidenceSubmitted: "Kanıt gönderildi", noCaptureTargets: "Kapsamınızda aksiyon alınabilir görev hedefi yok.", gpsCapture: "GPS gözlemi al", gpsObserved: "GPS gözlemi alındı", photoUnavailable: "Fotoğraf için özel kanıt taşıma hattı gerekir. Ham dosya, base64 ve public URL reddedilir.", addRow: "Satır ekle", removeRow: "Satırı kaldır",
  review: "İncele", accept: "Kabul et", rework: "Yeniden çalışma", reject: "Reddet", reason: "Gerekçe", noEvidence: "İnceleme bekleyen gönderilmiş kanıt yok.", sendReminder: "Hatırlatma kuyruğa al", escalate: "Eskalasyonu kuyruğa al", queuedNotSent: "Bildirim niyeti kuyruğa alındı. Ortak bildirim servisi göndermeden teslim edildi sayılmaz.",
  missionDetail: "Görev detayı", noMissions: "Görev bulunmuyor.", noTemplates: "Şablon bulunmuyor.", selectedTargets: "Seçili hedefler", evidenceFingerprint: "Kanıt parmak izi", reviewDecision: "İnceleme kararı", providerBoundary: "Ortak bildirim sağlayıcısı gerekli", clientDeviceUnverified: "İstemci cihaz kimliği gözlem metadatasıdır; güvenilir cihaz kanıtı değildir.", location: "Lokasyon", createdBy: "Oluşturan", deadlineOverdue: "Son tarih geçti", permissionDenied: "Mevcut sunucu-yetkili izinleriniz bu Field aksiyonuna izin vermiyor.",
};

const de = { ...en, moduleDescription: "Gesteuerte Missionen erstellen, physische Nachweise erfassen, Nacharbeit prüfen und Abschluss über Serverautorität verfolgen.", commandCenter: "Leitstand", missions: "Missionen", missionBuilder: "Missions-Builder", templates: "Vorlagen", capture: "Schnellerfassung", evidenceReview: "Nachweisprüfung", analytics: "Analysen", loading: "Field Intelligence wird geladen…", loadError: "Field Intelligence konnte nicht vom autoritativen Dienst geladen werden.", offline: "Sie sind offline. Field-Änderungen bleiben bis zur Wiederverbindung deaktiviert.", empty: "Keine Field-Daten im autorisierten Umfang.", refresh: "Aktualisieren", activeMissions: "Aktive Missionen", targetCount: "Ziele", completion: "Abschluss", overdueTargets: "Überfällige Ziele", createMission: "Mission erstellen", templateEditor: "Vorlageneditor", quickCapture: "Schnelle Lagererfassung", submitEvidence: "Nachweis senden", accept: "Akzeptieren", rework: "Nacharbeit", reject: "Ablehnen", reason: "Grund", sendReminder: "Erinnerung einreihen", escalate: "Eskalation einreihen", photoUnavailable: "Fotos benötigen den privaten Nachweis-Transport. Rohdateien, Base64 und öffentliche URLs werden abgelehnt." };
const ar = { ...en, moduleDescription: "إنشاء مهام محكومة وجمع أدلة مادية ومراجعة إعادة العمل ومتابعة الإنجاز من سلطة الخادم.", commandCenter: "مركز القيادة", missions: "المهام", missionBuilder: "منشئ المهام", templates: "القوالب", capture: "التقاط سريع", evidenceReview: "مراجعة الأدلة", analytics: "التحليلات", loading: "جارٍ تحميل Field Intelligence…", loadError: "تعذر تحميل Field Intelligence من الخدمة الموثوقة.", offline: "أنت غير متصل. تعديلات Field متوقفة حتى عودة الاتصال.", empty: "لا توجد سجلات Field ضمن نطاقك المصرح.", refresh: "تحديث", activeMissions: "المهام النشطة", targetCount: "الأهداف", completion: "الإنجاز", overdueTargets: "الأهداف المتأخرة", createMission: "إنشاء مهمة", templateEditor: "محرر القالب", quickCapture: "التقاط سريع للمستودع", submitEvidence: "إرسال الدليل", accept: "قبول", rework: "إعادة العمل", reject: "رفض", reason: "السبب", sendReminder: "وضع التذكير في الطابور", escalate: "وضع التصعيد في الطابور", photoUnavailable: "تتطلب الصورة قناة الأدلة الخاصة. تُرفض الملفات الخام وBase64 والروابط العامة." };
const fr = { ...en, moduleDescription: "Créez des missions gouvernées, collectez des preuves physiques, traitez les reprises et suivez l’exécution depuis l’autorité serveur.", commandCenter: "Centre de commande", missions: "Missions", missionBuilder: "Créateur de mission", templates: "Modèles", capture: "Saisie rapide", evidenceReview: "Revue des preuves", analytics: "Analytique", loading: "Chargement de Field Intelligence…", loadError: "Field Intelligence n’a pas pu être chargé depuis le service faisant autorité.", offline: "Vous êtes hors ligne. Les mutations Field sont désactivées jusqu’au retour de la connexion.", empty: "Aucune donnée Field dans votre périmètre autorisé.", refresh: "Actualiser", activeMissions: "Missions actives", targetCount: "Cibles", completion: "Achèvement", overdueTargets: "Cibles en retard", createMission: "Créer la mission", templateEditor: "Éditeur de modèle", quickCapture: "Saisie rapide entrepôt", submitEvidence: "Envoyer la preuve", accept: "Accepter", rework: "Reprise", reject: "Rejeter", reason: "Motif", sendReminder: "Mettre le rappel en file", escalate: "Mettre l’escalade en file", photoUnavailable: "La photo nécessite le transport privé des preuves. Les fichiers bruts, Base64 et URL publiques sont refusés." };
const es = { ...en, moduleDescription: "Cree misiones gobernadas, recopile evidencia física, revise retrabajos y supervise la finalización desde la autoridad del servidor.", commandCenter: "Centro de mando", missions: "Misiones", missionBuilder: "Constructor de misiones", templates: "Plantillas", capture: "Captura rápida", evidenceReview: "Revisión de evidencia", analytics: "Analítica", loading: "Cargando Field Intelligence…", loadError: "No se pudo cargar Field Intelligence desde el servicio autoritativo.", offline: "Está sin conexión. Las mutaciones de Field quedan deshabilitadas hasta recuperar conectividad.", empty: "No hay registros Field en su alcance autorizado.", refresh: "Actualizar", activeMissions: "Misiones activas", targetCount: "Objetivos", completion: "Finalización", overdueTargets: "Objetivos vencidos", createMission: "Crear misión", templateEditor: "Editor de plantillas", quickCapture: "Captura rápida de almacén", submitEvidence: "Enviar evidencia", accept: "Aceptar", rework: "Retrabajo", reject: "Rechazar", reason: "Motivo", sendReminder: "Encolar recordatorio", escalate: "Encolar escalado", photoUnavailable: "La foto requiere transporte privado de evidencia. Se rechazan archivos sin procesar, Base64 y URL públicas." };
const it = { ...en, moduleDescription: "Crea missioni governate, raccogli prove fisiche, gestisci le rilavorazioni e monitora il completamento tramite autorità server.", commandCenter: "Centro di comando", missions: "Missioni", missionBuilder: "Costruttore missioni", templates: "Modelli", capture: "Acquisizione rapida", evidenceReview: "Revisione prove", analytics: "Analisi", loading: "Caricamento Field Intelligence…", loadError: "Impossibile caricare Field Intelligence dal servizio autorevole.", offline: "Sei offline. Le modifiche Field sono disabilitate finché non torna la connettività.", empty: "Nessun record Field nel tuo ambito autorizzato.", refresh: "Aggiorna", activeMissions: "Missioni attive", targetCount: "Obiettivi", completion: "Completamento", overdueTargets: "Obiettivi scaduti", createMission: "Crea missione", templateEditor: "Editor modelli", quickCapture: "Acquisizione rapida magazzino", submitEvidence: "Invia prova", accept: "Accetta", rework: "Rilavorazione", reject: "Rifiuta", reason: "Motivo", sendReminder: "Accoda promemoria", escalate: "Accoda escalation", photoUnavailable: "La foto richiede il trasporto privato delle prove. File grezzi, Base64 e URL pubblici vengono rifiutati." };
const nl = { ...en, moduleDescription: "Maak beheerde missies, verzamel fysiek bewijs, beoordeel herwerk en volg voltooiing via serverautoriteit.", commandCenter: "Commandocentrum", missions: "Missies", missionBuilder: "Missiebouwer", templates: "Sjablonen", capture: "Snelle invoer", evidenceReview: "Bewijsbeoordeling", analytics: "Analyse", loading: "Field Intelligence laden…", loadError: "Field Intelligence kon niet vanuit de gezaghebbende service worden geladen.", offline: "Je bent offline. Field-mutaties zijn uitgeschakeld tot de verbinding terug is.", empty: "Geen Field-records binnen je geautoriseerde scope.", refresh: "Vernieuwen", activeMissions: "Actieve missies", targetCount: "Doelen", completion: "Voltooiing", overdueTargets: "Verlopen doelen", createMission: "Missie maken", templateEditor: "Sjablooneditor", quickCapture: "Snelle magazijninvoer", submitEvidence: "Bewijs indienen", accept: "Accepteren", rework: "Herwerk", reject: "Afwijzen", reason: "Reden", sendReminder: "Herinnering in wachtrij", escalate: "Escalatie in wachtrij", photoUnavailable: "Foto vereist privé-bewijstransport. Ruwe bestanden, Base64 en openbare URL’s worden geweigerd." };
const pl = { ...en, moduleDescription: "Twórz zarządzane misje, zbieraj dowody fizyczne, przeglądaj poprawki i monitoruj realizację z autorytetu serwera.", commandCenter: "Centrum dowodzenia", missions: "Misje", missionBuilder: "Kreator misji", templates: "Szablony", capture: "Szybkie zbieranie", evidenceReview: "Przegląd dowodów", analytics: "Analityka", loading: "Ładowanie Field Intelligence…", loadError: "Nie udało się załadować Field Intelligence z autorytatywnej usługi.", offline: "Jesteś offline. Zmiany Field są wyłączone do powrotu łączności.", empty: "Brak rekordów Field w autoryzowanym zakresie.", refresh: "Odśwież", activeMissions: "Aktywne misje", targetCount: "Cele", completion: "Realizacja", overdueTargets: "Zaległe cele", createMission: "Utwórz misję", templateEditor: "Edytor szablonów", quickCapture: "Szybkie zbieranie magazynowe", submitEvidence: "Prześlij dowód", accept: "Akceptuj", rework: "Poprawa", reject: "Odrzuć", reason: "Powód", sendReminder: "Dodaj przypomnienie do kolejki", escalate: "Dodaj eskalację do kolejki", photoUnavailable: "Zdjęcie wymaga prywatnego transportu dowodów. Surowe pliki, Base64 i publiczne URL są odrzucane." };
const ptBR = { ...en, moduleDescription: "Crie missões governadas, colete evidências físicas, revise retrabalho e acompanhe a conclusão pela autoridade do servidor.", commandCenter: "Central de comando", missions: "Missões", missionBuilder: "Construtor de missões", templates: "Modelos", capture: "Captura rápida", evidenceReview: "Revisão de evidências", analytics: "Análises", loading: "Carregando Field Intelligence…", loadError: "Não foi possível carregar Field Intelligence pelo serviço autoritativo.", offline: "Você está offline. As mutações Field ficam desativadas até a conectividade voltar.", empty: "Não há registros Field no seu escopo autorizado.", refresh: "Atualizar", activeMissions: "Missões ativas", targetCount: "Alvos", completion: "Conclusão", overdueTargets: "Alvos atrasados", createMission: "Criar missão", templateEditor: "Editor de modelos", quickCapture: "Captura rápida de armazém", submitEvidence: "Enviar evidência", accept: "Aceitar", rework: "Retrabalho", reject: "Rejeitar", reason: "Motivo", sendReminder: "Enfileirar lembrete", escalate: "Enfileirar escalonamento", photoUnavailable: "Foto exige transporte privado de evidências. Arquivos brutos, Base64 e URLs públicas são rejeitados." };

export const FIELD_MESSAGES = Object.freeze({ tr, en, de, ar, fr, es, it, nl, pl, "pt-BR": ptBR });

export function translateField(locale, key, params = {}) {
  const message = FIELD_MESSAGES[locale]?.[key];
  if (typeof message !== "string") return key;
  return message.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}

export function fieldMessageCoverage(locales) {
  const keys = Object.keys(FIELD_MESSAGES.en).sort();
  return Object.fromEntries(locales.map((locale) => [locale, keys.filter((key) => typeof FIELD_MESSAGES[locale]?.[key] !== "string")]));
}
