import React, { createContext, useContext, useMemo, useState } from "react";

const tr = {
  notifications: "Bildirim Merkezi",
  workspace: "Çalışma Alanı",
  supplier: "Tedarikçi Portalı",
  admin: "Merkez Depo Operasyon",
  planning: "PO Yükleme",
  capacity: "Kapasite Yönetimi",
  audit: "Audit Kayıtları",
  kpi: "KPI & Analitik",
  openPo: "Açık PO",
  totalReservation: "Toplam Rezervasyon",
  activeReservation: "Aktif Rezervasyon",
  avgCapacity: "Ortalama Kapasite",
  refresh: "Verileri Yenile",
  connected: "Backend bağlı",
  disconnected: "Backend bağlantısı yok",
  checking: "Bağlantı kontrol ediliyor",
  appearance: "Görünüm",
  light: "Açık",
  dark: "Koyu",
  language: "Dil",
  decisionCenter: "Inbound Karar Merkezi",
  decisionSubtitle: "KPI’ları izle, rapor kur veya sohbet ederek oluştur.",
  commandTitle: "DockOS Komut ve Rapor Alanı",
  commandSubtitle:
    "Hazır cümlelere bağlı kalmadan sor; rapor veya güvenli admin önizlemesi oluştur.",
  run: "Çalıştır",
  allSuppliers: "Tüm Tedarikçiler",
  allWarehouses: "Tüm Merkez Depolar",
  capacityTitle: "Slot ve Tedarikçi Kapasite Matrisi",
  capacitySubtitle:
    "Tarihleri, saatleri ve tedarikçi limitlerini tek ekrandan yönet.",
  dailyMax: "Günlük Max Palet",
  edit: "Düzenle",
  cancel: "İptal",
  save: "Kaydet",
  supplierKicker: "DockOS · Tedarikçi",
  supplierTitle: "Tedarikçi Rezervasyon Portalı",
  supplierSubtitle:
    "Sevkiyat veya kargo akışını seç; PO üzerinden kaydını oluştur.",
  supplierView: "Tedarikçi Görünümü",
  shipmentMethod: "1. Gönderim Yöntemi",
  dcShipment: "Merkez Depo Sevkiyatı",
  dcShipmentDesc:
    "Araç, plaka, tarih ve saat seçilir. Slot kapasitesinden düşer.",
  cargoShipment: "Kargo Gönderimi",
  cargoShipmentDesc:
    "Kargo tarihi ve takip numarası girilir. Slot kapasitesinden düşmez.",
  companyWarehousePo: "2. Firma, Merkez Depo ve PO Seçimi",
  companyWarehouse: "2. Firma ve Merkez Depo",
  supplierLabel: "Tedarikçi",
  warehouseLabel: "Merkez Depo",
  noOpenPo: "Bu tedarikçi ve depo için açık PO bulunamadı.",
  due: "Termin",
  quantityInfo: "3. Miktar Bilgileri",
  palletCount: "Palet Sayısı *",
  skuCount: "SKU Sayısı *",
  boxCount: "Koli Sayısı",
  reservationDateTime: "4. Rezervasyon Tarihi ve Saati",
  suitableDate: "Uygun Tarih *",
  selectDate: "Tarih seçin",
  suitableTime: "Uygun Saat *",
  selectTime: "Saat seçin",
  available: "Uygun",
  cargoInfo: "3. Kargo Bilgileri",
  cargoDate: "Kargo Gönderim Tarihi *",
  trackingNo: "Kargo Takip Numarası *",
  shipmentDetailsTitle: "5. Sevkiyat Detayları",
  shipmentHelp:
    "Ürün sıcaklık tipi, araç sayısı, özel boşaltma gereksinimi, planlanan geliş saati ve operasyonun bilmesi gereken istisnaları yaz.",
  shipmentDetails: "Sevkiyat Detayları *",
  waybill: "İrsaliye / Sevk No",
  shipmentForm: "Sevk Şekli",
  select: "Seçiniz",
  bulk: "Dökme",
  palletized: "Paletli",
  mixed: "Karma",
  vehicleType: "Araç Tipi",
  truck: "Kamyon",
  semiTruck: "Tır",
  van: "Kamyonet",
  vehicleCount: "Araç Sayısı",
  plates: "Araç Plakası / Plakaları *",
  saving: "Kaydediliyor...",
  createReservation: "Rezervasyon Oluştur",
  createCargo: "Kargo Kaydı Oluştur",
  upcomingRecords: "Bekleyen ve Gelecek Kayıtlarım",
  noRecords: "Henüz kayıt bulunmuyor.",
  record: "Kayıt",
  type: "Tür",
  dateTime: "Tarih / Saat",
  plateTracking: "Plaka / Takip",
  status: "Durum",
  action: "Aksiyon",
  cancelAction: "İptal Et",
  notificationKicker: "DockOS · Otomatik Bildirim Akışı",
  notificationTitle: "Kurumsal Bildirim Merkezi",
  notificationSubtitle:
    "Oluşturma, 48/24 saat hatırlatma, düzenleme ve iptal e-postalarını otomatik izler.",
  autoActive: "Otomatik Gönderim Aktif",
  sent: "Gönderildi",
  pending: "Bekliyor",
  waitingConfig: "SMTP Ayarı Bekliyor",
  failed: "Hata",
  cancelled: "İptal",
  event: "Olay",
  reservation: "Rezervasyon",
  scheduled: "Planlanan",
  recipients: "Alıcılar",
  subject: "Konu",
  attempts: "Deneme",
  waitingAddress: "Adres bekliyor",
  noNotifications: "Henüz bildirim kaydı yok.",
  autoInfo:
    "Liste otomatik yenilenir; vadesi gelen postaları backend gönderir.",
  private: "Özel",
  welcome:
    "Raporu normal cümleyle iste. Yaklaşan rezervasyon, plaka, tedarikçi, dönem veya performans sorularını anlayabilirim.",
  you: "Sen",
  reportBuilder: "No-code Rapor Kurucu",
  builderTitle: "Raporunu üç seçimle oluştur",
  buildReport: "Dinamik Rapor Oluştur",
  selectedPeriod: "Üstteki Tarih Filtresi",
  last7: "Son 7 Gün",
  thisMonth: "Bu Ay",
  generatedReport: "Otomatik Oluşturulan Rapor",
  secureAnalytics: "Güvenli Analitik",
  adminPreview: "Admin Komutu · Önizleme",
  confirmApply: "Kontrol Ettim, Limiti Uygula",
  applying: "Uygulanıyor...",
  actionSuccess: "Komut başarıyla uygulandı.",
  noData: "Seçili filtrelerde veri bulunmuyor.",
  selectedPeriodHelp: "Seçili dönemde",
  waitingOps: "Operasyon bekliyor",
  onTime: "Zamanında Geliş",
  checkedVehicles: "Kontrol edilen araçlar",
  completion: "Tamamlanma",
  closedReservations: "Kapanan rezervasyon",
  cancelRate: "İptal Oranı",
  capacityUsage: "Kapasite Kullanımı",
  palletCapacity: "Palet kapasitesi",
  reservationStatus: "Rezervasyon Durumu",
  operationStage: "Operasyonun hangi aşamada olduğunu gösterir",
  shipmentDistribution: "Gönderim Dağılımı",
  shipmentRatio: "Sevkiyat ve kargo oranı",
  supplierVolume: "Tedarikçi Hacmi",
  busiestSuppliers: "En yoğun tedarikçiler",
  warehouseVolume: "Merkez Depo Hacmi",
  warehouseDistribution: "Rezervasyonların depo dağılımı",
  dailyTrend: "Günlük Rezervasyon Trendi",
  trendSubtitle: "Toplam, geç geliş ve iptal hareketi",
  supplierPerformance: "Tedarikçi Performans Tablosu",
  compareIssues: "Sorunları tek bakışta karşılaştır",
  total: "Toplam",
  active: "Aktif",
  completed: "Tamamlanan",
  late: "Geç",
  noShow: "No-show",
  success: "Başarı",
  promptPlaceholder: "Örn: En yakın rezervasyon hangi tedarikçiye ait?",
};

const en = {
  ...tr,
  notifications: "Notification Center",
  workspace: "Workspace",
  supplier: "Supplier Portal",
  admin: "DC Operations",
  planning: "PO Upload",
  capacity: "Capacity Management",
  audit: "Audit Log",
  kpi: "KPI & Analytics",
  openPo: "Open POs",
  totalReservation: "Total Reservations",
  activeReservation: "Active Reservations",
  avgCapacity: "Average Capacity",
  refresh: "Refresh Data",
  connected: "Backend connected",
  disconnected: "Backend unavailable",
  checking: "Checking connection",
  appearance: "Appearance",
  light: "Light",
  dark: "Dark",
  language: "Language",
  decisionCenter: "Inbound Decision Center",
  decisionSubtitle: "Monitor KPIs, build reports or ask conversationally.",
  commandTitle: "DockOS Command & Report",
  commandSubtitle:
    "Ask freely without preset sentences; create a report or safe admin preview.",
  run: "Run",
  allSuppliers: "All Suppliers",
  allWarehouses: "All Distribution Centers",
  capacityTitle: "Slot & Supplier Capacity Matrix",
  capacitySubtitle: "Manage dates, slots and supplier limits in one place.",
  dailyMax: "Daily Max Pallets",
  edit: "Edit",
  cancel: "Cancel",
  save: "Save",
  supplierKicker: "DockOS · Supplier",
  supplierTitle: "Supplier Reservation Portal",
  supplierSubtitle:
    "Choose a delivery or cargo flow and create the record from a PO.",
  supplierView: "Supplier View",
  shipmentMethod: "1. Delivery Method",
  dcShipment: "Distribution Center Delivery",
  dcShipmentDesc:
    "Select vehicle, plate, date and time. It consumes slot capacity.",
  cargoShipment: "Cargo Shipment",
  cargoShipmentDesc:
    "Enter cargo date and tracking number. It does not consume slot capacity.",
  companyWarehousePo: "2. Company, Distribution Center and PO",
  companyWarehouse: "2. Company and Distribution Center",
  supplierLabel: "Supplier",
  warehouseLabel: "Distribution Center",
  noOpenPo: "No open PO was found for this supplier and DC.",
  due: "Due",
  quantityInfo: "3. Quantity Details",
  palletCount: "Pallet Count *",
  skuCount: "SKU Count *",
  boxCount: "Box Count",
  reservationDateTime: "4. Reservation Date and Time",
  suitableDate: "Available Date *",
  selectDate: "Select date",
  suitableTime: "Available Time *",
  selectTime: "Select time",
  available: "Available",
  cargoInfo: "3. Cargo Details",
  cargoDate: "Cargo Shipment Date *",
  trackingNo: "Cargo Tracking Number *",
  shipmentDetailsTitle: "5. Shipment Details",
  shipmentHelp:
    "Enter temperature type, vehicle count, unloading needs, planned arrival time and operational exceptions.",
  shipmentDetails: "Shipment Details *",
  waybill: "Waybill / Dispatch No",
  shipmentForm: "Shipment Form",
  select: "Select",
  bulk: "Loose",
  palletized: "Palletized",
  mixed: "Mixed",
  vehicleType: "Vehicle Type",
  truck: "Truck",
  semiTruck: "Semi-trailer",
  van: "Van",
  vehicleCount: "Vehicle Count",
  plates: "Vehicle Plate(s) *",
  saving: "Saving...",
  createReservation: "Create Reservation",
  createCargo: "Create Cargo Record",
  upcomingRecords: "My Pending and Upcoming Records",
  noRecords: "No records yet.",
  record: "Record",
  type: "Type",
  dateTime: "Date / Time",
  plateTracking: "Plate / Tracking",
  status: "Status",
  action: "Action",
  cancelAction: "Cancel",
  notificationKicker: "DockOS · Automated Notification Flow",
  notificationTitle: "Corporate Notification Center",
  notificationSubtitle:
    "Automatically tracks creation, 48/24-hour reminders, edits and cancellations.",
  autoActive: "Automatic Delivery Active",
  sent: "Sent",
  pending: "Pending",
  waitingConfig: "Waiting for SMTP",
  failed: "Failed",
  cancelled: "Cancelled",
  event: "Event",
  reservation: "Reservation",
  scheduled: "Scheduled",
  recipients: "Recipients",
  subject: "Subject",
  attempts: "Attempts",
  waitingAddress: "Waiting for address",
  noNotifications: "No notification records yet.",
  autoInfo: "The list refreshes automatically; the backend sends due messages.",
  private: "Private",
  welcome:
    "Ask in a normal sentence. I understand upcoming reservations, plates, suppliers, periods and performance questions.",
  you: "You",
  reportBuilder: "No-code Report Builder",
  builderTitle: "Create your report with three selections",
  buildReport: "Build Dynamic Report",
  selectedPeriod: "Date Filter Above",
  last7: "Last 7 Days",
  thisMonth: "This Month",
  generatedReport: "Automatically Generated Report",
  secureAnalytics: "Secure Analytics",
  adminPreview: "Admin Command · Preview",
  confirmApply: "Reviewed, Apply Limit",
  applying: "Applying...",
  actionSuccess: "Command applied successfully.",
  noData: "No data for the selected filters.",
  selectedPeriodHelp: "In selected period",
  waitingOps: "Waiting for operations",
  onTime: "On-time Arrival",
  checkedVehicles: "Checked vehicles",
  completion: "Completion",
  closedReservations: "Closed reservations",
  cancelRate: "Cancellation Rate",
  capacityUsage: "Capacity Usage",
  palletCapacity: "Pallet capacity",
  reservationStatus: "Reservation Status",
  operationStage: "Shows the current operational stage",
  shipmentDistribution: "Shipment Distribution",
  shipmentRatio: "Delivery and cargo ratio",
  supplierVolume: "Supplier Volume",
  busiestSuppliers: "Busiest suppliers",
  warehouseVolume: "Distribution Center Volume",
  warehouseDistribution: "Reservation distribution by DC",
  dailyTrend: "Daily Reservation Trend",
  trendSubtitle: "Total, late and cancellation movement",
  supplierPerformance: "Supplier Performance Table",
  compareIssues: "Compare issues at a glance",
  total: "Total",
  active: "Active",
  completed: "Completed",
  late: "Late",
  noShow: "No-show",
  success: "Success",
  promptPlaceholder: "Example: Which supplier owns the nearest reservation?",
};

const de = {
  ...en,
  notifications: "Benachrichtigungszentrum",
  workspace: "Arbeitsbereich",
  supplier: "Lieferantenportal",
  admin: "Zentrallager-Betrieb",
  planning: "PO-Upload",
  capacity: "Kapazitätsverwaltung",
  audit: "Audit-Protokoll",
  kpi: "KPI & Analytik",
  openPo: "Offene POs",
  totalReservation: "Reservierungen gesamt",
  activeReservation: "Aktive Reservierungen",
  avgCapacity: "Durchschnittliche Kapazität",
  refresh: "Daten aktualisieren",
  connected: "Backend verbunden",
  disconnected: "Backend nicht erreichbar",
  checking: "Verbindung wird geprüft",
  appearance: "Darstellung",
  light: "Hell",
  dark: "Dunkel",
  language: "Sprache",
  decisionCenter: "Inbound-Entscheidungszentrum",
  decisionSubtitle: "KPIs überwachen, Berichte erstellen oder frei fragen.",
  commandTitle: "DockOS Befehl & Bericht",
  commandSubtitle:
    "Ohne vorgegebene Sätze frei fragen; Bericht oder sichere Admin-Vorschau erstellen.",
  run: "Ausführen",
  allSuppliers: "Alle Lieferanten",
  allWarehouses: "Alle Zentrallager",
  capacityTitle: "Slot- und Lieferanten-Kapazitätsmatrix",
  capacitySubtitle: "Daten, Slots und Lieferantenlimits zentral verwalten.",
  dailyMax: "Tägliches Palettenmaximum",
  edit: "Bearbeiten",
  cancel: "Stornieren",
  save: "Speichern",
  supplierKicker: "DockOS · Lieferant",
  supplierTitle: "Lieferanten-Reservierungsportal",
  supplierSubtitle:
    "Liefer- oder Frachtprozess wählen und den Datensatz aus einer PO erstellen.",
  supplierView: "Lieferantenansicht",
  shipmentMethod: "1. Versandart",
  dcShipment: "Zentrallager-Anlieferung",
  dcShipmentDesc:
    "Fahrzeug, Kennzeichen, Datum und Uhrzeit wählen. Belegt Slot-Kapazität.",
  cargoShipment: "Frachtversand",
  cargoShipmentDesc:
    "Versanddatum und Sendungsnummer eingeben. Belegt keine Slot-Kapazität.",
  companyWarehousePo: "2. Firma, Zentrallager und PO",
  companyWarehouse: "2. Firma und Zentrallager",
  supplierLabel: "Lieferant",
  warehouseLabel: "Zentrallager",
  noOpenPo:
    "Für diesen Lieferanten und dieses Lager wurde keine offene PO gefunden.",
  due: "Termin",
  quantityInfo: "3. Mengenangaben",
  palletCount: "Palettenanzahl *",
  skuCount: "SKU-Anzahl *",
  boxCount: "Kartonanzahl",
  reservationDateTime: "4. Reservierungsdatum und -zeit",
  suitableDate: "Verfügbares Datum *",
  selectDate: "Datum wählen",
  suitableTime: "Verfügbare Uhrzeit *",
  selectTime: "Uhrzeit wählen",
  available: "Verfügbar",
  cargoInfo: "3. Frachtdaten",
  cargoDate: "Versanddatum *",
  trackingNo: "Sendungsnummer *",
  shipmentDetailsTitle: "5. Lieferdetails",
  shipmentHelp:
    "Temperaturtyp, Fahrzeuganzahl, Entladeanforderungen, Ankunftszeit und Ausnahmen eingeben.",
  shipmentDetails: "Lieferdetails *",
  waybill: "Lieferschein / Versandnr.",
  shipmentForm: "Versandform",
  select: "Auswählen",
  bulk: "Lose",
  palletized: "Palettiert",
  mixed: "Gemischt",
  vehicleType: "Fahrzeugtyp",
  truck: "Lkw",
  semiTruck: "Sattelzug",
  van: "Transporter",
  vehicleCount: "Fahrzeuganzahl",
  plates: "Kennzeichen *",
  saving: "Wird gespeichert...",
  createReservation: "Reservierung erstellen",
  createCargo: "Fracht erfassen",
  upcomingRecords: "Meine offenen und kommenden Datensätze",
  noRecords: "Noch keine Datensätze.",
  record: "Datensatz",
  type: "Typ",
  dateTime: "Datum / Zeit",
  plateTracking: "Kennzeichen / Tracking",
  status: "Status",
  action: "Aktion",
  cancelAction: "Stornieren",
  notificationKicker: "DockOS · Automatischer Benachrichtigungsfluss",
  notificationTitle: "Unternehmens-Benachrichtigungszentrum",
  notificationSubtitle:
    "Erstellung, 48/24-Stunden-Erinnerungen, Änderungen und Stornierungen werden automatisch verarbeitet.",
  autoActive: "Automatischer Versand aktiv",
  sent: "Gesendet",
  pending: "Ausstehend",
  waitingConfig: "Wartet auf SMTP",
  failed: "Fehlgeschlagen",
  cancelled: "Storniert",
  event: "Ereignis",
  reservation: "Reservierung",
  scheduled: "Geplant",
  recipients: "Empfänger",
  subject: "Betreff",
  attempts: "Versuche",
  waitingAddress: "Adresse fehlt",
  noNotifications: "Noch keine Benachrichtigungen.",
  autoInfo:
    "Die Liste aktualisiert sich automatisch; das Backend sendet fällige Nachrichten.",
  private: "Privat",
  welcome:
    "Stellen Sie Ihre Frage frei. Kommende Reservierungen, Kennzeichen, Lieferanten, Zeiträume und Leistung werden verstanden.",
  you: "Sie",
  reportBuilder: "No-Code-Berichtsersteller",
  builderTitle: "Bericht mit drei Auswahlen erstellen",
  buildReport: "Dynamischen Bericht erstellen",
  selectedPeriod: "Datumsfilter oben",
  last7: "Letzte 7 Tage",
  thisMonth: "Dieser Monat",
  generatedReport: "Automatisch erstellter Bericht",
  secureAnalytics: "Sichere Analyse",
  adminPreview: "Admin-Befehl · Vorschau",
  confirmApply: "Geprüft, Limit anwenden",
  applying: "Wird angewendet...",
  actionSuccess: "Befehl erfolgreich ausgeführt.",
  noData: "Keine Daten für die ausgewählten Filter.",
  selectedPeriodHelp: "Im gewählten Zeitraum",
  waitingOps: "Wartet auf Betrieb",
  onTime: "Pünktliche Ankunft",
  checkedVehicles: "Geprüfte Fahrzeuge",
  completion: "Abschluss",
  closedReservations: "Geschlossene Reservierungen",
  cancelRate: "Stornoquote",
  capacityUsage: "Kapazitätsauslastung",
  palletCapacity: "Palettenkapazität",
  reservationStatus: "Reservierungsstatus",
  operationStage: "Zeigt die aktuelle Betriebsphase",
  shipmentDistribution: "Versandverteilung",
  shipmentRatio: "Anlieferungs- und Frachtanteil",
  supplierVolume: "Lieferantenvolumen",
  busiestSuppliers: "Lieferanten mit höchstem Volumen",
  warehouseVolume: "Zentrallager-Volumen",
  warehouseDistribution: "Reservierungen nach Lager",
  dailyTrend: "Täglicher Reservierungstrend",
  trendSubtitle: "Gesamt-, Verspätungs- und Stornobewegung",
  supplierPerformance: "Lieferanten-Leistungstabelle",
  compareIssues: "Probleme auf einen Blick vergleichen",
  total: "Gesamt",
  active: "Aktiv",
  completed: "Abgeschlossen",
  late: "Verspätet",
  noShow: "Nicht erschienen",
  success: "Erfolg",
  promptPlaceholder:
    "Beispiel: Zu welchem Lieferanten gehört die nächste Reservierung?",
};

const ar = {
  ...en,
  notifications: "مركز الإشعارات",
  workspace: "مساحة العمل",
  supplier: "بوابة المورد",
  admin: "عمليات المستودع المركزي",
  planning: "تحميل أوامر الشراء",
  capacity: "إدارة السعة",
  audit: "سجل التدقيق",
  kpi: "المؤشرات والتحليلات",
  openPo: "أوامر شراء مفتوحة",
  totalReservation: "إجمالي الحجوزات",
  activeReservation: "الحجوزات النشطة",
  avgCapacity: "متوسط السعة",
  refresh: "تحديث البيانات",
  connected: "الخادم متصل",
  disconnected: "الخادم غير متاح",
  checking: "جارٍ فحص الاتصال",
  appearance: "المظهر",
  light: "فاتح",
  dark: "داكن",
  language: "اللغة",
  decisionCenter: "مركز قرارات الوارد",
  decisionSubtitle: "راقب المؤشرات وأنشئ التقارير أو اسأل بحرية.",
  commandTitle: "أوامر وتقارير DockOS",
  commandSubtitle:
    "اسأل بحرية دون جمل ثابتة وأنشئ تقريراً أو معاينة إدارية آمنة.",
  run: "تشغيل",
  allSuppliers: "جميع الموردين",
  allWarehouses: "جميع المستودعات المركزية",
  capacityTitle: "مصفوفة سعة المواعيد والموردين",
  capacitySubtitle: "أدر التواريخ والمواعيد وحدود الموردين من شاشة واحدة.",
  dailyMax: "الحد اليومي للمنصات",
  edit: "تعديل",
  cancel: "إلغاء",
  save: "حفظ",
  supplierKicker: "DockOS · المورد",
  supplierTitle: "بوابة حجز المورد",
  supplierSubtitle: "اختر التوريد أو الشحن وأنشئ السجل من أمر الشراء.",
  supplierView: "عرض المورد",
  shipmentMethod: "1. طريقة الإرسال",
  dcShipment: "توريد المستودع المركزي",
  dcShipmentDesc: "حدد المركبة واللوحة والتاريخ والوقت. يستهلك سعة الموعد.",
  cargoShipment: "شحنة بريدية",
  cargoShipmentDesc: "أدخل تاريخ الشحن ورقم التتبع. لا يستهلك سعة الموعد.",
  companyWarehousePo: "2. الشركة والمستودع وأمر الشراء",
  companyWarehouse: "2. الشركة والمستودع",
  supplierLabel: "المورد",
  warehouseLabel: "المستودع المركزي",
  noOpenPo: "لا يوجد أمر شراء مفتوح لهذا المورد والمستودع.",
  due: "موعد التسليم",
  quantityInfo: "3. معلومات الكمية",
  palletCount: "عدد المنصات *",
  skuCount: "عدد SKU *",
  boxCount: "عدد الصناديق",
  reservationDateTime: "4. تاريخ ووقت الحجز",
  suitableDate: "التاريخ المتاح *",
  selectDate: "اختر التاريخ",
  suitableTime: "الوقت المتاح *",
  selectTime: "اختر الوقت",
  available: "متاح",
  cargoInfo: "3. معلومات الشحن",
  cargoDate: "تاريخ الشحن *",
  trackingNo: "رقم التتبع *",
  shipmentDetailsTitle: "5. تفاصيل التوريد",
  shipmentHelp:
    "أدخل نوع الحرارة وعدد المركبات ومتطلبات التفريغ ووقت الوصول والاستثناءات.",
  shipmentDetails: "تفاصيل التوريد *",
  waybill: "رقم مستند الشحن",
  shipmentForm: "شكل الشحنة",
  select: "اختر",
  bulk: "سائب",
  palletized: "على منصات",
  mixed: "مختلط",
  vehicleType: "نوع المركبة",
  truck: "شاحنة",
  semiTruck: "شاحنة مقطورة",
  van: "شاحنة صغيرة",
  vehicleCount: "عدد المركبات",
  plates: "لوحات المركبات *",
  saving: "جارٍ الحفظ...",
  createReservation: "إنشاء حجز",
  createCargo: "إنشاء سجل شحن",
  upcomingRecords: "سجلاتي المعلقة والقادمة",
  noRecords: "لا توجد سجلات بعد.",
  record: "السجل",
  type: "النوع",
  dateTime: "التاريخ / الوقت",
  plateTracking: "اللوحة / التتبع",
  status: "الحالة",
  action: "الإجراء",
  cancelAction: "إلغاء",
  notificationKicker: "DockOS · تدفق الإشعارات الآلي",
  notificationTitle: "مركز الإشعارات المؤسسي",
  notificationSubtitle:
    "يعالج آلياً الإنشاء وتذكيرات 48/24 ساعة والتعديلات والإلغاءات.",
  autoActive: "الإرسال التلقائي نشط",
  sent: "تم الإرسال",
  pending: "قيد الانتظار",
  waitingConfig: "بانتظار SMTP",
  failed: "فشل",
  cancelled: "ملغي",
  event: "الحدث",
  reservation: "الحجز",
  scheduled: "الموعد",
  recipients: "المستلمون",
  subject: "الموضوع",
  attempts: "المحاولات",
  waitingAddress: "بانتظار العنوان",
  noNotifications: "لا توجد إشعارات بعد.",
  autoInfo: "تتحدث القائمة تلقائياً ويرسل الخادم الرسائل المستحقة.",
  private: "خاص",
  welcome:
    "اسأل بجملة طبيعية. أفهم الحجوزات القادمة واللوحات والموردين والفترات والأداء.",
  you: "أنت",
  reportBuilder: "منشئ التقارير بدون كود",
  builderTitle: "أنشئ تقريرك بثلاثة اختيارات",
  buildReport: "إنشاء تقرير ديناميكي",
  selectedPeriod: "مرشح التاريخ أعلاه",
  last7: "آخر 7 أيام",
  thisMonth: "هذا الشهر",
  generatedReport: "تقرير تم إنشاؤه تلقائياً",
  secureAnalytics: "تحليلات آمنة",
  adminPreview: "أمر إداري · معاينة",
  confirmApply: "تمت المراجعة، تطبيق الحد",
  applying: "جارٍ التطبيق...",
  actionSuccess: "تم تنفيذ الأمر بنجاح.",
  noData: "لا توجد بيانات للمرشحات المختارة.",
  selectedPeriodHelp: "في الفترة المحددة",
  waitingOps: "بانتظار العملية",
  onTime: "الوصول في الوقت",
  checkedVehicles: "المركبات المفحوصة",
  completion: "الإكمال",
  closedReservations: "الحجوزات المغلقة",
  cancelRate: "نسبة الإلغاء",
  capacityUsage: "استخدام السعة",
  palletCapacity: "سعة المنصات",
  reservationStatus: "حالة الحجز",
  operationStage: "يعرض المرحلة التشغيلية الحالية",
  shipmentDistribution: "توزيع الشحنات",
  shipmentRatio: "نسبة التوريد والشحن",
  supplierVolume: "حجم المورد",
  busiestSuppliers: "أكثر الموردين نشاطاً",
  warehouseVolume: "حجم المستودع",
  warehouseDistribution: "توزيع الحجوزات حسب المستودع",
  dailyTrend: "اتجاه الحجوزات اليومي",
  trendSubtitle: "إجمالي وتأخر وإلغاء",
  supplierPerformance: "جدول أداء الموردين",
  compareIssues: "قارن المشكلات بنظرة واحدة",
  total: "الإجمالي",
  active: "نشط",
  completed: "مكتمل",
  late: "متأخر",
  noShow: "لم يحضر",
  success: "النجاح",
  promptPlaceholder: "مثال: الحجز الأقرب تابع لأي مورد؟",
};

const screenTranslations = {
  tr: {
    adminKicker: "DockOS · Merkez Depo",
    adminTitle: "Rezervasyon Kontrol Ekranı",
    adminSubtitle:
      "Gelen sevkiyatları plaka, tedarikçi, irsaliye veya PO ile arayın.",
    searchReservation:
      "Rezervasyon no, tedarikçi, plaka, irsaliye veya PO ara...",
    allStatuses: "Tüm Durumlar",
    approved: "Onaylı",
    revision: "Revizyon",
    refreshing: "Yenileniyor...",
    refreshShort: "Yenile",
    downloadCsv: "CSV İndir",
    noMatching: "Kriterlere uygun rezervasyon yok.",
    palletSku: "Palet / SKU",
    vehiclePlate: "Araç / Plaka",
    arrived: "Geldi mi?",
    dockSuitable: "Rampa uygun mu?",
    onTimeQuestion: "Saatinde mi?",
    note: "Not",
    yes: "Evet",
    no: "Hayır",
    complete: "Tamamla",
    adminEdit: "Merkez Depo Düzenlemesi",
    date: "Tarih",
    time: "Saat",
    pallet: "Palet",
    sku: "SKU",
    plate: "Plaka",
    shipmentDetail: "Sevkiyat Detayı",
    editReason: "Değişiklik Nedeni *",
    emailReasonHelp: "Tedarikçiye gidecek kurumsal e-postada gösterilir.",
    saveNotify: "Değişikliği Kaydet ve Bildirim Gönder",
    reservationCancel: "Rezervasyon İptali",
    cancelEmailInfo: "İptal bilgisi kurumsal e-posta akışına alınacak.",
    cancelReasonPlaceholder: "İptal nedenini yazın (zorunlu)",
    dismiss: "Vazgeç",
    cancelNotify: "İptal Et ve Bildir",
    capacityKicker: "DockOS · Kapasite Orkestrasyonu",
    dateBasket: "1. Tarih Sepeti",
    singleDate: "Tek Tarih Ekle",
    addDate: "Tarihi Ekle",
    rangeStart: "Aralık Başlangıcı",
    rangeEnd: "Aralık Bitişi",
    addRange: "Aralığı Sepete Ekle",
    next7: "Önümüzdeki 7 Gün",
    onlyToday: "Yalnızca Bugün",
    clearDates: "Tarihleri Temizle",
    slotLimitSection: "2. Saat ve Genel Slot Limiti",
    palletLimit: "Palet Limiti",
    skuLimit: "SKU Limiti",
    applyGeneralLimit: "Genel Slot Limitini Uygula",
    multiSupplierCapacity: "4. Çoklu Tedarikçi Sabit Kapasitesi",
    multiSupplierDesc:
      "Slot rezervine ek olarak günlük maksimum palet sınırı koy; böylece tek tedarikçi tüm günü bloklayamaz.",
    addSupplier: "Tedarikçi Ekle",
    reservedPallet: "Ayrılmış Palet",
    reservedSku: "Ayrılmış SKU",
    noLimit: "Limit yok",
    remove: "Kaldır",
    applyCapacity: "Tedarikçiye Kapasiteyi Uygula",
    totalPallet: "Toplam Palet",
    usedPallet: "Kullanılan Palet",
    remainingPallet: "Kalan Palet",
    totalSku: "Toplam SKU",
    usedSku: "Kullanılan SKU",
    remainingSku: "Kalan SKU",
    activeAllocations: "Aktif Sabit Kapasite Ayrımları",
    dailyUpperLimit: "Günlük Üst Limit",
    maxAbbr: "Maks.",
    palletUnit: "palet",
    noFixedCapacity: "Seçili tarihlerde sabit tedarikçi kapasitesi yok.",
    selectedSlotView: "Seçili Tarihlerin Slot Görünümü",
    used: "Kullanılan",
    remaining: "Kalan",
    open: "Açık",
    full: "Dolu",
    scopeDate: "tarih",
    scopeHour: "saat",
    scopeSupplier: "tedarikçi",
    customSlotTitle: "Parçalı slot oluştur",
    customSlotHelp:
      "Başlangıç, süre ve adedi belirle. Örneğin 260 dakika, saatlere bölünmeden tek rezervasyon bloğu olur.",
    slotStart: "Başlangıç Saati",
    slotDuration: "Blok Süresi (dk)",
    slotCount: "Blok Adedi",
    addSlotBlocks: "Özel Blokları Oluştur",
    customSlotInvalid:
      "Başlangıç, 15–720 dakika süre ve 1–24 blok girin; toplam süre 24 saati aşamaz.",
    customSlotsAdded: "özel blok oluşturuldu; önceki saatlik seçimin yerini aldı.",
    customBlockPreview: "Oluşacak tek parça blok:",
    minutesEachBlock: "dk / blok",
    managementChoiceTitle: "2. Tarihleri nasıl yönetmek istiyorsun?",
    managementChoiceHelp:
      "Önce seçili tarihleri tamamen blokla veya yalnızca ihtiyacın olan saatleri parçalı yönet.",
    blockWholeDay: "Tam Günü Blokla",
    blockWholeDayHelp:
      "Seçili tarihlerde rezervasyona açık tüm slotları kapatır.",
    managePartial: "Parçalı / Saatlik Yönet",
    managePartialHelp: "Yalnızca belirlediğin saatleri ve blokları açar.",
    blockActionHelp:
      "Aktif rezervasyon yoksa seçili tarihlerdeki tüm slotlar kapanır.",
    blockSelectedDates: "Seçili Tarihleri Tamamen Blokla",
    blockDatesConfirm: "Seçili tarihlerdeki tüm açık slotlar kapatılsın mı?",
    reopenHoursTitle: "Bloklanan tarihte saat aç",
    reopenHoursHelp:
      "Tam gün kapattıktan sonra istisna olarak açmak istediğin saatleri ekle.",
    quickHourSelection: "Hazır saatleri toplu seç",
    allHours: "Tüm Saatler (06–24)",
    morningHours: "Sabah (06–12)",
    afternoonHours: "Gündüz (12–18)",
    eveningHours: "Akşam (18–24)",
    clearHourSelection: "Saat Seçimini Temizle",
    openSelectedSlots: "Seçili Slotları Aç / Kaydet",
    chooseManagementMode:
      "Devam etmek için tam gün bloklama veya parçalı yönetim yöntemini seç.",
    selectDateFirst: "Önce en az bir tarih seçmelisin.",
    slotManagerTitle: "3. Slot Yönetimi",
    slotManagerHelp:
      "İstediğin satırları işaretle; seçilenleri toplu düzenle veya sil. Saat değişikliği için tekli düzenlemeyi kullan.",
    selectAllVisible: "Görünenlerin Tümünü Seç",
    slotSelected: "slot seçildi",
    clearSelection: "Seçimi Temizle",
    bulkSlotActions: "Toplu Slot İşlemleri",
    bulkSlotActionsHelp: "Yeni kapasite yalnızca işaretlediğin slotlara uygulanır.",
    applyToSelected: "Seçilenleri Düzenle",
    deleteSelected: "Seçilenleri Sil",
    selectManagedSlotFirst: "Önce en az bir slot işaretlemelisin.",
    bulkDeleteSlotConfirm: "Seçilen {count} slot kalıcı olarak silinsin mi? Aktif rezervasyonlu slot varsa işlem durdurulur.",
    showClosedSlots: "Kapalı slotları göster",
    noManagedSlots:
      "Gösterilecek açık slot yok. Parçalı yönetimden yeni saat açabilirsin.",
    blocked: "Bloklu",
    deleteSlot: "Sil",
    deleteSlotConfirm:
      "Bu slot kalıcı olarak silinsin mi? Aktif rezervasyonu varsa işlem yapılmaz.",
    planningKicker: "DockOS · Planlama & OPEX",
    bulkPoUpload: "Toplu PO Yükleme",
    planningSubtitle:
      "Connected Sheet sorgu çıktısını CSV olarak yükleyin. Tek tek PO girişi yapılmaz.",
    chooseCsvStep: "CSV dosyasını seç",
    chooseCsvStepHelp: "Connected Sheet çıktısını seç.",
    validateStep: "Kolon ve örnekleri doğrula",
    validateStepHelp: "Kolonları ve ilk satırları kontrol et.",
    uploadStep: "PO listesini yükle",
    uploadStepHelp: "Doğrulanan PO listesini sisteme aktar.",
    chooseCsv: "CSV Dosyası Seç",
    csvDropHelp: "CSV dosyasını buraya tıkla veya sürükleyip bırak.",
    noFile: "Dosya seçilmedi",
    clearPrevious: "Önceki CSV yüklemelerini temizleyip yeniden yükle",
    clearPreviousHelp:
      "Aynı PO numaralarını güncellerken önceki yüklemeleri temizler.",
    uploadActionHint: "Dosya seçildiğinde doğrulama özeti burada görünür.",
    uploadPoRows: "PO Satırını Yükle",
    expectedColumns: "Beklenen CSV Kolonları",
    auditKicker: "DockOS · Güvenlik",
    auditTitle: "Audit Kayıtları",
    auditSubtitle: "Kritik kapasite, randevu, PO ve varış değişiklikleri.",
    user: "Kullanıcı",
    operation: "İşlem",
    entity: "Varlık",
    detail: "Detay",
    noAudit: "Henüz audit kaydı bulunmuyor.",
    selectDateHour: "En az bir tarih ve saat seçmelisin.",
    noMoreSupplier: "Seçilebilecek başka tedarikçi kalmadı.",
    addOneSupplier: "En az bir tedarikçi eklemelisin.",
    listRefreshed: "Liste yenilendi",
    cancelMin: "İptal açıklaması en az 5 karakter olmalıdır.",
    reservationCancelled: "Rezervasyon iptal edildi.",
    rowsRead: "satır okundu.",
    missingColumns: "Eksik kolonlar",
    selectPo: "En az bir PO seçmelisin.",
    skuRequired: "SKU sayısı zorunludur.",
    palletRequired: "Palet sayısı zorunludur.",
    reservationDateRequired: "Rezervasyon tarihi ve saati zorunludur.",
    plateRequired: "Araç plakası zorunludur.",
    shipmentMin: "Sevkiyat detayları en az 5 karakter olmalıdır.",
    cargoDateRequired: "Kargo gönderim tarihi zorunludur.",
    trackingRequired: "Kargo takip numarası zorunludur.",
    recordNo: "Kayıt No",
    noAccess: "DockOS erişimi yok.",
    accessHelp:
      "Bu kullanıcı için DockOS görüntüleme yetkisi Access Control üzerinden açılmalı.",
    backControl: "Control Center’a dön",
    backendFailed: "DockOS backend bağlantısı kurulamadı.",
    accessProfile: "DockOS erişim profili",
    userMissing: "Kullanıcı bulunamadı",
    administrator: "DockOS yöneticisi",
    standardUser: "Standart DockOS kullanıcısı",
    permission: "Yetki",
    screens: "ekran",
    actions: "aksiyon",
    dataScope: "Veri kapsamı",
    allTurkey: "Tüm Türkiye",
    warehouseMissing: "Depo seçilmedi",
    supplierMissing: "Tedarikçi seçilmedi",
    regionMissing: "Bölge seçilmedi",
    noScope: "Kapsam yok",
    dockIncompatible: "Rampa Uyumsuzluğu",
    unspecified: "Belirtilmedi",
    accessManagement: "Erişim Yönetimi",
    supplierEmailAccess: "Tedarikçi E-posta ve PO Erişimi",
    supplierEmailAccessSubtitle:
      "Hangi e-posta adresinin hangi tedarikçi ve merkez depo PO'larını görebileceğini yönetin.",
    adminOnly: "Yalnızca Admin",
    accessIdentityTitle: "Kullanıcı Kimliği",
    accessIdentityHelp:
      "Erişim verilecek kurumsal e-posta adresini ve arayüz dilini tanımlayın.",
    emailAddress: "E-posta Adresi",
    preferredLanguage: "Tercih Edilen Dil",
    accessActive: "Erişim Aktif",
    activeAccessHelp:
      "Kapalı olduğunda kullanıcı hiçbir tedarikçi veya PO kaydını görüntüleyemez.",
    visibleSuppliers: "Görülebilen Tedarikçiler",
    visibleSuppliersHelp:
      "Kullanıcı yalnızca seçilen tedarikçilerin PO ve rezervasyonlarını görür.",
    allWarehousesAccess: "Seçilen tedarikçiler için tüm merkez depolar",
    visibleWarehouses: "Görülebilen Merkez Depolar",
    visibleWarehousesHelp:
      "Tüm depolar kapalıysa kullanıcının erişebileceği depoları seçin.",
    clearForm: "Formu Temizle",
    saveAccess: "Erişimi Kaydet",
    existingAccessMappings: "Mevcut Erişim Eşleşmeleri",
    accessRuleHint:
      "Erişim kuralları backend tarafından uygulanır; yalnızca ekran filtresi değildir.",
    searchEmailSupplier: "E-posta veya tedarikçi ara...",
    active: "Aktif",
    passive: "Pasif",
    noAccessMapping: "Erişim eşleşmesi bulunamadı.",
    accessDeleteConfirm: "Bu e-posta erişim eşleşmesi kaldırılsın mı?",
    singleAppointmentRule:
      "Örnek: 10:00–14:00 bloğu açıldığında 10–11, 11–12, 12–13 ve 13–14 slotları kaldırılır; tedarikçi yalnızca tek 10:00–14:00 randevusu görür.",
  },
  en: {
    adminKicker: "DockOS · Distribution Center",
    adminTitle: "Reservation Control",
    adminSubtitle:
      "Search inbound deliveries by plate, supplier, waybill or PO.",
    searchReservation:
      "Search reservation no, supplier, plate, waybill or PO...",
    allStatuses: "All Statuses",
    approved: "Approved",
    revision: "Revision",
    refreshing: "Refreshing...",
    refreshShort: "Refresh",
    downloadCsv: "Download CSV",
    noMatching: "No reservation matches the criteria.",
    palletSku: "Pallets / SKU",
    vehiclePlate: "Vehicle / Plate",
    arrived: "Arrived?",
    dockSuitable: "Dock suitable?",
    onTimeQuestion: "On time?",
    note: "Note",
    yes: "Yes",
    no: "No",
    complete: "Complete",
    adminEdit: "Distribution Center Edit",
    date: "Date",
    time: "Time",
    pallet: "Pallet",
    sku: "SKU",
    plate: "Plate",
    shipmentDetail: "Shipment Detail",
    editReason: "Change Reason *",
    emailReasonHelp: "Shown in the corporate email sent to the supplier.",
    saveNotify: "Save Change and Send Notification",
    reservationCancel: "Reservation Cancellation",
    cancelEmailInfo:
      "Cancellation information will enter the corporate email flow.",
    cancelReasonPlaceholder: "Enter cancellation reason (required)",
    dismiss: "Back",
    cancelNotify: "Cancel and Notify",
    capacityKicker: "DockOS · Capacity Orchestration",
    dateBasket: "1. Date Basket",
    singleDate: "Add Single Date",
    addDate: "Add Date",
    rangeStart: "Range Start",
    rangeEnd: "Range End",
    addRange: "Add Range",
    next7: "Next 7 Days",
    onlyToday: "Today Only",
    clearDates: "Clear Dates",
    slotLimitSection: "2. Time and General Slot Limit",
    palletLimit: "Pallet Limit",
    skuLimit: "SKU Limit",
    applyGeneralLimit: "Apply General Slot Limit",
    multiSupplierCapacity: "4. Multi-Supplier Reserved Capacity",
    multiSupplierDesc:
      "Set a daily pallet maximum in addition to slot allocation so one supplier cannot block the full day.",
    addSupplier: "Add Supplier",
    reservedPallet: "Reserved Pallets",
    reservedSku: "Reserved SKU",
    noLimit: "No limit",
    remove: "Remove",
    applyCapacity: "Apply Capacity to Supplier(s)",
    totalPallet: "Total Pallets",
    usedPallet: "Used Pallets",
    remainingPallet: "Remaining Pallets",
    totalSku: "Total SKU",
    usedSku: "Used SKU",
    remainingSku: "Remaining SKU",
    activeAllocations: "Active Reserved Capacity Allocations",
    dailyUpperLimit: "Daily Upper Limit",
    maxAbbr: "Max.",
    palletUnit: "pallets",
    noFixedCapacity: "No reserved supplier capacity on the selected dates.",
    selectedSlotView: "Slot View for Selected Dates",
    used: "Used",
    remaining: "Remaining",
    open: "Open",
    full: "Full",
    scopeDate: "dates",
    scopeHour: "hours",
    scopeSupplier: "suppliers",
    customSlotTitle: "Create partial slots",
    customSlotHelp:
      "Set start, duration and count. For example, 260 minutes becomes one continuous reservation block.",
    slotStart: "Start Time",
    slotDuration: "Block Duration (min)",
    slotCount: "Block Count",
    addSlotBlocks: "Create Custom Blocks",
    customSlotInvalid:
      "Enter a start time, 15–720 minute duration and 1–24 blocks; total duration cannot exceed 24 hours.",
    customSlotsAdded: "custom block(s) created and replaced the previous hourly selection.",
    customBlockPreview: "Continuous block preview:",
    minutesEachBlock: "min / block",
    managementChoiceTitle: "2. How should these dates be managed?",
    managementChoiceHelp:
      "Block all selected dates first or manage only the required hours as partial slots.",
    blockWholeDay: "Block the Whole Day",
    blockWholeDayHelp: "Closes every reservation slot on the selected dates.",
    managePartial: "Partial / Hourly Management",
    managePartialHelp: "Opens only the hours and blocks you define.",
    blockActionHelp:
      "All slots close when the selected dates have no active reservations.",
    blockSelectedDates: "Block Selected Dates Completely",
    blockDatesConfirm: "Close all open slots on the selected dates?",
    reopenHoursTitle: "Open hours on a blocked date",
    reopenHoursHelp:
      "After closing the whole day, add only the exception hours you want to reopen.",
    quickHourSelection: "Select ready hours in bulk",
    allHours: "All Hours (06–24)",
    morningHours: "Morning (06–12)",
    afternoonHours: "Day (12–18)",
    eveningHours: "Evening (18–24)",
    clearHourSelection: "Clear Hour Selection",
    openSelectedSlots: "Open / Save Selected Slots",
    chooseManagementMode:
      "Choose whole-day blocking or partial management to continue.",
    selectDateFirst: "Select at least one date first.",
    slotManagerTitle: "3. Slot Management",
    slotManagerHelp:
      "Check any rows, then edit or delete only the selected slots in bulk. Use row edit to change a time range.",
    selectAllVisible: "Select All Visible",
    slotSelected: "slot(s) selected",
    clearSelection: "Clear Selection",
    bulkSlotActions: "Bulk Slot Actions",
    bulkSlotActionsHelp: "The new capacity applies only to checked slots.",
    applyToSelected: "Edit Selected",
    deleteSelected: "Delete Selected",
    selectManagedSlotFirst: "Select at least one slot first.",
    bulkDeleteSlotConfirm: "Permanently delete the selected {count} slots? The operation stops if any slot has an active reservation.",
    showClosedSlots: "Show closed slots",
    noManagedSlots: "No open slots to show. Add hours from partial management.",
    blocked: "Blocked",
    deleteSlot: "Delete",
    deleteSlotConfirm:
      "Permanently delete this slot? The operation is rejected when it has an active reservation.",
    planningKicker: "DockOS · Planning & OPEX",
    bulkPoUpload: "Bulk PO Upload",
    planningSubtitle:
      "Upload the Connected Sheet query output as CSV. Individual PO entry is not required.",
    chooseCsvStep: "Select the CSV file",
    chooseCsvStepHelp: "Select the Connected Sheet export.",
    validateStep: "Validate columns and samples",
    validateStepHelp: "Check columns and sample rows.",
    uploadStep: "Upload the PO list",
    uploadStepHelp: "Import the validated PO list.",
    chooseCsv: "Select CSV File",
    csvDropHelp: "Click here or drag and drop a CSV file.",
    noFile: "No file selected",
    clearPrevious: "Clear previous CSV uploads before reloading",
    clearPreviousHelp:
      "Clears previous uploads while updating matching PO numbers.",
    uploadActionHint:
      "The validation summary appears here after a file is selected.",
    uploadPoRows: "Upload PO Rows",
    expectedColumns: "Expected CSV Columns",
    auditKicker: "DockOS · Security",
    auditTitle: "Audit Log",
    auditSubtitle: "Critical capacity, reservation, PO and arrival changes.",
    user: "User",
    operation: "Operation",
    entity: "Entity",
    detail: "Detail",
    noAudit: "No audit records yet.",
    selectDateHour: "Select at least one date and time.",
    noMoreSupplier: "No additional supplier is available.",
    addOneSupplier: "Add at least one supplier.",
    listRefreshed: "List refreshed",
    cancelMin: "Cancellation reason must be at least 5 characters.",
    reservationCancelled: "Reservation cancelled.",
    rowsRead: "rows read.",
    missingColumns: "Missing columns",
    selectPo: "Select at least one PO.",
    skuRequired: "SKU count is required.",
    palletRequired: "Pallet count is required.",
    reservationDateRequired: "Reservation date and time are required.",
    plateRequired: "Vehicle plate is required.",
    shipmentMin: "Shipment details must be at least 5 characters.",
    cargoDateRequired: "Cargo shipment date is required.",
    trackingRequired: "Cargo tracking number is required.",
    recordNo: "Record No",
    noAccess: "No DockOS access.",
    accessHelp:
      "DockOS view permission must be granted through Access Control for this user.",
    backControl: "Back to Control Center",
    backendFailed: "Could not connect to the DockOS backend.",
    accessProfile: "DockOS access profile",
    userMissing: "User not found",
    administrator: "DockOS administrator",
    standardUser: "Standard DockOS user",
    permission: "Permission",
    screens: "screens",
    actions: "actions",
    dataScope: "Data scope",
    allTurkey: "All Türkiye",
    warehouseMissing: "No DC selected",
    supplierMissing: "No supplier selected",
    regionMissing: "No region selected",
    noScope: "No scope",
    dockIncompatible: "Dock Incompatibility",
    unspecified: "Unspecified",
    accessManagement: "Access Management",
    supplierEmailAccess: "Supplier Email and PO Access",
    supplierEmailAccessSubtitle:
      "Manage which supplier and distribution center POs each email address can view.",
    adminOnly: "Admin Only",
    accessIdentityTitle: "User Identity",
    accessIdentityHelp:
      "Define the corporate email address and interface language for this access.",
    emailAddress: "Email Address",
    preferredLanguage: "Preferred Language",
    accessActive: "Access Active",
    activeAccessHelp:
      "When disabled, the user cannot view any supplier or PO records.",
    visibleSuppliers: "Visible Suppliers",
    visibleSuppliersHelp:
      "The user sees only the selected suppliers' POs and reservations.",
    allWarehousesAccess: "All distribution centers for selected suppliers",
    visibleWarehouses: "Visible Distribution Centers",
    visibleWarehousesHelp:
      "When all DCs is off, select the DCs this user can access.",
    clearForm: "Clear Form",
    saveAccess: "Save Access",
    existingAccessMappings: "Existing Access Mappings",
    accessRuleHint:
      "Access rules are enforced by the backend, not only by screen filters.",
    searchEmailSupplier: "Search email or supplier...",
    active: "Active",
    passive: "Inactive",
    noAccessMapping: "No access mapping found.",
    accessDeleteConfirm: "Remove this email access mapping?",
    singleAppointmentRule:
      "Example: opening a 10:00–14:00 block removes 10–11, 11–12, 12–13 and 13–14; the supplier sees one 10:00–14:00 appointment only.",
  },
  de: {
    adminKicker: "DockOS · Zentrallager",
    adminTitle: "Reservierungskontrolle",
    adminSubtitle:
      "Eingehende Lieferungen nach Kennzeichen, Lieferant, Lieferschein oder PO suchen.",
    searchReservation:
      "Reservierungsnr., Lieferant, Kennzeichen, Lieferschein oder PO suchen...",
    allStatuses: "Alle Status",
    approved: "Genehmigt",
    revision: "Revision",
    refreshing: "Wird aktualisiert...",
    refreshShort: "Aktualisieren",
    downloadCsv: "CSV herunterladen",
    noMatching: "Keine passende Reservierung gefunden.",
    palletSku: "Paletten / SKU",
    vehiclePlate: "Fahrzeug / Kennzeichen",
    arrived: "Angekommen?",
    dockSuitable: "Rampe geeignet?",
    onTimeQuestion: "Pünktlich?",
    note: "Notiz",
    yes: "Ja",
    no: "Nein",
    complete: "Abschließen",
    adminEdit: "Bearbeitung durch Zentrallager",
    date: "Datum",
    time: "Uhrzeit",
    pallet: "Paletten",
    sku: "SKU",
    plate: "Kennzeichen",
    shipmentDetail: "Lieferdetails",
    editReason: "Änderungsgrund *",
    emailReasonHelp:
      "Wird in der Unternehmens-E-Mail an den Lieferanten angezeigt.",
    saveNotify: "Änderung speichern und Benachrichtigung senden",
    reservationCancel: "Reservierung stornieren",
    cancelEmailInfo:
      "Die Stornierung wird in den Unternehmens-E-Mail-Fluss aufgenommen.",
    cancelReasonPlaceholder: "Stornogrund eingeben (Pflichtfeld)",
    dismiss: "Zurück",
    cancelNotify: "Stornieren und benachrichtigen",
    capacityKicker: "DockOS · Kapazitätssteuerung",
    dateBasket: "1. Datumsauswahl",
    singleDate: "Einzeldatum hinzufügen",
    addDate: "Datum hinzufügen",
    rangeStart: "Zeitraum von",
    rangeEnd: "Zeitraum bis",
    addRange: "Zeitraum hinzufügen",
    next7: "Nächste 7 Tage",
    onlyToday: "Nur heute",
    clearDates: "Daten löschen",
    slotLimitSection: "2. Uhrzeit und allgemeines Slot-Limit",
    palletLimit: "Palettenlimit",
    skuLimit: "SKU-Limit",
    applyGeneralLimit: "Allgemeines Slot-Limit anwenden",
    multiSupplierCapacity: "4. Reservierte Kapazität für mehrere Lieferanten",
    multiSupplierDesc:
      "Zusätzlich zur Slot-Reservierung ein tägliches Palettenmaximum setzen, damit ein Lieferant nicht den ganzen Tag blockiert.",
    addSupplier: "Lieferant hinzufügen",
    reservedPallet: "Reservierte Paletten",
    reservedSku: "Reservierte SKU",
    noLimit: "Kein Limit",
    remove: "Entfernen",
    applyCapacity: "Kapazität auf Lieferant(en) anwenden",
    totalPallet: "Paletten gesamt",
    usedPallet: "Belegte Paletten",
    remainingPallet: "Verbleibende Paletten",
    totalSku: "SKU gesamt",
    usedSku: "Belegte SKU",
    remainingSku: "Verbleibende SKU",
    activeAllocations: "Aktive reservierte Kapazitäten",
    dailyUpperLimit: "Tägliche Obergrenze",
    maxAbbr: "Max.",
    palletUnit: "Paletten",
    noFixedCapacity:
      "Keine reservierte Lieferantenkapazität an den ausgewählten Tagen.",
    selectedSlotView: "Slot-Ansicht der ausgewählten Tage",
    used: "Belegt",
    remaining: "Verbleibend",
    open: "Offen",
    full: "Voll",
    scopeDate: "Tage",
    scopeHour: "Stunden",
    scopeSupplier: "Lieferanten",
    customSlotTitle: "Teilslots erstellen",
    customSlotHelp:
      "Start, Dauer und Anzahl festlegen. Zum Beispiel werden 260 Minuten als ein durchgehender Reservierungsblock erstellt.",
    slotStart: "Startzeit",
    slotDuration: "Blockdauer (Min.)",
    slotCount: "Blockanzahl",
    addSlotBlocks: "Benutzerdefinierte Blöcke erstellen",
    customSlotInvalid:
      "Startzeit, 15–720 Minuten Dauer und 1–24 Blöcke eingeben; die Gesamtdauer darf 24 Stunden nicht überschreiten.",
    customSlotsAdded: "benutzerdefinierte Blöcke erstellt; die vorherige Stundenauswahl wurde ersetzt.",
    customBlockPreview: "Vorschau des durchgehenden Blocks:",
    minutesEachBlock: "Min. / Block",
    managementChoiceTitle: "2. Wie sollen diese Daten verwaltet werden?",
    managementChoiceHelp:
      "Ausgewählte Tage vollständig sperren oder nur benötigte Stunden als Teilslots verwalten.",
    blockWholeDay: "Ganzen Tag sperren",
    blockWholeDayHelp:
      "Schließt alle Reservierungsslots an den ausgewählten Tagen.",
    managePartial: "Teilweise / stündlich",
    managePartialHelp: "Öffnet nur die festgelegten Stunden und Blöcke.",
    blockActionHelp:
      "Alle Slots werden geschlossen, sofern keine aktive Reservierung besteht.",
    blockSelectedDates: "Ausgewählte Tage vollständig sperren",
    blockDatesConfirm:
      "Alle offenen Slots an den ausgewählten Tagen schließen?",
    reopenHoursTitle: "Stunden an gesperrtem Tag öffnen",
    reopenHoursHelp:
      "Nach der Tagessperre nur gewünschte Ausnahmezeiten wieder öffnen.",
    quickHourSelection: "Vorgegebene Zeiten gesammelt auswählen",
    allHours: "Alle Stunden (06–24)",
    morningHours: "Morgen (06–12)",
    afternoonHours: "Tag (12–18)",
    eveningHours: "Abend (18–24)",
    clearHourSelection: "Zeitauswahl löschen",
    openSelectedSlots: "Ausgewählte Slots öffnen / speichern",
    chooseManagementMode:
      "Zum Fortfahren Tagessperre oder Teilverwaltung auswählen.",
    selectDateFirst: "Zuerst mindestens ein Datum auswählen.",
    slotManagerTitle: "3. Slot-Verwaltung",
    slotManagerHelp:
      "Beliebige Zeilen markieren und nur die ausgewählten Slots gesammelt bearbeiten oder löschen. Zeitänderungen erfolgen zeilenweise.",
    selectAllVisible: "Alle sichtbaren auswählen",
    slotSelected: "Slot(s) ausgewählt",
    clearSelection: "Auswahl löschen",
    bulkSlotActions: "Sammelaktionen für Slots",
    bulkSlotActionsHelp: "Die neue Kapazität gilt nur für markierte Slots.",
    applyToSelected: "Ausgewählte bearbeiten",
    deleteSelected: "Ausgewählte löschen",
    selectManagedSlotFirst: "Zuerst mindestens einen Slot auswählen.",
    bulkDeleteSlotConfirm: "Die ausgewählten {count} Slots dauerhaft löschen? Bei einer aktiven Reservierung wird der Vorgang gestoppt.",
    showClosedSlots: "Geschlossene Slots anzeigen",
    noManagedSlots:
      "Keine offenen Slots. Über die Teilverwaltung können Stunden hinzugefügt werden.",
    blocked: "Gesperrt",
    deleteSlot: "Löschen",
    deleteSlotConfirm:
      "Diesen Slot dauerhaft löschen? Bei aktiver Reservierung wird der Vorgang abgelehnt.",
    planningKicker: "DockOS · Planung & OPEX",
    bulkPoUpload: "PO-Massenimport",
    planningSubtitle:
      "Connected-Sheet-Abfrage als CSV hochladen. Einzelne PO-Eingabe ist nicht erforderlich.",
    chooseCsvStep: "CSV-Datei auswählen",
    chooseCsvStepHelp: "Connected-Sheet-Export auswählen.",
    validateStep: "Spalten und Beispiele prüfen",
    validateStepHelp: "Spalten und Beispielzeilen prüfen.",
    uploadStep: "PO-Liste hochladen",
    uploadStepHelp: "Geprüfte PO-Liste importieren.",
    chooseCsv: "CSV-Datei auswählen",
    csvDropHelp: "CSV-Datei hier anklicken oder ablegen.",
    noFile: "Keine Datei ausgewählt",
    clearPrevious: "Frühere CSV-Uploads vor erneutem Laden löschen",
    clearPreviousHelp:
      "Entfernt frühere Uploads beim Aktualisieren gleicher PO-Nummern.",
    uploadActionHint:
      "Nach der Dateiauswahl erscheint hier die Prüfzusammenfassung.",
    uploadPoRows: "PO-Zeilen hochladen",
    expectedColumns: "Erwartete CSV-Spalten",
    auditKicker: "DockOS · Sicherheit",
    auditTitle: "Audit-Protokoll",
    auditSubtitle:
      "Kritische Änderungen an Kapazität, Reservierung, PO und Ankunft.",
    user: "Benutzer",
    operation: "Vorgang",
    entity: "Objekt",
    detail: "Details",
    noAudit: "Noch keine Audit-Einträge.",
    selectDateHour: "Mindestens ein Datum und eine Uhrzeit auswählen.",
    noMoreSupplier: "Kein weiterer Lieferant verfügbar.",
    addOneSupplier: "Mindestens einen Lieferanten hinzufügen.",
    listRefreshed: "Liste aktualisiert",
    cancelMin: "Der Stornogrund muss mindestens 5 Zeichen enthalten.",
    reservationCancelled: "Reservierung storniert.",
    rowsRead: "Zeilen gelesen.",
    missingColumns: "Fehlende Spalten",
    selectPo: "Mindestens eine PO auswählen.",
    skuRequired: "SKU-Anzahl ist erforderlich.",
    palletRequired: "Palettenanzahl ist erforderlich.",
    reservationDateRequired: "Reservierungsdatum und -zeit sind erforderlich.",
    plateRequired: "Kennzeichen ist erforderlich.",
    shipmentMin: "Lieferdetails müssen mindestens 5 Zeichen enthalten.",
    cargoDateRequired: "Frachtversanddatum ist erforderlich.",
    trackingRequired: "Sendungsnummer ist erforderlich.",
    recordNo: "Datensatznr.",
    noAccess: "Kein DockOS-Zugriff.",
    accessHelp:
      "Die DockOS-Anzeigeberechtigung muss für diesen Benutzer über Access Control erteilt werden.",
    backControl: "Zurück zum Control Center",
    backendFailed: "Verbindung zum DockOS-Backend fehlgeschlagen.",
    accessProfile: "DockOS-Zugriffsprofil",
    userMissing: "Benutzer nicht gefunden",
    administrator: "DockOS-Administrator",
    standardUser: "Standard-DockOS-Benutzer",
    permission: "Berechtigung",
    screens: "Ansichten",
    actions: "Aktionen",
    dataScope: "Datenumfang",
    allTurkey: "Gesamte Türkei",
    warehouseMissing: "Kein Lager ausgewählt",
    supplierMissing: "Kein Lieferant ausgewählt",
    regionMissing: "Keine Region ausgewählt",
    noScope: "Kein Umfang",
    dockIncompatible: "Rampen-Inkompatibilität",
    unspecified: "Nicht angegeben",
    accessManagement: "Zugriffsverwaltung",
    supplierEmailAccess: "Lieferanten-E-Mail- und PO-Zugriff",
    supplierEmailAccessSubtitle:
      "Verwalten Sie, welche Lieferanten- und Zentrallager-POs jede E-Mail-Adresse sehen darf.",
    adminOnly: "Nur Admin",
    accessIdentityTitle: "Benutzeridentität",
    accessIdentityHelp:
      "Geschäftliche E-Mail-Adresse und Oberflächensprache für diesen Zugriff festlegen.",
    emailAddress: "E-Mail-Adresse",
    preferredLanguage: "Bevorzugte Sprache",
    accessActive: "Zugriff aktiv",
    activeAccessHelp:
      "Bei Deaktivierung kann der Benutzer keine Lieferanten- oder PO-Daten sehen.",
    visibleSuppliers: "Sichtbare Lieferanten",
    visibleSuppliersHelp:
      "Der Benutzer sieht nur POs und Reservierungen der ausgewählten Lieferanten.",
    allWarehousesAccess: "Alle Zentrallager für ausgewählte Lieferanten",
    visibleWarehouses: "Sichtbare Zentrallager",
    visibleWarehousesHelp:
      "Wenn alle Lager deaktiviert sind, wählen Sie die erlaubten Lager.",
    clearForm: "Formular leeren",
    saveAccess: "Zugriff speichern",
    existingAccessMappings: "Bestehende Zugriffszuordnungen",
    accessRuleHint:
      "Zugriffsregeln werden im Backend erzwungen, nicht nur als Bildschirmfilter.",
    searchEmailSupplier: "E-Mail oder Lieferant suchen...",
    active: "Aktiv",
    passive: "Inaktiv",
    noAccessMapping: "Keine Zugriffszuordnung gefunden.",
    accessDeleteConfirm: "Diese E-Mail-Zugriffszuordnung entfernen?",
    singleAppointmentRule:
      "Beispiel: Ein Block 10:00–14:00 entfernt 10–11, 11–12, 12–13 und 13–14; der Lieferant sieht nur einen Termin 10:00–14:00.",
  },
  ar: {
    adminKicker: "DockOS · المستودع المركزي",
    adminTitle: "مراقبة الحجوزات",
    adminSubtitle:
      "ابحث في الشحنات الواردة باللوحة أو المورد أو مستند الشحن أو أمر الشراء.",
    searchReservation:
      "ابحث برقم الحجز أو المورد أو اللوحة أو مستند الشحن أو أمر الشراء...",
    allStatuses: "جميع الحالات",
    approved: "معتمد",
    revision: "مراجعة",
    refreshing: "جارٍ التحديث...",
    refreshShort: "تحديث",
    downloadCsv: "تنزيل CSV",
    noMatching: "لا يوجد حجز مطابق للمعايير.",
    palletSku: "المنصات / SKU",
    vehiclePlate: "المركبة / اللوحة",
    arrived: "وصل؟",
    dockSuitable: "المنصة مناسبة؟",
    onTimeQuestion: "في الموعد؟",
    note: "ملاحظة",
    yes: "نعم",
    no: "لا",
    complete: "إكمال",
    adminEdit: "تعديل المستودع المركزي",
    date: "التاريخ",
    time: "الوقت",
    pallet: "المنصات",
    sku: "SKU",
    plate: "اللوحة",
    shipmentDetail: "تفاصيل التوريد",
    editReason: "سبب التغيير *",
    emailReasonHelp: "يظهر في البريد المؤسسي المرسل إلى المورد.",
    saveNotify: "حفظ التغيير وإرسال إشعار",
    reservationCancel: "إلغاء الحجز",
    cancelEmailInfo: "ستدخل معلومات الإلغاء في تدفق البريد المؤسسي.",
    cancelReasonPlaceholder: "اكتب سبب الإلغاء (إلزامي)",
    dismiss: "رجوع",
    cancelNotify: "إلغاء وإشعار",
    capacityKicker: "DockOS · تنسيق السعة",
    dateBasket: "1. مجموعة التواريخ",
    singleDate: "إضافة تاريخ",
    addDate: "أضف التاريخ",
    rangeStart: "بداية النطاق",
    rangeEnd: "نهاية النطاق",
    addRange: "أضف النطاق",
    next7: "الأيام السبعة القادمة",
    onlyToday: "اليوم فقط",
    clearDates: "مسح التواريخ",
    slotLimitSection: "2. الوقت والحد العام للموعد",
    palletLimit: "حد المنصات",
    skuLimit: "حد SKU",
    applyGeneralLimit: "تطبيق الحد العام للموعد",
    multiSupplierCapacity: "4. السعة المحجوزة لعدة موردين",
    multiSupplierDesc:
      "ضع حداً يومياً للمنصات إضافة إلى حجز الموعد حتى لا يحجز مورد واحد اليوم بالكامل.",
    addSupplier: "إضافة مورد",
    reservedPallet: "المنصات المحجوزة",
    reservedSku: "SKU المحجوز",
    noLimit: "بلا حد",
    remove: "إزالة",
    applyCapacity: "تطبيق السعة على الموردين",
    totalPallet: "إجمالي المنصات",
    usedPallet: "المنصات المستخدمة",
    remainingPallet: "المنصات المتبقية",
    totalSku: "إجمالي SKU",
    usedSku: "SKU المستخدم",
    remainingSku: "SKU المتبقي",
    activeAllocations: "تخصيصات السعة المحجوزة النشطة",
    dailyUpperLimit: "الحد اليومي الأعلى",
    maxAbbr: "الحد الأقصى",
    palletUnit: "منصة",
    noFixedCapacity: "لا توجد سعة مورد محجوزة في التواريخ المحددة.",
    selectedSlotView: "عرض المواعيد للتواريخ المحددة",
    used: "مستخدم",
    remaining: "متبقي",
    open: "مفتوح",
    full: "ممتلئ",
    scopeDate: "تواريخ",
    scopeHour: "ساعات",
    scopeSupplier: "موردون",
    customSlotTitle: "إنشاء مواعيد جزئية",
    customSlotHelp:
      "حدد البداية والمدة والعدد. على سبيل المثال تُنشأ 260 دقيقة كفترة حجز واحدة متصلة.",
    slotStart: "وقت البدء",
    slotDuration: "مدة الفترة (دقيقة)",
    slotCount: "عدد الفترات",
    addSlotBlocks: "إنشاء فترات مخصصة",
    customSlotInvalid:
      "أدخل وقت البدء ومدة من 15 إلى 720 دقيقة وعدداً من 1 إلى 24؛ ويجب ألا يتجاوز الإجمالي 24 ساعة.",
    customSlotsAdded: "تم إنشاء الفترات المخصصة واستبدال تحديد الساعات السابق.",
    customBlockPreview: "معاينة الفترة المتصلة:",
    minutesEachBlock: "دقيقة / فترة",
    managementChoiceTitle: "2. كيف تريد إدارة التواريخ؟",
    managementChoiceHelp:
      "احظر الأيام المحددة بالكامل أو أدر الساعات المطلوبة فقط كمواعيد جزئية.",
    blockWholeDay: "حظر اليوم بالكامل",
    blockWholeDayHelp: "يغلق جميع مواعيد الحجز في التواريخ المحددة.",
    managePartial: "إدارة جزئية / بالساعة",
    managePartialHelp: "يفتح الساعات والفترات التي تحددها فقط.",
    blockActionHelp: "تُغلق جميع المواعيد إذا لم توجد حجوزات نشطة.",
    blockSelectedDates: "حظر التواريخ المحددة بالكامل",
    blockDatesConfirm:
      "هل تريد إغلاق جميع المواعيد المفتوحة في التواريخ المحددة؟",
    reopenHoursTitle: "فتح ساعات في يوم محظور",
    reopenHoursHelp:
      "بعد إغلاق اليوم بالكامل أضف ساعات الاستثناء التي تريد فتحها.",
    quickHourSelection: "تحديد الساعات الجاهزة دفعة واحدة",
    allHours: "كل الساعات (06–24)",
    morningHours: "الصباح (06–12)",
    afternoonHours: "النهار (12–18)",
    eveningHours: "المساء (18–24)",
    clearHourSelection: "مسح تحديد الساعات",
    openSelectedSlots: "فتح / حفظ المواعيد المحددة",
    chooseManagementMode: "اختر حظر اليوم بالكامل أو الإدارة الجزئية للمتابعة.",
    selectDateFirst: "اختر تاريخاً واحداً على الأقل أولاً.",
    slotManagerTitle: "3. إدارة المواعيد",
    slotManagerHelp: "حدد الصفوف المطلوبة ثم عدّل أو احذف المواعيد المحددة فقط دفعة واحدة. استخدم تعديل الصف لتغيير الوقت.",
    selectAllVisible: "تحديد كل الظاهر",
    slotSelected: "موعد محدد",
    clearSelection: "مسح التحديد",
    bulkSlotActions: "إجراءات جماعية للمواعيد",
    bulkSlotActionsHelp: "تُطبق السعة الجديدة على المواعيد المحددة فقط.",
    applyToSelected: "تعديل المحدد",
    deleteSelected: "حذف المحدد",
    selectManagedSlotFirst: "حدد موعداً واحداً على الأقل أولاً.",
    bulkDeleteSlotConfirm: "هل تريد حذف {count} من المواعيد المحددة نهائياً؟ تتوقف العملية إذا وُجد حجز نشط.",
    showClosedSlots: "إظهار المواعيد المغلقة",
    noManagedSlots: "لا توجد مواعيد مفتوحة. أضف ساعات من الإدارة الجزئية.",
    blocked: "محظور",
    deleteSlot: "حذف",
    deleteSlotConfirm:
      "هل تريد حذف هذا الموعد نهائياً؟ تُرفض العملية إذا كان له حجز نشط.",
    planningKicker: "DockOS · التخطيط و OPEX",
    bulkPoUpload: "تحميل أوامر الشراء بالجملة",
    planningSubtitle:
      "حمّل ناتج استعلام Connected Sheet بصيغة CSV دون إدخال كل أمر شراء على حدة.",
    chooseCsvStep: "اختر ملف CSV",
    chooseCsvStepHelp: "اختر ملف التصدير من Connected Sheet.",
    validateStep: "تحقق من الأعمدة والعينات",
    validateStepHelp: "تحقق من الأعمدة والصفوف النموذجية.",
    uploadStep: "حمّل قائمة أوامر الشراء",
    uploadStepHelp: "استورد قائمة أوامر الشراء المعتمدة.",
    chooseCsv: "اختر ملف CSV",
    csvDropHelp: "انقر هنا أو اسحب ملف CSV وأفلته.",
    noFile: "لم يتم اختيار ملف",
    clearPrevious: "امسح تحميلات CSV السابقة قبل إعادة التحميل",
    clearPreviousHelp:
      "يمسح التحميلات السابقة عند تحديث أرقام أوامر الشراء المتطابقة.",
    uploadActionHint: "يظهر ملخص التحقق هنا بعد اختيار الملف.",
    uploadPoRows: "تحميل صفوف أوامر الشراء",
    expectedColumns: "أعمدة CSV المتوقعة",
    auditKicker: "DockOS · الأمان",
    auditTitle: "سجل التدقيق",
    auditSubtitle: "تغييرات السعة والحجز وأوامر الشراء والوصول المهمة.",
    user: "المستخدم",
    operation: "العملية",
    entity: "الكيان",
    detail: "التفاصيل",
    noAudit: "لا توجد سجلات تدقيق بعد.",
    selectDateHour: "اختر تاريخاً ووقتاً واحداً على الأقل.",
    noMoreSupplier: "لا يوجد مورد إضافي متاح.",
    addOneSupplier: "أضف مورداً واحداً على الأقل.",
    listRefreshed: "تم تحديث القائمة",
    cancelMin: "يجب ألا يقل سبب الإلغاء عن 5 أحرف.",
    reservationCancelled: "تم إلغاء الحجز.",
    rowsRead: "صفاً تمت قراءته.",
    missingColumns: "الأعمدة الناقصة",
    selectPo: "اختر أمر شراء واحداً على الأقل.",
    skuRequired: "عدد SKU مطلوب.",
    palletRequired: "عدد المنصات مطلوب.",
    reservationDateRequired: "تاريخ ووقت الحجز مطلوبان.",
    plateRequired: "لوحة المركبة مطلوبة.",
    shipmentMin: "يجب ألا تقل تفاصيل التوريد عن 5 أحرف.",
    cargoDateRequired: "تاريخ الشحن مطلوب.",
    trackingRequired: "رقم التتبع مطلوب.",
    recordNo: "رقم السجل",
    noAccess: "لا يوجد وصول إلى DockOS.",
    accessHelp: "يجب منح المستخدم صلاحية عرض DockOS عبر Access Control.",
    backControl: "العودة إلى Control Center",
    backendFailed: "تعذر الاتصال بخادم DockOS.",
    accessProfile: "ملف وصول DockOS",
    userMissing: "لم يتم العثور على المستخدم",
    administrator: "مدير DockOS",
    standardUser: "مستخدم DockOS قياسي",
    permission: "الصلاحية",
    screens: "شاشات",
    actions: "إجراءات",
    dataScope: "نطاق البيانات",
    allTurkey: "كل تركيا",
    warehouseMissing: "لم يتم اختيار مستودع",
    supplierMissing: "لم يتم اختيار مورد",
    regionMissing: "لم يتم اختيار منطقة",
    noScope: "لا يوجد نطاق",
    dockIncompatible: "عدم توافق المنصة",
    unspecified: "غير محدد",
    accessManagement: "إدارة الوصول",
    supplierEmailAccess: "وصول بريد المورد وأوامر الشراء",
    supplierEmailAccessSubtitle:
      "أدر أي أوامر شراء للموردين والمستودعات يمكن لكل بريد إلكتروني رؤيتها.",
    adminOnly: "للمدير فقط",
    accessIdentityTitle: "هوية المستخدم",
    accessIdentityHelp:
      "حدد البريد المؤسسي ولغة الواجهة لهذا الوصول.",
    emailAddress: "البريد الإلكتروني",
    preferredLanguage: "اللغة المفضلة",
    accessActive: "الوصول نشط",
    activeAccessHelp:
      "عند التعطيل لن يتمكن المستخدم من رؤية أي مورد أو أمر شراء.",
    visibleSuppliers: "الموردون المرئيون",
    visibleSuppliersHelp:
      "يرى المستخدم أوامر الشراء والحجوزات للموردين المحددين فقط.",
    allWarehousesAccess: "جميع المستودعات للموردين المحددين",
    visibleWarehouses: "المستودعات المرئية",
    visibleWarehousesHelp:
      "عند إيقاف جميع المستودعات اختر المستودعات المسموح بها.",
    clearForm: "مسح النموذج",
    saveAccess: "حفظ الوصول",
    existingAccessMappings: "تعيينات الوصول الحالية",
    accessRuleHint: "تُطبق قواعد الوصول في الخادم وليست مجرد مرشحات شاشة.",
    searchEmailSupplier: "ابحث بالبريد أو المورد...",
    active: "نشط",
    passive: "غير نشط",
    noAccessMapping: "لم يتم العثور على تعيين وصول.",
    accessDeleteConfirm: "إزالة تعيين وصول هذا البريد؟",
    singleAppointmentRule:
      "مثال: فتح الفترة 10:00–14:00 يزيل الفترات 10–11 و11–12 و12–13 و13–14؛ ويرى المورد موعداً واحداً فقط من 10:00 إلى 14:00.",
  },
};

const translations = {
  tr: { ...tr, ...screenTranslations.tr },
  en: { ...en, ...screenTranslations.en },
  de: { ...de, ...screenTranslations.de },
  ar: { ...ar, ...screenTranslations.ar },
};
const DockOSUiContext = createContext(null);

export function DockOSUiProvider({ children }) {
  const [theme, setThemeState] = useState(() =>
    localStorage.getItem("dockos-theme") === "dark" ? "dark" : "light",
  );
  const [locale, setLocaleState] = useState(() =>
    ["tr", "en", "de", "ar"].includes(localStorage.getItem("dockos-locale"))
      ? localStorage.getItem("dockos-locale")
      : "tr",
  );
  const setTheme = (value) => {
    localStorage.setItem("dockos-theme", value);
    setThemeState(value);
  };
  const setLocale = (value) => {
    localStorage.setItem("dockos-locale", value);
    setLocaleState(value);
  };
  const value = useMemo(
    () => ({
      theme,
      setTheme,
      locale,
      setLocale,
      dir: locale === "ar" ? "rtl" : "ltr",
      localeCode:
        locale === "de"
          ? "de-DE"
          : locale === "en"
            ? "en-GB"
            : locale === "ar"
              ? "ar"
              : "tr-TR",
      t: (key) => translations[locale]?.[key] || translations.tr[key] || key,
    }),
    [theme, locale],
  );
  return (
    <DockOSUiContext.Provider value={value}>
      {children}
    </DockOSUiContext.Provider>
  );
}

export function useDockOSUi() {
  const context = useContext(DockOSUiContext);
  if (!context)
    throw new Error("useDockOSUi must be used inside DockOSUiProvider");
  return context;
}
