import React,{useEffect,useMemo,useState}from"react";
import{getKpis,getNotificationOutbox,getReservations,getSlots}from"./dockosApi.js";
import{useDockOSUi}from"./DockOSUiContext.jsx";
import"./dockos-control-tower.css";

const COPY={
 tr:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Randevu, kapasite, varış ve bildirim sağlığı tek karar görünümünde.",reservations:"Rezervasyon",util:"Kapasite Kullanımı",arrived:"Varış Kaydı",exceptions:"Açık İstisna",capacity:"Kapasite Basıncı",outbox:"Bildirim Sağlığı",risk:"Operasyon Risk Kuyruğu",healthy:"Sağlıklı",retry:"Tekrar Dene",posture:"Operasyon Durumu",stable:"Kontrol altında",watch:"Yakın izleme",critical:"Müdahale gerekli",active:"Aktif Randevu",capacityTotal:"Toplam Kapasite",used:"Kullanılan",failed:"Başarısız",events:"Olay",empty:"Açık risk bulunmuyor",warehouse:"Depo / DC",slot:"Slot",pressure:"Doluluk",notificationRate:"Başarılı Bildirim",authority:"Canonical API authority"},
 en:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Reservations, capacity, arrivals and notification health in one decision surface.",reservations:"Reservations",util:"Capacity Utilization",arrived:"Arrival Records",exceptions:"Open Exceptions",capacity:"Capacity Pressure",outbox:"Notification Health",risk:"Operations Risk Queue",healthy:"Healthy",retry:"Retry",posture:"Operational Posture",stable:"Under control",watch:"Watch closely",critical:"Intervention required",active:"Active Reservations",capacityTotal:"Total Capacity",used:"Used",failed:"Failed",events:"Events",empty:"No open operational risk",warehouse:"Warehouse / DC",slot:"Slot",pressure:"Pressure",notificationRate:"Successful Notifications",authority:"Canonical API authority"},
 de:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Reservierungen, Kapazität, Ankünfte und Benachrichtigungen in einer Entscheidungsansicht.",reservations:"Reservierungen",util:"Kapazitätsnutzung",arrived:"Ankunftseinträge",exceptions:"Offene Ausnahmen",capacity:"Kapazitätsdruck",outbox:"Benachrichtigungen",risk:"Operationsrisiken",healthy:"Gesund",retry:"Erneut",posture:"Betriebslage",stable:"Unter Kontrolle",watch:"Genau beobachten",critical:"Eingriff erforderlich",active:"Aktive Reservierungen",capacityTotal:"Gesamtkapazität",used:"Genutzt",failed:"Fehlgeschlagen",events:"Ereignisse",empty:"Kein offenes Betriebsrisiko",warehouse:"Lager / DC",slot:"Slot",pressure:"Druck",notificationRate:"Erfolgreiche Benachrichtigungen",authority:"Kanonische API-Autorität"},
 ar:{eyebrow:"EAY · عمليات الأرصفة",title:"مركز تحكم DockOS",sub:"الحجوزات والسعة والوصول وصحة الإشعارات في واجهة قرار واحدة.",reservations:"الحجوزات",util:"استخدام السعة",arrived:"سجلات الوصول",exceptions:"الاستثناءات المفتوحة",capacity:"ضغط السعة",outbox:"صحة الإشعارات",risk:"قائمة مخاطر التشغيل",healthy:"سليم",retry:"إعادة المحاولة",posture:"حالة التشغيل",stable:"تحت السيطرة",watch:"مراقبة دقيقة",critical:"يتطلب تدخلاً",active:"الحجوزات النشطة",capacityTotal:"السعة الإجمالية",used:"المستخدم",failed:"فشل",events:"الأحداث",empty:"لا توجد مخاطر تشغيل مفتوحة",warehouse:"المستودع / المركز",slot:"الفترة",pressure:"الضغط",notificationRate:"الإشعارات الناجحة",authority:"مرجعية API الأساسية"},
 fr:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Réservations, capacité, arrivées et notifications sur une seule surface de décision.",reservations:"Réservations",util:"Utilisation capacité",arrived:"Arrivées enregistrées",exceptions:"Exceptions ouvertes",capacity:"Pression capacité",outbox:"Santé notifications",risk:"File des risques opérationnels",healthy:"Sain",retry:"Réessayer",posture:"Posture opérationnelle",stable:"Sous contrôle",watch:"Surveillance étroite",critical:"Intervention requise",active:"Réservations actives",capacityTotal:"Capacité totale",used:"Utilisée",failed:"Échec",events:"Événements",empty:"Aucun risque opérationnel ouvert",warehouse:"Entrepôt / DC",slot:"Créneau",pressure:"Pression",notificationRate:"Notifications réussies",authority:"Autorité API canonique"},
 es:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Reservas, capacidad, llegadas y notificaciones en una sola vista de decisión.",reservations:"Reservas",util:"Uso de capacidad",arrived:"Llegadas registradas",exceptions:"Excepciones abiertas",capacity:"Presión de capacidad",outbox:"Salud de notificaciones",risk:"Cola de riesgo operativo",healthy:"Saludable",retry:"Reintentar",posture:"Estado operativo",stable:"Bajo control",watch:"Vigilar de cerca",critical:"Intervención requerida",active:"Reservas activas",capacityTotal:"Capacidad total",used:"Utilizada",failed:"Fallidas",events:"Eventos",empty:"Sin riesgo operativo abierto",warehouse:"Almacén / DC",slot:"Franja",pressure:"Presión",notificationRate:"Notificaciones exitosas",authority:"Autoridad API canónica"},
 it:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Prenotazioni, capacità, arrivi e notifiche in un'unica vista decisionale.",reservations:"Prenotazioni",util:"Utilizzo capacità",arrived:"Arrivi registrati",exceptions:"Eccezioni aperte",capacity:"Pressione capacità",outbox:"Salute notifiche",risk:"Coda rischi operativi",healthy:"Sano",retry:"Riprova",posture:"Stato operativo",stable:"Sotto controllo",watch:"Monitorare da vicino",critical:"Intervento richiesto",active:"Prenotazioni attive",capacityTotal:"Capacità totale",used:"Utilizzata",failed:"Fallite",events:"Eventi",empty:"Nessun rischio operativo aperto",warehouse:"Magazzino / DC",slot:"Slot",pressure:"Pressione",notificationRate:"Notifiche riuscite",authority:"Autorità API canonica"},
 nl:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Reserveringen, capaciteit, aankomsten en meldingen in één beslissingsweergave.",reservations:"Reserveringen",util:"Capaciteitsgebruik",arrived:"Aankomstregistraties",exceptions:"Open uitzonderingen",capacity:"Capaciteitsdruk",outbox:"Meldingsgezondheid",risk:"Operationele risicowachtrij",healthy:"Gezond",retry:"Opnieuw",posture:"Operationele status",stable:"Onder controle",watch:"Nauw volgen",critical:"Interventie vereist",active:"Actieve reserveringen",capacityTotal:"Totale capaciteit",used:"Gebruikt",failed:"Mislukt",events:"Gebeurtenissen",empty:"Geen open operationeel risico",warehouse:"Magazijn / DC",slot:"Slot",pressure:"Druk",notificationRate:"Succesvolle meldingen",authority:"Canonieke API-autoriteit"},
 pl:{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Rezerwacje, pojemność, przyjazdy i powiadomienia w jednym widoku decyzyjnym.",reservations:"Rezerwacje",util:"Wykorzystanie pojemności",arrived:"Zarejestrowane przyjazdy",exceptions:"Otwarte wyjątki",capacity:"Presja pojemności",outbox:"Stan powiadomień",risk:"Kolejka ryzyka operacyjnego",healthy:"Zdrowy",retry:"Ponów",posture:"Stan operacyjny",stable:"Pod kontrolą",watch:"Ścisły monitoring",critical:"Wymagana interwencja",active:"Aktywne rezerwacje",capacityTotal:"Łączna pojemność",used:"Wykorzystane",failed:"Nieudane",events:"Zdarzenia",empty:"Brak otwartego ryzyka operacyjnego",warehouse:"Magazyn / DC",slot:"Slot",pressure:"Presja",notificationRate:"Udane powiadomienia",authority:"Kanoniczny autorytet API"},
 "pt-BR":{eyebrow:"EAY · DOCK OPERATIONS",title:"DockOS Control Tower",sub:"Reservas, capacidade, chegadas e notificações em uma única visão de decisão.",reservations:"Reservas",util:"Uso de capacidade",arrived:"Chegadas registradas",exceptions:"Exceções abertas",capacity:"Pressão de capacidade",outbox:"Saúde das notificações",risk:"Fila de risco operacional",healthy:"Saudável",retry:"Tentar novamente",posture:"Postura operacional",stable:"Sob controle",watch:"Monitorar de perto",critical:"Intervenção necessária",active:"Reservas ativas",capacityTotal:"Capacidade total",used:"Utilizada",failed:"Falhas",events:"Eventos",empty:"Nenhum risco operacional aberto",warehouse:"Armazém / DC",slot:"Slot",pressure:"Pressão",notificationRate:"Notificações bem-sucedidas",authority:"Autoridade API canônica"}
};

const terminalStatuses=new Set(["cancelled","canceled","completed"]);
const failureStatuses=new Set(["failed","dead","error"]);

export default function DockOSExecutiveControlTower(){
 const{locale="tr",dir="ltr"}=useDockOSUi();const c=COPY[locale]||COPY.en;
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError(false);Promise.all([getKpis({}),getReservations({}),getSlots({}),getNotificationOutbox(100)]).then(([kpis,reservations,slots,outbox])=>{if(active)setData({kpis:kpis||{},reservations:reservations||[],slots:slots||[],outbox:outbox||[]})}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reload]);
 const model=useMemo(()=>{if(!data)return null;const cap=data.slots.reduce((s,x)=>s+Number(x.capacity||x.total_capacity||0),0);const used=data.slots.reduce((s,x)=>s+Number(x.reserved_count||x.used_capacity||0),0);const util=cap?used/cap*100:0;const arrived=data.reservations.filter(x=>String(x.status||"").toLowerCase().includes("arriv")||x.arrived_at).length;const active=data.reservations.filter(x=>!terminalStatuses.has(String(x.status||"").toLowerCase())).length;const failed=data.outbox.filter(x=>failureStatuses.has(String(x.status||"").toLowerCase())).length;const successRate=data.outbox.length?Math.max(0,(data.outbox.length-failed)/data.outbox.length*100):100;const risky=data.slots.map(x=>{const cc=Number(x.capacity||x.total_capacity||0),uu=Number(x.reserved_count||x.used_capacity||0);return{...x,_capacity:cc,_used:uu,_pressure:cc?uu/cc*100:0}}).filter(x=>x._pressure>=85).sort((a,b)=>b._pressure-a._pressure);const posture=util>=100||failed>0||risky.some(x=>x._pressure>=100)?"critical":util>=85||risky.length?"watch":"stable";return{cap,used,util,arrived,active,failed,successRate,risky,posture}},[data]);
 if(loading)return <section className="dock-ct-state" role="status" aria-busy="true">…</section>;
 if(error)return <section className="dock-ct-state" role="alert"><button type="button" onClick={()=>setReload(v=>v+1)}>{c.retry}</button></section>;
 const postureLabel=model.posture==="critical"?c.critical:model.posture==="watch"?c.watch:c.stable;
 return <section className="dock-ct" dir={dir}>
  <header><div><span>{c.eyebrow}</span><h2>{c.title}</h2><p>{c.sub}</p></div><div className={`dock-posture ${model.posture}`}><span>{c.posture}</span><strong>{postureLabel}</strong><small>{c.authority}</small></div></header>
  <div className="dock-ct-kpis"><K l={c.reservations} v={data.reservations.length}/><K l={c.active} v={model.active}/><K l={c.util} v={`${model.util.toFixed(1)}%`} hot={model.util>=90}/><K l={c.arrived} v={model.arrived}/><K l={c.exceptions} v={model.failed} hot={model.failed>0}/></div>
  <div className="dock-ct-grid">
   <article><h3>{c.capacity}</h3><div className="dock-pressure" aria-label={`${c.util} ${model.util.toFixed(1)}%`}><i data-pressure={model.posture} style={{width:`${Math.min(100,model.util)}%`}}/></div><div className="dock-stat-row"><span>{c.used}<strong>{model.used}</strong></span><span>{c.capacityTotal}<strong>{model.cap}</strong></span></div></article>
   <article><h3>{c.outbox}</h3><strong className={model.failed?"dock-alert":"dock-ok"}>{model.failed?`${model.failed} ${c.failed}`:c.healthy}</strong><div className="dock-stat-row"><span>{c.notificationRate}<strong>{model.successRate.toFixed(1)}%</strong></span><span>{c.events}<strong>{data.outbox.length}</strong></span></div></article>
   <article className="wide"><h3>{c.risk}</h3>{model.risky.length?<div className="dock-risk-list"><div className="dock-risk-head"><b>{c.warehouse}</b><span>{c.slot}</span><strong>{c.pressure}</strong></div>{model.risky.slice(0,10).map((x,i)=><div key={`${x.warehouse_name||x.warehouse||"dc"}-${x.date||i}-${x.slot||i}`}><b>{x.warehouse_name||x.warehouse||"DC"}</b><span>{x.date||""} · {x.slot||""}</span><strong>{x._used} / {x._capacity} · {x._pressure.toFixed(0)}%</strong></div>)}</div>:<p className="dock-empty">{c.empty}</p>}</article>
  </div>
 </section>
}
function K({l,v,hot}){return <div className={hot?"dock-ct-kpi hot":"dock-ct-kpi"}><span>{l}</span><strong>{v}</strong></div>}
