import React,{useEffect,useMemo,useState}from"react";
import{getKpis,getNotificationOutbox,getReservations,getSlots}from"./dockosApi.js";
import{useDockOSUi}from"./DockOSUiContext.jsx";
import"./dockos-control-tower.css";

const COPY={
 tr:{title:"DockOS Control Tower",sub:"Randevu, kapasite, tedarikçi ve bildirim sağlığı tek operasyon görünümünde.",reservations:"Rezervasyon",util:"Kapasite Kullanımı",arrival:"Varış Uyum",exceptions:"Açık İstisna",capacity:"Kapasite Basıncı",supplier:"Tedarikçi / DC Riski",outbox:"Bildirim Sağlığı",risk:"Operasyon Risk Kuyruğu",healthy:"Sağlıklı",retry:"Tekrar Dene"},
 en:{title:"DockOS Control Tower",sub:"Reservations, capacity, supplier and notification health in one operational view.",reservations:"Reservations",util:"Capacity Utilization",arrival:"Arrival Compliance",exceptions:"Open Exceptions",capacity:"Capacity Pressure",supplier:"Supplier / DC Risk",outbox:"Notification Health",risk:"Operations Risk Queue",healthy:"Healthy",retry:"Retry"},
 de:{title:"DockOS Control Tower",sub:"Reservierungen, Kapazität, Lieferanten und Benachrichtigungen in einer operativen Sicht.",reservations:"Reservierungen",util:"Kapazitätsnutzung",arrival:"Ankunftstreue",exceptions:"Offene Ausnahmen",capacity:"Kapazitätsdruck",supplier:"Lieferanten-/DC-Risiko",outbox:"Benachrichtigungen",risk:"Operationsrisiken",healthy:"Gesund",retry:"Erneut"},
 ar:{title:"مركز تحكم DockOS",sub:"الحجوزات والسعة والموردون وصحة الإشعارات في عرض تشغيلي واحد.",reservations:"الحجوزات",util:"استخدام السعة",arrival:"التزام الوصول",exceptions:"الاستثناءات المفتوحة",capacity:"ضغط السعة",supplier:"مخاطر المورد / المركز",outbox:"صحة الإشعارات",risk:"قائمة مخاطر التشغيل",healthy:"سليم",retry:"إعادة المحاولة"}
};

export default function DockOSExecutiveControlTower(){
 const{locale="tr",dir="ltr"}=useDockOSUi();const c=COPY[locale]||COPY.en;
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError(false);Promise.all([getKpis({}),getReservations({}),getSlots({}),getNotificationOutbox(100)]).then(([kpis,reservations,slots,outbox])=>{if(active)setData({kpis:kpis||{},reservations:reservations||[],slots:slots||[],outbox:outbox||[]})}).catch(()=>{if(active)setError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reload]);
 const model=useMemo(()=>{if(!data)return null;const cap=data.slots.reduce((s,x)=>s+Number(x.capacity||x.total_capacity||0),0);const used=data.slots.reduce((s,x)=>s+Number(x.reserved_count||x.used_capacity||0),0);const util=cap?used/cap*100:0;const arrived=data.reservations.filter(x=>String(x.status||"").toLowerCase().includes("arriv")||x.arrived_at).length;const active=data.reservations.filter(x=>!["cancelled","canceled","completed"].includes(String(x.status||"").toLowerCase())).length;const failed=data.outbox.filter(x=>["failed","dead","error"].includes(String(x.status||"").toLowerCase())).length;const risky=data.slots.filter(x=>{const cc=Number(x.capacity||x.total_capacity||0),uu=Number(x.reserved_count||x.used_capacity||0);return cc>0&&uu/cc>=.9}).sort((a,b)=>Number(b.reserved_count||b.used_capacity||0)-Number(a.reserved_count||a.used_capacity||0));return{cap,used,util,arrived,active,failed,risky}},[data]);
 if(loading)return <section className="dock-ct-state" role="status" aria-busy="true">…</section>;
 if(error)return <section className="dock-ct-state" role="alert"><button onClick={()=>setReload(v=>v+1)}>{c.retry}</button></section>;
 return <section className="dock-ct" dir={dir}><header><div><span>EAY · DOCK OPERATIONS</span><h2>{c.title}</h2><p>{c.sub}</p></div></header><div className="dock-ct-kpis"><K l={c.reservations} v={data.reservations.length}/><K l={c.util} v={`${model.util.toFixed(1)}%`} hot={model.util>=90}/><K l={c.arrival} v={model.arrived}/><K l={c.exceptions} v={model.failed} hot={model.failed>0}/></div><div className="dock-ct-grid"><article><h3>{c.capacity}</h3><div className="dock-pressure"><i style={{width:`${Math.min(100,model.util)}%`}}/></div><p>{model.used} / {model.cap}</p></article><article><h3>{c.outbox}</h3><strong>{model.failed?`${model.failed} exception`:c.healthy}</strong><p>{data.outbox.length} events</p></article><article className="wide"><h3>{c.risk}</h3><div className="dock-risk-list">{model.risky.slice(0,8).map((x,i)=><div key={`${x.warehouse_name||x.warehouse||"dc"}-${x.date||i}-${x.slot||i}`}><b>{x.warehouse_name||x.warehouse||"DC"}</b><span>{x.date||""} · {x.slot||""}</span><strong>{Number(x.reserved_count||x.used_capacity||0)} / {Number(x.capacity||x.total_capacity||0)}</strong></div>)}</div></article></div></section>
}
function K({l,v,hot}){return <div className={hot?"dock-ct-kpi hot":"dock-ct-kpi"}><span>{l}</span><strong>{v}</strong></div>}
