import React, { useEffect, useMemo, useState } from "react";
import { CalendarPlus, CalendarRange, CheckCircle2, Clock3, MapPin, RefreshCw, ShieldCheck, XCircle } from "lucide-react";

import { mutateCandidateInterview, viewCandidateInterview } from "./recruitmentApi.js";
import "./candidateInterviewPortal.css";

const COPY = {
  tr: { eyebrow:"EAY Güvenli Aday Portalı", title:"Mülakat zamanınızı seçin", intro:"Uygun saatlerden birini seçebilir, mevcut randevunuzu yeniden planlayabilir veya iptal edebilirsiniz.", loading:"Mülakat seçenekleri doğrulanıyor…", invalid:"Bu mülakat bağlantısı geçersiz veya süresi dolmuş olabilir.", mode:"Görüşme tipi", location:"Lokasyon / kanal", duration:"Süre", available:"Uygun saatler", full:"Dolu", book:"Bu saati seç", reschedule:"Bu saate taşı", cancel:"Randevuyu iptal et", booked:"Randevunuz", addCalendar:"Takvime ekle (.ics)", saved:"Mülakat randevunuz kaydedildi.", cancelled:"Mülakat randevunuz iptal edildi.", rotating:"Güvenlik nedeniyle her değişiklikten sonra bağlantı yetkisi otomatik yenilenir.", noSlots:"Şu anda uygun slot yok. İK yeni slot açtığında tekrar kontrol edebilirsiniz.", closed:"Bu mülakat planı artık self-service için açık değil.", instructions:"Hazırlık notları" },
  en: { eyebrow:"EAY Secure Candidate Portal", title:"Choose your interview time", intro:"Select an available time, reschedule your current booking, or cancel it.", loading:"Verifying interview options…", invalid:"This interview link may be invalid or expired.", mode:"Meeting type", location:"Location / channel", duration:"Duration", available:"Available times", full:"Full", book:"Choose this time", reschedule:"Move to this time", cancel:"Cancel booking", booked:"Your booking", addCalendar:"Add to calendar (.ics)", saved:"Your interview booking was saved.", cancelled:"Your interview booking was cancelled.", rotating:"For security, the capability is automatically rotated after every change.", noSlots:"No slot is currently available. Check again when HR opens new times.", closed:"This interview schedule is no longer open for self-service.", instructions:"Preparation notes" },
  de: { eyebrow:"EAY Sicheres Bewerberportal", title:"Interviewzeit wählen", intro:"Wählen Sie einen verfügbaren Termin, verschieben Sie Ihre Buchung oder stornieren Sie sie.", loading:"Interviewoptionen werden geprüft…", invalid:"Dieser Interview-Link ist möglicherweise ungültig oder abgelaufen.", mode:"Gesprächsart", location:"Ort / Kanal", duration:"Dauer", available:"Verfügbare Zeiten", full:"Belegt", book:"Termin wählen", reschedule:"Auf diesen Termin verschieben", cancel:"Termin stornieren", booked:"Ihre Buchung", addCalendar:"Zum Kalender hinzufügen (.ics)", saved:"Ihre Interviewbuchung wurde gespeichert.", cancelled:"Ihre Interviewbuchung wurde storniert.", rotating:"Aus Sicherheitsgründen wird die Berechtigung nach jeder Änderung automatisch erneuert.", noSlots:"Derzeit ist kein Termin verfügbar.", closed:"Dieser Interviewplan ist nicht mehr für Self-Service geöffnet.", instructions:"Vorbereitungshinweise" },
  ar: { eyebrow:"بوابة EAY الآمنة للمرشحين", title:"اختر موعد المقابلة", intro:"اختر موعداً متاحاً أو أعد جدولة الحجز الحالي أو قم بإلغائه.", loading:"جارٍ التحقق من خيارات المقابلة…", invalid:"قد يكون رابط المقابلة غير صالح أو منتهي الصلاحية.", mode:"نوع المقابلة", location:"المكان / القناة", duration:"المدة", available:"المواعيد المتاحة", full:"ممتلئ", book:"اختر هذا الموعد", reschedule:"انقل إلى هذا الموعد", cancel:"إلغاء الحجز", booked:"حجزك", addCalendar:"إضافة إلى التقويم (.ics)", saved:"تم حفظ موعد المقابلة.", cancelled:"تم إلغاء موعد المقابلة.", rotating:"للأمان يتم تدوير صلاحية الرابط تلقائياً بعد كل تغيير.", noSlots:"لا يوجد موعد متاح حالياً.", closed:"لم يعد جدول المقابلة مفتوحاً للخدمة الذاتية.", instructions:"ملاحظات التحضير" },
};

function localeKey(){const raw=(navigator.language||"en").toLowerCase();if(raw.startsWith("tr"))return"tr";if(raw.startsWith("de"))return"de";if(raw.startsWith("ar"))return"ar";return"en";}
function readCapability(){const params=new URLSearchParams(String(window.location.hash||"").replace(/^#/,""));const value=params.get("interview");if(value){try{sessionStorage.setItem("eay.candidate.interview.capability",value);}catch{}window.history.replaceState(null,"",`${window.location.pathname}${window.location.search}`);return value;}try{return sessionStorage.getItem("eay.candidate.interview.capability")||"";}catch{return"";}}
function saveCapability(value){try{sessionStorage.setItem("eay.candidate.interview.capability",value);}catch{}}
function clearCapability(){try{sessionStorage.removeItem("eay.candidate.interview.capability");}catch{}}
function displayDate(value){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}
function icsDate(value){return new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z");}
function icsEscape(value){return String(value||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");}

export default function CandidateInterviewPortal(){
  const language=localeKey();const c=COPY[language]||COPY.en;const rtl=language==="ar";
  const [capability,setCapability]=useState(()=>readCapability());const [schedule,setSchedule]=useState(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");
  useEffect(()=>{document.title=c.title;if(!capability){setError(c.invalid);return;}let active=true;viewCandidateInterview(capability).then((result)=>{if(active)setSchedule(result);}).catch(()=>{if(active){clearCapability();setError(c.invalid);}});return()=>{active=false;};},[capability,c.invalid,c.title]);
  const bookedSlot=useMemo(()=>schedule?.slots?.find((slot)=>slot.slotId===schedule?.booking?.slotId)||null,[schedule]);
  async function mutate(action,slotId=null){setBusy(`${action}-${slotId||""}`);setError("");setNotice("");try{const result=await mutateCandidateInterview(capability,action,slotId);if(result.nextCapability){saveCapability(result.nextCapability);setCapability(result.nextCapability);}setSchedule(result.schedule);setNotice(action==="CANCEL"?c.cancelled:c.saved);}catch(err){setError(err.message);}finally{setBusy("");}}
  function downloadCalendar(){if(!bookedSlot||!schedule)return;const uid=`${schedule.scheduleId}-${schedule.booking?.bookingId||"booking"}@eay`;const content=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//EAY//Candidate Interview//EN","CALSCALE:GREGORIAN","METHOD:PUBLISH","BEGIN:VEVENT",`UID:${uid}`,`DTSTAMP:${icsDate(new Date())}`,`DTSTART:${icsDate(bookedSlot.startsAt)}`,`DTEND:${icsDate(bookedSlot.endsAt)}`,`SUMMARY:${icsEscape(schedule.title)}`,`LOCATION:${icsEscape(schedule.locationLabel)}`,`DESCRIPTION:${icsEscape(schedule.instructions)}`,"END:VEVENT","END:VCALENDAR",""].join("\r\n");const blob=new Blob([content],{type:"text/calendar;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");try{a.href=url;a.download="eay-interview.ics";a.click();}finally{URL.revokeObjectURL(url);}}
  if(error&&!schedule)return <main className="candidate-interview-page" dir={rtl?"rtl":"ltr"}><section className="candidate-interview-shell"><div className="candidate-interview-result error" role="alert"><XCircle size={48}/><h1>{c.invalid}</h1></div></section></main>;
  if(!schedule)return <main className="candidate-interview-page" dir={rtl?"rtl":"ltr"}><section className="candidate-interview-shell"><div className="candidate-interview-loading" role="status"><RefreshCw size={24}/>{c.loading}</div></section></main>;
  const open=schedule.status==="OPEN";const available=(schedule.slots||[]).filter((slot)=>slot.status==="OPEN"&&slot.remaining>0&&new Date(slot.startsAt)>new Date());
  return <main className="candidate-interview-page" dir={rtl?"rtl":"ltr"}><section className="candidate-interview-shell" aria-live="polite"><div className="candidate-interview-brand"><ShieldCheck size={21}/>{c.eyebrow}</div><header><h1>{c.title}</h1><p>{c.intro}</p></header>{error?<div className="candidate-interview-alert error" role="alert">{error}</div>:null}{notice?<div className="candidate-interview-alert success" role="status"><CheckCircle2 size={16}/>{notice}</div>:null}<div className="candidate-interview-meta"><div><small>{c.mode}</small><strong>{schedule.meetingMode}</strong></div><div><small>{c.duration}</small><strong>{schedule.durationMinutes} min</strong></div><div><small>{c.location}</small><strong>{schedule.locationLabel||"—"}</strong></div></div>{schedule.instructions?<div className="candidate-interview-note"><strong>{c.instructions}</strong><p>{schedule.instructions}</p></div>:null}<div className="candidate-interview-security"><ShieldCheck size={16}/><span>{c.rotating}</span></div>{bookedSlot&&schedule.booking?.status==="BOOKED"?<section className="candidate-interview-booked"><div><small>{c.booked}</small><strong>{displayDate(bookedSlot.startsAt)}</strong></div><div className="candidate-interview-booked-actions"><button type="button" onClick={downloadCalendar}><CalendarPlus size={16}/>{c.addCalendar}</button>{open?<button type="button" className="danger" disabled={busy.startsWith("CANCEL")} onClick={()=>mutate("CANCEL")}><XCircle size={16}/>{c.cancel}</button>:null}</div></section>:null}<section className="candidate-interview-slots"><h2><CalendarRange size={18}/>{c.available}</h2>{!open?<p>{c.closed}</p>:available.length?available.map((slot)=><article key={slot.slotId} className={slot.slotId===bookedSlot?.slotId?"selected":""}><div><Clock3 size={17}/><span><strong>{displayDate(slot.startsAt)}</strong><small>{slot.remaining}/{slot.capacity}</small></span></div>{slot.slotId===bookedSlot?.slotId?<CheckCircle2 size={20}/>:<button type="button" disabled={Boolean(busy)} onClick={()=>mutate(schedule.booking?.status==="BOOKED"?"RESCHEDULE":"BOOK",slot.slotId)}>{schedule.booking?.status==="BOOKED"?c.reschedule:c.book}</button>}</article>):<p>{c.noSlots}</p>}</section></section></main>;
}
