const COPY = {
  tr: {
    evidenceTitle: "Gizlilik Kontrollü Kanıt Aktarımı", evidenceSubtitle: "Yalnız cihazda yüz/PII bulanıklaştırması tamamlanmış türev private gateway'e yüklenir. Upload veya client claim, server privacy doğrulaması değildir.", auditRun: "Denetim çalışması", auditItemKey: "Denetim maddesi", sanitizedFile: "Bulanıklaştırılmış private kanıt", sourceFingerprint: "Orijinal kaynak SHA-256", privacyPolicy: "Gizlilik politika sürümü", detectorModel: "Cihaz redaction modeli", canonicalFrames: "Kanonik kare", processedFrames: "Redaction uygulanmış kare", faceBlurConfirm: "Tüm yüz ve PII alanlarının cihazda bulanıklaştırıldığını doğruluyorum", evidenceUpload: "Private kanıtı yükle", evidenceUploading: "Yükleniyor…", privacyHold: "SERVER PRIVACY HOLD", privacyHoldBody: "Server privacy verifier için public tetikleme endpoint'i yok. Kanıt private ve bağlıdır; fakat AI hattına veya doğrulanmış kapanışa geçemez.", videoHold: "Video transport kontrollü HOLD durumunda", videoHoldBody: "Mevcut server privacy authority yalnız image/jpeg doğrular. Video için kanonik kare manifesti ve server verifier endpoint'i olmadan tamamlandı denmez.", attachAction: "Kapanış kanıtı olarak aksiyona bağla", evidenceError: "Kanıt aktarımı tamamlanamadı", frameMismatch: "Her kanonik kare redaction kapsamına alınmalıdır.", storageReceipt: "Private storage receipt alındı", redactionBound: "Server-bound redaction claim oluşturuldu", noRuns: "Kanıt kabul edebilen bir denetim çalışması yok.",
    actionsTitle: "Düzeltici Aksiyon Merkezi", actionsSubtitle: "Bulgudan kapanış kanıtına kadar aynı denetim maddesine bağlı, sürüm kontrollü aksiyon akışı.", actionNoCases: "Yetkili kapsamda aksiyon bulunmuyor.", actionSelect: "Detayını açmak için bir aksiyon seçin.", actionOrigin: "Orijinal denetim maddesine git", actionClosureEvidence: "Kapanış kanıtı referansı", actionVerificationReceipt: "Doğrulama receipt referansı", actionStart: "Aksiyonu başlat", actionSubmit: "Doğrulamaya gönder", actionVerify: "İnsan doğrulaması", actionClose: "Aksiyonu kapat", actionSaveError: "Aksiyon güncellenemedi", assignee: "Atanan", dueDate: "SLA / son tarih", priority: "Öncelik", status: "Durum", originalQuestion: "Orijinal soru / madde", actionReadOnly: "Bu durum veya yetki kapsamında güncelleme yapılamaz.",
    startAuditTitle: "Yeni denetim başlat", program: "Denetim programı", locationId: "Lokasyon kimliği", sourceMode: "Kanıt modu", startAuditHelp: "Yalnız aktif, sunucu tarafından doğrulanan program sürümleri başlatılabilir. Yönetici ataması istemciden gönderilmez.", cancel: "Vazgeç", starting: "Başlatılıyor…", startAuditError: "Denetim başlatılamadı", activeProgramsRequired: "Başlatmak için yetkili kapsamda aktif bir denetim programı gerekir.",
    moduleTitle: "EAY Audit", moduleDescription: "Görsel, video ve operasyon gerçekliğini birleştiren denetim komuta merkezi.", moduleMeta: "Audit Intelligence", eyebrow: "EAY Audit Intelligence", title: "Denetim Komuta Merkezi", subtitle: "Standartları, kanıtı, aksiyonları ve Jarvis değerlendirmesini tek bir doğrulanabilir akışta yönetin.", preview: "Foundation Preview — canlı şirket verisi bağlanmadan metrikler örneklenmez.", start: "Denetim Başlat", standards: "Standartlar", schedule: "Planlama", audits: "Denetimler", actions: "Aksiyonlar", assurance: "Güvence", intelligence: "Jarvis", locations: "Lokasyonlar", critical: "Kritik Bulgular", overdue: "Geciken Aksiyonlar", repeat: "Tekrar Eden Bulgular", coverage: "Kanıt Kapsamı", noLiveData: "Canlı audit truth henüz bağlı değil", noLiveDataBody: "Bu ekran sahte KPI üretmez. İlk gerçek denetim veya yetkili veri kaynağı geldiğinde özetler burada oluşur.", connect: "Truth kaynağını bağla", jarvisTitle: "Jarvis Denetim Brifingi", jarvisBody: "Canlı veri geldiğinde Jarvis; tekrar eden riskleri, AI–denetçi ayrışmalarını, SLA ihlallerini ve lokasyon kümelerini burada açıklar.", askJarvis: "Jarvis'e sor", attention: "Dikkat Gerektirenler", evidence: "Evidence & Privacy", redaction: "Yüz/PII anonimleştirme zorunlu", redactionBody: "Fotoğraf veya video AI hattına girmeden önce redaction receipt üretmelidir. Yüz tanıma yapılmaz.", verification: "Kapanış doğrulaması", verificationBody: "Tamamlandı, kapandı demek değildir. Yeni kanıt AI veya yetkili insan tarafından doğrulanmadan aksiyon kapanmaz.", disagreement: "AI ↔ Denetçi Güvence Akışı", disagreementBody: "AI ve denetçi farklı karar verirse olay denetçi bazında kaydedilir, yönetici incelemesine ve gerekirse Operasyon Standartları'na yükselir.", videoAudit: "Video Audit", videoAuditBody: "Soru göstermeden yönlendirilmiş çekim: giriş → kahve → fırın → raf → soğuk alan. Sistem yalnız yeterli kanıt bulunan kontrolleri sonuçlandırır.", truthBoundary: "Truth Boundary", truthBoundaryBody: "AI confidence tek başına audit truth değildir. Kaynak, zaman, lokasyon, model, kural ve insan kararı birlikte saklanır.", actionView: "Intelligence View", actionViewBody: "Table / Kanban / Calendar'ın ötesinde tekrar, SLA riski, closure verification ve kök-neden kümelerini gösterir.",
    assuranceKicker: "Audit Assurance", assuranceTitle: "AI ↔ Denetçi Güvence Merkezi", assuranceSubtitle: "Ayrışmaları denetçi bazında izleyin; atanmış yönetici kararını ve gerektiğinde Operasyon Standartları incelemesini aynı kanıt zincirinde yönetin.", assuranceRefresh: "Yenile", assuranceLoadError: "Güvence verisi yüklenemedi", assuranceLoadErrorBody: "Yetki veya bağlantı doğrulanmadan güvence metriği üretilmez.", assuranceManagerQueue: "Yönetici incelemesi", assuranceStandardsQueue: "Standartlar incelemesi", assuranceUnassignedQueue: "Atanmamış", assuranceResolved: "Çözümlenen", assuranceCases: "Ayrışma vakaları", assuranceLoading: "Canlı güvence vakaları yükleniyor…", assuranceNoCases: "Yetkili kapsamda AI–denetçi ayrışması bulunmuyor.", assuranceSelectCase: "İncelenecek vakayı seçin", assuranceSelectCaseBody: "Karar, lokasyon ve kanıt zinciri seçilen vakaya göre açılır.", assuranceAuditor: "Denetçi", assuranceManager: "Yönetici", assuranceUnassigned: "Atanmamış", assuranceVersion: "Vaka sürümü", assuranceReason: "Karar gerekçesi", assuranceReasonPlaceholder: "Kanıta ve standarda dayalı karar gerekçesini yazın…", assuranceSaveError: "Güvence kararı kaydedilemedi.", assuranceConfirmAi: "AI kararını doğrula", assuranceConfirmAuditor: "Denetçi kararını doğrula", assuranceStandardChanged: "Standart değişmeli", assuranceModelReview: "Model incelemesi gerekli", assuranceNoChange: "Değişiklik yok", assuranceReadOnly: "Bu vaka için karar yetkiniz yok; kanıt ve sonuçlar salt okunur gösteriliyor.", assuranceCalibration: "Denetçi Kalibrasyonu", assuranceCalibrationBody: "Bu görünüm kalite ve model kalibrasyonu içindir; tek başına performans/HR yaptırımı değildir.", assuranceNoCalibration: "Karşılaştırılabilir AI–denetçi kararı henüz yok.", assuranceComparable: "Karşılaştırılabilir", assuranceAgreement: "Uyum", assuranceDisagreements: "Ayrışma", assuranceManagerAi: "Yönetici / AI", assuranceManagerAuditor: "Yönetici / Denetçi", assuranceStandardsReviewed: "Standartlar İncelemesi",
  },
  en: {
    evidenceTitle: "Privacy-Controlled Evidence Handoff", evidenceSubtitle: "Only a derivative with on-device face/PII blur completed is uploaded to the private gateway. Upload or a client claim is not server privacy verification.", auditRun: "Audit run", auditItemKey: "Audit item", sanitizedFile: "Blurred private evidence", sourceFingerprint: "Original source SHA-256", privacyPolicy: "Privacy policy version", detectorModel: "Device redaction model", canonicalFrames: "Canonical frames", processedFrames: "Redacted frames", faceBlurConfirm: "I confirm every face and PII region was blurred on device", evidenceUpload: "Upload private evidence", evidenceUploading: "Uploading…", privacyHold: "SERVER PRIVACY HOLD", privacyHoldBody: "No public trigger endpoint exists for the server privacy verifier. Evidence is private and bound, but cannot enter AI inference or verified closure.", videoHold: "Video transport is in controlled HOLD", videoHoldBody: "Current server privacy authority verifies image/jpeg only. Video cannot be called complete without a canonical-frame manifest and server verifier endpoint.", attachAction: "Attach as action closure evidence", evidenceError: "Evidence handoff could not complete", frameMismatch: "Every canonical frame must be covered by redaction.", storageReceipt: "Private storage receipt issued", redactionBound: "Server-bound redaction claim created", noRuns: "No audit run can accept evidence.",
    actionsTitle: "Corrective Action Center", actionsSubtitle: "A version-controlled action flow linked to the same audit item from finding through closure evidence.", actionNoCases: "No actions exist in the authorized scope.", actionSelect: "Select an action to open its details.", actionOrigin: "Go to original audit item", actionClosureEvidence: "Closure evidence reference", actionVerificationReceipt: "Verification receipt reference", actionStart: "Start action", actionSubmit: "Submit for verification", actionVerify: "Human verification", actionClose: "Close action", actionSaveError: "Action could not be updated", assignee: "Assignee", dueDate: "SLA / due date", priority: "Priority", status: "Status", originalQuestion: "Original question / item", actionReadOnly: "No update is available for this state or permission scope.",
    startAuditTitle: "Start a new audit", program: "Audit program", locationId: "Location ID", sourceMode: "Evidence mode", startAuditHelp: "Only active, server-authorized program versions can be started. Manager assignment is never supplied by the client.", cancel: "Cancel", starting: "Starting…", startAuditError: "Audit could not be started", activeProgramsRequired: "An active audit program in your authorized scope is required.",
    moduleTitle: "EAY Audit", moduleDescription: "Audit command center combining visual, video and operational truth.", moduleMeta: "Audit Intelligence", eyebrow: "EAY Audit Intelligence", title: "Audit Command Center", subtitle: "Manage standards, evidence, actions and Jarvis assessment in one verifiable flow.", preview: "Foundation Preview — metrics stay empty until live company truth is connected.", start: "Start Audit", standards: "Standards", schedule: "Scheduling", audits: "Audits", actions: "Actions", assurance: "Assurance", intelligence: "Jarvis", locations: "Locations", critical: "Critical Findings", overdue: "Overdue Actions", repeat: "Repeat Findings", coverage: "Evidence Coverage", noLiveData: "Live audit truth is not connected yet", noLiveDataBody: "This surface never invents KPIs. Summaries appear only after a real audit or an authorized source is connected.", connect: "Connect truth source", jarvisTitle: "Jarvis Audit Briefing", jarvisBody: "Once live data is available, Jarvis explains recurring risks, AI–auditor disagreements, SLA breaches and location clusters here.", askJarvis: "Ask Jarvis", attention: "Needs Attention", evidence: "Evidence & Privacy", redaction: "Face/PII redaction required", redactionBody: "Photo or video must produce a redaction receipt before entering the AI pipeline. Face recognition is not used.", verification: "Closure verification", verificationBody: "Completed is not closed. An action stays open until fresh evidence is verified by AI or an authorized reviewer.", disagreement: "AI ↔ Auditor Assurance", disagreementBody: "When AI and auditor disagree, the event is recorded per auditor, routed to the manager and escalated to Operations Standards when needed.", videoAudit: "Video Audit", videoAuditBody: "Guided capture without exposing questions: entrance → coffee → oven → shelves → cold zone. Only controls with sufficient evidence are concluded.", truthBoundary: "Truth Boundary", truthBoundaryBody: "AI confidence alone is not audit truth. Source, time, location, model, rule and human decision remain linked.", actionView: "Intelligence View", actionViewBody: "Beyond Table / Kanban / Calendar: recurrence, SLA risk, closure verification and root-cause clusters.",
    assuranceKicker: "Audit Assurance", assuranceTitle: "AI ↔ Auditor Assurance Center", assuranceSubtitle: "Track disagreement per auditor and manage assigned-manager decisions plus Operations Standards escalation in the same evidence chain.", assuranceRefresh: "Refresh", assuranceLoadError: "Assurance data could not be loaded", assuranceLoadErrorBody: "No assurance metric is produced until authorization and connectivity are verified.", assuranceManagerQueue: "Manager review", assuranceStandardsQueue: "Standards review", assuranceUnassignedQueue: "Unassigned", assuranceResolved: "Resolved", assuranceCases: "Disagreement cases", assuranceLoading: "Loading live assurance cases…", assuranceNoCases: "No AI–auditor disagreement exists in the authorized scope.", assuranceSelectCase: "Select a case to review", assuranceSelectCaseBody: "Decision, location and evidence context open for the selected case.", assuranceAuditor: "Auditor", assuranceManager: "Manager", assuranceUnassigned: "Unassigned", assuranceVersion: "Case version", assuranceReason: "Decision rationale", assuranceReasonPlaceholder: "Write a rationale grounded in evidence and the active standard…", assuranceSaveError: "Assurance decision could not be saved.", assuranceConfirmAi: "Confirm AI decision", assuranceConfirmAuditor: "Confirm auditor decision", assuranceStandardChanged: "Standard should change", assuranceModelReview: "Model review required", assuranceNoChange: "No change", assuranceReadOnly: "You do not hold decision authority for this case; evidence and outcomes remain read-only.", assuranceCalibration: "Auditor Calibration", assuranceCalibrationBody: "This view supports quality and model calibration; it is not an automatic performance or HR sanction.", assuranceNoCalibration: "No comparable AI–auditor decisions exist yet.", assuranceComparable: "Comparable", assuranceAgreement: "Agreement", assuranceDisagreements: "Disagreements", assuranceManagerAi: "Manager / AI", assuranceManagerAuditor: "Manager / Auditor", assuranceStandardsReviewed: "Standards Reviewed",
  },
};

const localizedOverrides = {
  de: { moduleDescription: "Audit-Kommandozentrale für visuelle, Video- und operative Evidenz.", title: "Audit-Kommandozentrale", start: "Audit starten", standards: "Standards", schedule: "Planung", audits: "Audits", actions: "Maßnahmen", locations: "Standorte", critical: "Kritische Befunde", overdue: "Überfällige Maßnahmen", repeat: "Wiederholte Befunde", coverage: "Evidenzabdeckung", askJarvis: "Jarvis fragen", attention: "Handlungsbedarf", redaction: "Gesichts-/PII-Anonymisierung erforderlich", verification: "Abschlussprüfung", disagreement: "AI ↔ Auditor Assurance", videoAudit: "Video-Audit" },
  ar: { moduleDescription: "مركز قيادة للتدقيق يجمع الأدلة المرئية والفيديو والحقيقة التشغيلية.", title: "مركز قيادة التدقيق", start: "بدء التدقيق", standards: "المعايير", schedule: "الجدولة", audits: "عمليات التدقيق", actions: "الإجراءات", locations: "المواقع", critical: "نتائج حرجة", overdue: "إجراءات متأخرة", repeat: "نتائج متكررة", coverage: "تغطية الأدلة", askJarvis: "اسأل Jarvis", attention: "يتطلب الانتباه", redaction: "إخفاء الوجه/البيانات الشخصية إلزامي", verification: "التحقق من الإغلاق", disagreement: "ضمان AI ↔ المدقق", videoAudit: "تدقيق بالفيديو" },
  fr: { moduleDescription: "Centre de commande d'audit réunissant preuves visuelles, vidéo et vérité opérationnelle.", title: "Centre de commande d'audit", start: "Démarrer l'audit", standards: "Standards", schedule: "Planification", audits: "Audits", actions: "Actions", locations: "Sites", critical: "Constats critiques", overdue: "Actions en retard", repeat: "Constats récurrents", coverage: "Couverture des preuves", askJarvis: "Demander à Jarvis", attention: "À surveiller", redaction: "Anonymisation visage/PII obligatoire", verification: "Vérification de clôture", disagreement: "Assurance AI ↔ Auditeur", videoAudit: "Audit vidéo" },
  es: { moduleDescription: "Centro de mando de auditoría que combina evidencia visual, vídeo y realidad operativa.", title: "Centro de mando de auditoría", start: "Iniciar auditoría", standards: "Estándares", schedule: "Planificación", audits: "Auditorías", actions: "Acciones", locations: "Ubicaciones", critical: "Hallazgos críticos", overdue: "Acciones vencidas", repeat: "Hallazgos repetidos", coverage: "Cobertura de evidencia", askJarvis: "Preguntar a Jarvis", attention: "Requiere atención", redaction: "Anonimización de rostro/PII obligatoria", verification: "Verificación de cierre", disagreement: "Garantía AI ↔ Auditor", videoAudit: "Auditoría de vídeo" },
  it: { moduleDescription: "Centro di comando audit che unisce evidenze visive, video e verità operativa.", title: "Centro di comando audit", start: "Avvia audit", standards: "Standard", schedule: "Pianificazione", audits: "Audit", actions: "Azioni", locations: "Sedi", critical: "Rilievi critici", overdue: "Azioni scadute", repeat: "Rilievi ricorrenti", coverage: "Copertura evidenze", askJarvis: "Chiedi a Jarvis", attention: "Richiede attenzione", redaction: "Anonimizzazione volto/PII obbligatoria", verification: "Verifica chiusura", disagreement: "Garanzia AI ↔ Auditor", videoAudit: "Video audit" },
  nl: { moduleDescription: "Audit-commandocentrum dat visueel bewijs, video en operationele waarheid combineert.", title: "Audit-commandocentrum", start: "Audit starten", standards: "Standaarden", schedule: "Planning", audits: "Audits", actions: "Acties", locations: "Locaties", critical: "Kritieke bevindingen", overdue: "Achterstallige acties", repeat: "Herhaalde bevindingen", coverage: "Bewijsdekking", askJarvis: "Vraag Jarvis", attention: "Aandacht vereist", redaction: "Gezichts-/PII-anonimisering verplicht", verification: "Sluitingsverificatie", disagreement: "AI ↔ Auditor Assurance", videoAudit: "Video-audit" },
  pl: { moduleDescription: "Centrum dowodzenia audytem łączące dowody wizualne, wideo i prawdę operacyjną.", title: "Centrum dowodzenia audytem", start: "Rozpocznij audyt", standards: "Standardy", schedule: "Planowanie", audits: "Audyty", actions: "Działania", locations: "Lokalizacje", critical: "Krytyczne ustalenia", overdue: "Zaległe działania", repeat: "Powtarzające się ustalenia", coverage: "Pokrycie dowodowe", askJarvis: "Zapytaj Jarvis", attention: "Wymaga uwagi", redaction: "Anonimizacja twarzy/PII obowiązkowa", verification: "Weryfikacja zamknięcia", disagreement: "AI ↔ Auditor Assurance", videoAudit: "Audyt wideo" },
  "pt-BR": { moduleDescription: "Centro de comando de auditoria que combina evidência visual, vídeo e verdade operacional.", title: "Centro de comando de auditoria", start: "Iniciar auditoria", standards: "Padrões", schedule: "Agendamento", audits: "Auditorias", actions: "Ações", locations: "Locais", critical: "Achados críticos", overdue: "Ações atrasadas", repeat: "Achados recorrentes", coverage: "Cobertura de evidências", askJarvis: "Perguntar ao Jarvis", attention: "Requer atenção", redaction: "Anonimização de rosto/PII obrigatória", verification: "Verificação de encerramento", disagreement: "Garantia AI ↔ Auditor", videoAudit: "Auditoria por vídeo" },
};

for (const [locale, overrides] of Object.entries(localizedOverrides)) COPY[locale] = { ...COPY.en, ...overrides };

function normalizedLocale(locale) {
  const raw = String(locale || "tr");
  if (COPY[raw]) return raw;
  const base = raw.split("-")[0].toLowerCase();
  return COPY[base] ? base : "en";
}

export function auditCopy(locale, key) {
  return COPY[normalizedLocale(locale)]?.[key] || COPY.en[key] || key;
}

export function localizeAuditModule(locale) {
  return { title: auditCopy(locale, "moduleTitle"), description: auditCopy(locale, "moduleDescription"), meta: auditCopy(locale, "moduleMeta") };
}

export function auditMessageCoverage(locales = ["tr", "en", "de", "ar", "fr", "es", "it", "nl", "pl", "pt-BR"]) {
  const canonical = Object.keys(COPY.en).sort();
  const missing = {};
  const extra = {};
  for (const locale of locales) {
    const keys = Object.keys(COPY[locale] || {}).sort();
    missing[locale] = canonical.filter((key) => !keys.includes(key));
    extra[locale] = keys.filter((key) => !canonical.includes(key));
  }
  return { missing, extra };
}
