import React, { useMemo } from "react";
import { apiDownload } from "../../api/client.js";
import { usePlatformPreferences } from "../../platform/preferences/PlatformPreferencesContext.jsx";
import "./budget-control-tower.css";

const COPY = {
  tr:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Bütçe, gerçekleşen, commitment, forecast ve finansal güvence aynı kanıta bağlı görünümde.",budget:"Bütçe",actual:"Actual",commitment:"Commitment",forecast:"Forecast",headroom:"Kalan Alan",variance:"Forecast Farkı",util:"Kullanım",risk:"Kontrol Bulguları",cost:"Cost Center Performansı",category:"Kategori Görünümü",supplier:"Supplier Exposure",reports:"Yönetim Raporları",download:"Executive CSV",evidence:"Kanıt",human:"İnsan incelemesi gerekli",noMutation:"AI finansal kaydı değiştiremez"},
  en:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Budget, actuals, commitments, forecast and assurance on one evidence-bound surface.",budget:"Budget",actual:"Actual",commitment:"Commitment",forecast:"Forecast",headroom:"Headroom",variance:"Forecast Variance",util:"Utilization",risk:"Control Findings",cost:"Cost Center Performance",category:"Category View",supplier:"Supplier Exposure",reports:"Management Reports",download:"Executive CSV",evidence:"Evidence",human:"Human review required",noMutation:"AI cannot mutate financial truth"},
  de:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Budget, Ist, Verpflichtungen, Forecast und Assurance in einer evidenzgebundenen Sicht.",budget:"Budget",actual:"Ist",commitment:"Verpflichtung",forecast:"Forecast",headroom:"Spielraum",variance:"Forecast-Abweichung",util:"Auslastung",risk:"Kontrollbefunde",cost:"Kostenstellen",category:"Kategorien",supplier:"Lieferantenexposure",reports:"Managementberichte",download:"Executive CSV",evidence:"Evidenz",human:"Menschliche Prüfung erforderlich",noMutation:"KI ändert keine Finanzwahrheit"},
  ar:{eyebrow:"EAY · المالية",title:"مركز الرقابة المالية",sub:"الميزانية والفعلي والالتزامات والتوقعات والضمان المالي في عرض موثق واحد.",budget:"الميزانية",actual:"الفعلي",commitment:"الالتزام",forecast:"التوقع",headroom:"المتبقي",variance:"فرق التوقع",util:"الاستخدام",risk:"نتائج الرقابة",cost:"مراكز التكلفة",category:"الفئات",supplier:"تعرض الموردين",reports:"تقارير الإدارة",download:"CSV تنفيذي",evidence:"الدليل",human:"تتطلب مراجعة بشرية",noMutation:"الذكاء الاصطناعي لا يغير الحقيقة المالية"},
  fr:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Budget, réel, engagements, prévision et assurance sur une vue liée aux preuves.",budget:"Budget",actual:"Réel",commitment:"Engagement",forecast:"Prévision",headroom:"Marge",variance:"Écart prévision",util:"Utilisation",risk:"Constats de contrôle",cost:"Centres de coûts",category:"Catégories",supplier:"Exposition fournisseurs",reports:"Rapports de gestion",download:"CSV exécutif",evidence:"Preuve",human:"Revue humaine requise",noMutation:"L'IA ne modifie pas la vérité financière"},
  es:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Presupuesto, real, compromisos, forecast y assurance en una vista basada en evidencia.",budget:"Presupuesto",actual:"Real",commitment:"Compromiso",forecast:"Forecast",headroom:"Margen",variance:"Variación forecast",util:"Utilización",risk:"Hallazgos de control",cost:"Centros de coste",category:"Categorías",supplier:"Exposición proveedores",reports:"Informes de gestión",download:"CSV ejecutivo",evidence:"Evidencia",human:"Revisión humana requerida",noMutation:"La IA no modifica la verdad financiera"},
  it:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Budget, actual, impegni, forecast e assurance in una vista legata alle evidenze.",budget:"Budget",actual:"Actual",commitment:"Impegno",forecast:"Forecast",headroom:"Margine",variance:"Scostamento forecast",util:"Utilizzo",risk:"Rilievi di controllo",cost:"Centri di costo",category:"Categorie",supplier:"Esposizione fornitori",reports:"Report direzionali",download:"CSV executive",evidence:"Evidenza",human:"Revisione umana richiesta",noMutation:"L'IA non modifica la verità finanziaria"},
  nl:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Budget, actuals, verplichtingen, forecast en assurance in één evidence-gebonden view.",budget:"Budget",actual:"Actual",commitment:"Verplichting",forecast:"Forecast",headroom:"Ruimte",variance:"Forecastverschil",util:"Benutting",risk:"Controlebevindingen",cost:"Kostenplaatsen",category:"Categorieën",supplier:"Leveranciersblootstelling",reports:"Managementrapporten",download:"Executive CSV",evidence:"Bewijs",human:"Menselijke review vereist",noMutation:"AI wijzigt financiële waarheid niet"},
  pl:{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Budżet, wykonanie, zobowiązania, prognoza i assurance w jednym widoku opartym na dowodach.",budget:"Budżet",actual:"Wykonanie",commitment:"Zobowiązanie",forecast:"Prognoza",headroom:"Pozostało",variance:"Odchylenie prognozy",util:"Wykorzystanie",risk:"Ustalenia kontrolne",cost:"Centra kosztów",category:"Kategorie",supplier:"Ekspozycja dostawców",reports:"Raporty zarządcze",download:"CSV Executive",evidence:"Dowód",human:"Wymagana weryfikacja człowieka",noMutation:"AI nie zmienia prawdy finansowej"},
  "pt-BR":{eyebrow:"EAY · FINANCE",title:"Financial Control Tower",sub:"Orçamento, realizado, compromissos, forecast e assurance em uma visão vinculada a evidências.",budget:"Orçamento",actual:"Realizado",commitment:"Compromisso",forecast:"Forecast",headroom:"Saldo",variance:"Variação forecast",util:"Utilização",risk:"Achados de controle",cost:"Centros de custo",category:"Categorias",supplier:"Exposição fornecedores",reports:"Relatórios gerenciais",download:"CSV executivo",evidence:"Evidência",human:"Revisão humana necessária",noMutation:"A IA não altera a verdade financeira"}
};

const money=(v,locale)=>new Intl.NumberFormat(locale||"tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(v||0));
const pct=(v,locale)=>`${Number(v||0).toLocaleString(locale||undefined,{maximumFractionDigits:1})}%`;

export default function BudgetControlTower({data}){
  const { locale="tr", localeMeta }=usePlatformPreferences();
  const dir=localeMeta?.dir||"ltr";
  const c=COPY[locale]||COPY.en;
  const maxCost=useMemo(()=>Math.max(1,...(data?.cost_centers||[]).map(x=>Number(x.budget||0))),[data]);
  async function download(){const blob=await apiDownload("/v1/budget/reports/executive.csv");const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="eay-budget-executive-pack.csv";a.click();URL.revokeObjectURL(url)}
  const s=data.summary||{};
  return <main className="bct" dir={dir}>
    <header className="bct-head"><div><span>{c.eyebrow}</span><h1>{c.title}</h1><p>{c.sub}</p></div><button onClick={download}>{c.download}</button></header>
    <section className="bct-kpis">
      <K l={c.budget} v={money(s.budget,locale)}/><K l={c.actual} v={money(s.actual,locale)}/><K l={c.commitment} v={money(s.commitment,locale)}/><K l={c.forecast} v={money(s.forecast,locale)} hot={Number(s.forecast_variance)<0}/><K l={c.headroom} v={money(s.remaining_headroom,locale)} hot={Number(s.remaining_headroom)<0}/><K l={c.util} v={pct(s.forecast_utilization_pct,locale)} hot={Number(s.forecast_utilization_pct)>100}/>
    </section>
    <section className="bct-grid">
      <Card title={c.cost} wide><div className="bct-bars">{(data.cost_centers||[]).slice(0,12).map(x=><div className="bct-bar" key={x.cost_center}><b>{x.cost_center}</b><div><i style={{width:`${Math.min(100,Number(x.forecast||0)/maxCost*100)}%`}}/></div><span>{money(x.forecast,locale)} / {money(x.budget,locale)}</span></div>)}</div></Card>
      <Card title={c.risk}><div className="bct-findings">{(data.findings||[]).slice(0,10).map(x=><article key={x.finding_id} data-severity={x.severity}><span>{x.severity}</span><b>{x.cost_center} · {x.category}</b><p>{x.reason} · {money(x.forecast,locale)} / {money(x.budget,locale)}</p><small>{c.evidence}: {String(x.evidence_fingerprint).slice(0,16)}… · {c.human}</small></article>)}</div></Card>
      <Card title={c.category}><div className="bct-table">{(data.categories||[]).slice(0,10).map(x=><div key={x.category}><b>{x.category}</b><span>{money(x.actual,locale)}</span><span>{money(x.forecast,locale)}</span><span>{money(x.forecast_variance,locale)}</span></div>)}</div></Card>
      <Card title={c.supplier}><ol className="bct-suppliers">{(data.suppliers||[]).slice(0,10).map(x=><li key={x.supplier}><span>{x.supplier}</span><b>{money(x.exposure,locale)}</b></li>)}</ol></Card>
      <Card title={c.reports} wide><div className="bct-reports">{(data.report_catalog||[]).map(x=><span key={x}>{x.replaceAll("_"," ")}</span>)}</div><footer><code>{String(data.evidence_fingerprint).slice(0,24)}…</code><strong>{c.noMutation}</strong></footer></Card>
    </section>
  </main>
}
function K({l,v,hot}){return <div className={hot?"bct-kpi hot":"bct-kpi"}><span>{l}</span><strong>{v}</strong></div>}
function Card({title,children,wide}){return <section className={wide?"bct-card wide":"bct-card"}><h2>{title}</h2>{children}</section>}
