export const ACADEMY_AUTHORING_MESSAGES = Object.freeze({
  tr: { createPath: "Öğrenme yolu oluştur", pathKey: "Yol anahtarı", certificateEnabled: "Tamamlanınca sertifika oluştur", publishedContent: "Yayınlanmış içerik sürümleri", audienceRoles: "Hedef roller", audienceOptional: "Rol hedefleme opsiyoneldir; rol seçilmezse yol yalnız manuel atamayla açılır.", dueDays: "Tamamlama süresi (gün)", savePath: "Öğrenme yolunu kaydet", noPublishedContent: "Önce en az bir içerik sürümünü yayınlayın.", noAudienceRoles: "Bu tenant için kullanılabilir rol bulunmuyor.", selectContentError: "En az bir yayınlanmış içerik sürümü seçin.", createError: "Öğrenme yolu oluşturulamadı.", manualOnly: "Manuel atama" },
  en: { createPath: "Create learning path", pathKey: "Path key", certificateEnabled: "Issue a certificate on completion", publishedContent: "Published content versions", audienceRoles: "Audience roles", audienceOptional: "Role targeting is optional; without a role, the path is available through manual assignment only.", dueDays: "Due in (days)", savePath: "Save learning path", noPublishedContent: "Publish at least one content version first.", noAudienceRoles: "No audience roles are available for this tenant.", selectContentError: "Select at least one published content version.", createError: "Learning path could not be created.", manualOnly: "Manual assignment" },
  de: { createPath: "Lernpfad erstellen", pathKey: "Pfadschlüssel", certificateEnabled: "Nach Abschluss ein Zertifikat ausstellen", publishedContent: "Veröffentlichte Inhaltsversionen", audienceRoles: "Zielrollen", audienceOptional: "Die Rollenzuweisung ist optional; ohne Rolle ist der Pfad nur per manueller Zuweisung verfügbar.", dueDays: "Fällig in (Tagen)", savePath: "Lernpfad speichern", noPublishedContent: "Veröffentlichen Sie zuerst mindestens eine Inhaltsversion.", noAudienceRoles: "Für diesen Mandanten sind keine Zielrollen verfügbar.", selectContentError: "Wählen Sie mindestens eine veröffentlichte Inhaltsversion aus.", createError: "Der Lernpfad konnte nicht erstellt werden.", manualOnly: "Manuelle Zuweisung" },
  ar: { createPath: "إنشاء مسار تعلم", pathKey: "مفتاح المسار", certificateEnabled: "إصدار شهادة عند الإكمال", publishedContent: "إصدارات المحتوى المنشورة", audienceRoles: "الأدوار المستهدفة", audienceOptional: "استهداف الأدوار اختياري؛ من دون دور لا يتاح المسار إلا عبر التعيين اليدوي.", dueDays: "المهلة (بالأيام)", savePath: "حفظ مسار التعلم", noPublishedContent: "انشر إصدار محتوى واحدًا على الأقل أولًا.", noAudienceRoles: "لا توجد أدوار مستهدفة متاحة لهذا المستأجر.", selectContentError: "اختر إصدار محتوى منشورًا واحدًا على الأقل.", createError: "تعذر إنشاء مسار التعلم.", manualOnly: "تعيين يدوي" },
  fr: { createPath: "Créer un parcours d’apprentissage", pathKey: "Clé du parcours", certificateEnabled: "Émettre un certificat à la fin", publishedContent: "Versions de contenu publiées", audienceRoles: "Rôles ciblés", audienceOptional: "Le ciblage par rôle est facultatif ; sans rôle, le parcours est disponible uniquement par affectation manuelle.", dueDays: "Échéance (jours)", savePath: "Enregistrer le parcours", noPublishedContent: "Publiez d’abord au moins une version de contenu.", noAudienceRoles: "Aucun rôle cible n’est disponible pour ce tenant.", selectContentError: "Sélectionnez au moins une version de contenu publiée.", createError: "Le parcours d’apprentissage n’a pas pu être créé.", manualOnly: "Affectation manuelle" },
  es: { createPath: "Crear ruta de aprendizaje", pathKey: "Clave de la ruta", certificateEnabled: "Emitir certificado al completar", publishedContent: "Versiones de contenido publicadas", audienceRoles: "Roles objetivo", audienceOptional: "La segmentación por rol es opcional; sin un rol, la ruta solo estará disponible mediante asignación manual.", dueDays: "Vence en (días)", savePath: "Guardar ruta de aprendizaje", noPublishedContent: "Publica primero al menos una versión de contenido.", noAudienceRoles: "No hay roles objetivo disponibles para este tenant.", selectContentError: "Selecciona al menos una versión de contenido publicada.", createError: "No se pudo crear la ruta de aprendizaje.", manualOnly: "Asignación manual" },
  it: { createPath: "Crea percorso di apprendimento", pathKey: "Chiave del percorso", certificateEnabled: "Emetti un certificato al completamento", publishedContent: "Versioni di contenuto pubblicate", audienceRoles: "Ruoli destinatari", audienceOptional: "Il targeting per ruolo è facoltativo; senza un ruolo, il percorso è disponibile solo tramite assegnazione manuale.", dueDays: "Scadenza (giorni)", savePath: "Salva percorso di apprendimento", noPublishedContent: "Pubblica prima almeno una versione di contenuto.", noAudienceRoles: "Non sono disponibili ruoli destinatari per questo tenant.", selectContentError: "Seleziona almeno una versione di contenuto pubblicata.", createError: "Impossibile creare il percorso di apprendimento.", manualOnly: "Assegnazione manuale" },
  nl: { createPath: "Leerpad maken", pathKey: "Padsleutel", certificateEnabled: "Certificaat uitgeven na voltooiing", publishedContent: "Gepubliceerde inhoudsversies", audienceRoles: "Doelrollen", audienceOptional: "Roltargeting is optioneel; zonder rol is het pad alleen beschikbaar via handmatige toewijzing.", dueDays: "Vervalt over (dagen)", savePath: "Leerpad opslaan", noPublishedContent: "Publiceer eerst ten minste één inhoudsversie.", noAudienceRoles: "Er zijn geen doelrollen beschikbaar voor deze tenant.", selectContentError: "Selecteer ten minste één gepubliceerde inhoudsversie.", createError: "Het leerpad kon niet worden gemaakt.", manualOnly: "Handmatige toewijzing" },
  pl: { createPath: "Utwórz ścieżkę nauki", pathKey: "Klucz ścieżki", certificateEnabled: "Wydaj certyfikat po ukończeniu", publishedContent: "Opublikowane wersje treści", audienceRoles: "Role docelowe", audienceOptional: "Kierowanie do ról jest opcjonalne; bez roli ścieżka jest dostępna tylko przez ręczne przypisanie.", dueDays: "Termin (dni)", savePath: "Zapisz ścieżkę nauki", noPublishedContent: "Najpierw opublikuj co najmniej jedną wersję treści.", noAudienceRoles: "Brak dostępnych ról docelowych dla tego tenant-a.", selectContentError: "Wybierz co najmniej jedną opublikowaną wersję treści.", createError: "Nie udało się utworzyć ścieżki nauki.", manualOnly: "Ręczne przypisanie" },
  "pt-BR": { createPath: "Criar trilha de aprendizagem", pathKey: "Chave da trilha", certificateEnabled: "Emitir certificado na conclusão", publishedContent: "Versões de conteúdo publicadas", audienceRoles: "Funções de público", audienceOptional: "O direcionamento por função é opcional; sem uma função, a trilha fica disponível apenas por atribuição manual.", dueDays: "Prazo (dias)", savePath: "Salvar trilha de aprendizagem", noPublishedContent: "Publique primeiro pelo menos uma versão de conteúdo.", noAudienceRoles: "Não há funções de público disponíveis para este tenant.", selectContentError: "Selecione pelo menos uma versão de conteúdo publicada.", createError: "Não foi possível criar a trilha de aprendizagem.", manualOnly: "Atribuição manual" },
});

export function translateAcademyAuthoring(locale, key) {
  return ACADEMY_AUTHORING_MESSAGES[locale]?.[key] || ACADEMY_AUTHORING_MESSAGES.en[key] || key;
}

export function academyAuthoringMessageCoverage(locales) {
  const referenceKeys = Object.keys(ACADEMY_AUTHORING_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, referenceKeys.filter((key) => typeof ACADEMY_AUTHORING_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(ACADEMY_AUTHORING_MESSAGES[locale] || {}).filter((key) => !referenceKeys.includes(key)).sort()])),
  };
}
