export const ACADEMY_SKILL_GAP_MESSAGES = Object.freeze({
  tr: { skillGap: "Yetkinlik açığı", skillGapHint: "Rol beklentileri ile son doğrulanmış kanıtınızı karşılaştırın ve açığı kapatan öğrenme yollarını görün.", noGaps: "Doğrulanmış kanıta göre mevcut rolleriniz için açık görünmüyor.", currentLevel: "Mevcut seviye", requiredLevel: "Gerekli seviye", gap: "Açık", requiredBy: "Rol gereksinimi", latestEvidence: "Son kanıt", recommendedPaths: "Önerilen öğrenme yolları", noRecommendation: "Bu açığı tek başına kapatan yayınlanmış ve rolünüze atanmış bir öğrenme yolu henüz yok.", policy: "Öneri politikası", refresh: "Yenile", loadError: "Yetkinlik açığı yüklenemedi.", openLearning: "Öğrenmeye devam et", openAcademy: "Academy'de aç" },
  en: { skillGap: "Skill gaps", skillGapHint: "Compare role expectations with your latest verified evidence and see learning paths that close the gap.", noGaps: "No gap is visible for your current roles based on verified evidence.", currentLevel: "Current level", requiredLevel: "Required level", gap: "Gap", requiredBy: "Required by", latestEvidence: "Latest evidence", recommendedPaths: "Recommended learning paths", noRecommendation: "No published, role-assigned learning path currently closes this gap on its own.", policy: "Recommendation policy", refresh: "Refresh", loadError: "Skill gaps could not be loaded.", openLearning: "Continue learning", openAcademy: "Open in Academy" },
  de: { skillGap: "Kompetenzlücken", skillGapHint: "Vergleichen Sie Rollenanforderungen mit Ihrem neuesten verifizierten Nachweis und sehen Sie passende Lernpfade.", noGaps: "Für Ihre aktuellen Rollen ist anhand verifizierter Nachweise keine Lücke sichtbar.", currentLevel: "Aktuelles Niveau", requiredLevel: "Erforderliches Niveau", gap: "Lücke", requiredBy: "Erforderlich für", latestEvidence: "Letzter Nachweis", recommendedPaths: "Empfohlene Lernpfade", noRecommendation: "Derzeit schließt kein veröffentlichter, Ihrer Rolle zugewiesener Lernpfad diese Lücke allein.", policy: "Empfehlungsrichtlinie", refresh: "Aktualisieren", loadError: "Kompetenzlücken konnten nicht geladen werden.", openLearning: "Lernen fortsetzen", openAcademy: "In Academy öffnen" },
  ar: { skillGap: "فجوات المهارات", skillGapHint: "قارن متطلبات الدور بآخر دليل موثق واعرض مسارات التعلم التي تغلق الفجوة.", noGaps: "لا توجد فجوة ظاهرة لأدوارك الحالية استنادًا إلى الأدلة الموثقة.", currentLevel: "المستوى الحالي", requiredLevel: "المستوى المطلوب", gap: "الفجوة", requiredBy: "مطلوب للدور", latestEvidence: "أحدث دليل", recommendedPaths: "مسارات التعلم المقترحة", noRecommendation: "لا يوجد حاليًا مسار تعلم منشور ومخصص لدورك يغلق هذه الفجوة بمفرده.", policy: "سياسة التوصية", refresh: "تحديث", loadError: "تعذر تحميل فجوات المهارات.", openLearning: "متابعة التعلم", openAcademy: "فتح في Academy" },
  fr: { skillGap: "Écarts de compétences", skillGapHint: "Comparez les attentes du rôle à votre dernière preuve vérifiée et voyez les parcours qui comblent l’écart.", noGaps: "Aucun écart n’est visible pour vos rôles actuels selon les preuves vérifiées.", currentLevel: "Niveau actuel", requiredLevel: "Niveau requis", gap: "Écart", requiredBy: "Requis par", latestEvidence: "Dernière preuve", recommendedPaths: "Parcours recommandés", noRecommendation: "Aucun parcours publié et attribué à votre rôle ne comble actuellement cet écart à lui seul.", policy: "Politique de recommandation", refresh: "Actualiser", loadError: "Les écarts de compétences n’ont pas pu être chargés.", openLearning: "Continuer l’apprentissage", openAcademy: "Ouvrir dans Academy" },
  es: { skillGap: "Brechas de competencias", skillGapHint: "Compara las expectativas del rol con tu evidencia verificada más reciente y consulta rutas que cierran la brecha.", noGaps: "No se observa ninguna brecha para tus roles actuales según la evidencia verificada.", currentLevel: "Nivel actual", requiredLevel: "Nivel requerido", gap: "Brecha", requiredBy: "Requerido por", latestEvidence: "Última evidencia", recommendedPaths: "Rutas recomendadas", noRecommendation: "Actualmente ninguna ruta publicada y asignada a tu rol cierra por sí sola esta brecha.", policy: "Política de recomendación", refresh: "Actualizar", loadError: "No se pudieron cargar las brechas de competencias.", openLearning: "Continuar aprendizaje", openAcademy: "Abrir en Academy" },
  it: { skillGap: "Gap di competenza", skillGapHint: "Confronta le aspettative del ruolo con l’ultima evidenza verificata e visualizza i percorsi che colmano il gap.", noGaps: "Non risultano gap per i ruoli attuali in base alle evidenze verificate.", currentLevel: "Livello attuale", requiredLevel: "Livello richiesto", gap: "Gap", requiredBy: "Richiesto da", latestEvidence: "Ultima evidenza", recommendedPaths: "Percorsi consigliati", noRecommendation: "Nessun percorso pubblicato e assegnato al tuo ruolo colma attualmente questo gap da solo.", policy: "Politica di raccomandazione", refresh: "Aggiorna", loadError: "Impossibile caricare i gap di competenza.", openLearning: "Continua l’apprendimento", openAcademy: "Apri in Academy" },
  nl: { skillGap: "Vaardigheidstekorten", skillGapHint: "Vergelijk rolverwachtingen met uw meest recente geverifieerde bewijs en bekijk leerpaden die het tekort sluiten.", noGaps: "Op basis van geverifieerd bewijs is voor uw huidige rollen geen tekort zichtbaar.", currentLevel: "Huidig niveau", requiredLevel: "Vereist niveau", gap: "Tekort", requiredBy: "Vereist door", latestEvidence: "Laatste bewijs", recommendedPaths: "Aanbevolen leerpaden", noRecommendation: "Geen gepubliceerd en aan uw rol toegewezen leerpad sluit dit tekort momenteel zelfstandig.", policy: "Aanbevelingsbeleid", refresh: "Vernieuwen", loadError: "Vaardigheidstekorten konden niet worden geladen.", openLearning: "Doorgaan met leren", openAcademy: "Openen in Academy" },
  pl: { skillGap: "Luki kompetencyjne", skillGapHint: "Porównaj wymagania roli z najnowszym zweryfikowanym dowodem i zobacz ścieżki, które zamykają lukę.", noGaps: "Na podstawie zweryfikowanych dowodów nie widać luki dla obecnych ról.", currentLevel: "Obecny poziom", requiredLevel: "Wymagany poziom", gap: "Luka", requiredBy: "Wymagane przez", latestEvidence: "Najnowszy dowód", recommendedPaths: "Rekomendowane ścieżki", noRecommendation: "Obecnie żadna opublikowana i przypisana do roli ścieżka nie zamyka tej luki samodzielnie.", policy: "Polityka rekomendacji", refresh: "Odśwież", loadError: "Nie udało się załadować luk kompetencyjnych.", openLearning: "Kontynuuj naukę", openAcademy: "Otwórz w Academy" },
  "pt-BR": { skillGap: "Lacunas de competência", skillGapHint: "Compare as expectativas do papel com sua evidência verificada mais recente e veja trilhas que fecham a lacuna.", noGaps: "Nenhuma lacuna está visível para seus papéis atuais com base em evidências verificadas.", currentLevel: "Nível atual", requiredLevel: "Nível necessário", gap: "Lacuna", requiredBy: "Exigido por", latestEvidence: "Última evidência", recommendedPaths: "Trilhas recomendadas", noRecommendation: "Nenhuma trilha publicada e atribuída ao seu papel fecha esta lacuna sozinha no momento.", policy: "Política de recomendação", refresh: "Atualizar", loadError: "Não foi possível carregar as lacunas de competência.", openLearning: "Continuar aprendendo", openAcademy: "Abrir no Academy" },
});

export function translateAcademySkillGap(locale, key) {
  return ACADEMY_SKILL_GAP_MESSAGES[locale]?.[key] || ACADEMY_SKILL_GAP_MESSAGES.en[key] || key;
}

export function academySkillGapMessageCoverage(locales) {
  const keys = Object.keys(ACADEMY_SKILL_GAP_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, keys.filter((key) => typeof ACADEMY_SKILL_GAP_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(ACADEMY_SKILL_GAP_MESSAGES[locale] || {}).filter((key) => !keys.includes(key)).sort()])),
  };
}
