export const ACADEMY_LOCALIZATION_TELEMETRY_MESSAGES = Object.freeze({
  tr: { telemetry: "Yerelleştirme kapsamı", telemetryHint: "Kapsam, varsayılan dildeki en güncel yayımlanmış içeriklerin yetkili çeviri durumundan hesaplanır. Dil kalitesi için kanıtsız skor üretilmez.", sourceLocale: "Kaynak dil", requiredCoverage: "Zorunlu dil kapsamı", authorityGaps: "Yetki açığı", staleTranslations: "Eski kaynaklı çeviri", pendingReview: "İnceleme bekleyen", targetLocale: "Hedef dil", requiredLocale: "Zorunlu", sourceContent: "Kaynak içerik", authoritative: "Yetkili", missingLineage: "Lineage eksik", coverage: "Kapsam", machineDraft: "Makine taslağı", rejected: "Reddedilen", noTelemetry: "Etkin hedef dil için kapsam verisi yok." },
  en: { telemetry: "Localization coverage", telemetryHint: "Coverage is derived from authoritative translations of the latest published content in the default locale. No unsupported linguistic quality score is generated.", sourceLocale: "Source locale", requiredCoverage: "Required-locale coverage", authorityGaps: "Authority gaps", staleTranslations: "Stale translations", pendingReview: "Pending review", targetLocale: "Target locale", requiredLocale: "Required", sourceContent: "Source content", authoritative: "Authoritative", missingLineage: "Missing lineage", coverage: "Coverage", machineDraft: "Machine draft", rejected: "Rejected", noTelemetry: "No coverage data exists for an enabled target locale." },
  de: { telemetry: "Lokalisierungsabdeckung", telemetryHint: "Die Abdeckung wird aus autorisierten Übersetzungen der neuesten veröffentlichten Inhalte der Standardsprache abgeleitet. Es wird kein unbelegter Sprachqualitätswert erzeugt.", sourceLocale: "Quellsprache", requiredCoverage: "Abdeckung Pflichtsprachen", authorityGaps: "Autorisierungslücken", staleTranslations: "Veraltete Übersetzungen", pendingReview: "Prüfung ausstehend", targetLocale: "Zielsprache", requiredLocale: "Pflicht", sourceContent: "Quellinhalte", authoritative: "Autorisiert", missingLineage: "Fehlende Linie", coverage: "Abdeckung", machineDraft: "Maschinenentwurf", rejected: "Abgelehnt", noTelemetry: "Keine Abdeckungsdaten für eine aktivierte Zielsprache." },
  ar: { telemetry: "تغطية الترجمة", telemetryHint: "تُحسب التغطية من الترجمات المعتمدة لأحدث المحتوى المنشور باللغة الافتراضية. لا يتم إنشاء درجة جودة لغوية بلا دليل.", sourceLocale: "لغة المصدر", requiredCoverage: "تغطية اللغات المطلوبة", authorityGaps: "فجوات الاعتماد", staleTranslations: "ترجمات قديمة", pendingReview: "بانتظار المراجعة", targetLocale: "اللغة الهدف", requiredLocale: "مطلوبة", sourceContent: "محتوى المصدر", authoritative: "معتمدة", missingLineage: "سلسلة مفقودة", coverage: "التغطية", machineDraft: "مسودة آلية", rejected: "مرفوضة", noTelemetry: "لا توجد بيانات تغطية للغات الهدف المفعلة." },
  fr: { telemetry: "Couverture de localisation", telemetryHint: "La couverture provient des traductions faisant autorité du contenu publié le plus récent dans la langue par défaut. Aucun score linguistique non prouvé n’est généré.", sourceLocale: "Langue source", requiredCoverage: "Couverture des langues requises", authorityGaps: "Écarts d’autorité", staleTranslations: "Traductions obsolètes", pendingReview: "En attente de revue", targetLocale: "Langue cible", requiredLocale: "Requise", sourceContent: "Contenu source", authoritative: "Autoritative", missingLineage: "Lignée manquante", coverage: "Couverture", machineDraft: "Brouillon machine", rejected: "Rejetée", noTelemetry: "Aucune donnée de couverture pour une langue cible activée." },
  es: { telemetry: "Cobertura de localización", telemetryHint: "La cobertura se deriva de traducciones autorizadas del contenido publicado más reciente en el idioma predeterminado. No se genera una puntuación lingüística sin evidencia.", sourceLocale: "Idioma de origen", requiredCoverage: "Cobertura de idiomas requeridos", authorityGaps: "Brechas de autoridad", staleTranslations: "Traducciones obsoletas", pendingReview: "Pendiente de revisión", targetLocale: "Idioma destino", requiredLocale: "Requerido", sourceContent: "Contenido fuente", authoritative: "Autorizado", missingLineage: "Linaje faltante", coverage: "Cobertura", machineDraft: "Borrador automático", rejected: "Rechazado", noTelemetry: "No hay datos de cobertura para un idioma destino habilitado." },
  it: { telemetry: "Copertura localizzazione", telemetryHint: "La copertura deriva dalle traduzioni autorevoli dei contenuti pubblicati più recenti nella lingua predefinita. Non viene creato alcun punteggio linguistico privo di evidenza.", sourceLocale: "Lingua sorgente", requiredCoverage: "Copertura lingue obbligatorie", authorityGaps: "Gap di autorità", staleTranslations: "Traduzioni obsolete", pendingReview: "In revisione", targetLocale: "Lingua target", requiredLocale: "Obbligatoria", sourceContent: "Contenuto sorgente", authoritative: "Autorevole", missingLineage: "Lineage mancante", coverage: "Copertura", machineDraft: "Bozza automatica", rejected: "Rifiutata", noTelemetry: "Nessun dato di copertura per una lingua target abilitata." },
  nl: { telemetry: "Lokalisatiedekking", telemetryHint: "Dekking wordt afgeleid uit gezaghebbende vertalingen van de nieuwste gepubliceerde inhoud in de standaardtaal. Er wordt geen onbewezen taalkwaliteitsscore gemaakt.", sourceLocale: "Brontaal", requiredCoverage: "Dekking verplichte talen", authorityGaps: "Autoriteitsgaten", staleTranslations: "Verouderde vertalingen", pendingReview: "Wacht op beoordeling", targetLocale: "Doeltaal", requiredLocale: "Verplicht", sourceContent: "Broninhoud", authoritative: "Gezaghebbend", missingLineage: "Ontbrekende lineage", coverage: "Dekking", machineDraft: "Machineconcept", rejected: "Afgewezen", noTelemetry: "Geen dekkingsgegevens voor een ingeschakelde doeltaal." },
  pl: { telemetry: "Pokrycie lokalizacji", telemetryHint: "Pokrycie jest wyliczane z autorytatywnych tłumaczeń najnowszej opublikowanej treści w języku domyślnym. Nie jest tworzony nieudowodniony wynik jakości językowej.", sourceLocale: "Język źródłowy", requiredCoverage: "Pokrycie wymaganych języków", authorityGaps: "Luki autorytetu", staleTranslations: "Nieaktualne tłumaczenia", pendingReview: "Oczekuje na przegląd", targetLocale: "Język docelowy", requiredLocale: "Wymagany", sourceContent: "Treść źródłowa", authoritative: "Autorytatywne", missingLineage: "Brak lineage", coverage: "Pokrycie", machineDraft: "Szkic maszynowy", rejected: "Odrzucone", noTelemetry: "Brak danych pokrycia dla włączonego języka docelowego." },
  "pt-BR": { telemetry: "Cobertura de localização", telemetryHint: "A cobertura é derivada das traduções autoritativas do conteúdo publicado mais recente no idioma padrão. Nenhuma pontuação linguística sem evidência é gerada.", sourceLocale: "Idioma de origem", requiredCoverage: "Cobertura de idiomas obrigatórios", authorityGaps: "Lacunas de autoridade", staleTranslations: "Traduções desatualizadas", pendingReview: "Aguardando revisão", targetLocale: "Idioma de destino", requiredLocale: "Obrigatório", sourceContent: "Conteúdo de origem", authoritative: "Autoritativo", missingLineage: "Lineage ausente", coverage: "Cobertura", machineDraft: "Rascunho automático", rejected: "Rejeitado", noTelemetry: "Não há dados de cobertura para um idioma de destino habilitado." },
});

export function translateAcademyLocalizationTelemetry(locale, key) {
  return ACADEMY_LOCALIZATION_TELEMETRY_MESSAGES[locale]?.[key] || ACADEMY_LOCALIZATION_TELEMETRY_MESSAGES.en[key] || key;
}

export function academyLocalizationTelemetryMessageCoverage(locales) {
  const keys = Object.keys(ACADEMY_LOCALIZATION_TELEMETRY_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, keys.filter((key) => typeof ACADEMY_LOCALIZATION_TELEMETRY_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(ACADEMY_LOCALIZATION_TELEMETRY_MESSAGES[locale] || {}).filter((key) => !keys.includes(key)).sort()])),
  };
}
