export const ACADEMY_EXPANSION_MESSAGES = Object.freeze({
  tr: {
    scenarioStudio: "Senaryo Stüdyosu", scenarioHint: "Karar, görev ve sonuç düğümlerinden doğrulanabilir bir öğrenme senaryosu oluşturun.", interactionStudio: "Etkileşim zaman çizelgesi", contentVersion: "İçerik sürümü", scenarioKey: "Senaryo anahtarı", versionNumber: "Sürüm", passingScore: "Geçme puanı", entryNode: "Başlangıç düğümü", nodes: "Düğümler", edges: "Bağlantılar", addNode: "Düğüm ekle", addEdge: "Bağlantı ekle", nodeKey: "Düğüm anahtarı", nodeType: "Düğüm türü", prompt: "İstem", terminal: "Son düğüm", terminalOutcome: "Sonuç", fromNode: "Kaynak düğüm", toNode: "Hedef düğüm", choiceKey: "Seçim anahtarı", choiceLabel: "Seçim etiketi", scoreDelta: "Puan etkisi", correctChoice: "Doğru seçim", saveScenario: "Senaryoyu kaydet", scenarioSaved: "Senaryo kaydedildi.", noPublishedVersions: "Önce en az bir yayınlanmış içerik sürümü oluşturun.", studioError: "Senaryo kaydedilemedi.", achievements: "Yetkinlikler ve rozetler", achievementsHint: "Yalnız doğrulanmış Academy kanıtından üretilen kazanımlar gösterilir.", validCredential: "Geçerli", revokedCredential: "Geri çekildi", expiredCredential: "Süresi doldu", observedLevel: "Doğrulanmış seviye", evidence: "Kanıt", issuedAt: "Veriliş", expiresAt: "Bitiş", noCredentials: "Henüz doğrulanmış rozet bulunmuyor.", portablePending: "İmzalı taşınabilir rozet henüz etkin değil", localizationGovernance: "Yerelleştirme yönetişimi", localizationHint: "Tenant dilleri, çeviri soy zinciri ve maker-checker onayını yönetin.", localePolicy: "Dil politikası", translations: "Çeviriler", locale: "Dil", enabled: "Etkin", required: "Zorunlu", machineDraft: "Makine taslağına izin ver", savePolicy: "Politikayı kaydet", policySaved: "Dil politikası kaydedildi.", authoritative: "Otoritatif", stale: "Güncel değil", sourceVersion: "Kaynak sürüm", targetVersion: "Hedef sürüm", translationMethod: "Çeviri yöntemi", submitReview: "İncelemeye gönder", approve: "Onayla", reject: "Reddet", noTranslations: "Henüz çeviri soy zinciri yok.", governanceError: "Yerelleştirme işlemi tamamlanamadı.", refresh: "Yenile", backToAcademy: "Academy'ye dön"
  },
  en: {
    scenarioStudio: "Scenario Studio", scenarioHint: "Build an auditable learning scenario from decision, task and outcome nodes.", interactionStudio: "Interaction timeline", contentVersion: "Content version", scenarioKey: "Scenario key", versionNumber: "Version", passingScore: "Passing score", entryNode: "Entry node", nodes: "Nodes", edges: "Edges", addNode: "Add node", addEdge: "Add edge", nodeKey: "Node key", nodeType: "Node type", prompt: "Prompt", terminal: "Terminal node", terminalOutcome: "Terminal outcome", fromNode: "From node", toNode: "To node", choiceKey: "Choice key", choiceLabel: "Choice label", scoreDelta: "Score delta", correctChoice: "Correct choice", saveScenario: "Save scenario", scenarioSaved: "Scenario saved.", noPublishedVersions: "Publish at least one content version first.", studioError: "Scenario could not be saved.", achievements: "Skills and badges", achievementsHint: "Only achievements derived from verified Academy evidence are shown.", validCredential: "Valid", revokedCredential: "Revoked", expiredCredential: "Expired", observedLevel: "Verified level", evidence: "Evidence", issuedAt: "Issued", expiresAt: "Expires", noCredentials: "No verified badges yet.", portablePending: "Signed portable badge is not enabled yet", localizationGovernance: "Localization governance", localizationHint: "Manage tenant locales, translation lineage and maker-checker approval.", localePolicy: "Locale policy", translations: "Translations", locale: "Locale", enabled: "Enabled", required: "Required", machineDraft: "Allow machine draft", savePolicy: "Save policy", policySaved: "Locale policy saved.", authoritative: "Authoritative", stale: "Stale", sourceVersion: "Source version", targetVersion: "Target version", translationMethod: "Translation method", submitReview: "Submit for review", approve: "Approve", reject: "Reject", noTranslations: "No translation lineage yet.", governanceError: "Localization action could not be completed.", refresh: "Refresh", backToAcademy: "Back to Academy"
  },
  de: {
    scenarioStudio: "Szenario-Studio", scenarioHint: "Erstellen Sie ein prüfbares Lernszenario aus Entscheidungs-, Aufgaben- und Ergebnis-Knoten.", interactionStudio: "Interaktions-Zeitleiste", contentVersion: "Inhaltsversion", scenarioKey: "Szenario-Schlüssel", versionNumber: "Version", passingScore: "Bestehensgrenze", entryNode: "Startknoten", nodes: "Knoten", edges: "Verbindungen", addNode: "Knoten hinzufügen", addEdge: "Verbindung hinzufügen", nodeKey: "Knotenschlüssel", nodeType: "Knotentyp", prompt: "Anweisung", terminal: "Endknoten", terminalOutcome: "Endergebnis", fromNode: "Von Knoten", toNode: "Zu Knoten", choiceKey: "Auswahlschlüssel", choiceLabel: "Auswahlbezeichnung", scoreDelta: "Punktänderung", correctChoice: "Richtige Auswahl", saveScenario: "Szenario speichern", scenarioSaved: "Szenario gespeichert.", noPublishedVersions: "Veröffentlichen Sie zuerst mindestens eine Inhaltsversion.", studioError: "Szenario konnte nicht gespeichert werden.", achievements: "Kompetenzen und Badges", achievementsHint: "Es werden nur aus verifizierten Academy-Nachweisen abgeleitete Erfolge angezeigt.", validCredential: "Gültig", revokedCredential: "Widerrufen", expiredCredential: "Abgelaufen", observedLevel: "Verifiziertes Niveau", evidence: "Nachweis", issuedAt: "Ausgestellt", expiresAt: "Gültig bis", noCredentials: "Noch keine verifizierten Badges.", portablePending: "Signiertes portables Badge ist noch nicht aktiviert", localizationGovernance: "Lokalisierungs-Governance", localizationHint: "Tenant-Sprachen, Übersetzungsherkunft und Vier-Augen-Freigabe verwalten.", localePolicy: "Sprachrichtlinie", translations: "Übersetzungen", locale: "Sprache", enabled: "Aktiv", required: "Erforderlich", machineDraft: "Maschinenentwurf erlauben", savePolicy: "Richtlinie speichern", policySaved: "Sprachrichtlinie gespeichert.", authoritative: "Verbindlich", stale: "Veraltet", sourceVersion: "Quellversion", targetVersion: "Zielversion", translationMethod: "Übersetzungsmethode", submitReview: "Zur Prüfung senden", approve: "Freigeben", reject: "Ablehnen", noTranslations: "Noch keine Übersetzungsherkunft.", governanceError: "Lokalisierungsaktion konnte nicht abgeschlossen werden.", refresh: "Aktualisieren", backToAcademy: "Zurück zu Academy"
  },
  ar: {
    scenarioStudio: "استوديو السيناريو", scenarioHint: "أنشئ سيناريو تعلم قابلًا للتدقيق من عقد القرار والمهمة والنتيجة.", interactionStudio: "الخط الزمني للتفاعل", contentVersion: "إصدار المحتوى", scenarioKey: "مفتاح السيناريو", versionNumber: "الإصدار", passingScore: "درجة النجاح", entryNode: "عقدة البداية", nodes: "العقد", edges: "الروابط", addNode: "إضافة عقدة", addEdge: "إضافة رابط", nodeKey: "مفتاح العقدة", nodeType: "نوع العقدة", prompt: "النص", terminal: "عقدة نهائية", terminalOutcome: "النتيجة النهائية", fromNode: "من عقدة", toNode: "إلى عقدة", choiceKey: "مفتاح الاختيار", choiceLabel: "تسمية الاختيار", scoreDelta: "تأثير الدرجة", correctChoice: "اختيار صحيح", saveScenario: "حفظ السيناريو", scenarioSaved: "تم حفظ السيناريو.", noPublishedVersions: "انشر إصدار محتوى واحدًا على الأقل أولًا.", studioError: "تعذر حفظ السيناريو.", achievements: "المهارات والشارات", achievementsHint: "تظهر فقط الإنجازات المشتقة من أدلة Academy الموثقة.", validCredential: "صالحة", revokedCredential: "مسحوبة", expiredCredential: "منتهية", observedLevel: "المستوى الموثق", evidence: "الدليل", issuedAt: "تاريخ الإصدار", expiresAt: "تاريخ الانتهاء", noCredentials: "لا توجد شارات موثقة بعد.", portablePending: "الشارة المحمولة الموقعة غير مفعلة بعد", localizationGovernance: "حوكمة الترجمة", localizationHint: "إدارة لغات المستأجر وسلسلة الترجمة واعتماد المراجع المنفصل.", localePolicy: "سياسة اللغة", translations: "الترجمات", locale: "اللغة", enabled: "مفعلة", required: "مطلوبة", machineDraft: "السماح بمسودة آلية", savePolicy: "حفظ السياسة", policySaved: "تم حفظ سياسة اللغة.", authoritative: "معتمدة", stale: "قديمة", sourceVersion: "إصدار المصدر", targetVersion: "الإصدار الهدف", translationMethod: "طريقة الترجمة", submitReview: "إرسال للمراجعة", approve: "اعتماد", reject: "رفض", noTranslations: "لا توجد سلسلة ترجمة بعد.", governanceError: "تعذر إكمال إجراء الترجمة.", refresh: "تحديث", backToAcademy: "العودة إلى Academy"
  },
  fr: {
    scenarioStudio: "Studio de scénarios", scenarioHint: "Créez un scénario d’apprentissage auditable avec des nœuds de décision, tâche et résultat.", interactionStudio: "Chronologie interactive", contentVersion: "Version du contenu", scenarioKey: "Clé du scénario", versionNumber: "Version", passingScore: "Score de réussite", entryNode: "Nœud d’entrée", nodes: "Nœuds", edges: "Liens", addNode: "Ajouter un nœud", addEdge: "Ajouter un lien", nodeKey: "Clé du nœud", nodeType: "Type de nœud", prompt: "Consigne", terminal: "Nœud terminal", terminalOutcome: "Résultat terminal", fromNode: "Depuis", toNode: "Vers", choiceKey: "Clé du choix", choiceLabel: "Libellé du choix", scoreDelta: "Impact score", correctChoice: "Bon choix", saveScenario: "Enregistrer le scénario", scenarioSaved: "Scénario enregistré.", noPublishedVersions: "Publiez d’abord au moins une version de contenu.", studioError: "Le scénario n’a pas pu être enregistré.", achievements: "Compétences et badges", achievementsHint: "Seuls les acquis issus de preuves Academy vérifiées sont affichés.", validCredential: "Valide", revokedCredential: "Révoqué", expiredCredential: "Expiré", observedLevel: "Niveau vérifié", evidence: "Preuve", issuedAt: "Émis", expiresAt: "Expire", noCredentials: "Aucun badge vérifié pour le moment.", portablePending: "Le badge portable signé n’est pas encore activé", localizationGovernance: "Gouvernance de localisation", localizationHint: "Gérez les langues du tenant, la lignée des traductions et la validation à quatre yeux.", localePolicy: "Politique de langue", translations: "Traductions", locale: "Langue", enabled: "Activée", required: "Obligatoire", machineDraft: "Autoriser le brouillon machine", savePolicy: "Enregistrer la politique", policySaved: "Politique de langue enregistrée.", authoritative: "Faisant autorité", stale: "Obsolète", sourceVersion: "Version source", targetVersion: "Version cible", translationMethod: "Méthode de traduction", submitReview: "Soumettre à validation", approve: "Approuver", reject: "Rejeter", noTranslations: "Aucune lignée de traduction.", governanceError: "L’action de localisation a échoué.", refresh: "Actualiser", backToAcademy: "Retour à Academy"
  },
  es: {
    scenarioStudio: "Estudio de escenarios", scenarioHint: "Crea un escenario de aprendizaje auditable con nodos de decisión, tarea y resultado.", interactionStudio: "Línea de tiempo interactiva", contentVersion: "Versión de contenido", scenarioKey: "Clave del escenario", versionNumber: "Versión", passingScore: "Puntuación mínima", entryNode: "Nodo inicial", nodes: "Nodos", edges: "Enlaces", addNode: "Añadir nodo", addEdge: "Añadir enlace", nodeKey: "Clave del nodo", nodeType: "Tipo de nodo", prompt: "Indicador", terminal: "Nodo terminal", terminalOutcome: "Resultado terminal", fromNode: "Desde", toNode: "Hasta", choiceKey: "Clave de opción", choiceLabel: "Etiqueta de opción", scoreDelta: "Impacto de puntuación", correctChoice: "Opción correcta", saveScenario: "Guardar escenario", scenarioSaved: "Escenario guardado.", noPublishedVersions: "Publica primero al menos una versión de contenido.", studioError: "No se pudo guardar el escenario.", achievements: "Competencias e insignias", achievementsHint: "Solo se muestran logros derivados de evidencia Academy verificada.", validCredential: "Válida", revokedCredential: "Revocada", expiredCredential: "Caducada", observedLevel: "Nivel verificado", evidence: "Evidencia", issuedAt: "Emitida", expiresAt: "Caduca", noCredentials: "Aún no hay insignias verificadas.", portablePending: "La insignia portátil firmada aún no está habilitada", localizationGovernance: "Gobernanza de localización", localizationHint: "Gestiona idiomas del tenant, linaje de traducción y aprobación de doble control.", localePolicy: "Política de idioma", translations: "Traducciones", locale: "Idioma", enabled: "Activo", required: "Obligatorio", machineDraft: "Permitir borrador automático", savePolicy: "Guardar política", policySaved: "Política guardada.", authoritative: "Autoritativa", stale: "Desactualizada", sourceVersion: "Versión fuente", targetVersion: "Versión destino", translationMethod: "Método de traducción", submitReview: "Enviar a revisión", approve: "Aprobar", reject: "Rechazar", noTranslations: "Aún no hay linaje de traducción.", governanceError: "No se pudo completar la acción de localización.", refresh: "Actualizar", backToAcademy: "Volver a Academy"
  },
  it: {
    scenarioStudio: "Studio scenari", scenarioHint: "Crea uno scenario formativo verificabile con nodi decisionali, attività e risultato.", interactionStudio: "Timeline interattiva", contentVersion: "Versione contenuto", scenarioKey: "Chiave scenario", versionNumber: "Versione", passingScore: "Punteggio minimo", entryNode: "Nodo iniziale", nodes: "Nodi", edges: "Collegamenti", addNode: "Aggiungi nodo", addEdge: "Aggiungi collegamento", nodeKey: "Chiave nodo", nodeType: "Tipo nodo", prompt: "Prompt", terminal: "Nodo terminale", terminalOutcome: "Esito terminale", fromNode: "Da", toNode: "A", choiceKey: "Chiave scelta", choiceLabel: "Etichetta scelta", scoreDelta: "Impatto punteggio", correctChoice: "Scelta corretta", saveScenario: "Salva scenario", scenarioSaved: "Scenario salvato.", noPublishedVersions: "Pubblica prima almeno una versione del contenuto.", studioError: "Impossibile salvare lo scenario.", achievements: "Competenze e badge", achievementsHint: "Sono mostrati solo risultati derivati da evidenze Academy verificate.", validCredential: "Valido", revokedCredential: "Revocato", expiredCredential: "Scaduto", observedLevel: "Livello verificato", evidence: "Evidenza", issuedAt: "Emesso", expiresAt: "Scade", noCredentials: "Nessun badge verificato.", portablePending: "Il badge portabile firmato non è ancora attivo", localizationGovernance: "Governance localizzazione", localizationHint: "Gestisci lingue tenant, lineage delle traduzioni e approvazione a quattro occhi.", localePolicy: "Politica lingua", translations: "Traduzioni", locale: "Lingua", enabled: "Attiva", required: "Obbligatoria", machineDraft: "Consenti bozza automatica", savePolicy: "Salva politica", policySaved: "Politica lingua salvata.", authoritative: "Autorevole", stale: "Non aggiornata", sourceVersion: "Versione sorgente", targetVersion: "Versione destinazione", translationMethod: "Metodo traduzione", submitReview: "Invia a revisione", approve: "Approva", reject: "Rifiuta", noTranslations: "Nessun lineage di traduzione.", governanceError: "Azione di localizzazione non completata.", refresh: "Aggiorna", backToAcademy: "Torna ad Academy"
  },
  nl: {
    scenarioStudio: "Scenariostudio", scenarioHint: "Bouw een controleerbaar leerscenario met beslis-, taak- en resultaatknooppunten.", interactionStudio: "Interactietijdlijn", contentVersion: "Inhoudsversie", scenarioKey: "Scenariosleutel", versionNumber: "Versie", passingScore: "Slagingsscore", entryNode: "Startknooppunt", nodes: "Knooppunten", edges: "Verbindingen", addNode: "Knooppunt toevoegen", addEdge: "Verbinding toevoegen", nodeKey: "Knooppuntsleutel", nodeType: "Knooppunttype", prompt: "Prompt", terminal: "Eindknooppunt", terminalOutcome: "Eindresultaat", fromNode: "Van", toNode: "Naar", choiceKey: "Keuzesleutel", choiceLabel: "Keuzelabel", scoreDelta: "Score-effect", correctChoice: "Juiste keuze", saveScenario: "Scenario opslaan", scenarioSaved: "Scenario opgeslagen.", noPublishedVersions: "Publiceer eerst minimaal één inhoudsversie.", studioError: "Scenario kon niet worden opgeslagen.", achievements: "Vaardigheden en badges", achievementsHint: "Alleen resultaten uit geverifieerd Academy-bewijs worden getoond.", validCredential: "Geldig", revokedCredential: "Ingetrokken", expiredCredential: "Verlopen", observedLevel: "Geverifieerd niveau", evidence: "Bewijs", issuedAt: "Uitgegeven", expiresAt: "Verloopt", noCredentials: "Nog geen geverifieerde badges.", portablePending: "Ondertekende draagbare badge is nog niet actief", localizationGovernance: "Lokalisatiegovernance", localizationHint: "Beheer tenant-talen, vertalingslijn en vier-ogen-goedkeuring.", localePolicy: "Taalbeleid", translations: "Vertalingen", locale: "Taal", enabled: "Actief", required: "Verplicht", machineDraft: "Machineconcept toestaan", savePolicy: "Beleid opslaan", policySaved: "Taalbeleid opgeslagen.", authoritative: "Autoritatief", stale: "Verouderd", sourceVersion: "Bronversie", targetVersion: "Doelversie", translationMethod: "Vertaalmethode", submitReview: "Ter beoordeling indienen", approve: "Goedkeuren", reject: "Afwijzen", noTranslations: "Nog geen vertalingslijn.", governanceError: "Lokalisatieactie kon niet worden voltooid.", refresh: "Vernieuwen", backToAcademy: "Terug naar Academy"
  },
  pl: {
    scenarioStudio: "Studio scenariuszy", scenarioHint: "Zbuduj audytowalny scenariusz szkoleniowy z węzłów decyzji, zadania i wyniku.", interactionStudio: "Oś interakcji", contentVersion: "Wersja treści", scenarioKey: "Klucz scenariusza", versionNumber: "Wersja", passingScore: "Próg zaliczenia", entryNode: "Węzeł startowy", nodes: "Węzły", edges: "Połączenia", addNode: "Dodaj węzeł", addEdge: "Dodaj połączenie", nodeKey: "Klucz węzła", nodeType: "Typ węzła", prompt: "Polecenie", terminal: "Węzeł końcowy", terminalOutcome: "Wynik końcowy", fromNode: "Z węzła", toNode: "Do węzła", choiceKey: "Klucz wyboru", choiceLabel: "Etykieta wyboru", scoreDelta: "Wpływ na wynik", correctChoice: "Poprawny wybór", saveScenario: "Zapisz scenariusz", scenarioSaved: "Scenariusz zapisany.", noPublishedVersions: "Najpierw opublikuj co najmniej jedną wersję treści.", studioError: "Nie udało się zapisać scenariusza.", achievements: "Umiejętności i odznaki", achievementsHint: "Pokazywane są tylko osiągnięcia oparte na zweryfikowanych dowodach Academy.", validCredential: "Ważna", revokedCredential: "Cofnięta", expiredCredential: "Wygasła", observedLevel: "Zweryfikowany poziom", evidence: "Dowód", issuedAt: "Wydano", expiresAt: "Wygasa", noCredentials: "Brak zweryfikowanych odznak.", portablePending: "Podpisana przenośna odznaka nie jest jeszcze aktywna", localizationGovernance: "Nadzór nad lokalizacją", localizationHint: "Zarządzaj językami tenant-a, linią tłumaczeń i zasadą dwóch par oczu.", localePolicy: "Polityka języka", translations: "Tłumaczenia", locale: "Język", enabled: "Aktywny", required: "Wymagany", machineDraft: "Zezwól na szkic maszynowy", savePolicy: "Zapisz politykę", policySaved: "Polityka języka zapisana.", authoritative: "Autorytatywna", stale: "Nieaktualna", sourceVersion: "Wersja źródłowa", targetVersion: "Wersja docelowa", translationMethod: "Metoda tłumaczenia", submitReview: "Wyślij do przeglądu", approve: "Zatwierdź", reject: "Odrzuć", noTranslations: "Brak linii tłumaczeń.", governanceError: "Nie udało się wykonać operacji lokalizacji.", refresh: "Odśwież", backToAcademy: "Wróć do Academy"
  },
  "pt-BR": {
    scenarioStudio: "Estúdio de cenários", scenarioHint: "Crie um cenário de aprendizagem auditável com nós de decisão, tarefa e resultado.", interactionStudio: "Linha do tempo interativa", contentVersion: "Versão do conteúdo", scenarioKey: "Chave do cenário", versionNumber: "Versão", passingScore: "Pontuação mínima", entryNode: "Nó inicial", nodes: "Nós", edges: "Conexões", addNode: "Adicionar nó", addEdge: "Adicionar conexão", nodeKey: "Chave do nó", nodeType: "Tipo do nó", prompt: "Prompt", terminal: "Nó terminal", terminalOutcome: "Resultado terminal", fromNode: "Do nó", toNode: "Para o nó", choiceKey: "Chave da escolha", choiceLabel: "Rótulo da escolha", scoreDelta: "Impacto na pontuação", correctChoice: "Escolha correta", saveScenario: "Salvar cenário", scenarioSaved: "Cenário salvo.", noPublishedVersions: "Publique primeiro pelo menos uma versão de conteúdo.", studioError: "Não foi possível salvar o cenário.", achievements: "Competências e badges", achievementsHint: "Somente conquistas derivadas de evidências Academy verificadas são exibidas.", validCredential: "Válido", revokedCredential: "Revogado", expiredCredential: "Expirado", observedLevel: "Nível verificado", evidence: "Evidência", issuedAt: "Emitido", expiresAt: "Expira", noCredentials: "Ainda não há badges verificados.", portablePending: "O badge portátil assinado ainda não está ativo", localizationGovernance: "Governança de localização", localizationHint: "Gerencie idiomas do tenant, linhagem de tradução e aprovação em quatro olhos.", localePolicy: "Política de idioma", translations: "Traduções", locale: "Idioma", enabled: "Ativo", required: "Obrigatório", machineDraft: "Permitir rascunho por máquina", savePolicy: "Salvar política", policySaved: "Política de idioma salva.", authoritative: "Autoritativo", stale: "Desatualizado", sourceVersion: "Versão de origem", targetVersion: "Versão de destino", translationMethod: "Método de tradução", submitReview: "Enviar para revisão", approve: "Aprovar", reject: "Rejeitar", noTranslations: "Ainda não há linhagem de tradução.", governanceError: "Não foi possível concluir a ação de localização.", refresh: "Atualizar", backToAcademy: "Voltar para Academy"
  }
});

export function translateAcademyExpansion(locale, key) {
  return ACADEMY_EXPANSION_MESSAGES[locale]?.[key] || ACADEMY_EXPANSION_MESSAGES.en[key] || key;
}

export function academyExpansionMessageCoverage(locales) {
  const keys = Object.keys(ACADEMY_EXPANSION_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, keys.filter((key) => typeof ACADEMY_EXPANSION_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(ACADEMY_EXPANSION_MESSAGES[locale] || {}).filter((key) => !keys.includes(key)).sort()])),
  };
}
