export const ACADEMY_GRAPH_MESSAGES = Object.freeze({
  tr: { graphCanvas: "Senaryo grafiği", graphHint: "Düğümleri sürükleyin veya odaklandıktan sonra ok tuşlarıyla taşıyın. Bağlantılar sunucuya gönderilen gerçek senaryo kenarlarını gösterir.", selectedNode: "Seçili düğüm", entryNode: "Başlangıç düğümü", removeNode: "Düğümü kaldır", removeEdge: "Bağlantıyı kaldır", moveNodeUp: "Düğümü yukarı taşı", moveNodeDown: "Düğümü aşağı taşı", cannotRemoveTerminal: "Senaryoda en az bir son düğüm kalmalıdır.", keyboardMove: "Ok tuşlarıyla taşı", zoomIn: "Yakınlaştır", zoomOut: "Uzaklaştır", fitView: "Görünüme sığdır", resetView: "Görünümü sıfırla", zoomLevel: "Yakınlaştırma", preflight: "Grafik ön kontrolü", preflightReady: "Taslak grafik temel yapısal kontrolleri geçti.", missingNodeKey: "Bir veya daha fazla düğüm anahtarı boş.", duplicateNodeKey: "Aynı düğüm anahtarı birden fazla kez kullanılıyor.", missingTerminal: "Senaryoda en az bir son düğüm olmalı.", brokenEdgeReference: "Bir bağlantı mevcut olmayan bir düğüme referans veriyor.", duplicateChoice: "Aynı kaynak düğümde choice anahtarı tekrarlanıyor.", blankEdgeLabel: "Bir bağlantının görünen etiketi boş." },
  en: { graphCanvas: "Scenario graph", graphHint: "Drag nodes or move a focused node with the arrow keys. Connections represent the actual scenario edges submitted to the server.", selectedNode: "Selected node", entryNode: "Entry node", removeNode: "Remove node", removeEdge: "Remove edge", moveNodeUp: "Move node up", moveNodeDown: "Move node down", cannotRemoveTerminal: "At least one terminal node must remain in the scenario.", keyboardMove: "Move with arrow keys", zoomIn: "Zoom in", zoomOut: "Zoom out", fitView: "Fit view", resetView: "Reset view", zoomLevel: "Zoom", preflight: "Graph preflight", preflightReady: "The draft graph passes the basic structural checks.", missingNodeKey: "One or more node keys are blank.", duplicateNodeKey: "A node key is used more than once.", missingTerminal: "The scenario requires at least one terminal node.", brokenEdgeReference: "An edge references a node that does not exist.", duplicateChoice: "A choice key is duplicated for the same source node.", blankEdgeLabel: "An edge has an empty display label." },
  de: { graphCanvas: "Szenariograf", graphHint: "Ziehen Sie Knoten oder verschieben Sie einen fokussierten Knoten mit den Pfeiltasten. Verbindungen zeigen die tatsächlich an den Server gesendeten Szenariokanten.", selectedNode: "Ausgewählter Knoten", entryNode: "Einstiegsknoten", removeNode: "Knoten entfernen", removeEdge: "Verbindung entfernen", moveNodeUp: "Knoten nach oben verschieben", moveNodeDown: "Knoten nach unten verschieben", cannotRemoveTerminal: "Im Szenario muss mindestens ein Endknoten verbleiben.", keyboardMove: "Mit Pfeiltasten verschieben", zoomIn: "Vergrößern", zoomOut: "Verkleinern", fitView: "Ansicht einpassen", resetView: "Ansicht zurücksetzen", zoomLevel: "Zoom", preflight: "Grafik-Vorprüfung", preflightReady: "Der Entwurfsgraph besteht die grundlegenden Strukturprüfungen.", missingNodeKey: "Mindestens ein Knotenschlüssel ist leer.", duplicateNodeKey: "Ein Knotenschlüssel wird mehrfach verwendet.", missingTerminal: "Das Szenario benötigt mindestens einen Endknoten.", brokenEdgeReference: "Eine Verbindung verweist auf einen nicht vorhandenen Knoten.", duplicateChoice: "Ein Auswahl-Schlüssel ist für denselben Quellknoten doppelt.", blankEdgeLabel: "Eine Verbindung hat eine leere sichtbare Beschriftung." },
  ar: { graphCanvas: "مخطط السيناريو", graphHint: "اسحب العقد أو حرّك العقدة المركزة بمفاتيح الأسهم. تمثل الروابط حواف السيناريو الفعلية المرسلة إلى الخادم.", selectedNode: "العقدة المحددة", entryNode: "عقدة البداية", removeNode: "إزالة العقدة", removeEdge: "إزالة الرابط", moveNodeUp: "نقل العقدة إلى أعلى", moveNodeDown: "نقل العقدة إلى أسفل", cannotRemoveTerminal: "يجب أن تبقى عقدة نهائية واحدة على الأقل في السيناريو.", keyboardMove: "التحريك بمفاتيح الأسهم", zoomIn: "تكبير", zoomOut: "تصغير", fitView: "ملاءمة العرض", resetView: "إعادة ضبط العرض", zoomLevel: "التكبير", preflight: "فحص المخطط", preflightReady: "يجتاز مخطط المسودة الفحوصات الهيكلية الأساسية.", missingNodeKey: "مفتاح عقدة واحد أو أكثر فارغ.", duplicateNodeKey: "تم استخدام مفتاح عقدة أكثر من مرة.", missingTerminal: "يحتاج السيناريو إلى عقدة نهائية واحدة على الأقل.", brokenEdgeReference: "يوجد رابط يشير إلى عقدة غير موجودة.", duplicateChoice: "تم تكرار مفتاح اختيار للعقدة المصدر نفسها.", blankEdgeLabel: "يوجد رابط دون تسمية ظاهرة." },
  fr: { graphCanvas: "Graphe du scénario", graphHint: "Faites glisser les nœuds ou déplacez un nœud focalisé avec les flèches. Les connexions représentent les arêtes réellement envoyées au serveur.", selectedNode: "Nœud sélectionné", entryNode: "Nœud d’entrée", removeNode: "Supprimer le nœud", removeEdge: "Supprimer le lien", moveNodeUp: "Monter le nœud", moveNodeDown: "Descendre le nœud", cannotRemoveTerminal: "Le scénario doit conserver au moins un nœud terminal.", keyboardMove: "Déplacer avec les flèches", zoomIn: "Zoom avant", zoomOut: "Zoom arrière", fitView: "Ajuster la vue", resetView: "Réinitialiser la vue", zoomLevel: "Zoom", preflight: "Précontrôle du graphe", preflightReady: "Le graphe brouillon passe les contrôles structurels de base.", missingNodeKey: "Une ou plusieurs clés de nœud sont vides.", duplicateNodeKey: "Une clé de nœud est utilisée plusieurs fois.", missingTerminal: "Le scénario nécessite au moins un nœud terminal.", brokenEdgeReference: "Un lien référence un nœud inexistant.", duplicateChoice: "Une clé de choix est dupliquée pour le même nœud source.", blankEdgeLabel: "Un lien possède un libellé visible vide." },
  es: { graphCanvas: "Grafo del escenario", graphHint: "Arrastra los nodos o mueve el nodo enfocado con las flechas. Las conexiones representan las aristas reales enviadas al servidor.", selectedNode: "Nodo seleccionado", entryNode: "Nodo de entrada", removeNode: "Eliminar nodo", removeEdge: "Eliminar enlace", moveNodeUp: "Subir nodo", moveNodeDown: "Bajar nodo", cannotRemoveTerminal: "Debe quedar al menos un nodo terminal en el escenario.", keyboardMove: "Mover con las flechas", zoomIn: "Acercar", zoomOut: "Alejar", fitView: "Ajustar vista", resetView: "Restablecer vista", zoomLevel: "Zoom", preflight: "Prevalidación del grafo", preflightReady: "El grafo en borrador supera las comprobaciones estructurales básicas.", missingNodeKey: "Una o más claves de nodo están vacías.", duplicateNodeKey: "Una clave de nodo se usa más de una vez.", missingTerminal: "El escenario requiere al menos un nodo terminal.", brokenEdgeReference: "Un enlace referencia un nodo inexistente.", duplicateChoice: "Una clave de elección está duplicada para el mismo nodo origen.", blankEdgeLabel: "Un enlace tiene la etiqueta visible vacía." },
  it: { graphCanvas: "Grafo dello scenario", graphHint: "Trascina i nodi o sposta il nodo focalizzato con i tasti freccia. Le connessioni rappresentano gli archi reali inviati al server.", selectedNode: "Nodo selezionato", entryNode: "Nodo iniziale", removeNode: "Rimuovi nodo", removeEdge: "Rimuovi collegamento", moveNodeUp: "Sposta nodo su", moveNodeDown: "Sposta nodo giù", cannotRemoveTerminal: "Nello scenario deve rimanere almeno un nodo terminale.", keyboardMove: "Sposta con i tasti freccia", zoomIn: "Ingrandisci", zoomOut: "Riduci", fitView: "Adatta vista", resetView: "Reimposta vista", zoomLevel: "Zoom", preflight: "Precontrollo del grafo", preflightReady: "Il grafo in bozza supera i controlli strutturali di base.", missingNodeKey: "Una o più chiavi nodo sono vuote.", duplicateNodeKey: "Una chiave nodo è usata più di una volta.", missingTerminal: "Lo scenario richiede almeno un nodo terminale.", brokenEdgeReference: "Un collegamento fa riferimento a un nodo inesistente.", duplicateChoice: "Una chiave scelta è duplicata per lo stesso nodo sorgente.", blankEdgeLabel: "Un collegamento ha un'etichetta visibile vuota." },
  nl: { graphCanvas: "Scenariograaf", graphHint: "Sleep knooppunten of verplaats een gefocust knooppunt met de pijltjestoetsen. Verbindingen zijn de werkelijke scenario-randen die naar de server gaan.", selectedNode: "Geselecteerd knooppunt", entryNode: "Startknooppunt", removeNode: "Knooppunt verwijderen", removeEdge: "Verbinding verwijderen", moveNodeUp: "Knooppunt omhoog", moveNodeDown: "Knooppunt omlaag", cannotRemoveTerminal: "Er moet minstens één eindknooppunt in het scenario blijven.", keyboardMove: "Verplaatsen met pijltjestoetsen", zoomIn: "Inzoomen", zoomOut: "Uitzoomen", fitView: "Passend maken", resetView: "Weergave herstellen", zoomLevel: "Zoom", preflight: "Grafiekvoorcontrole", preflightReady: "De conceptgrafiek doorstaat de basiscontroles op structuur.", missingNodeKey: "Een of meer knooppuntsleutels zijn leeg.", duplicateNodeKey: "Een knooppuntsleutel wordt meer dan één keer gebruikt.", missingTerminal: "Het scenario vereist minimaal één eindknooppunt.", brokenEdgeReference: "Een verbinding verwijst naar een niet-bestaand knooppunt.", duplicateChoice: "Een keuzesleutel is dubbel voor hetzelfde bronknooppunt.", blankEdgeLabel: "Een verbinding heeft een leeg zichtbaar label." },
  pl: { graphCanvas: "Graf scenariusza", graphHint: "Przeciągaj węzły lub przesuwaj aktywny węzeł klawiszami strzałek. Połączenia odzwierciedlają rzeczywiste krawędzie scenariusza wysyłane do serwera.", selectedNode: "Wybrany węzeł", entryNode: "Węzeł wejściowy", removeNode: "Usuń węzeł", removeEdge: "Usuń połączenie", moveNodeUp: "Przesuń węzeł w górę", moveNodeDown: "Przesuń węzeł w dół", cannotRemoveTerminal: "W scenariuszu musi pozostać co najmniej jeden węzeł końcowy.", keyboardMove: "Przesuwaj strzałkami", zoomIn: "Powiększ", zoomOut: "Pomniejsz", fitView: "Dopasuj widok", resetView: "Resetuj widok", zoomLevel: "Powiększenie", preflight: "Wstępna kontrola grafu", preflightReady: "Szkic grafu przechodzi podstawowe kontrole strukturalne.", missingNodeKey: "Co najmniej jeden klucz węzła jest pusty.", duplicateNodeKey: "Klucz węzła jest użyty więcej niż raz.", missingTerminal: "Scenariusz wymaga co najmniej jednego węzła końcowego.", brokenEdgeReference: "Połączenie wskazuje na nieistniejący węzeł.", duplicateChoice: "Klucz wyboru jest zduplikowany dla tego samego węzła źródłowego.", blankEdgeLabel: "Połączenie ma pustą widoczną etykietę." },
  "pt-BR": { graphCanvas: "Grafo do cenário", graphHint: "Arraste os nós ou mova o nó em foco com as setas. As conexões representam as arestas reais do cenário enviadas ao servidor.", selectedNode: "Nó selecionado", entryNode: "Nó de entrada", removeNode: "Remover nó", removeEdge: "Remover conexão", moveNodeUp: "Mover nó para cima", moveNodeDown: "Mover nó para baixo", cannotRemoveTerminal: "Pelo menos um nó terminal deve permanecer no cenário.", keyboardMove: "Mover com as setas", zoomIn: "Ampliar", zoomOut: "Reduzir", fitView: "Ajustar à visualização", resetView: "Redefinir visualização", zoomLevel: "Zoom", preflight: "Pré-validação do grafo", preflightReady: "O grafo em rascunho passa pelas verificações estruturais básicas.", missingNodeKey: "Uma ou mais chaves de nó estão vazias.", duplicateNodeKey: "Uma chave de nó é usada mais de uma vez.", missingTerminal: "O cenário exige pelo menos um nó terminal.", brokenEdgeReference: "Uma conexão referencia um nó inexistente.", duplicateChoice: "Uma chave de escolha está duplicada para o mesmo nó de origem.", blankEdgeLabel: "Uma conexão possui rótulo visível vazio." },
});

export function translateAcademyGraph(locale, key) {
  return ACADEMY_GRAPH_MESSAGES[locale]?.[key] || ACADEMY_GRAPH_MESSAGES.en[key] || key;
}

export function academyGraphMessageCoverage(locales) {
  const keys = Object.keys(ACADEMY_GRAPH_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, keys.filter((key) => typeof ACADEMY_GRAPH_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(ACADEMY_GRAPH_MESSAGES[locale] || {}).filter((key) => !keys.includes(key)).sort()])),
  };
}
