export const ACADEMY_INTERACTION_MESSAGES = Object.freeze({
  tr: { hint: "Video ve etkileşimli içerik üzerinde doğrulanabilir kontrol noktaları, hotspot'lar, sorular ve dallanmalar oluşturun.", timeline: "Zaman çizelgesi", timeMs: "Zaman (ms)", blocking: "Engelleyici", scoreWeight: "Puan ağırlığı", payload: "Ek payload (JSON)", addInteraction: "Etkileşim ekle", save: "Zaman çizelgesini kaydet", saved: "Etkileşim zaman çizelgesi kaydedildi.", error: "Etkileşim zaman çizelgesi kaydedilemedi.", prompt: "İstem", status: "Yayın durumu" },
  en: { hint: "Author verifiable checkpoints, hotspots, questions and branches on video and interactive content.", timeline: "Timeline", timeMs: "Time (ms)", blocking: "Blocking", scoreWeight: "Score weight", payload: "Additional payload (JSON)", addInteraction: "Add interaction", save: "Save timeline", saved: "Interaction timeline saved.", error: "Interaction timeline could not be saved.", prompt: "Prompt", status: "Publication status" },
  de: { hint: "Erstellen Sie überprüfbare Checkpoints, Hotspots, Fragen und Verzweigungen für Video- und interaktive Inhalte.", timeline: "Zeitleiste", timeMs: "Zeit (ms)", blocking: "Blockierend", scoreWeight: "Punktgewicht", payload: "Zusätzliche Nutzlast (JSON)", addInteraction: "Interaktion hinzufügen", save: "Zeitleiste speichern", saved: "Interaktions-Zeitleiste gespeichert.", error: "Interaktions-Zeitleiste konnte nicht gespeichert werden.", prompt: "Anweisung", status: "Veröffentlichungsstatus" },
  ar: { hint: "أنشئ نقاط تحقق ونقاط تفاعلية وأسئلة وتفرعات قابلة للتحقق على الفيديو والمحتوى التفاعلي.", timeline: "الخط الزمني", timeMs: "الوقت (مللي ثانية)", blocking: "حاجز", scoreWeight: "وزن الدرجة", payload: "بيانات إضافية (JSON)", addInteraction: "إضافة تفاعل", save: "حفظ الخط الزمني", saved: "تم حفظ الخط الزمني للتفاعل.", error: "تعذر حفظ الخط الزمني للتفاعل.", prompt: "النص", status: "حالة النشر" },
  fr: { hint: "Créez des checkpoints, hotspots, questions et branches vérifiables sur les vidéos et contenus interactifs.", timeline: "Chronologie", timeMs: "Temps (ms)", blocking: "Bloquant", scoreWeight: "Poids du score", payload: "Payload complémentaire (JSON)", addInteraction: "Ajouter une interaction", save: "Enregistrer la chronologie", saved: "Chronologie interactive enregistrée.", error: "La chronologie interactive n’a pas pu être enregistrée.", prompt: "Consigne", status: "Statut de publication" },
  es: { hint: "Crea checkpoints, hotspots, preguntas y ramificaciones verificables sobre vídeo y contenido interactivo.", timeline: "Línea de tiempo", timeMs: "Tiempo (ms)", blocking: "Bloqueante", scoreWeight: "Peso de puntuación", payload: "Payload adicional (JSON)", addInteraction: "Añadir interacción", save: "Guardar línea de tiempo", saved: "Línea de tiempo interactiva guardada.", error: "No se pudo guardar la línea de tiempo interactiva.", prompt: "Indicador", status: "Estado de publicación" },
  it: { hint: "Crea checkpoint, hotspot, domande e diramazioni verificabili su video e contenuti interattivi.", timeline: "Timeline", timeMs: "Tempo (ms)", blocking: "Bloccante", scoreWeight: "Peso punteggio", payload: "Payload aggiuntivo (JSON)", addInteraction: "Aggiungi interazione", save: "Salva timeline", saved: "Timeline interattiva salvata.", error: "Impossibile salvare la timeline interattiva.", prompt: "Prompt", status: "Stato pubblicazione" },
  nl: { hint: "Maak verifieerbare checkpoints, hotspots, vragen en vertakkingen voor video en interactieve content.", timeline: "Tijdlijn", timeMs: "Tijd (ms)", blocking: "Blokkerend", scoreWeight: "Scoregewicht", payload: "Extra payload (JSON)", addInteraction: "Interactie toevoegen", save: "Tijdlijn opslaan", saved: "Interactietijdlijn opgeslagen.", error: "Interactietijdlijn kon niet worden opgeslagen.", prompt: "Prompt", status: "Publicatiestatus" },
  pl: { hint: "Twórz weryfikowalne checkpointy, hotspoty, pytania i rozgałęzienia dla wideo i treści interaktywnych.", timeline: "Oś czasu", timeMs: "Czas (ms)", blocking: "Blokujące", scoreWeight: "Waga punktów", payload: "Dodatkowy payload (JSON)", addInteraction: "Dodaj interakcję", save: "Zapisz oś czasu", saved: "Oś interakcji zapisana.", error: "Nie udało się zapisać osi interakcji.", prompt: "Polecenie", status: "Status publikacji" },
  "pt-BR": { hint: "Crie checkpoints, hotspots, perguntas e ramificações verificáveis em vídeos e conteúdos interativos.", timeline: "Linha do tempo", timeMs: "Tempo (ms)", blocking: "Bloqueador", scoreWeight: "Peso da pontuação", payload: "Payload adicional (JSON)", addInteraction: "Adicionar interação", save: "Salvar linha do tempo", saved: "Linha do tempo interativa salva.", error: "Não foi possível salvar a linha do tempo interativa.", prompt: "Prompt", status: "Status de publicação" },
});

export function translateAcademyInteraction(locale, key) {
  const messages = ACADEMY_INTERACTION_MESSAGES[locale] || ACADEMY_INTERACTION_MESSAGES.en;
  return messages[key] || ACADEMY_INTERACTION_MESSAGES.en[key] || key;
}

export function academyInteractionMessageCoverage(locales) {
  const keys = Object.keys(ACADEMY_INTERACTION_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, keys.filter((key) => typeof ACADEMY_INTERACTION_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(ACADEMY_INTERACTION_MESSAGES[locale] || {}).filter((key) => !keys.includes(key)).sort()])),
  };
}
