export const AUDIT_LOG_MESSAGES = Object.freeze({
  tr: { title: "Audit Log", eyebrow: "Platform Çekirdeği", subtitle: "İzin verilen, reddedilen ve hataya düşen platform işlemlerini tenant bağlamında izleyin.", total: "Toplam", allowed: "İzin verilen", denied: "Reddedilen", error: "Hata", actor: "Aktör", decision: "Karar", action: "Aksiyon", all: "Tümü", filter: "Filtrele", clear: "Temizle", time: "Zaman", status: "Durum", requestId: "Request ID", empty: "Kayıt bulunamadı.", loadError: "Audit kayıtları alınamadı.", actorPlaceholder: "Aktör kimliği", actionPlaceholder: "get:/v1/context" },
  en: { title: "Audit Log", eyebrow: "Platform Core", subtitle: "Review allowed, denied and failed platform actions within the tenant boundary.", total: "Total", allowed: "Allowed", denied: "Denied", error: "Error", actor: "Actor", decision: "Decision", action: "Action", all: "All", filter: "Filter", clear: "Clear", time: "Time", status: "Status", requestId: "Request ID", empty: "No audit records found.", loadError: "Audit records could not be loaded.", actorPlaceholder: "Actor identity", actionPlaceholder: "get:/v1/context" },
  de: { title: "Audit-Protokoll", eyebrow: "Plattformkern", subtitle: "Prüfen Sie erlaubte, abgelehnte und fehlgeschlagene Plattformaktionen innerhalb der Mandantengrenze.", total: "Gesamt", allowed: "Erlaubt", denied: "Abgelehnt", error: "Fehler", actor: "Akteur", decision: "Entscheidung", action: "Aktion", all: "Alle", filter: "Filtern", clear: "Leeren", time: "Zeit", status: "Status", requestId: "Request-ID", empty: "Keine Audit-Einträge gefunden.", loadError: "Audit-Einträge konnten nicht geladen werden.", actorPlaceholder: "Akteuridentität", actionPlaceholder: "get:/v1/context" },
  ar: { title: "سجل التدقيق", eyebrow: "نواة المنصة", subtitle: "راجع إجراءات المنصة المسموح بها والمرفوضة والفاشلة ضمن حدود المستأجر.", total: "الإجمالي", allowed: "مسموح", denied: "مرفوض", error: "خطأ", actor: "الفاعل", decision: "القرار", action: "الإجراء", all: "الكل", filter: "تصفية", clear: "مسح", time: "الوقت", status: "الحالة", requestId: "معرّف الطلب", empty: "لا توجد سجلات تدقيق.", loadError: "تعذر تحميل سجلات التدقيق.", actorPlaceholder: "هوية الفاعل", actionPlaceholder: "get:/v1/context" },
  fr: { title: "Journal d’audit", eyebrow: "Noyau de plateforme", subtitle: "Consultez les actions de plateforme autorisées, refusées et en erreur dans la limite du tenant.", total: "Total", allowed: "Autorisé", denied: "Refusé", error: "Erreur", actor: "Acteur", decision: "Décision", action: "Action", all: "Tous", filter: "Filtrer", clear: "Effacer", time: "Heure", status: "Statut", requestId: "ID de requête", empty: "Aucun enregistrement d’audit.", loadError: "Impossible de charger les enregistrements d’audit.", actorPlaceholder: "Identité de l’acteur", actionPlaceholder: "get:/v1/context" },
  es: { title: "Registro de auditoría", eyebrow: "Núcleo de plataforma", subtitle: "Revise las acciones de plataforma permitidas, denegadas y fallidas dentro del límite del tenant.", total: "Total", allowed: "Permitido", denied: "Denegado", error: "Error", actor: "Actor", decision: "Decisión", action: "Acción", all: "Todos", filter: "Filtrar", clear: "Limpiar", time: "Hora", status: "Estado", requestId: "ID de solicitud", empty: "No se encontraron registros de auditoría.", loadError: "No se pudieron cargar los registros de auditoría.", actorPlaceholder: "Identidad del actor", actionPlaceholder: "get:/v1/context" },
  it: { title: "Registro audit", eyebrow: "Core della piattaforma", subtitle: "Controlla le azioni di piattaforma consentite, negate e fallite entro il confine del tenant.", total: "Totale", allowed: "Consentito", denied: "Negato", error: "Errore", actor: "Attore", decision: "Decisione", action: "Azione", all: "Tutti", filter: "Filtra", clear: "Pulisci", time: "Ora", status: "Stato", requestId: "ID richiesta", empty: "Nessun record di audit trovato.", loadError: "Impossibile caricare i record di audit.", actorPlaceholder: "Identità attore", actionPlaceholder: "get:/v1/context" },
  nl: { title: "Auditlogboek", eyebrow: "Platformkern", subtitle: "Bekijk toegestane, geweigerde en mislukte platformacties binnen de tenantgrens.", total: "Totaal", allowed: "Toegestaan", denied: "Geweigerd", error: "Fout", actor: "Actor", decision: "Besluit", action: "Actie", all: "Alle", filter: "Filteren", clear: "Wissen", time: "Tijd", status: "Status", requestId: "Request-ID", empty: "Geen auditrecords gevonden.", loadError: "Auditrecords konden niet worden geladen.", actorPlaceholder: "Actoridentiteit", actionPlaceholder: "get:/v1/context" },
  pl: { title: "Dziennik audytu", eyebrow: "Rdzeń platformy", subtitle: "Przeglądaj dozwolone, odrzucone i błędne działania platformy w granicach tenantu.", total: "Łącznie", allowed: "Dozwolone", denied: "Odrzucone", error: "Błąd", actor: "Aktor", decision: "Decyzja", action: "Akcja", all: "Wszystkie", filter: "Filtruj", clear: "Wyczyść", time: "Czas", status: "Status", requestId: "ID żądania", empty: "Nie znaleziono wpisów audytu.", loadError: "Nie udało się załadować wpisów audytu.", actorPlaceholder: "Tożsamość aktora", actionPlaceholder: "get:/v1/context" },
  "pt-BR": { title: "Log de auditoria", eyebrow: "Núcleo da plataforma", subtitle: "Revise ações de plataforma permitidas, negadas e com falha dentro do limite do tenant.", total: "Total", allowed: "Permitido", denied: "Negado", error: "Erro", actor: "Ator", decision: "Decisão", action: "Ação", all: "Todos", filter: "Filtrar", clear: "Limpar", time: "Horário", status: "Status", requestId: "ID da solicitação", empty: "Nenhum registro de auditoria encontrado.", loadError: "Não foi possível carregar os registros de auditoria.", actorPlaceholder: "Identidade do ator", actionPlaceholder: "get:/v1/context" },
});

export function translateAuditLog(locale, key) {
  return AUDIT_LOG_MESSAGES[locale]?.[key] || AUDIT_LOG_MESSAGES.en[key] || key;
}

export function auditLogMessageCoverage(locales) {
  const referenceKeys = Object.keys(AUDIT_LOG_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, referenceKeys.filter((key) => typeof AUDIT_LOG_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(AUDIT_LOG_MESSAGES[locale] || {}).filter((key) => !referenceKeys.includes(key)).sort()])),
  };
}
