const SHARED_PRODUCT_LABELS = Object.freeze({
  modulePlanogramTitle: "Planogram Studio",
  moduleDockosTitle: "DockOS",
  moduleBudgetTitle: "Budget Control",
  moduleWorkforceTitle: "Workforce",
  moduleRecruitmentTitle: "Recruitment",
  moduleAcademyTitle: "EAY Academy",
  moduleJarvisTitle: "Jarvis",
  moduleInsightTitle: "AI Insight",
  moduleInventoryTitle: "Inventory",
  moduleAuditTitle: "Audit Log",
  moduleAccessTitle: "Access Control",
  modulePlanogramMeta: "Shelf · Fixture · Facing",
  moduleDockosMeta: "PO · ST · Dock",
  moduleBudgetMeta: "PR · PO · Cost",
  moduleWorkforceMeta: "Shift · Attendance · Team",
  moduleRecruitmentMeta: "Request · Candidate · Hire",
  moduleAcademyMeta: "Learning · Studio · Jarvis",
  moduleJarvisMeta: "Tools · Scope · Evidence",
  moduleInsightMeta: "Metric · Provenance · Gate",
  moduleInventoryMeta: "Count · Variance · Audit",
  moduleAuditMeta: "Actor · Decision · Request",
  moduleAccessMeta: "User · Group · Role",
});

const tr = {
  greetingMorning: "Günaydın", greetingDay: "İyi günler", greetingEvening: "İyi akşamlar", controlReady: "kontrol merkezi hazır.", tagline: "Operasyonu takip etme. Ona yön ver.", searchPlaceholder: "Modül, operasyon alanı veya yetki ara…", superAdmin: "Super Admin", authorizedUser: "Yetkili kullanıcı", lightTheme: "Açık", darkTheme: "Koyu", logout: "Çıkış", commandStatus: "Kontrol durumu", visibleModules: "Görünen modül", activeAccess: "Aktif erişim", preparing: "Hazırlanan", roleBasedActive: "Rol tabanlı görünüm aktif", emptyModules: "Bu kullanıcı için görünen modül yok.", emptyModulesDetail: "Bir platform yöneticisinin gerekli modül erişimini vermesi gerekiyor.", ready: "Hazır", governed: "Yönetilen", admin: "Admin", scope: "Kapsam", shortcut: "Kısayol", modulePreparing: "Hazırlanıyor", enterModule: "Modüle gir", openModuleAria: "{module} modülünü aç",
  groupStoreIntelligence: "Mağaza Zekâsı", groupInboundControl: "Mal Kabul Kontrolü", groupFinanceOperations: "Finans Operasyonları", groupPeopleOperations: "İnsan Operasyonları", groupTalentOperations: "Yetenek Operasyonları", groupKnowledge: "Bilgi ve Öğrenme", groupIntelligence: "Zekâ", groupInventoryControl: "Envanter Kontrolü", groupAdministration: "Platform Yönetimi",
  modulePlanogramDescription: "Raf yerleşimi, fixture-first planlama, kategori optimizasyonu ve fiziksel doğruluk yönetimi.", moduleDockosDescription: "Sevkiyat, randevu, tedarikçi, PO ve depo kapasite kontrolü.", moduleBudgetDescription: "PR, PO, maliyet merkezi, fatura ve bütçe görünürlüğü.", moduleWorkforceDescription: "Çalışan, vardiya, devam, dönem kapanışı ve saha iş gücü yönetimi.", moduleRecruitmentDescription: "Normdan işe girişe kadar aday, onay ve Employee Master yaşam döngüsü.", moduleAcademyDescription: "Öğrenme yolları, interaktif içerik, yetkinlik, sertifika ve kaynaklı Jarvis eğitmen.", moduleJarvisDescription: "Yetki sınırında yönetilen araçlar, kaynak doğruluğu ve operasyonel zekâ.", moduleInsightDescription: "Canonical KPI etkinliği, provenance ve kanıt görünürlüğü.", moduleInventoryDescription: "Terminal sayımı, kör sayım, fark mutabakatı, yeniden sayım ve resmi tutanak yönetimi.", moduleAuditDescription: "Platform erişimlerini, reddedilen işlemleri ve hata kayıtlarını yetkili kapsamda izle.", moduleAccessDescription: "Kullanıcı, grup, rol ve modül yetkilerini sunucu otoritesiyle yönet.",
};

const en = {
  greetingMorning: "Good morning", greetingDay: "Good afternoon", greetingEvening: "Good evening", controlReady: "the control center is ready.", tagline: "Do not just track operations. Lead them.", searchPlaceholder: "Search modules, operational areas, or permissions…", superAdmin: "Super Admin", authorizedUser: "Authorized user", lightTheme: "Light", darkTheme: "Dark", logout: "Sign out", commandStatus: "Command status", visibleModules: "Visible modules", activeAccess: "Active access", preparing: "Preparing", roleBasedActive: "Role-based view is active", emptyModules: "No modules are visible for this user.", emptyModulesDetail: "A platform administrator must grant the required module access.", ready: "Ready", governed: "Governed", admin: "Admin", scope: "Scope", shortcut: "Shortcut", modulePreparing: "Preparing", enterModule: "Open module", openModuleAria: "Open {module}",
  groupStoreIntelligence: "Store Intelligence", groupInboundControl: "Inbound Control", groupFinanceOperations: "Finance Operations", groupPeopleOperations: "People Operations", groupTalentOperations: "Talent Operations", groupKnowledge: "Knowledge & Learning", groupIntelligence: "Intelligence", groupInventoryControl: "Inventory Control", groupAdministration: "Platform Administration",
  modulePlanogramDescription: "Shelf placement, fixture-first planning, category optimization, and physical-truth control.", moduleDockosDescription: "Shipment, appointment, supplier, PO, and warehouse-capacity control.", moduleBudgetDescription: "Visibility across PRs, POs, cost centers, invoices, and budgets.", moduleWorkforceDescription: "Employee, shift, attendance, period-close, and field workforce management.", moduleRecruitmentDescription: "Candidate, approval, and Employee Master lifecycle from staffing norm to hire.", moduleAcademyDescription: "Learning paths, interactive content, competency, certificates, and a source-grounded Jarvis tutor.", moduleJarvisDescription: "Governed tools, source truth, and operational intelligence within authorized scope.", moduleInsightDescription: "Canonical KPI activation, provenance, and evidence visibility.", moduleInventoryDescription: "Terminal counting, blind counts, variance reconciliation, recounts, and formal records.", moduleAuditDescription: "Review platform access, denied operations, and errors within authorized scope.", moduleAccessDescription: "Manage users, groups, roles, and module permissions through server authority.",
};

const de = {
  greetingMorning: "Guten Morgen", greetingDay: "Guten Tag", greetingEvening: "Guten Abend", controlReady: "das Kontrollzentrum ist bereit.", tagline: "Betrieb nicht nur verfolgen. Aktiv steuern.", searchPlaceholder: "Module, Betriebsbereiche oder Berechtigungen suchen…", superAdmin: "Super Admin", authorizedUser: "Berechtigter Benutzer", lightTheme: "Hell", darkTheme: "Dunkel", logout: "Abmelden", commandStatus: "Kontrollstatus", visibleModules: "Sichtbare Module", activeAccess: "Aktiver Zugriff", preparing: "In Vorbereitung", roleBasedActive: "Rollenbasierte Ansicht ist aktiv", emptyModules: "Für diesen Benutzer sind keine Module sichtbar.", emptyModulesDetail: "Ein Plattformadministrator muss den erforderlichen Modulzugriff gewähren.", ready: "Bereit", governed: "Governed", admin: "Admin", scope: "Umfang", shortcut: "Kurzbefehl", modulePreparing: "Wird vorbereitet", enterModule: "Modul öffnen", openModuleAria: "{module} öffnen",
  groupStoreIntelligence: "Filialintelligenz", groupInboundControl: "Wareneingangskontrolle", groupFinanceOperations: "Finanzoperationen", groupPeopleOperations: "Personaloperationen", groupTalentOperations: "Talentoperationen", groupKnowledge: "Wissen & Lernen", groupIntelligence: "Intelligenz", groupInventoryControl: "Bestandskontrolle", groupAdministration: "Plattformverwaltung",
  modulePlanogramDescription: "Regalplatzierung, fixture-first Planung, Kategorieoptimierung und Kontrolle der physischen Wahrheit.", moduleDockosDescription: "Steuerung von Sendungen, Terminen, Lieferanten, POs und Lagerkapazität.", moduleBudgetDescription: "Transparenz über PRs, POs, Kostenstellen, Rechnungen und Budgets.", moduleWorkforceDescription: "Mitarbeiter-, Schicht-, Anwesenheits-, Periodenabschluss- und Einsatzplanung.", moduleRecruitmentDescription: "Kandidaten-, Freigabe- und Employee-Master-Lebenszyklus vom Personalbedarf bis zur Einstellung.", moduleAcademyDescription: "Lernpfade, interaktive Inhalte, Kompetenzen, Zertifikate und quellenbasierter Jarvis-Tutor.", moduleJarvisDescription: "Kontrollierte Werkzeuge, Quellenwahrheit und Betriebsintelligenz im Berechtigungsrahmen.", moduleInsightDescription: "Aktivierung, Provenienz und Nachweise kanonischer KPIs.", moduleInventoryDescription: "Terminalzählung, Blindzählung, Differenzabgleich, Nachzählung und formelle Protokolle.", moduleAuditDescription: "Plattformzugriffe, abgelehnte Vorgänge und Fehler im zulässigen Umfang prüfen.", moduleAccessDescription: "Benutzer, Gruppen, Rollen und Modulrechte über Serverautorität verwalten.",
};

const ar = {
  greetingMorning: "صباح الخير", greetingDay: "مرحباً", greetingEvening: "مساء الخير", controlReady: "مركز التحكم جاهز.", tagline: "لا تكتفِ بمتابعة العمليات. قُدها.", searchPlaceholder: "ابحث عن وحدة أو مجال تشغيل أو صلاحية…", superAdmin: "المشرف الأعلى", authorizedUser: "مستخدم مخوّل", lightTheme: "فاتح", darkTheme: "داكن", logout: "تسجيل الخروج", commandStatus: "حالة التحكم", visibleModules: "الوحدات الظاهرة", activeAccess: "الوصول النشط", preparing: "قيد التجهيز", roleBasedActive: "العرض القائم على الأدوار مفعّل", emptyModules: "لا توجد وحدات ظاهرة لهذا المستخدم.", emptyModulesDetail: "يجب على مسؤول المنصة منح الوصول المطلوب للوحدات.", ready: "جاهز", governed: "محكوم", admin: "إدارة", scope: "النطاق", shortcut: "اختصار", modulePreparing: "قيد التجهيز", enterModule: "فتح الوحدة", openModuleAria: "فتح وحدة {module}",
  groupStoreIntelligence: "ذكاء المتجر", groupInboundControl: "ضبط الاستلام", groupFinanceOperations: "العمليات المالية", groupPeopleOperations: "عمليات الأفراد", groupTalentOperations: "عمليات المواهب", groupKnowledge: "المعرفة والتعلم", groupIntelligence: "الذكاء", groupInventoryControl: "ضبط المخزون", groupAdministration: "إدارة المنصة",
  modulePlanogramDescription: "توزيع الرفوف والتخطيط المبني على التجهيزات وتحسين الفئات وضبط الحقيقة المادية.", moduleDockosDescription: "ضبط الشحنات والمواعيد والموردين وأوامر الشراء وسعة المستودع.", moduleBudgetDescription: "رؤية موحدة لطلبات الشراء والأوامر ومراكز التكلفة والفواتير والميزانية.", moduleWorkforceDescription: "إدارة الموظفين والورديات والحضور وإغلاق الفترات والقوى العاملة الميدانية.", moduleRecruitmentDescription: "دورة المرشح والموافقة وEmployee Master من الاحتياج الوظيفي حتى التعيين.", moduleAcademyDescription: "مسارات تعلم ومحتوى تفاعلي وكفاءات وشهادات ومدرس Jarvis مستند إلى المصادر.", moduleJarvisDescription: "أدوات محكومة وحقيقة مصدرية وذكاء تشغيلي ضمن نطاق الصلاحية.", moduleInsightDescription: "تفعيل مؤشرات الأداء المعتمدة ومصدرها وحالة الأدلة.", moduleInventoryDescription: "الجرد عبر الأجهزة والجرد الأعمى وتسوية الفروقات وإعادة الجرد والمحاضر الرسمية.", moduleAuditDescription: "مراجعة وصول المنصة والعمليات المرفوضة والأخطاء ضمن النطاق المصرح.", moduleAccessDescription: "إدارة المستخدمين والمجموعات والأدوار وصلاحيات الوحدات عبر سلطة الخادم.",
};

const fr = {
  greetingMorning: "Bonjour", greetingDay: "Bonjour", greetingEvening: "Bonsoir", controlReady: "le centre de contrôle est prêt.", tagline: "Ne vous contentez pas de suivre les opérations. Pilotez-les.", searchPlaceholder: "Rechercher un module, un domaine opérationnel ou une autorisation…", superAdmin: "Super Admin", authorizedUser: "Utilisateur autorisé", lightTheme: "Clair", darkTheme: "Sombre", logout: "Se déconnecter", commandStatus: "État de commande", visibleModules: "Modules visibles", activeAccess: "Accès actif", preparing: "En préparation", roleBasedActive: "Vue basée sur les rôles active", emptyModules: "Aucun module n’est visible pour cet utilisateur.", emptyModulesDetail: "Un administrateur de plateforme doit accorder les accès requis.", ready: "Prêt", governed: "Gouverné", admin: "Admin", scope: "Périmètre", shortcut: "Raccourci", modulePreparing: "Préparation", enterModule: "Ouvrir le module", openModuleAria: "Ouvrir {module}",
  groupStoreIntelligence: "Intelligence magasin", groupInboundControl: "Contrôle réception", groupFinanceOperations: "Opérations financières", groupPeopleOperations: "Opérations RH", groupTalentOperations: "Opérations talents", groupKnowledge: "Connaissance & apprentissage", groupIntelligence: "Intelligence", groupInventoryControl: "Contrôle des stocks", groupAdministration: "Administration plateforme",
  modulePlanogramDescription: "Placement en rayon, planification fixture-first, optimisation des catégories et contrôle de la vérité physique.", moduleDockosDescription: "Contrôle des expéditions, rendez-vous, fournisseurs, PO et capacité d’entrepôt.", moduleBudgetDescription: "Visibilité sur les PR, PO, centres de coûts, factures et budgets.", moduleWorkforceDescription: "Gestion des employés, équipes, présences, clôtures de période et effectifs terrain.", moduleRecruitmentDescription: "Cycle candidat, approbation et Employee Master du besoin d’effectif à l’embauche.", moduleAcademyDescription: "Parcours, contenu interactif, compétences, certificats et tuteur Jarvis fondé sur les sources.", moduleJarvisDescription: "Outils gouvernés, vérité des sources et intelligence opérationnelle dans le périmètre autorisé.", moduleInsightDescription: "Activation, provenance et preuves des KPI canoniques.", moduleInventoryDescription: "Comptage terminal, inventaire aveugle, rapprochement des écarts, recomptage et procès-verbaux.", moduleAuditDescription: "Examiner les accès plateforme, opérations refusées et erreurs dans le périmètre autorisé.", moduleAccessDescription: "Gérer utilisateurs, groupes, rôles et droits de module via l’autorité serveur.",
};

const es = {
  greetingMorning: "Buenos días", greetingDay: "Buenas tardes", greetingEvening: "Buenas noches", controlReady: "el centro de control está listo.", tagline: "No te limites a seguir la operación. Dirígela.", searchPlaceholder: "Buscar módulo, área operativa o permiso…", superAdmin: "Super Admin", authorizedUser: "Usuario autorizado", lightTheme: "Claro", darkTheme: "Oscuro", logout: "Cerrar sesión", commandStatus: "Estado de control", visibleModules: "Módulos visibles", activeAccess: "Acceso activo", preparing: "En preparación", roleBasedActive: "Vista basada en roles activa", emptyModules: "No hay módulos visibles para este usuario.", emptyModulesDetail: "Un administrador de plataforma debe conceder el acceso necesario.", ready: "Listo", governed: "Gobernado", admin: "Admin", scope: "Alcance", shortcut: "Atajo", modulePreparing: "Preparando", enterModule: "Abrir módulo", openModuleAria: "Abrir {module}",
  groupStoreIntelligence: "Inteligencia de tienda", groupInboundControl: "Control de recepción", groupFinanceOperations: "Operaciones financieras", groupPeopleOperations: "Operaciones de personas", groupTalentOperations: "Operaciones de talento", groupKnowledge: "Conocimiento y aprendizaje", groupIntelligence: "Inteligencia", groupInventoryControl: "Control de inventario", groupAdministration: "Administración de plataforma",
  modulePlanogramDescription: "Ubicación en estantería, planificación fixture-first, optimización de categorías y control de verdad física.", moduleDockosDescription: "Control de envíos, citas, proveedores, PO y capacidad de almacén.", moduleBudgetDescription: "Visibilidad de PR, PO, centros de coste, facturas y presupuestos.", moduleWorkforceDescription: "Gestión de empleados, turnos, asistencia, cierre de periodos y fuerza laboral de campo.", moduleRecruitmentDescription: "Ciclo de candidato, aprobación y Employee Master desde la norma hasta la contratación.", moduleAcademyDescription: "Rutas de aprendizaje, contenido interactivo, competencias, certificados y tutor Jarvis basado en fuentes.", moduleJarvisDescription: "Herramientas gobernadas, verdad de fuentes e inteligencia operativa dentro del alcance autorizado.", moduleInsightDescription: "Activación, procedencia y evidencia de KPI canónicos.", moduleInventoryDescription: "Conteo con terminal, conteo ciego, conciliación de diferencias, recuento y actas formales.", moduleAuditDescription: "Revisar accesos, operaciones denegadas y errores dentro del alcance autorizado.", moduleAccessDescription: "Gestionar usuarios, grupos, roles y permisos de módulo mediante autoridad del servidor.",
};

const it = {
  greetingMorning: "Buongiorno", greetingDay: "Buon pomeriggio", greetingEvening: "Buonasera", controlReady: "il centro di controllo è pronto.", tagline: "Non limitarti a seguire le operazioni. Guidale.", searchPlaceholder: "Cerca modulo, area operativa o autorizzazione…", superAdmin: "Super Admin", authorizedUser: "Utente autorizzato", lightTheme: "Chiaro", darkTheme: "Scuro", logout: "Esci", commandStatus: "Stato comando", visibleModules: "Moduli visibili", activeAccess: "Accesso attivo", preparing: "In preparazione", roleBasedActive: "Vista basata sui ruoli attiva", emptyModules: "Nessun modulo è visibile per questo utente.", emptyModulesDetail: "Un amministratore di piattaforma deve concedere l’accesso richiesto.", ready: "Pronto", governed: "Governato", admin: "Admin", scope: "Ambito", shortcut: "Scorciatoia", modulePreparing: "Preparazione", enterModule: "Apri modulo", openModuleAria: "Apri {module}",
  groupStoreIntelligence: "Intelligenza negozio", groupInboundControl: "Controllo inbound", groupFinanceOperations: "Operazioni finanziarie", groupPeopleOperations: "Operazioni persone", groupTalentOperations: "Operazioni talenti", groupKnowledge: "Conoscenza e apprendimento", groupIntelligence: "Intelligenza", groupInventoryControl: "Controllo inventario", groupAdministration: "Amministrazione piattaforma",
  modulePlanogramDescription: "Posizionamento a scaffale, pianificazione fixture-first, ottimizzazione categorie e controllo della verità fisica.", moduleDockosDescription: "Controllo di spedizioni, appuntamenti, fornitori, PO e capacità di magazzino.", moduleBudgetDescription: "Visibilità su PR, PO, centri di costo, fatture e budget.", moduleWorkforceDescription: "Gestione di dipendenti, turni, presenze, chiusura periodi e forza lavoro sul campo.", moduleRecruitmentDescription: "Ciclo candidato, approvazione ed Employee Master dal fabbisogno all’assunzione.", moduleAcademyDescription: "Percorsi, contenuti interattivi, competenze, certificati e tutor Jarvis basato sulle fonti.", moduleJarvisDescription: "Strumenti governati, verità delle fonti e intelligenza operativa entro l’ambito autorizzato.", moduleInsightDescription: "Attivazione, provenienza ed evidenze dei KPI canonici.", moduleInventoryDescription: "Conteggio terminale, conteggio cieco, riconciliazione differenze, ricontrollo e verbali formali.", moduleAuditDescription: "Esamina accessi, operazioni negate ed errori entro l’ambito autorizzato.", moduleAccessDescription: "Gestisci utenti, gruppi, ruoli e permessi dei moduli tramite autorità server.",
};

const nl = {
  greetingMorning: "Goedemorgen", greetingDay: "Goedemiddag", greetingEvening: "Goedenavond", controlReady: "het controlecentrum is gereed.", tagline: "Volg de operatie niet alleen. Stuur haar aan.", searchPlaceholder: "Zoek module, operationeel domein of bevoegdheid…", superAdmin: "Super Admin", authorizedUser: "Bevoegde gebruiker", lightTheme: "Licht", darkTheme: "Donker", logout: "Afmelden", commandStatus: "Besturingsstatus", visibleModules: "Zichtbare modules", activeAccess: "Actieve toegang", preparing: "In voorbereiding", roleBasedActive: "Rolgebaseerde weergave is actief", emptyModules: "Er zijn geen modules zichtbaar voor deze gebruiker.", emptyModulesDetail: "Een platformbeheerder moet de vereiste moduletoegang verlenen.", ready: "Gereed", governed: "Beheerd", admin: "Admin", scope: "Bereik", shortcut: "Sneltoets", modulePreparing: "Wordt voorbereid", enterModule: "Module openen", openModuleAria: "Open {module}",
  groupStoreIntelligence: "Winkelintelligentie", groupInboundControl: "Inboundcontrole", groupFinanceOperations: "Financiële operaties", groupPeopleOperations: "People Operations", groupTalentOperations: "Talent Operations", groupKnowledge: "Kennis & leren", groupIntelligence: "Intelligentie", groupInventoryControl: "Voorraadcontrole", groupAdministration: "Platformbeheer",
  modulePlanogramDescription: "Schapplaatsing, fixture-first planning, categorie-optimalisatie en controle op fysieke waarheid.", moduleDockosDescription: "Beheer van zendingen, afspraken, leveranciers, PO's en magazijncapaciteit.", moduleBudgetDescription: "Zicht op PR's, PO's, kostenplaatsen, facturen en budgetten.", moduleWorkforceDescription: "Beheer van medewerkers, diensten, aanwezigheid, periodeafsluiting en veldbezetting.", moduleRecruitmentDescription: "Kandidaat-, goedkeurings- en Employee Master-cyclus van norm tot indiensttreding.", moduleAcademyDescription: "Leerpaden, interactieve inhoud, competenties, certificaten en brongebonden Jarvis-tutor.", moduleJarvisDescription: "Beheerde tools, bronwaarheid en operationele intelligentie binnen bevoegd bereik.", moduleInsightDescription: "Activatie, herkomst en bewijs van canonieke KPI's.", moduleInventoryDescription: "Terminaltelling, blinde telling, verschilafstemming, hertelling en formele verslagen.", moduleAuditDescription: "Controleer platformtoegang, geweigerde acties en fouten binnen bevoegd bereik.", moduleAccessDescription: "Beheer gebruikers, groepen, rollen en modulemachtigingen via serverautoriteit.",
};

const pl = {
  greetingMorning: "Dzień dobry", greetingDay: "Dzień dobry", greetingEvening: "Dobry wieczór", controlReady: "centrum sterowania jest gotowe.", tagline: "Nie tylko obserwuj operacje. Kieruj nimi.", searchPlaceholder: "Szukaj modułu, obszaru operacyjnego lub uprawnienia…", superAdmin: "Super Admin", authorizedUser: "Uprawniony użytkownik", lightTheme: "Jasny", darkTheme: "Ciemny", logout: "Wyloguj", commandStatus: "Stan sterowania", visibleModules: "Widoczne moduły", activeAccess: "Aktywny dostęp", preparing: "W przygotowaniu", roleBasedActive: "Widok oparty na rolach jest aktywny", emptyModules: "Brak modułów widocznych dla tego użytkownika.", emptyModulesDetail: "Administrator platformy musi nadać wymagany dostęp do modułów.", ready: "Gotowe", governed: "Zarządzane", admin: "Admin", scope: "Zakres", shortcut: "Skrót", modulePreparing: "Przygotowywanie", enterModule: "Otwórz moduł", openModuleAria: "Otwórz {module}",
  groupStoreIntelligence: "Inteligencja sklepu", groupInboundControl: "Kontrola przyjęć", groupFinanceOperations: "Operacje finansowe", groupPeopleOperations: "Operacje pracownicze", groupTalentOperations: "Operacje talentowe", groupKnowledge: "Wiedza i nauka", groupIntelligence: "Inteligencja", groupInventoryControl: "Kontrola zapasów", groupAdministration: "Administracja platformą",
  modulePlanogramDescription: "Rozmieszczenie na półkach, planowanie fixture-first, optymalizacja kategorii i kontrola prawdy fizycznej.", moduleDockosDescription: "Kontrola dostaw, wizyt, dostawców, PO i pojemności magazynu.", moduleBudgetDescription: "Widoczność PR, PO, centrów kosztów, faktur i budżetów.", moduleWorkforceDescription: "Zarządzanie pracownikami, zmianami, obecnością, zamknięciem okresu i personelem terenowym.", moduleRecruitmentDescription: "Cykl kandydata, akceptacji i Employee Master od normy zatrudnienia do przyjęcia.", moduleAcademyDescription: "Ścieżki nauki, treści interaktywne, kompetencje, certyfikaty i tutor Jarvis oparty na źródłach.", moduleJarvisDescription: "Zarządzane narzędzia, prawda źródłowa i inteligencja operacyjna w granicach uprawnień.", moduleInsightDescription: "Aktywacja, pochodzenie i dowody kanonicznych KPI.", moduleInventoryDescription: "Liczenie terminalowe, liczenie w ciemno, uzgadnianie różnic, ponowne liczenie i protokoły.", moduleAuditDescription: "Przeglądaj dostęp, odrzucone operacje i błędy w autoryzowanym zakresie.", moduleAccessDescription: "Zarządzaj użytkownikami, grupami, rolami i prawami modułów przez autorytet serwera.",
};

const ptBR = {
  greetingMorning: "Bom dia", greetingDay: "Boa tarde", greetingEvening: "Boa noite", controlReady: "o centro de controle está pronto.", tagline: "Não apenas acompanhe a operação. Lidere-a.", searchPlaceholder: "Buscar módulo, área operacional ou permissão…", superAdmin: "Super Admin", authorizedUser: "Usuário autorizado", lightTheme: "Claro", darkTheme: "Escuro", logout: "Sair", commandStatus: "Status de comando", visibleModules: "Módulos visíveis", activeAccess: "Acesso ativo", preparing: "Em preparação", roleBasedActive: "Visão baseada em funções ativa", emptyModules: "Nenhum módulo está visível para este usuário.", emptyModulesDetail: "Um administrador da plataforma deve conceder o acesso necessário.", ready: "Pronto", governed: "Governado", admin: "Admin", scope: "Escopo", shortcut: "Atalho", modulePreparing: "Preparando", enterModule: "Abrir módulo", openModuleAria: "Abrir {module}",
  groupStoreIntelligence: "Inteligência de loja", groupInboundControl: "Controle de recebimento", groupFinanceOperations: "Operações financeiras", groupPeopleOperations: "Operações de pessoas", groupTalentOperations: "Operações de talentos", groupKnowledge: "Conhecimento e aprendizagem", groupIntelligence: "Inteligência", groupInventoryControl: "Controle de estoque", groupAdministration: "Administração da plataforma",
  modulePlanogramDescription: "Posicionamento em prateleira, planejamento fixture-first, otimização de categorias e controle da verdade física.", moduleDockosDescription: "Controle de remessas, agendamentos, fornecedores, POs e capacidade do armazém.", moduleBudgetDescription: "Visibilidade de PRs, POs, centros de custo, faturas e orçamentos.", moduleWorkforceDescription: "Gestão de funcionários, turnos, presença, fechamento de período e força de trabalho de campo.", moduleRecruitmentDescription: "Ciclo de candidato, aprovação e Employee Master da norma de quadro à contratação.", moduleAcademyDescription: "Trilhas, conteúdo interativo, competências, certificados e tutor Jarvis fundamentado em fontes.", moduleJarvisDescription: "Ferramentas governadas, verdade das fontes e inteligência operacional dentro do escopo autorizado.", moduleInsightDescription: "Ativação, proveniência e evidências de KPIs canônicos.", moduleInventoryDescription: "Contagem por terminal, contagem cega, reconciliação de divergências, recontagem e registros formais.", moduleAuditDescription: "Revise acessos, operações negadas e erros dentro do escopo autorizado.", moduleAccessDescription: "Gerencie usuários, grupos, funções e permissões de módulos pela autoridade do servidor.",
};

function withShared(messages) {
  return Object.freeze({ ...SHARED_PRODUCT_LABELS, ...messages });
}

export const CONTROL_CENTER_MESSAGES = Object.freeze({
  tr: withShared(tr), en: withShared(en), de: withShared(de), ar: withShared(ar), fr: withShared(fr), es: withShared(es), it: withShared(it), nl: withShared(nl), pl: withShared(pl), "pt-BR": withShared(ptBR),
});

export function translateControlCenter(locale, key, params = {}) {
  const message = CONTROL_CENTER_MESSAGES[locale]?.[key] ?? CONTROL_CENTER_MESSAGES.en?.[key];
  if (typeof message !== "string") return key;
  return message.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}

export function controlCenterMessageCoverage(locales) {
  const referenceKeys = Object.keys(CONTROL_CENTER_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(locales.map((locale) => [locale, referenceKeys.filter((key) => typeof CONTROL_CENTER_MESSAGES[locale]?.[key] !== "string")])),
    extra: Object.fromEntries(locales.map((locale) => [locale, Object.keys(CONTROL_CENTER_MESSAGES[locale] || {}).filter((key) => !referenceKeys.includes(key)).sort()])),
  };
}
