export const INTELLIGENCE_MESSAGES = Object.freeze({
  tr: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Yetkin dahilinde operasyon bilgisini güvenli araçlarla birleştirir.", insightTitle: "Insight", insightSubtitle: "Canonical KPI sözleşmelerinin etkinlik ve kanıt durumunu gösterir.", workspaceLoading: "Çalışma alanı hazırlanıyor…", workspaceLoadError: "Çalışma alanı yüklenemedi.", tenantBound: "Şirket sınırına bağlı", capabilities: "Yetkinlikler", governedTools: "Yönetilen araçlar", canonicalMetrics: "Canonical metrikler", productionReady: "Production hazır", blocked: "Bloke", candidate: "Aday", source: "Kaynak", blockers: "Blokerlar", externalEvidenceRequired: "Gerçek dış ortam kanıtı gerekli", noCapabilities: "Bu kullanıcı için kullanılabilir yetkinlik yok.", askUnavailable: "Genel Jarvis sohbeti henüz açılmadı", askUnavailableDetail: "Tenant-safe runtime ve yönetilen veri sözleşmesi hazır olmadan müşteri sohbeti açılmaz.", tenantDiscriminator: "Tenant ayırıcı", candidateUnverified: "Aday · doğrulanmadı", queryContract: "Sorgu sözleşmesi", available: "Yetkili", unavailable: "Yetkisiz",
  },
  en: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Combines operational knowledge through governed tools within your authority.", insightTitle: "Insight", insightSubtitle: "Shows activation and evidence state for canonical KPI contracts.", workspaceLoading: "Preparing workspace…", workspaceLoadError: "Workspace could not be loaded.", tenantBound: "Tenant-bound", capabilities: "Capabilities", governedTools: "Governed tools", canonicalMetrics: "Canonical metrics", productionReady: "Production ready", blocked: "Blocked", candidate: "Candidate", source: "Source", blockers: "Blockers", externalEvidenceRequired: "Real external evidence required", noCapabilities: "No capabilities are available for this user.", askUnavailable: "General Jarvis chat is not enabled yet", askUnavailableDetail: "Customer chat remains closed until the tenant-safe runtime and governed data contract are ready.", tenantDiscriminator: "Tenant discriminator", candidateUnverified: "Candidate · unverified", queryContract: "Query contract", available: "Authorized", unavailable: "Unauthorized",
  },
  de: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Verknüpft Betriebswissen innerhalb deiner Berechtigung über kontrollierte Werkzeuge.", insightTitle: "Insight", insightSubtitle: "Zeigt Aktivierungs- und Nachweisstatus kanonischer KPI-Verträge.", workspaceLoading: "Arbeitsbereich wird vorbereitet…", workspaceLoadError: "Arbeitsbereich konnte nicht geladen werden.", tenantBound: "Mandantengebunden", capabilities: "Fähigkeiten", governedTools: "Kontrollierte Werkzeuge", canonicalMetrics: "Kanonische Kennzahlen", productionReady: "Produktionsbereit", blocked: "Blockiert", candidate: "Kandidat", source: "Quelle", blockers: "Blocker", externalEvidenceRequired: "Realer externer Nachweis erforderlich", noCapabilities: "Für diesen Benutzer sind keine Fähigkeiten verfügbar.", askUnavailable: "Allgemeiner Jarvis-Chat ist noch nicht aktiviert", askUnavailableDetail: "Kundenchat bleibt geschlossen, bis mandantensichere Laufzeit und kontrollierter Datenvertrag bereit sind.", tenantDiscriminator: "Mandantentrenner", candidateUnverified: "Kandidat · nicht verifiziert", queryContract: "Abfragevertrag", available: "Berechtigt", unavailable: "Nicht berechtigt",
  },
  ar: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "يجمع المعرفة التشغيلية عبر أدوات محكومة ضمن صلاحياتك.", insightTitle: "Insight", insightSubtitle: "يعرض حالة التفعيل والأدلة لعقود مؤشرات الأداء المعتمدة.", workspaceLoading: "جارٍ تجهيز مساحة العمل…", workspaceLoadError: "تعذر تحميل مساحة العمل.", tenantBound: "مقيّد بالشركة", capabilities: "القدرات", governedTools: "الأدوات المحكومة", canonicalMetrics: "المقاييس المعتمدة", productionReady: "جاهز للإنتاج", blocked: "محظور", candidate: "مرشح", source: "المصدر", blockers: "العوائق", externalEvidenceRequired: "يلزم دليل حقيقي من البيئة الخارجية", noCapabilities: "لا توجد قدرات متاحة لهذا المستخدم.", askUnavailable: "محادثة Jarvis العامة غير مفعلة بعد", askUnavailableDetail: "تبقى محادثة العميل مغلقة حتى تصبح بيئة التشغيل الآمنة للمستأجر وعقد البيانات المحكوم جاهزين.", tenantDiscriminator: "فاصل المستأجر", candidateUnverified: "مرشح · غير متحقق", queryContract: "عقد الاستعلام", available: "مصرح", unavailable: "غير مصرح",
  },
  fr: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Combine les connaissances opérationnelles via des outils gouvernés dans le périmètre de vos droits.", insightTitle: "Insight", insightSubtitle: "Affiche l’état d’activation et de preuve des contrats KPI canoniques.", workspaceLoading: "Préparation de l’espace…", workspaceLoadError: "Impossible de charger l’espace.", tenantBound: "Lié au tenant", capabilities: "Capacités", governedTools: "Outils gouvernés", canonicalMetrics: "Métriques canoniques", productionReady: "Prêt pour la production", blocked: "Bloqué", candidate: "Candidat", source: "Source", blockers: "Blocages", externalEvidenceRequired: "Preuve externe réelle requise", noCapabilities: "Aucune capacité disponible pour cet utilisateur.", askUnavailable: "Le chat Jarvis général n’est pas encore activé", askUnavailableDetail: "Le chat client reste fermé tant que l’exécution isolée par tenant et le contrat de données gouverné ne sont pas prêts.", tenantDiscriminator: "Discriminateur de tenant", candidateUnverified: "Candidat · non vérifié", queryContract: "Contrat de requête", available: "Autorisé", unavailable: "Non autorisé",
  },
  es: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Combina conocimiento operativo mediante herramientas gobernadas dentro de tus permisos.", insightTitle: "Insight", insightSubtitle: "Muestra el estado de activación y evidencia de los contratos KPI canónicos.", workspaceLoading: "Preparando el espacio…", workspaceLoadError: "No se pudo cargar el espacio.", tenantBound: "Vinculado al tenant", capabilities: "Capacidades", governedTools: "Herramientas gobernadas", canonicalMetrics: "Métricas canónicas", productionReady: "Listo para producción", blocked: "Bloqueado", candidate: "Candidato", source: "Fuente", blockers: "Bloqueos", externalEvidenceRequired: "Se requiere evidencia externa real", noCapabilities: "No hay capacidades disponibles para este usuario.", askUnavailable: "El chat general de Jarvis aún no está habilitado", askUnavailableDetail: "El chat del cliente permanece cerrado hasta que el runtime aislado por tenant y el contrato de datos gobernado estén listos.", tenantDiscriminator: "Discriminador de tenant", candidateUnverified: "Candidato · sin verificar", queryContract: "Contrato de consulta", available: "Autorizado", unavailable: "No autorizado",
  },
  it: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Combina conoscenza operativa tramite strumenti governati entro le tue autorizzazioni.", insightTitle: "Insight", insightSubtitle: "Mostra stato di attivazione e prove dei contratti KPI canonici.", workspaceLoading: "Preparazione dello spazio…", workspaceLoadError: "Impossibile caricare lo spazio.", tenantBound: "Vincolato al tenant", capabilities: "Capacità", governedTools: "Strumenti governati", canonicalMetrics: "Metriche canoniche", productionReady: "Pronto per produzione", blocked: "Bloccato", candidate: "Candidato", source: "Fonte", blockers: "Blocchi", externalEvidenceRequired: "È richiesta prova esterna reale", noCapabilities: "Nessuna capacità disponibile per questo utente.", askUnavailable: "La chat Jarvis generale non è ancora abilitata", askUnavailableDetail: "La chat cliente resta chiusa finché runtime tenant-safe e contratto dati governato non sono pronti.", tenantDiscriminator: "Discriminatore tenant", candidateUnverified: "Candidato · non verificato", queryContract: "Contratto query", available: "Autorizzato", unavailable: "Non autorizzato",
  },
  nl: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Combineert operationele kennis via beheerde tools binnen je bevoegdheid.", insightTitle: "Insight", insightSubtitle: "Toont activatie- en bewijsstatus van canonieke KPI-contracten.", workspaceLoading: "Werkruimte wordt voorbereid…", workspaceLoadError: "Werkruimte kon niet worden geladen.", tenantBound: "Tenantgebonden", capabilities: "Mogelijkheden", governedTools: "Beheerde tools", canonicalMetrics: "Canonieke metrics", productionReady: "Productieklaar", blocked: "Geblokkeerd", candidate: "Kandidaat", source: "Bron", blockers: "Blokkades", externalEvidenceRequired: "Echt extern bewijs vereist", noCapabilities: "Er zijn geen mogelijkheden beschikbaar voor deze gebruiker.", askUnavailable: "Algemene Jarvis-chat is nog niet ingeschakeld", askUnavailableDetail: "Klantchat blijft gesloten totdat de tenant-veilige runtime en het beheerde datacontract gereed zijn.", tenantDiscriminator: "Tenantdiscriminator", candidateUnverified: "Kandidaat · niet geverifieerd", queryContract: "Querycontract", available: "Geautoriseerd", unavailable: "Niet geautoriseerd",
  },
  pl: {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Łączy wiedzę operacyjną przez kontrolowane narzędzia w granicach uprawnień.", insightTitle: "Insight", insightSubtitle: "Pokazuje stan aktywacji i dowodów kanonicznych kontraktów KPI.", workspaceLoading: "Przygotowywanie przestrzeni…", workspaceLoadError: "Nie udało się załadować przestrzeni.", tenantBound: "Powiązane z tenantem", capabilities: "Możliwości", governedTools: "Kontrolowane narzędzia", canonicalMetrics: "Kanoniczne metryki", productionReady: "Gotowe produkcyjnie", blocked: "Zablokowane", candidate: "Kandydat", source: "Źródło", blockers: "Blokery", externalEvidenceRequired: "Wymagany rzeczywisty dowód zewnętrzny", noCapabilities: "Brak dostępnych możliwości dla tego użytkownika.", askUnavailable: "Ogólny czat Jarvis nie jest jeszcze włączony", askUnavailableDetail: "Czat klienta pozostaje zamknięty do czasu gotowości bezpiecznego runtime tenantowego i kontrolowanego kontraktu danych.", tenantDiscriminator: "Dyskryminator tenantu", candidateUnverified: "Kandydat · niezweryfikowany", queryContract: "Kontrakt zapytania", available: "Uprawniony", unavailable: "Brak uprawnień",
  },
  "pt-BR": {
    jarvisTitle: "Jarvis", jarvisSubtitle: "Combina conhecimento operacional por ferramentas governadas dentro da sua autoridade.", insightTitle: "Insight", insightSubtitle: "Mostra o estado de ativação e evidência dos contratos KPI canônicos.", workspaceLoading: "Preparando o espaço…", workspaceLoadError: "Não foi possível carregar o espaço.", tenantBound: "Vinculado ao tenant", capabilities: "Capacidades", governedTools: "Ferramentas governadas", canonicalMetrics: "Métricas canônicas", productionReady: "Pronto para produção", blocked: "Bloqueado", candidate: "Candidato", source: "Fonte", blockers: "Bloqueios", externalEvidenceRequired: "Evidência externa real necessária", noCapabilities: "Nenhuma capacidade disponível para este usuário.", askUnavailable: "O chat geral do Jarvis ainda não está habilitado", askUnavailableDetail: "O chat do cliente permanece fechado até que o runtime seguro por tenant e o contrato de dados governado estejam prontos.", tenantDiscriminator: "Discriminador de tenant", candidateUnverified: "Candidato · não verificado", queryContract: "Contrato de consulta", available: "Autorizado", unavailable: "Não autorizado",
  },
});

export function translateIntelligence(locale, key) {
  return INTELLIGENCE_MESSAGES[locale]?.[key] || key;
}

export function intelligenceMessageCoverage(locales) {
  const referenceKeys = Object.keys(INTELLIGENCE_MESSAGES.en).sort();
  return {
    missing: Object.fromEntries(
      locales.map((locale) => [
        locale,
        referenceKeys.filter(
          (key) => typeof INTELLIGENCE_MESSAGES[locale]?.[key] !== "string"
        ),
      ])
    ),
    extra: Object.fromEntries(
      locales.map((locale) => [
        locale,
        Object.keys(INTELLIGENCE_MESSAGES[locale] || {})
          .filter((key) => !referenceKeys.includes(key))
          .sort(),
      ])
    ),
  };
}
