export const SUPPORTED_LOCALES = Object.freeze([
  { code: "tr", label: "Turkish", nativeLabel: "Türkçe", dir: "ltr" },
  { code: "en", label: "English", nativeLabel: "English", dir: "ltr" },
  { code: "de", label: "German", nativeLabel: "Deutsch", dir: "ltr" },
  { code: "ar", label: "Arabic", nativeLabel: "العربية", dir: "rtl" },
  { code: "fr", label: "French", nativeLabel: "Français", dir: "ltr" },
  { code: "es", label: "Spanish", nativeLabel: "Español", dir: "ltr" },
  { code: "it", label: "Italian", nativeLabel: "Italiano", dir: "ltr" },
  { code: "nl", label: "Dutch", nativeLabel: "Nederlands", dir: "ltr" },
  { code: "pl", label: "Polish", nativeLabel: "Polski", dir: "ltr" },
  { code: "pt-BR", label: "Portuguese (Brazil)", nativeLabel: "Português (Brasil)", dir: "ltr" },
]);

const tr = {
  accessibility: "Erişilebilirlik", accessibilitySettings: "Erişilebilirlik ve dil ayarları", language: "Dil", textSize: "Metin boyutu", standard: "Standart", large: "Büyük", extraLarge: "Çok büyük", contrast: "Kontrast", highContrast: "Yüksek kontrast", reduceMotion: "Hareketi azalt", readableFont: "Okunabilir yazı tipi", underlineLinks: "Bağlantıları altı çizili göster", largeTargets: "Büyük dokunma hedefleri", focusMode: "Sade / odak modu", media: "Medya tercihleri", captions: "Altyazıları varsayılan açık tut", transcript: "Transkripti önceliklendir", audioDescription: "Sesli betimlemeyi tercih et", visualAlerts: "Sesli uyarıları görsel olarak da göster", reset: "Varsayılana dön", close: "Kapat", openSettings: "Erişilebilirlik ayarlarını aç", skipToContent: "Ana içeriğe geç", noDiagnosis: "Bu ayarlar ihtiyaç tercihleridir; sağlık/engel teşhisi kaydedilmez.",
  loading: "Yükleniyor…", retry: "Tekrar dene", refresh: "Yenile", back: "Geri", home: "Ana sayfa", save: "Kaydet", cancel: "Vazgeç", search: "Ara", filter: "Filtrele", all: "Tümü", status: "Durum", actions: "İşlemler", errorTitle: "Bir sorun oluştu", emptyTitle: "Burada henüz bir kayıt yok", permissionDenied: "Bu işlem için yetkin yok.", offline: "Bağlantı yok. Güvenli olduğunda tekrar denenecek.", completed: "Tamamlandı", inProgress: "Devam ediyor", assigned: "Atandı", due: "Son tarih", progress: "İlerleme", continueAction: "Devam et", start: "Başla", open: "Aç", view: "Görüntüle", create: "Oluştur", publish: "Yayınla", draft: "Taslak", published: "Yayında",
  academy: "Academy", academySubtitle: "Öğren, uygula, hatırla ve gelişimi kanıtla.", myLearning: "Öğrenmelerim", catalog: "Katalog", learningPaths: "Öğrenme yolları", assignments: "Görevler", certificates: "Sertifikalar", jarvisTutor: "Jarvis Eğitmen", contentStudio: "İçerik Stüdyosu", audiences: "Hedef Kitleler", analytics: "Öğrenme Analitiği", liveLearning: "Canlı Eğitim", academyLoading: "Academy çalışma alanın hazırlanıyor…", academyEmpty: "Şu anda sana atanmış bir öğrenme yok.", academyLoadError: "Academy bilgileri alınamadı.", academyTenant: "Şirket", academySubject: "Kullanıcı", academyContent: "İçerikler", academyEnrollments: "Atamalar", academyRequired: "Zorunlu", academyOptional: "İsteğe bağlı", academyResume: "Kaldığın yerden devam et", academyAskJarvis: "Jarvis'e sor", academyQuestionPlaceholder: "Eğitim, prosedür veya uygulama hakkında sor…", academySourceAnswer: "Kaynaklı yanıt", academyNoAnswer: "Onaylı eğitim kaynaklarında yeterli kanıt bulunamadı.", academySources: "Kaynaklar", academyTimestamp: "İlgili bölüm", academyContentVersion: "İçerik sürümü", academyCreateContent: "Yeni içerik", academyCreatePath: "Öğrenme yolu oluştur", academyCreateQuiz: "Quiz oluştur", academyAssign: "Kişiye / gruba ata", academyManageAudience: "Kitle ve erişim yönetimi", academyTitle: "Başlık", academyDescription: "Açıklama", academyContentType: "İçerik türü", academySlug: "İçerik kodu", academyDuration: "Süre", academyUpload: "Medya ekle", academyDocument: "Doküman", academyVideo: "Video", academyInteractive: "İnteraktif", academyLive: "Canlı", academyQuiz: "Quiz", academyCheckpoint: "Kontrol noktası", academyPrerequisite: "Ön koşul", academyRetention: "Hatırlama", academyMastery: "Yetkinlik", academyFieldProof: "Saha kanıtı", academyCompletionRule: "Tamamlama kuralı", academyNoPermission: "Bu Academy alanını yönetme yetkin yok.", academyAdmin: "Academy Yönetimi",
};

const en = {
  accessibility: "Accessibility", accessibilitySettings: "Accessibility and language settings", language: "Language", textSize: "Text size", standard: "Standard", large: "Large", extraLarge: "Extra large", contrast: "Contrast", highContrast: "High contrast", reduceMotion: "Reduce motion", readableFont: "Readable font", underlineLinks: "Underline links", largeTargets: "Large touch targets", focusMode: "Simplified / focus mode", media: "Media preferences", captions: "Keep captions on by default", transcript: "Prefer transcript", audioDescription: "Prefer audio description", visualAlerts: "Show visual equivalents for audio alerts", reset: "Reset defaults", close: "Close", openSettings: "Open accessibility settings", skipToContent: "Skip to main content", noDiagnosis: "These are access preferences; no disability or health diagnosis is stored.",
  loading: "Loading…", retry: "Try again", refresh: "Refresh", back: "Back", home: "Home", save: "Save", cancel: "Cancel", search: "Search", filter: "Filter", all: "All", status: "Status", actions: "Actions", errorTitle: "Something went wrong", emptyTitle: "There is nothing here yet", permissionDenied: "You do not have permission for this action.", offline: "No connection. The action will retry when it is safe.", completed: "Completed", inProgress: "In progress", assigned: "Assigned", due: "Due", progress: "Progress", continueAction: "Continue", start: "Start", open: "Open", view: "View", create: "Create", publish: "Publish", draft: "Draft", published: "Published",
  academy: "Academy", academySubtitle: "Learn, apply, retain, and prove improvement.", myLearning: "My learning", catalog: "Catalog", learningPaths: "Learning paths", assignments: "Assignments", certificates: "Certificates", jarvisTutor: "Jarvis Tutor", contentStudio: "Content Studio", audiences: "Audiences", analytics: "Learning Analytics", liveLearning: "Live Learning", academyLoading: "Preparing your Academy workspace…", academyEmpty: "You do not have any assigned learning right now.", academyLoadError: "Academy information could not be loaded.", academyTenant: "Company", academySubject: "User", academyContent: "Content", academyEnrollments: "Assignments", academyRequired: "Required", academyOptional: "Optional", academyResume: "Resume where you left off", academyAskJarvis: "Ask Jarvis", academyQuestionPlaceholder: "Ask about a training, procedure, or practice…", academySourceAnswer: "Grounded answer", academyNoAnswer: "There is not enough evidence in approved learning sources.", academySources: "Sources", academyTimestamp: "Relevant section", academyContentVersion: "Content version", academyCreateContent: "New content", academyCreatePath: "Create learning path", academyCreateQuiz: "Create quiz", academyAssign: "Assign to person / group", academyManageAudience: "Audience and access management", academyTitle: "Title", academyDescription: "Description", academyContentType: "Content type", academySlug: "Content code", academyDuration: "Duration", academyUpload: "Add media", academyDocument: "Document", academyVideo: "Video", academyInteractive: "Interactive", academyLive: "Live", academyQuiz: "Quiz", academyCheckpoint: "Checkpoint", academyPrerequisite: "Prerequisite", academyRetention: "Retention", academyMastery: "Mastery", academyFieldProof: "Field proof", academyCompletionRule: "Completion rule", academyNoPermission: "You do not have permission to manage this Academy area.", academyAdmin: "Academy Administration",
};

const de = {
  accessibility: "Barrierefreiheit", accessibilitySettings: "Barrierefreiheit und Sprache", language: "Sprache", textSize: "Textgröße", standard: "Standard", large: "Groß", extraLarge: "Sehr groß", contrast: "Kontrast", highContrast: "Hoher Kontrast", reduceMotion: "Bewegung reduzieren", readableFont: "Gut lesbare Schrift", underlineLinks: "Links unterstreichen", largeTargets: "Große Bedienflächen", focusMode: "Fokusmodus", media: "Medienpräferenzen", captions: "Untertitel standardmäßig aktivieren", transcript: "Transkript bevorzugen", audioDescription: "Audiodeskription bevorzugen", visualAlerts: "Akustische Hinweise auch visuell anzeigen", reset: "Zurücksetzen", close: "Schließen", openSettings: "Einstellungen zur Barrierefreiheit öffnen", skipToContent: "Zum Hauptinhalt springen", noDiagnosis: "Es werden nur Zugangspräferenzen gespeichert, keine Diagnose.",
  loading: "Wird geladen…", retry: "Erneut versuchen", refresh: "Aktualisieren", back: "Zurück", home: "Start", save: "Speichern", cancel: "Abbrechen", search: "Suchen", filter: "Filtern", all: "Alle", status: "Status", actions: "Aktionen", errorTitle: "Ein Fehler ist aufgetreten", emptyTitle: "Hier gibt es noch keine Einträge", permissionDenied: "Für diese Aktion fehlt die Berechtigung.", offline: "Keine Verbindung. Der Vorgang wird sicher erneut versucht.", completed: "Abgeschlossen", inProgress: "In Bearbeitung", assigned: "Zugewiesen", due: "Fällig", progress: "Fortschritt", continueAction: "Fortsetzen", start: "Starten", open: "Öffnen", view: "Anzeigen", create: "Erstellen", publish: "Veröffentlichen", draft: "Entwurf", published: "Veröffentlicht",
  academy: "Academy", academySubtitle: "Lernen, anwenden, behalten und Fortschritt nachweisen.", myLearning: "Mein Lernen", catalog: "Katalog", learningPaths: "Lernpfade", assignments: "Aufgaben", certificates: "Zertifikate", jarvisTutor: "Jarvis Tutor", contentStudio: "Content Studio", audiences: "Zielgruppen", analytics: "Lernanalytik", liveLearning: "Live-Lernen", academyLoading: "Academy-Arbeitsbereich wird vorbereitet…", academyEmpty: "Aktuell sind keine Lerninhalte zugewiesen.", academyLoadError: "Academy-Informationen konnten nicht geladen werden.", academyTenant: "Unternehmen", academySubject: "Benutzer", academyContent: "Inhalte", academyEnrollments: "Zuweisungen", academyRequired: "Pflicht", academyOptional: "Optional", academyResume: "Dort fortsetzen, wo du aufgehört hast", academyAskJarvis: "Jarvis fragen", academyQuestionPlaceholder: "Frage zu Training, Verfahren oder Praxis…", academySourceAnswer: "Quellenbasierte Antwort", academyNoAnswer: "In freigegebenen Lernquellen gibt es nicht genügend Belege.", academySources: "Quellen", academyTimestamp: "Relevanter Abschnitt", academyContentVersion: "Inhaltsversion", academyCreateContent: "Neuer Inhalt", academyCreatePath: "Lernpfad erstellen", academyCreateQuiz: "Quiz erstellen", academyAssign: "Person / Gruppe zuweisen", academyManageAudience: "Zielgruppen und Zugriff", academyTitle: "Titel", academyDescription: "Beschreibung", academyContentType: "Inhaltstyp", academySlug: "Inhaltscode", academyDuration: "Dauer", academyUpload: "Medien hinzufügen", academyDocument: "Dokument", academyVideo: "Video", academyInteractive: "Interaktiv", academyLive: "Live", academyQuiz: "Quiz", academyCheckpoint: "Kontrollpunkt", academyPrerequisite: "Voraussetzung", academyRetention: "Behalten", academyMastery: "Beherrschung", academyFieldProof: "Praxisnachweis", academyCompletionRule: "Abschlussregel", academyNoPermission: "Du darfst diesen Academy-Bereich nicht verwalten.", academyAdmin: "Academy-Verwaltung",
};

const ar = {
  accessibility: "إمكانية الوصول", accessibilitySettings: "إعدادات إمكانية الوصول واللغة", language: "اللغة", textSize: "حجم النص", standard: "قياسي", large: "كبير", extraLarge: "كبير جداً", contrast: "التباين", highContrast: "تباين عالٍ", reduceMotion: "تقليل الحركة", readableFont: "خط سهل القراءة", underlineLinks: "تسطير الروابط", largeTargets: "أهداف لمس كبيرة", focusMode: "وضع التركيز المبسط", media: "تفضيلات الوسائط", captions: "تشغيل التسميات التوضيحية افتراضياً", transcript: "تفضيل النص المكتوب", audioDescription: "تفضيل الوصف الصوتي", visualAlerts: "إظهار بديل مرئي للتنبيهات الصوتية", reset: "إعادة الضبط", close: "إغلاق", openSettings: "فتح إعدادات إمكانية الوصول", skipToContent: "الانتقال إلى المحتوى الرئيسي", noDiagnosis: "يتم حفظ تفضيلات الوصول فقط ولا يتم حفظ أي تشخيص صحي أو إعاقة.",
  loading: "جارٍ التحميل…", retry: "إعادة المحاولة", refresh: "تحديث", back: "رجوع", home: "الرئيسية", save: "حفظ", cancel: "إلغاء", search: "بحث", filter: "تصفية", all: "الكل", status: "الحالة", actions: "الإجراءات", errorTitle: "حدث خطأ", emptyTitle: "لا توجد سجلات هنا بعد", permissionDenied: "ليست لديك صلاحية لهذا الإجراء.", offline: "لا يوجد اتصال. ستتم إعادة المحاولة عندما يكون ذلك آمناً.", completed: "مكتمل", inProgress: "قيد التنفيذ", assigned: "مُعيّن", due: "الموعد النهائي", progress: "التقدم", continueAction: "متابعة", start: "ابدأ", open: "فتح", view: "عرض", create: "إنشاء", publish: "نشر", draft: "مسودة", published: "منشور",
  academy: "الأكاديمية", academySubtitle: "تعلّم وطبّق وتذكّر وأثبت التحسن.", myLearning: "تعلمي", catalog: "المكتبة", learningPaths: "مسارات التعلم", assignments: "المهام", certificates: "الشهادات", jarvisTutor: "مدرّس Jarvis", contentStudio: "استوديو المحتوى", audiences: "الفئات المستهدفة", analytics: "تحليلات التعلم", liveLearning: "التعلم المباشر", academyLoading: "جارٍ تجهيز مساحة الأكاديمية…", academyEmpty: "لا توجد حالياً تعلمّات معيّنة لك.", academyLoadError: "تعذر تحميل معلومات الأكاديمية.", academyTenant: "الشركة", academySubject: "المستخدم", academyContent: "المحتوى", academyEnrollments: "التعيينات", academyRequired: "إلزامي", academyOptional: "اختياري", academyResume: "تابع من حيث توقفت", academyAskJarvis: "اسأل Jarvis", academyQuestionPlaceholder: "اسأل عن تدريب أو إجراء أو ممارسة…", academySourceAnswer: "إجابة مستندة إلى المصادر", academyNoAnswer: "لا توجد أدلة كافية في مصادر التعلم المعتمدة.", academySources: "المصادر", academyTimestamp: "القسم المرتبط", academyContentVersion: "إصدار المحتوى", academyCreateContent: "محتوى جديد", academyCreatePath: "إنشاء مسار تعلم", academyCreateQuiz: "إنشاء اختبار", academyAssign: "إسناد إلى شخص / مجموعة", academyManageAudience: "إدارة الجمهور والوصول", academyTitle: "العنوان", academyDescription: "الوصف", academyContentType: "نوع المحتوى", academySlug: "رمز المحتوى", academyDuration: "المدة", academyUpload: "إضافة وسائط", academyDocument: "مستند", academyVideo: "فيديو", academyInteractive: "تفاعلي", academyLive: "مباشر", academyQuiz: "اختبار", academyCheckpoint: "نقطة تحقق", academyPrerequisite: "متطلب سابق", academyRetention: "الاحتفاظ", academyMastery: "الإتقان", academyFieldProof: "إثبات ميداني", academyCompletionRule: "قاعدة الإكمال", academyNoPermission: "ليست لديك صلاحية لإدارة هذا الجزء من الأكاديمية.", academyAdmin: "إدارة الأكاديمية",
};

const fr = {
  accessibility: "Accessibilité", accessibilitySettings: "Accessibilité et langue", language: "Langue", textSize: "Taille du texte", standard: "Standard", large: "Grand", extraLarge: "Très grand", contrast: "Contraste", highContrast: "Contraste élevé", reduceMotion: "Réduire les animations", readableFont: "Police lisible", underlineLinks: "Souligner les liens", largeTargets: "Grandes zones tactiles", focusMode: "Mode simplifié / concentration", media: "Préférences média", captions: "Activer les sous-titres par défaut", transcript: "Privilégier la transcription", audioDescription: "Privilégier l’audiodescription", visualAlerts: "Afficher aussi visuellement les alertes sonores", reset: "Réinitialiser", close: "Fermer", openSettings: "Ouvrir les paramètres d’accessibilité", skipToContent: "Aller au contenu principal", noDiagnosis: "Seules les préférences d’accès sont enregistrées, aucun diagnostic de santé ou de handicap.",
  loading: "Chargement…", retry: "Réessayer", refresh: "Actualiser", back: "Retour", home: "Accueil", save: "Enregistrer", cancel: "Annuler", search: "Rechercher", filter: "Filtrer", all: "Tous", status: "Statut", actions: "Actions", errorTitle: "Un problème est survenu", emptyTitle: "Aucun élément pour le moment", permissionDenied: "Vous n’avez pas l’autorisation pour cette action.", offline: "Pas de connexion. Une nouvelle tentative sera faite en toute sécurité.", completed: "Terminé", inProgress: "En cours", assigned: "Attribué", due: "Échéance", progress: "Progression", continueAction: "Continuer", start: "Commencer", open: "Ouvrir", view: "Voir", create: "Créer", publish: "Publier", draft: "Brouillon", published: "Publié",
  academy: "Academy", academySubtitle: "Apprendre, appliquer, mémoriser et prouver les progrès.", myLearning: "Mes apprentissages", catalog: "Catalogue", learningPaths: "Parcours d’apprentissage", assignments: "Missions", certificates: "Certificats", jarvisTutor: "Tuteur Jarvis", contentStudio: "Studio de contenu", audiences: "Publics", analytics: "Analytique d’apprentissage", liveLearning: "Formation en direct", academyLoading: "Préparation de votre espace Academy…", academyEmpty: "Aucun apprentissage ne vous est actuellement attribué.", academyLoadError: "Impossible de charger les informations Academy.", academyTenant: "Entreprise", academySubject: "Utilisateur", academyContent: "Contenus", academyEnrollments: "Affectations", academyRequired: "Obligatoire", academyOptional: "Facultatif", academyResume: "Reprendre où vous vous êtes arrêté", academyAskJarvis: "Demander à Jarvis", academyQuestionPlaceholder: "Posez une question sur une formation, une procédure ou une pratique…", academySourceAnswer: "Réponse sourcée", academyNoAnswer: "Les sources d’apprentissage approuvées ne contiennent pas assez d’éléments.", academySources: "Sources", academyTimestamp: "Section pertinente", academyContentVersion: "Version du contenu", academyCreateContent: "Nouveau contenu", academyCreatePath: "Créer un parcours", academyCreateQuiz: "Créer un quiz", academyAssign: "Attribuer à une personne / un groupe", academyManageAudience: "Gestion des publics et des accès", academyTitle: "Titre", academyDescription: "Description", academyContentType: "Type de contenu", academySlug: "Code du contenu", academyDuration: "Durée", academyUpload: "Ajouter un média", academyDocument: "Document", academyVideo: "Vidéo", academyInteractive: "Interactif", academyLive: "Direct", academyQuiz: "Quiz", academyCheckpoint: "Point de contrôle", academyPrerequisite: "Prérequis", academyRetention: "Rétention", academyMastery: "Maîtrise", academyFieldProof: "Preuve terrain", academyCompletionRule: "Règle d’achèvement", academyNoPermission: "Vous n’avez pas l’autorisation de gérer cet espace Academy.", academyAdmin: "Administration Academy",
};

const es = {
  accessibility: "Accesibilidad", accessibilitySettings: "Accesibilidad e idioma", language: "Idioma", textSize: "Tamaño del texto", standard: "Estándar", large: "Grande", extraLarge: "Muy grande", contrast: "Contraste", highContrast: "Alto contraste", reduceMotion: "Reducir movimiento", readableFont: "Fuente legible", underlineLinks: "Subrayar enlaces", largeTargets: "Objetivos táctiles grandes", focusMode: "Modo simplificado / enfoque", media: "Preferencias multimedia", captions: "Activar subtítulos por defecto", transcript: "Priorizar transcripción", audioDescription: "Preferir audiodescripción", visualAlerts: "Mostrar también visualmente las alertas sonoras", reset: "Restablecer", close: "Cerrar", openSettings: "Abrir ajustes de accesibilidad", skipToContent: "Ir al contenido principal", noDiagnosis: "Solo se guardan preferencias de acceso; no se almacena ningún diagnóstico de salud o discapacidad.",
  loading: "Cargando…", retry: "Volver a intentar", refresh: "Actualizar", back: "Atrás", home: "Inicio", save: "Guardar", cancel: "Cancelar", search: "Buscar", filter: "Filtrar", all: "Todos", status: "Estado", actions: "Acciones", errorTitle: "Se produjo un problema", emptyTitle: "Aún no hay registros", permissionDenied: "No tienes permiso para esta acción.", offline: "Sin conexión. Se volverá a intentar cuando sea seguro.", completed: "Completado", inProgress: "En curso", assigned: "Asignado", due: "Fecha límite", progress: "Progreso", continueAction: "Continuar", start: "Comenzar", open: "Abrir", view: "Ver", create: "Crear", publish: "Publicar", draft: "Borrador", published: "Publicado",
  academy: "Academy", academySubtitle: "Aprende, aplica, recuerda y demuestra la mejora.", myLearning: "Mi aprendizaje", catalog: "Catálogo", learningPaths: "Rutas de aprendizaje", assignments: "Tareas", certificates: "Certificados", jarvisTutor: "Tutor Jarvis", contentStudio: "Estudio de contenido", audiences: "Audiencias", analytics: "Analítica de aprendizaje", liveLearning: "Formación en directo", academyLoading: "Preparando tu espacio Academy…", academyEmpty: "Ahora mismo no tienes aprendizaje asignado.", academyLoadError: "No se pudo cargar la información de Academy.", academyTenant: "Empresa", academySubject: "Usuario", academyContent: "Contenido", academyEnrollments: "Asignaciones", academyRequired: "Obligatorio", academyOptional: "Opcional", academyResume: "Continúa donde lo dejaste", academyAskJarvis: "Preguntar a Jarvis", academyQuestionPlaceholder: "Pregunta sobre una formación, procedimiento o práctica…", academySourceAnswer: "Respuesta fundamentada", academyNoAnswer: "No hay pruebas suficientes en las fuentes de aprendizaje aprobadas.", academySources: "Fuentes", academyTimestamp: "Sección relevante", academyContentVersion: "Versión del contenido", academyCreateContent: "Nuevo contenido", academyCreatePath: "Crear ruta de aprendizaje", academyCreateQuiz: "Crear cuestionario", academyAssign: "Asignar a persona / grupo", academyManageAudience: "Gestión de audiencia y acceso", academyTitle: "Título", academyDescription: "Descripción", academyContentType: "Tipo de contenido", academySlug: "Código de contenido", academyDuration: "Duración", academyUpload: "Añadir medio", academyDocument: "Documento", academyVideo: "Vídeo", academyInteractive: "Interactivo", academyLive: "En directo", academyQuiz: "Cuestionario", academyCheckpoint: "Punto de control", academyPrerequisite: "Requisito previo", academyRetention: "Retención", academyMastery: "Dominio", academyFieldProof: "Evidencia de campo", academyCompletionRule: "Regla de finalización", academyNoPermission: "No tienes permiso para gestionar esta zona de Academy.", academyAdmin: "Administración de Academy",
};

const it = {
  accessibility: "Accessibilità", accessibilitySettings: "Accessibilità e lingua", language: "Lingua", textSize: "Dimensione testo", standard: "Standard", large: "Grande", extraLarge: "Molto grande", contrast: "Contrasto", highContrast: "Contrasto elevato", reduceMotion: "Riduci movimento", readableFont: "Carattere leggibile", underlineLinks: "Sottolinea i link", largeTargets: "Aree touch grandi", focusMode: "Modalità semplificata / concentrazione", media: "Preferenze media", captions: "Attiva i sottotitoli per impostazione predefinita", transcript: "Preferisci trascrizione", audioDescription: "Preferisci audiodescrizione", visualAlerts: "Mostra anche visivamente gli avvisi sonori", reset: "Ripristina", close: "Chiudi", openSettings: "Apri impostazioni di accessibilità", skipToContent: "Vai al contenuto principale", noDiagnosis: "Vengono salvate solo preferenze di accesso, non diagnosi sanitarie o di disabilità.",
  loading: "Caricamento…", retry: "Riprova", refresh: "Aggiorna", back: "Indietro", home: "Home", save: "Salva", cancel: "Annulla", search: "Cerca", filter: "Filtra", all: "Tutti", status: "Stato", actions: "Azioni", errorTitle: "Si è verificato un problema", emptyTitle: "Non ci sono ancora elementi", permissionDenied: "Non hai l’autorizzazione per questa azione.", offline: "Nessuna connessione. Verrà riprovato quando sarà sicuro.", completed: "Completato", inProgress: "In corso", assigned: "Assegnato", due: "Scadenza", progress: "Progresso", continueAction: "Continua", start: "Inizia", open: "Apri", view: "Visualizza", create: "Crea", publish: "Pubblica", draft: "Bozza", published: "Pubblicato",
  academy: "Academy", academySubtitle: "Impara, applica, ricorda e dimostra il miglioramento.", myLearning: "Il mio apprendimento", catalog: "Catalogo", learningPaths: "Percorsi di apprendimento", assignments: "Attività", certificates: "Certificati", jarvisTutor: "Tutor Jarvis", contentStudio: "Studio contenuti", audiences: "Destinatari", analytics: "Analisi dell’apprendimento", liveLearning: "Formazione live", academyLoading: "Preparazione dello spazio Academy…", academyEmpty: "Al momento non hai apprendimenti assegnati.", academyLoadError: "Impossibile caricare le informazioni Academy.", academyTenant: "Azienda", academySubject: "Utente", academyContent: "Contenuti", academyEnrollments: "Assegnazioni", academyRequired: "Obbligatorio", academyOptional: "Facoltativo", academyResume: "Riprendi da dove hai lasciato", academyAskJarvis: "Chiedi a Jarvis", academyQuestionPlaceholder: "Chiedi informazioni su formazione, procedura o pratica…", academySourceAnswer: "Risposta basata su fonti", academyNoAnswer: "Non ci sono prove sufficienti nelle fonti di apprendimento approvate.", academySources: "Fonti", academyTimestamp: "Sezione pertinente", academyContentVersion: "Versione contenuto", academyCreateContent: "Nuovo contenuto", academyCreatePath: "Crea percorso", academyCreateQuiz: "Crea quiz", academyAssign: "Assegna a persona / gruppo", academyManageAudience: "Gestione destinatari e accessi", academyTitle: "Titolo", academyDescription: "Descrizione", academyContentType: "Tipo di contenuto", academySlug: "Codice contenuto", academyDuration: "Durata", academyUpload: "Aggiungi media", academyDocument: "Documento", academyVideo: "Video", academyInteractive: "Interattivo", academyLive: "Live", academyQuiz: "Quiz", academyCheckpoint: "Checkpoint", academyPrerequisite: "Prerequisito", academyRetention: "Ritenzione", academyMastery: "Padronanza", academyFieldProof: "Prova sul campo", academyCompletionRule: "Regola di completamento", academyNoPermission: "Non hai l’autorizzazione per gestire quest’area Academy.", academyAdmin: "Amministrazione Academy",
};

const nl = {
  accessibility: "Toegankelijkheid", accessibilitySettings: "Toegankelijkheid en taal", language: "Taal", textSize: "Tekstgrootte", standard: "Standaard", large: "Groot", extraLarge: "Extra groot", contrast: "Contrast", highContrast: "Hoog contrast", reduceMotion: "Beweging verminderen", readableFont: "Leesbaar lettertype", underlineLinks: "Links onderstrepen", largeTargets: "Grote aanraakdoelen", focusMode: "Vereenvoudigde / focusmodus", media: "Mediavoorkeuren", captions: "Ondertiteling standaard aan", transcript: "Transcript verkiezen", audioDescription: "Audiodescriptie verkiezen", visualAlerts: "Geluidsmeldingen ook visueel tonen", reset: "Herstellen", close: "Sluiten", openSettings: "Toegankelijkheidsinstellingen openen", skipToContent: "Naar hoofdinhoud", noDiagnosis: "Alleen toegangsvoorkeuren worden opgeslagen; geen gezondheids- of handicapdiagnose.",
  loading: "Laden…", retry: "Opnieuw proberen", refresh: "Vernieuwen", back: "Terug", home: "Home", save: "Opslaan", cancel: "Annuleren", search: "Zoeken", filter: "Filteren", all: "Alle", status: "Status", actions: "Acties", errorTitle: "Er ging iets mis", emptyTitle: "Er zijn hier nog geen items", permissionDenied: "Je hebt geen toestemming voor deze actie.", offline: "Geen verbinding. Er wordt veilig opnieuw geprobeerd.", completed: "Voltooid", inProgress: "Bezig", assigned: "Toegewezen", due: "Vervaldatum", progress: "Voortgang", continueAction: "Doorgaan", start: "Starten", open: "Openen", view: "Bekijken", create: "Maken", publish: "Publiceren", draft: "Concept", published: "Gepubliceerd",
  academy: "Academy", academySubtitle: "Leer, pas toe, onthoud en bewijs verbetering.", myLearning: "Mijn leren", catalog: "Catalogus", learningPaths: "Leerpaden", assignments: "Opdrachten", certificates: "Certificaten", jarvisTutor: "Jarvis Tutor", contentStudio: "Contentstudio", audiences: "Doelgroepen", analytics: "Leeranalyses", liveLearning: "Live leren", academyLoading: "Je Academy-werkruimte wordt voorbereid…", academyEmpty: "Er is momenteel geen leeractiviteit aan je toegewezen.", academyLoadError: "Academy-informatie kon niet worden geladen.", academyTenant: "Bedrijf", academySubject: "Gebruiker", academyContent: "Inhoud", academyEnrollments: "Toewijzingen", academyRequired: "Verplicht", academyOptional: "Optioneel", academyResume: "Ga verder waar je gebleven was", academyAskJarvis: "Vraag Jarvis", academyQuestionPlaceholder: "Vraag over training, procedure of praktijk…", academySourceAnswer: "Brongebonden antwoord", academyNoAnswer: "Er is onvoldoende bewijs in goedgekeurde leerbronnen.", academySources: "Bronnen", academyTimestamp: "Relevant onderdeel", academyContentVersion: "Inhoudsversie", academyCreateContent: "Nieuwe inhoud", academyCreatePath: "Leerpad maken", academyCreateQuiz: "Quiz maken", academyAssign: "Toewijzen aan persoon / groep", academyManageAudience: "Doelgroep- en toegangsbeheer", academyTitle: "Titel", academyDescription: "Beschrijving", academyContentType: "Inhoudstype", academySlug: "Inhoudscode", academyDuration: "Duur", academyUpload: "Media toevoegen", academyDocument: "Document", academyVideo: "Video", academyInteractive: "Interactief", academyLive: "Live", academyQuiz: "Quiz", academyCheckpoint: "Controlepunt", academyPrerequisite: "Voorwaarde", academyRetention: "Behoud", academyMastery: "Beheersing", academyFieldProof: "Praktijkbewijs", academyCompletionRule: "Voltooiingsregel", academyNoPermission: "Je hebt geen toestemming om dit Academy-gebied te beheren.", academyAdmin: "Academy-beheer",
};

const pl = {
  accessibility: "Dostępność", accessibilitySettings: "Dostępność i język", language: "Język", textSize: "Rozmiar tekstu", standard: "Standardowy", large: "Duży", extraLarge: "Bardzo duży", contrast: "Kontrast", highContrast: "Wysoki kontrast", reduceMotion: "Ogranicz ruch", readableFont: "Czytelna czcionka", underlineLinks: "Podkreślaj linki", largeTargets: "Duże pola dotykowe", focusMode: "Tryb uproszczony / skupienia", media: "Preferencje mediów", captions: "Domyślnie włącz napisy", transcript: "Preferuj transkrypcję", audioDescription: "Preferuj audiodeskrypcję", visualAlerts: "Pokazuj wizualne odpowiedniki alertów dźwiękowych", reset: "Przywróć", close: "Zamknij", openSettings: "Otwórz ustawienia dostępności", skipToContent: "Przejdź do głównej treści", noDiagnosis: "Zapisywane są wyłącznie preferencje dostępu, bez diagnozy zdrowotnej lub niepełnosprawności.",
  loading: "Ładowanie…", retry: "Spróbuj ponownie", refresh: "Odśwież", back: "Wstecz", home: "Strona główna", save: "Zapisz", cancel: "Anuluj", search: "Szukaj", filter: "Filtruj", all: "Wszystkie", status: "Status", actions: "Działania", errorTitle: "Wystąpił problem", emptyTitle: "Nie ma tu jeszcze żadnych elementów", permissionDenied: "Nie masz uprawnień do tej czynności.", offline: "Brak połączenia. Próba zostanie ponowiona, gdy będzie to bezpieczne.", completed: "Ukończono", inProgress: "W toku", assigned: "Przypisano", due: "Termin", progress: "Postęp", continueAction: "Kontynuuj", start: "Rozpocznij", open: "Otwórz", view: "Zobacz", create: "Utwórz", publish: "Opublikuj", draft: "Szkic", published: "Opublikowano",
  academy: "Academy", academySubtitle: "Ucz się, stosuj, zapamiętuj i potwierdzaj rozwój.", myLearning: "Moja nauka", catalog: "Katalog", learningPaths: "Ścieżki nauki", assignments: "Zadania", certificates: "Certyfikaty", jarvisTutor: "Tutor Jarvis", contentStudio: "Studio treści", audiences: "Grupy odbiorców", analytics: "Analityka nauki", liveLearning: "Nauka na żywo", academyLoading: "Przygotowywanie przestrzeni Academy…", academyEmpty: "Obecnie nie masz przypisanych materiałów do nauki.", academyLoadError: "Nie udało się załadować informacji Academy.", academyTenant: "Firma", academySubject: "Użytkownik", academyContent: "Treści", academyEnrollments: "Przypisania", academyRequired: "Obowiązkowe", academyOptional: "Opcjonalne", academyResume: "Kontynuuj od miejsca, w którym skończyłeś", academyAskJarvis: "Zapytaj Jarvisa", academyQuestionPlaceholder: "Zapytaj o szkolenie, procedurę lub praktykę…", academySourceAnswer: "Odpowiedź oparta na źródłach", academyNoAnswer: "W zatwierdzonych źródłach szkoleniowych nie ma wystarczających dowodów.", academySources: "Źródła", academyTimestamp: "Powiązana sekcja", academyContentVersion: "Wersja treści", academyCreateContent: "Nowa treść", academyCreatePath: "Utwórz ścieżkę", academyCreateQuiz: "Utwórz quiz", academyAssign: "Przypisz osobie / grupie", academyManageAudience: "Zarządzanie grupami i dostępem", academyTitle: "Tytuł", academyDescription: "Opis", academyContentType: "Typ treści", academySlug: "Kod treści", academyDuration: "Czas trwania", academyUpload: "Dodaj media", academyDocument: "Dokument", academyVideo: "Wideo", academyInteractive: "Interaktywne", academyLive: "Na żywo", academyQuiz: "Quiz", academyCheckpoint: "Punkt kontrolny", academyPrerequisite: "Warunek wstępny", academyRetention: "Utrwalenie", academyMastery: "Opanowanie", academyFieldProof: "Dowód praktyczny", academyCompletionRule: "Reguła ukończenia", academyNoPermission: "Nie masz uprawnień do zarządzania tym obszarem Academy.", academyAdmin: "Administracja Academy",
};

const ptBR = {
  accessibility: "Acessibilidade", accessibilitySettings: "Acessibilidade e idioma", language: "Idioma", textSize: "Tamanho do texto", standard: "Padrão", large: "Grande", extraLarge: "Muito grande", contrast: "Contraste", highContrast: "Alto contraste", reduceMotion: "Reduzir movimento", readableFont: "Fonte legível", underlineLinks: "Sublinhar links", largeTargets: "Áreas de toque grandes", focusMode: "Modo simplificado / foco", media: "Preferências de mídia", captions: "Manter legendas ativas por padrão", transcript: "Preferir transcrição", audioDescription: "Preferir audiodescrição", visualAlerts: "Mostrar também visualmente os alertas sonoros", reset: "Redefinir", close: "Fechar", openSettings: "Abrir configurações de acessibilidade", skipToContent: "Ir para o conteúdo principal", noDiagnosis: "Apenas preferências de acesso são salvas; nenhum diagnóstico de saúde ou deficiência é armazenado.",
  loading: "Carregando…", retry: "Tentar novamente", refresh: "Atualizar", back: "Voltar", home: "Início", save: "Salvar", cancel: "Cancelar", search: "Pesquisar", filter: "Filtrar", all: "Todos", status: "Status", actions: "Ações", errorTitle: "Ocorreu um problema", emptyTitle: "Ainda não há itens aqui", permissionDenied: "Você não tem permissão para esta ação.", offline: "Sem conexão. A tentativa será repetida quando for seguro.", completed: "Concluído", inProgress: "Em andamento", assigned: "Atribuído", due: "Prazo", progress: "Progresso", continueAction: "Continuar", start: "Iniciar", open: "Abrir", view: "Ver", create: "Criar", publish: "Publicar", draft: "Rascunho", published: "Publicado",
  academy: "Academy", academySubtitle: "Aprenda, aplique, retenha e comprove a evolução.", myLearning: "Meu aprendizado", catalog: "Catálogo", learningPaths: "Trilhas de aprendizagem", assignments: "Tarefas", certificates: "Certificados", jarvisTutor: "Tutor Jarvis", contentStudio: "Estúdio de Conteúdo", audiences: "Públicos", analytics: "Análise de Aprendizagem", liveLearning: "Aprendizagem ao vivo", academyLoading: "Preparando seu espaço Academy…", academyEmpty: "Você não tem nenhum aprendizado atribuído no momento.", academyLoadError: "Não foi possível carregar as informações da Academy.", academyTenant: "Empresa", academySubject: "Usuário", academyContent: "Conteúdo", academyEnrollments: "Atribuições", academyRequired: "Obrigatório", academyOptional: "Opcional", academyResume: "Continue de onde parou", academyAskJarvis: "Perguntar ao Jarvis", academyQuestionPlaceholder: "Pergunte sobre um treinamento, procedimento ou prática…", academySourceAnswer: "Resposta fundamentada", academyNoAnswer: "Não há evidências suficientes nas fontes de aprendizagem aprovadas.", academySources: "Fontes", academyTimestamp: "Seção relevante", academyContentVersion: "Versão do conteúdo", academyCreateContent: "Novo conteúdo", academyCreatePath: "Criar trilha", academyCreateQuiz: "Criar quiz", academyAssign: "Atribuir a pessoa / grupo", academyManageAudience: "Gestão de público e acesso", academyTitle: "Título", academyDescription: "Descrição", academyContentType: "Tipo de conteúdo", academySlug: "Código do conteúdo", academyDuration: "Duração", academyUpload: "Adicionar mídia", academyDocument: "Documento", academyVideo: "Vídeo", academyInteractive: "Interativo", academyLive: "Ao vivo", academyQuiz: "Quiz", academyCheckpoint: "Ponto de controle", academyPrerequisite: "Pré-requisito", academyRetention: "Retenção", academyMastery: "Domínio", academyFieldProof: "Evidência em campo", academyCompletionRule: "Regra de conclusão", academyNoPermission: "Você não tem permissão para gerenciar esta área da Academy.", academyAdmin: "Administração da Academy",
};

export const MESSAGES = Object.freeze({ tr, en, de, ar, fr, es, it, nl, pl, "pt-BR": ptBR });

export function translate(locale, key, params = {}) {
  const dictionary = MESSAGES[locale];
  const message = dictionary?.[key];
  if (typeof message !== "string") return key;
  return message.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}

export function messageCoverage() {
  const locales = SUPPORTED_LOCALES.map((item) => item.code);
  const referenceKeys = Object.keys(MESSAGES.en).sort();
  return {
    locales,
    referenceKeys,
    missing: Object.fromEntries(
      locales.map((locale) => [
        locale,
        referenceKeys.filter((key) => typeof MESSAGES[locale]?.[key] !== "string"),
      ])
    ),
    extra: Object.fromEntries(
      locales.map((locale) => [
        locale,
        Object.keys(MESSAGES[locale] || {}).filter((key) => !referenceKeys.includes(key)).sort(),
      ])
    ),
  };
}
