const MESSAGES = Object.freeze({
  en:{title:"Picker Eye",subtitle:"Eye-level preview from the measured picker anchor with same-origin pack and fixture assets.",previewOnly:"PREVIEW · NOT FIELD PROOF",productAssets:"Pack assets",fixtureAssets:"Fixture assets",assetCoverage:"Asset coverage",loading:"Preparing Picker Eye…",error:"Picker Eye could not be rendered.",noAnchor:"Measured picker anchor unavailable; fallback camera used.",interaction:"Drag to look around and zoom; this scene does not grant layout or installation authority."},
  tr:{title:"Picker Gözü",subtitle:"Ölçülmüş picker noktasından, aynı-origin pack ve fixture asset'leriyle göz hizası önizleme.",previewOnly:"ÖNİZLEME · SAHA KANITI DEĞİL",productAssets:"Pack asset",fixtureAssets:"Fixture asset",assetCoverage:"Asset kapsamı",loading:"Picker Gözü hazırlanıyor…",error:"Picker Gözü oluşturulamadı.",noAnchor:"Ölçülmüş picker noktası yok; yedek kamera kullanıldı.",interaction:"Bakış için sürükle ve yakınlaştır; bu sahne yerleşim veya kurulum yetkisi vermez."},
  de:{title:"Picker Eye",subtitle:"Vorschau auf Augenhöhe vom gemessenen Picker-Anker mit Same-Origin-Pack- und Fixture-Assets.",previewOnly:"VORSCHAU · KEIN FELDNACHWEIS",productAssets:"Pack-Assets",fixtureAssets:"Fixture-Assets",assetCoverage:"Asset-Abdeckung",loading:"Picker Eye wird vorbereitet…",error:"Picker Eye konnte nicht gerendert werden.",noAnchor:"Kein gemessener Picker-Anker; Ersatzkamera wird verwendet.",interaction:"Ziehen zum Umschauen und zoomen; keine Layout- oder Installationsfreigabe."},
  ar:{title:"منظور الجامع",subtitle:"معاينة بمستوى العين من نقطة الجامع المقاسة مع أصول الحزم والتجهيزات من نفس المصدر.",previewOnly:"معاينة · ليست دليلاً ميدانياً",productAssets:"أصول العبوات",fixtureAssets:"أصول التجهيزات",assetCoverage:"تغطية الأصول",loading:"جارٍ إعداد منظور الجامع…",error:"تعذر عرض منظور الجامع.",noAnchor:"نقطة الجامع المقاسة غير متاحة؛ تم استخدام كاميرا بديلة.",interaction:"اسحب للنظر والتكبير؛ لا يمنح هذا المشهد صلاحية تخطيط أو تركيب."},
  fr:{title:"Vue Picker",subtitle:"Aperçu à hauteur des yeux depuis l'ancrage picker mesuré avec assets pack et fixture same-origin.",previewOnly:"APERÇU · PAS UNE PREUVE TERRAIN",productAssets:"Assets pack",fixtureAssets:"Assets fixture",assetCoverage:"Couverture assets",loading:"Préparation de la vue Picker…",error:"La vue Picker n'a pas pu être rendue.",noAnchor:"Ancrage picker mesuré indisponible ; caméra de secours utilisée.",interaction:"Glissez pour regarder et zoomer ; aucune autorité d'installation ou de layout."},
  es:{title:"Vista Picker",subtitle:"Vista a nivel de ojos desde el anclaje medido con assets de pack y fixture del mismo origen.",previewOnly:"VISTA PREVIA · NO ES EVIDENCIA DE CAMPO",productAssets:"Assets pack",fixtureAssets:"Assets fixture",assetCoverage:"Cobertura de assets",loading:"Preparando Vista Picker…",error:"No se pudo renderizar Vista Picker.",noAnchor:"No hay anclaje picker medido; se usa cámara alternativa.",interaction:"Arrastra para mirar y ampliar; no concede autoridad de layout o instalación."},
  it:{title:"Vista Picker",subtitle:"Anteprima ad altezza occhi dall'anchor picker misurato con asset pack e fixture same-origin.",previewOnly:"ANTEPRIMA · NON È PROVA SUL CAMPO",productAssets:"Asset pack",fixtureAssets:"Asset fixture",assetCoverage:"Copertura asset",loading:"Preparazione Vista Picker…",error:"Impossibile renderizzare Vista Picker.",noAnchor:"Anchor picker misurato non disponibile; usata camera di fallback.",interaction:"Trascina per guardare e zoomare; nessuna autorità di layout o installazione."},
  nl:{title:"Picker Eye",subtitle:"Ooghoogte-preview vanaf het gemeten picker-anker met same-origin pack- en fixture-assets.",previewOnly:"PREVIEW · GEEN VELDBEWIJS",productAssets:"Pack-assets",fixtureAssets:"Fixture-assets",assetCoverage:"Assetdekking",loading:"Picker Eye voorbereiden…",error:"Picker Eye kon niet worden weergegeven.",noAnchor:"Gemeten picker-anker ontbreekt; fallbackcamera gebruikt.",interaction:"Sleep om rond te kijken en zoom; geen layout- of installatiebevoegdheid."},
  pl:{title:"Widok Pickera",subtitle:"Podgląd z poziomu oczu od zmierzonego punktu pickera z assetami pack i fixture z tego samego źródła.",previewOnly:"PODGLĄD · TO NIE DOWÓD TERENOWY",productAssets:"Assety pack",fixtureAssets:"Assety fixture",assetCoverage:"Pokrycie assetów",loading:"Przygotowanie widoku pickera…",error:"Nie udało się wyrenderować widoku pickera.",noAnchor:"Brak zmierzonego punktu pickera; użyto kamery zastępczej.",interaction:"Przeciągaj, aby się rozglądać i przybliżać; brak uprawnień do layoutu lub instalacji."},
  "pt-BR":{title:"Visão do Picker",subtitle:"Prévia na altura dos olhos a partir do ponto medido do picker com assets de pack e fixture same-origin.",previewOnly:"PRÉVIA · NÃO É EVIDÊNCIA DE CAMPO",productAssets:"Assets de pack",fixtureAssets:"Assets de fixture",assetCoverage:"Cobertura de assets",loading:"Preparando Visão do Picker…",error:"Não foi possível renderizar a Visão do Picker.",noAnchor:"Ponto medido do picker indisponível; câmera alternativa usada.",interaction:"Arraste para olhar e ampliar; não concede autoridade de layout ou instalação."}
});

export function translatePlanogramPickerEye(locale,key){const table=MESSAGES[locale]||MESSAGES.en;return table[key]??MESSAGES.en[key]??key;}
export { MESSAGES as PLANOGRAM_PICKER_EYE_MESSAGES };
