const EN={title:"Uncertain scan regions",subtitle:"Low-confidence measured geometry must be confirmed or rejected before the reviewed draft can continue.",unresolved:"Unresolved",confirm:"Confirm",reject:"Reject",decision:"Decision",selectDecision:"Select decision",type:"Confirmed type",selectType:"Select type",typeRequired:"A confirmed uncertain region requires a valid type.",confidence:"Confidence",required:"Required",sourceType:"Detected type",reason:"Reason",reasonLow:"Below confidence threshold",reasonUnknown:"Unknown type requires classification",wall:"Wall",column:"Column",door:"Door",opening:"Opening",chiller:"Chiller",freezer:"Freezer",fixture:"Fixture",unknown:"Unknown",pending:"Pending review"};
const MESSAGES=Object.freeze({
 en:EN,
 tr:{title:"Belirsiz tarama bölgeleri",subtitle:"Düşük güvenli ölçülü geometri, incelenmiş taslak devam etmeden önce onaylanmalı veya reddedilmelidir.",unresolved:"Çözülmemiş",confirm:"Onayla",reject:"Reddet",decision:"Karar",selectDecision:"Karar seç",type:"Onaylanan tip",selectType:"Tip seç",typeRequired:"Onaylanan belirsiz bölge için geçerli bir tip gerekir.",confidence:"Güven",required:"Gerekli",sourceType:"Algılanan tip",reason:"Neden",reasonLow:"Güven eşiğinin altında",reasonUnknown:"Bilinmeyen tip sınıflandırma gerektiriyor",wall:"Duvar",column:"Kolon",door:"Kapı",opening:"Açıklık",chiller:"Soğutucu",freezer:"Dondurucu",fixture:"Fixture",unknown:"Bilinmeyen",pending:"İnceleme bekliyor"},
 de:{title:"Unsichere Scan-Bereiche",subtitle:"Geometrie mit niedriger Sicherheit muss bestätigt oder verworfen werden, bevor der geprüfte Entwurf fortgesetzt wird.",unresolved:"Ungelöst",confirm:"Bestätigen",reject:"Verwerfen",decision:"Entscheidung",selectDecision:"Entscheidung wählen",type:"Bestätigter Typ",selectType:"Typ wählen",typeRequired:"Ein bestätigter unsicherer Bereich benötigt einen gültigen Typ.",confidence:"Sicherheit",required:"Erforderlich",sourceType:"Erkannter Typ",reason:"Grund",reasonLow:"Unter Konfidenzschwelle",reasonUnknown:"Unbekannter Typ erfordert Klassifizierung",wall:"Wand",column:"Säule",door:"Tür",opening:"Öffnung",chiller:"Kühlmöbel",freezer:"Tiefkühler",fixture:"Fixture",unknown:"Unbekannt",pending:"Prüfung ausstehend"},
 ar:{title:"مناطق مسح غير مؤكدة",subtitle:"يجب تأكيد أو رفض الهندسة منخفضة الثقة قبل متابعة المسودة المراجعة.",unresolved:"غير محسوم",confirm:"تأكيد",reject:"رفض",decision:"القرار",selectDecision:"اختر القرار",type:"النوع المؤكد",selectType:"اختر النوع",typeRequired:"تتطلب المنطقة المؤكدة نوعاً صالحاً.",confidence:"الثقة",required:"المطلوب",sourceType:"النوع المكتشف",reason:"السبب",reasonLow:"أقل من حد الثقة",reasonUnknown:"نوع غير معروف يتطلب تصنيفاً",wall:"جدار",column:"عمود",door:"باب",opening:"فتحة",chiller:"مبرد",freezer:"مجمد",fixture:"تجهيز",unknown:"غير معروف",pending:"بانتظار المراجعة"},
 fr:{title:"Zones de scan incertaines",subtitle:"La géométrie mesurée à faible confiance doit être confirmée ou rejetée avant de poursuivre le brouillon revu.",unresolved:"Non résolu",confirm:"Confirmer",reject:"Rejeter",decision:"Décision",selectDecision:"Choisir une décision",type:"Type confirmé",selectType:"Choisir le type",typeRequired:"Une zone confirmée nécessite un type valide.",confidence:"Confiance",required:"Requis",sourceType:"Type détecté",reason:"Raison",reasonLow:"Sous le seuil de confiance",reasonUnknown:"Type inconnu à classifier",wall:"Mur",column:"Colonne",door:"Porte",opening:"Ouverture",chiller:"Réfrigérateur",freezer:"Congélateur",fixture:"Fixture",unknown:"Inconnu",pending:"Revue en attente"},
 es:{title:"Zonas de escaneo inciertas",subtitle:"La geometría de baja confianza debe confirmarse o rechazarse antes de continuar el borrador revisado.",unresolved:"Sin resolver",confirm:"Confirmar",reject:"Rechazar",decision:"Decisión",selectDecision:"Elegir decisión",type:"Tipo confirmado",selectType:"Elegir tipo",typeRequired:"Una zona confirmada requiere un tipo válido.",confidence:"Confianza",required:"Requerido",sourceType:"Tipo detectado",reason:"Motivo",reasonLow:"Por debajo del umbral",reasonUnknown:"Tipo desconocido requiere clasificación",wall:"Pared",column:"Columna",door:"Puerta",opening:"Apertura",chiller:"Refrigerador",freezer:"Congelador",fixture:"Fixture",unknown:"Desconocido",pending:"Revisión pendiente"},
 it:{title:"Zone di scansione incerte",subtitle:"La geometria a bassa confidenza deve essere confermata o rifiutata prima di continuare la bozza revisionata.",unresolved:"Non risolto",confirm:"Conferma",reject:"Rifiuta",decision:"Decisione",selectDecision:"Scegli decisione",type:"Tipo confermato",selectType:"Scegli tipo",typeRequired:"Una zona confermata richiede un tipo valido.",confidence:"Confidenza",required:"Richiesto",sourceType:"Tipo rilevato",reason:"Motivo",reasonLow:"Sotto la soglia",reasonUnknown:"Tipo sconosciuto da classificare",wall:"Parete",column:"Colonna",door:"Porta",opening:"Apertura",chiller:"Refrigeratore",freezer:"Congelatore",fixture:"Fixture",unknown:"Sconosciuto",pending:"Revisione in attesa"},
 nl:{title:"Onzekere scangebieden",subtitle:"Gemeten geometrie met lage zekerheid moet worden bevestigd of afgewezen voordat de beoordeelde versie verder kan.",unresolved:"Onopgelost",confirm:"Bevestigen",reject:"Afwijzen",decision:"Besluit",selectDecision:"Kies besluit",type:"Bevestigd type",selectType:"Kies type",typeRequired:"Een bevestigd onzeker gebied vereist een geldig type.",confidence:"Zekerheid",required:"Vereist",sourceType:"Gedetecteerd type",reason:"Reden",reasonLow:"Onder zekerheidsdrempel",reasonUnknown:"Onbekend type vereist classificatie",wall:"Muur",column:"Kolom",door:"Deur",opening:"Opening",chiller:"Koeling",freezer:"Vriezer",fixture:"Fixture",unknown:"Onbekend",pending:"Review vereist"},
 pl:{title:"Niepewne obszary skanu",subtitle:"Geometria o niskiej pewności musi zostać potwierdzona lub odrzucona przed kontynuacją szkicu.",unresolved:"Nierozwiązane",confirm:"Potwierdź",reject:"Odrzuć",decision:"Decyzja",selectDecision:"Wybierz decyzję",type:"Potwierdzony typ",selectType:"Wybierz typ",typeRequired:"Potwierdzony obszar wymaga prawidłowego typu.",confidence:"Pewność",required:"Wymagane",sourceType:"Wykryty typ",reason:"Powód",reasonLow:"Poniżej progu",reasonUnknown:"Nieznany typ wymaga klasyfikacji",wall:"Ściana",column:"Kolumna",door:"Drzwi",opening:"Otwór",chiller:"Chłodziarka",freezer:"Zamrażarka",fixture:"Fixture",unknown:"Nieznany",pending:"Oczekuje na przegląd"},
 "pt-BR":{title:"Regiões incertas do scan",subtitle:"A geometria medida com baixa confiança deve ser confirmada ou rejeitada antes de continuar o rascunho revisado.",unresolved:"Não resolvido",confirm:"Confirmar",reject:"Rejeitar",decision:"Decisão",selectDecision:"Escolher decisão",type:"Tipo confirmado",selectType:"Escolher tipo",typeRequired:"Uma região confirmada exige um tipo válido.",confidence:"Confiança",required:"Obrigatório",sourceType:"Tipo detectado",reason:"Motivo",reasonLow:"Abaixo do limite",reasonUnknown:"Tipo desconhecido exige classificação",wall:"Parede",column:"Coluna",door:"Porta",opening:"Abertura",chiller:"Refrigerador",freezer:"Freezer",fixture:"Fixture",unknown:"Desconhecido",pending:"Revisão pendente"}
});
export const PLANOGRAM_SCAN_UNCERTAINTY_MESSAGES=MESSAGES;
export function translatePlanogramScanUncertainty(locale,key){const table=MESSAGES[locale]||MESSAGES.en;return table[key]??MESSAGES.en[key]??key;}
