const M=Object.freeze({
 en:{catalogUpload:"Load attested fixture catalog",catalogNoFile:"No fixture catalog loaded",catalogLoaded:"Fixture catalog loaded: {name}",catalogFixture:"Catalog fixture",aisle:"Aisle",side:"Side",position:"Position",suggested:"Suggested match",ambiguous:"Multiple close matches",reviewRequired:"Human selection required",advancedImport:"Advanced: import completed binding JSON",interactiveReady:"Catalog-assisted binding ready",catalogInvalid:"Fixture catalog is invalid or contains unattested/incomplete records."},
 tr:{catalogUpload:"Onaylı fixture kataloğu yükle",catalogNoFile:"Fixture kataloğu yüklenmedi",catalogLoaded:"Fixture kataloğu yüklendi: {name}",catalogFixture:"Katalog fixture",aisle:"Koridor",side:"Taraf",position:"Pozisyon",suggested:"Önerilen eşleşme",ambiguous:"Birden fazla yakın eşleşme",reviewRequired:"İnsan seçimi gerekli",advancedImport:"Gelişmiş: tamamlanmış binding JSON içe aktar",interactiveReady:"Katalog destekli binding hazır",catalogInvalid:"Fixture kataloğu geçersiz veya attest edilmemiş/eksik kayıt içeriyor."},
 de:{catalogUpload:"Attestierten Fixture-Katalog laden",catalogNoFile:"Kein Fixture-Katalog geladen",catalogLoaded:"Fixture-Katalog geladen: {name}",catalogFixture:"Katalog-Fixture",aisle:"Gang",side:"Seite",position:"Position",suggested:"Vorgeschlagene Zuordnung",ambiguous:"Mehrere ähnliche Treffer",reviewRequired:"Menschliche Auswahl erforderlich",advancedImport:"Erweitert: fertiges Binding-JSON importieren",interactiveReady:"Kataloggestütztes Binding bereit",catalogInvalid:"Fixture-Katalog ist ungültig oder enthält unvollständige/nicht attestierte Einträge."},
 ar:{catalogUpload:"تحميل كتالوج التجهيزات الموثق",catalogNoFile:"لم يتم تحميل كتالوج تجهيزات",catalogLoaded:"تم تحميل الكتالوج: {name}",catalogFixture:"تجهيز الكتالوج",aisle:"الممر",side:"الجانب",position:"الموضع",suggested:"تطابق مقترح",ambiguous:"تطابقات متقاربة متعددة",reviewRequired:"يلزم اختيار بشري",advancedImport:"متقدم: استيراد JSON ربط مكتمل",interactiveReady:"الربط بمساعدة الكتالوج جاهز",catalogInvalid:"كتالوج التجهيزات غير صالح أو يحتوي سجلات ناقصة/غير موثقة."},
 fr:{catalogUpload:"Charger le catalogue fixtures attesté",catalogNoFile:"Aucun catalogue fixture chargé",catalogLoaded:"Catalogue fixture chargé : {name}",catalogFixture:"Fixture catalogue",aisle:"Allée",side:"Côté",position:"Position",suggested:"Correspondance suggérée",ambiguous:"Plusieurs correspondances proches",reviewRequired:"Sélection humaine requise",advancedImport:"Avancé : importer un binding JSON finalisé",interactiveReady:"Binding assisté par catalogue prêt",catalogInvalid:"Catalogue fixture invalide ou avec des entrées incomplètes/non attestées."},
 es:{catalogUpload:"Cargar catálogo de fixtures atestado",catalogNoFile:"No hay catálogo cargado",catalogLoaded:"Catálogo cargado: {name}",catalogFixture:"Fixture de catálogo",aisle:"Pasillo",side:"Lado",position:"Posición",suggested:"Coincidencia sugerida",ambiguous:"Varias coincidencias cercanas",reviewRequired:"Selección humana requerida",advancedImport:"Avanzado: importar binding JSON completado",interactiveReady:"Binding asistido por catálogo listo",catalogInvalid:"El catálogo es inválido o contiene registros incompletos/no atestados."},
 it:{catalogUpload:"Carica catalogo fixture attestato",catalogNoFile:"Nessun catalogo fixture caricato",catalogLoaded:"Catalogo fixture caricato: {name}",catalogFixture:"Fixture catalogo",aisle:"Corsia",side:"Lato",position:"Posizione",suggested:"Corrispondenza suggerita",ambiguous:"Più corrispondenze vicine",reviewRequired:"Selezione umana richiesta",advancedImport:"Avanzato: importa binding JSON completato",interactiveReady:"Binding assistito dal catalogo pronto",catalogInvalid:"Catalogo fixture non valido o con record incompleti/non attestati."},
 nl:{catalogUpload:"Geattesteerde fixturecatalogus laden",catalogNoFile:"Geen fixturecatalogus geladen",catalogLoaded:"Fixturecatalogus geladen: {name}",catalogFixture:"Catalogusfixture",aisle:"Gangpad",side:"Zijde",position:"Positie",suggested:"Voorgestelde match",ambiguous:"Meerdere nabije matches",reviewRequired:"Menselijke selectie vereist",advancedImport:"Geavanceerd: voltooide binding-JSON importeren",interactiveReady:"Catalogusgestuurde binding gereed",catalogInvalid:"Fixturecatalogus is ongeldig of bevat onvolledige/niet-geattesteerde records."},
 pl:{catalogUpload:"Wczytaj atestowany katalog fixture",catalogNoFile:"Nie wczytano katalogu fixture",catalogLoaded:"Katalog fixture wczytany: {name}",catalogFixture:"Fixture katalogowy",aisle:"Alejka",side:"Strona",position:"Pozycja",suggested:"Sugerowane dopasowanie",ambiguous:"Kilka podobnych dopasowań",reviewRequired:"Wymagany wybór człowieka",advancedImport:"Zaawansowane: importuj gotowy binding JSON",interactiveReady:"Binding wspomagany katalogiem gotowy",catalogInvalid:"Katalog fixture jest nieprawidłowy lub zawiera niepełne/nieatestowane rekordy."},
 "pt-BR":{catalogUpload:"Carregar catálogo de fixtures atestado",catalogNoFile:"Nenhum catálogo carregado",catalogLoaded:"Catálogo carregado: {name}",catalogFixture:"Fixture do catálogo",aisle:"Corredor",side:"Lado",position:"Posição",suggested:"Correspondência sugerida",ambiguous:"Várias correspondências próximas",reviewRequired:"Seleção humana obrigatória",advancedImport:"Avançado: importar binding JSON concluído",interactiveReady:"Binding assistido por catálogo pronto",catalogInvalid:"Catálogo de fixtures inválido ou com registros incompletos/não atestados."}
});
export function translatePlanogramFixtureCatalog(locale,key,params={}){const table=M[locale]||M.en;let value=table[key]??M.en[key]??key;for(const [name,replacement] of Object.entries(params))value=value.replaceAll(`{${name}}`,String(replacement));return value;}
export {M as PLANOGRAM_FIXTURE_CATALOG_MESSAGES};
