const MESSAGES=Object.freeze({
 en:{title:"Scanned Digital Twin",subtitle:"3D structural preview reconstructed from the fingerprint-bound reviewed scan.",previewOnly:"PREVIEW · NOT APPROVED STORE DNA",overview:"Overview",pickerView:"Picker view",loading:"Building scanned twin…",error:"Scanned twin could not be rendered.",measuredElements:"Measured elements",operationalZones:"Operational zones",fixtures:"Detected fixtures",boundary:"This scene proves only repository rendering of reviewed measurements; native-device accuracy and field acceptance remain required."},
 tr:{title:"Taranmış Dijital İkiz",subtitle:"Fingerprint'e bağlı incelenmiş taramadan yeniden oluşturulan 3D yapısal önizleme.",previewOnly:"ÖNİZLEME · ONAYLI STORE DNA DEĞİL",overview:"Genel görünüm",pickerView:"Picker görünümü",loading:"Taranmış ikiz oluşturuluyor…",error:"Taranmış ikiz oluşturulamadı.",measuredElements:"Ölçülmüş elemanlar",operationalZones:"Operasyon alanları",fixtures:"Algılanan fixture'lar",boundary:"Bu sahne yalnız incelenmiş ölçümlerin repository render kanıtıdır; native cihaz doğruluğu ve saha kabulü hâlâ gereklidir."},
 de:{title:"Gescannter Digital Twin",subtitle:"3D-Strukturvorschau aus dem fingerprint-gebundenen geprüften Scan.",previewOnly:"VORSCHAU · KEINE FREIGEGEBENE STORE DNA",overview:"Übersicht",pickerView:"Picker-Ansicht",loading:"Twin wird erstellt…",error:"Twin konnte nicht gerendert werden.",measuredElements:"Gemessene Elemente",operationalZones:"Betriebszonen",fixtures:"Erkannte Fixtures",boundary:"Nur Repository-Rendering geprüfter Messungen; Gerätegenauigkeit und Feldabnahme bleiben erforderlich."},
 ar:{title:"التوأم الرقمي الممسوح",subtitle:"معاينة هيكلية ثلاثية الأبعاد من المسح المراجع المرتبط بالبصمة.",previewOnly:"معاينة · ليست STORE DNA معتمدة",overview:"نظرة عامة",pickerView:"منظور الجامع",loading:"جارٍ بناء التوأم…",error:"تعذر عرض التوأم.",measuredElements:"عناصر مقاسة",operationalZones:"مناطق تشغيلية",fixtures:"تجهيزات مكتشفة",boundary:"هذا المشهد يثبت عرض القياسات المراجعة فقط؛ دقة الجهاز والقبول الميداني ما زالا مطلوبين."},
 fr:{title:"Digital Twin scanné",subtitle:"Aperçu structurel 3D reconstruit depuis le scan revu lié à son empreinte.",previewOnly:"APERÇU · STORE DNA NON APPROUVÉ",overview:"Vue générale",pickerView:"Vue picker",loading:"Construction du twin…",error:"Impossible de rendre le twin.",measuredElements:"Éléments mesurés",operationalZones:"Zones opérationnelles",fixtures:"Fixtures détectés",boundary:"Cette scène prouve uniquement le rendu des mesures revues ; précision native et validation terrain restent requises."},
 es:{title:"Gemelo Digital Escaneado",subtitle:"Vista estructural 3D reconstruida desde el escaneo revisado ligado a su huella.",previewOnly:"VISTA PREVIA · STORE DNA NO APROBADO",overview:"General",pickerView:"Vista picker",loading:"Creando gemelo…",error:"No se pudo renderizar el gemelo.",measuredElements:"Elementos medidos",operationalZones:"Zonas operativas",fixtures:"Fixtures detectados",boundary:"Solo demuestra renderizado de mediciones revisadas; precisión nativa y aceptación de campo siguen requeridas."},
 it:{title:"Digital Twin Scansionato",subtitle:"Anteprima strutturale 3D ricostruita dalla scansione revisionata legata al fingerprint.",previewOnly:"ANTEPRIMA · STORE DNA NON APPROVATO",overview:"Panoramica",pickerView:"Vista picker",loading:"Creazione twin…",error:"Impossibile renderizzare il twin.",measuredElements:"Elementi misurati",operationalZones:"Zone operative",fixtures:"Fixture rilevati",boundary:"Dimostra solo il rendering delle misure revisionate; accuratezza nativa e accettazione sul campo restano necessarie."},
 nl:{title:"Gescande Digital Twin",subtitle:"3D-structurele preview uit de fingerprint-gebonden beoordeelde scan.",previewOnly:"PREVIEW · GEEN GOEDGEKEURDE STORE DNA",overview:"Overzicht",pickerView:"Picker-weergave",loading:"Twin bouwen…",error:"Twin kon niet worden weergegeven.",measuredElements:"Gemeten elementen",operationalZones:"Operationele zones",fixtures:"Gedetecteerde fixtures",boundary:"Alleen renderingbewijs van beoordeelde metingen; apparaatnauwkeurigheid en veldacceptatie blijven vereist."},
 pl:{title:"Zeskanowany Digital Twin",subtitle:"Strukturalny podgląd 3D z przejrzanego skanu związanego fingerprintem.",previewOnly:"PODGLĄD · NIEZATWIERDZONE STORE DNA",overview:"Przegląd",pickerView:"Widok pickera",loading:"Budowanie twin…",error:"Nie udało się wyrenderować twin.",measuredElements:"Elementy zmierzone",operationalZones:"Strefy operacyjne",fixtures:"Wykryte fixture",boundary:"To tylko dowód renderowania przejrzanych pomiarów; dokładność urządzenia i akceptacja terenowa są nadal wymagane."},
 "pt-BR":{title:"Digital Twin Escaneado",subtitle:"Prévia estrutural 3D reconstruída do scan revisado vinculado ao fingerprint.",previewOnly:"PRÉVIA · STORE DNA NÃO APROVADO",overview:"Visão geral",pickerView:"Visão do picker",loading:"Construindo twin…",error:"Não foi possível renderizar o twin.",measuredElements:"Elementos medidos",operationalZones:"Zonas operacionais",fixtures:"Fixtures detectados",boundary:"Apenas prova o render das medições revisadas; precisão do dispositivo e aceitação de campo continuam obrigatórias."}
});
export function translatePlanogramScannedTwin(locale,key){const table=MESSAGES[locale]||MESSAGES.en;return table[key]??MESSAGES.en[key]??key;}
export {MESSAGES as PLANOGRAM_SCANNED_TWIN_MESSAGES};
