export const PLANOGRAM_SCENARIO_MESSAGES = Object.freeze({
  tr: {
    title: "Plan A/B/C/D karar portföyü", subtitle: "V5'in gerçek adaylarını operasyonel Pareto frontier üzerinde karşılaştır. Aynı plan birden fazla rolü kazanırsa kopyalanmaz.", previewOnly: "Senaryo önizlemesi · uygulama yetkisi yok", run: "Senaryo portföyünü üret", running: "V5 aday portföyü hesaplanıyor…", basketsRequired: "Senaryo portföyü için anonim sipariş sepetleri gerekir.", permissionRequired: "V5 senaryo araması için Planogram oluşturma yetkisi gerekir.", unavailable: "Bu aday veriyle karşılaştırılabilir V5 senaryo portföyü üretilemedi.", plan: "Plan", roles: "Karar rolleri", movedModules: "Taşınan modül", p95Route: "P95 rota", avgRoute: "Ort. rota", unplacedSales: "Yerleşmeyen satış ağırlığı", coverageShortfall: "Kapsama açığı", fingerprint: "Layout fingerprint", baseline: "Baseline / minimum değişiklik", engineSelected: "Motorun seçimi", fastestRoute: "En hızlı rota", qualityFirst: "Kalite ve kapsama öncelikli", frontier: "Pareto frontier", evaluated: "Değerlendirilen gerçek aday", frontierCount: "Frontier adayı", boundary: "Bu bounded arama global optimum, CAPEX karşılaştırması veya uygulama onayı değildir.", capexBoundary: "CAPEX bu portföyde kıyaslanmaz; finansal senaryo ayrı kaynaklı economics katmanında hesaplanır.", openTwin: "Bu planı twin'de aç", openingTwin: "Plan yeniden doğrulanıyor…", twinTitle: "Yeniden doğrulanmış senaryo twin'i", twinBoundary: "Bu twin yalnız server'ın aynı V5 aramasında yeniden ürettiği fingerprint eşleşmesinden çizilir; uygulama yetkisi vermez.", twinUnavailable: "Seçilen plan aynı V5 kanıtıyla yeniden doğrulanamadı.", selectedFingerprint: "Doğrulanan fingerprint",
  },
  en: {
    title: "Plan A/B/C/D decision portfolio", subtitle: "Compare real V5 candidates on an operational Pareto frontier. If one layout wins multiple roles, it is not duplicated.", previewOnly: "Scenario preview · no execution authority", run: "Generate scenario portfolio", running: "Calculating V5 candidate portfolio…", basketsRequired: "Anonymous order baskets are required for the scenario portfolio.", permissionRequired: "Planogram create permission is required for V5 scenario search.", unavailable: "A comparable V5 scenario portfolio could not be produced from this candidate data.", plan: "Plan", roles: "Decision roles", movedModules: "Moved modules", p95Route: "P95 route", avgRoute: "Avg. route", unplacedSales: "Weighted unplaced sales", coverageShortfall: "Coverage shortfall", fingerprint: "Layout fingerprint", baseline: "Baseline / minimum change", engineSelected: "Engine selected", fastestRoute: "Fastest route", qualityFirst: "Quality and coverage first", frontier: "Pareto frontier", evaluated: "Real candidates evaluated", frontierCount: "Frontier candidates", boundary: "This bounded search is not a global optimum, CAPEX comparison, or implementation approval.", capexBoundary: "CAPEX is not compared in this portfolio; financial scenarios are calculated separately in the sourced economics layer.", openTwin: "Open this plan in the twin", openingTwin: "Revalidating plan…", twinTitle: "Revalidated scenario twin", twinBoundary: "This twin renders only after the server reproduces the same fingerprint from the same V5 search; it grants no execution authority.", twinUnavailable: "The selected plan could not be revalidated from the same V5 evidence.", selectedFingerprint: "Validated fingerprint",
  },
  de: {
    title: "Plan-A/B/C/D-Entscheidungsportfolio", subtitle: "Vergleicht reale V5-Kandidaten auf einer operativen Pareto-Front. Gewinnt ein Layout mehrere Rollen, wird es nicht dupliziert.", previewOnly: "Szenariovorschau · keine Ausführungsautorität", run: "Szenarioportfolio erzeugen", running: "V5-Kandidatenportfolio wird berechnet…", basketsRequired: "Für das Szenarioportfolio sind anonymisierte Bestellkörbe erforderlich.", permissionRequired: "Für die V5-Szenariosuche ist die Planogram-Erstellberechtigung erforderlich.", unavailable: "Aus diesen Kandidatendaten konnte kein vergleichbares V5-Szenarioportfolio erzeugt werden.", plan: "Plan", roles: "Entscheidungsrollen", movedModules: "Verschobene Module", p95Route: "P95-Route", avgRoute: "Ø Route", unplacedSales: "Gewichteter nicht platzierter Umsatz", coverageShortfall: "Abdeckungslücke", fingerprint: "Layout-Fingerprint", baseline: "Baseline / minimale Änderung", engineSelected: "Engine-Auswahl", fastestRoute: "Schnellste Route", qualityFirst: "Qualität und Abdeckung zuerst", frontier: "Pareto-Front", evaluated: "Bewertete reale Kandidaten", frontierCount: "Frontier-Kandidaten", boundary: "Diese begrenzte Suche ist weder globales Optimum noch CAPEX-Vergleich oder Umsetzungsfreigabe.", capexBoundary: "CAPEX wird hier nicht verglichen; Finanzszenarien werden separat in der belegten Economics-Schicht berechnet.", openTwin: "Diesen Plan im Twin öffnen", openingTwin: "Plan wird erneut validiert…", twinTitle: "Erneut validierter Szenario-Twin", twinBoundary: "Der Twin wird nur dargestellt, wenn der Server denselben Fingerprint aus derselben V5-Suche reproduziert; keine Ausführungsautorität.", twinUnavailable: "Der ausgewählte Plan konnte mit denselben V5-Nachweisen nicht erneut validiert werden.", selectedFingerprint: "Validierter Fingerprint",
  },
  ar: {
    title: "محفظة القرار Plan A/B/C/D", subtitle: "قارن مرشحي V5 الحقيقيين على جبهة باريتو تشغيلية. إذا فاز مخطط واحد بأكثر من دور فلا يتم تكراره.", previewOnly: "معاينة سيناريو · دون صلاحية تنفيذ", run: "إنشاء محفظة السيناريوهات", running: "يتم حساب محفظة مرشحي V5…", basketsRequired: "يلزم وجود سلال طلبات مجهولة الهوية لمحفظة السيناريوهات.", permissionRequired: "يلزم إذن إنشاء Planogram للبحث في سيناريوهات V5.", unavailable: "تعذر إنتاج محفظة سيناريوهات V5 قابلة للمقارنة من هذه البيانات.", plan: "الخطة", roles: "أدوار القرار", movedModules: "الوحدات المنقولة", p95Route: "مسار P95", avgRoute: "متوسط المسار", unplacedSales: "المبيعات المرجحة غير الموزعة", coverageShortfall: "فجوة التغطية", fingerprint: "بصمة المخطط", baseline: "الأساس / أقل تغيير", engineSelected: "اختيار المحرك", fastestRoute: "أسرع مسار", qualityFirst: "الجودة والتغطية أولاً", frontier: "جبهة باريتو", evaluated: "مرشحون حقيقيون تم تقييمهم", frontierCount: "مرشحو الجبهة", boundary: "هذا البحث المحدود ليس أمثلية عالمية ولا مقارنة CAPEX ولا موافقة تنفيذ.", capexBoundary: "لا تتم مقارنة CAPEX هنا؛ تُحسب السيناريوهات المالية بشكل منفصل في طبقة economics المسندة بالمصادر.", openTwin: "افتح هذه الخطة في التوأم", openingTwin: "إعادة التحقق من الخطة…", twinTitle: "توأم السيناريو المعاد التحقق منه", twinBoundary: "يُعرض التوأم فقط بعد أن يعيد الخادم إنتاج البصمة نفسها من بحث V5 نفسه، دون منح صلاحية تنفيذ.", twinUnavailable: "تعذر إعادة التحقق من الخطة المختارة بنفس أدلة V5.", selectedFingerprint: "البصمة المتحققة",
  },
  fr: {
    title: "Portefeuille de décision Plan A/B/C/D", subtitle: "Compare les candidats V5 réels sur une frontière de Pareto opérationnelle. Un même layout gagnant plusieurs rôles n'est pas dupliqué.", previewOnly: "Aperçu scénario · aucune autorité d'exécution", run: "Générer le portefeuille de scénarios", running: "Calcul du portefeuille V5…", basketsRequired: "Des paniers anonymisés sont requis pour le portefeuille de scénarios.", permissionRequired: "La permission de création Planogram est requise pour la recherche V5.", unavailable: "Aucun portefeuille V5 comparable n'a pu être produit avec ces données.", plan: "Plan", roles: "Rôles de décision", movedModules: "Modules déplacés", p95Route: "Trajet P95", avgRoute: "Trajet moyen", unplacedSales: "Ventes non placées pondérées", coverageShortfall: "Écart de couverture", fingerprint: "Empreinte layout", baseline: "Baseline / changement minimal", engineSelected: "Sélection moteur", fastestRoute: "Trajet le plus rapide", qualityFirst: "Qualité et couverture prioritaires", frontier: "Frontière de Pareto", evaluated: "Candidats réels évalués", frontierCount: "Candidats frontière", boundary: "Cette recherche bornée n'est ni un optimum global, ni une comparaison CAPEX, ni une approbation d'exécution.", capexBoundary: "Le CAPEX n'est pas comparé ici; les scénarios financiers sont calculés séparément dans la couche economics sourcée.", openTwin: "Ouvrir ce plan dans le twin", openingTwin: "Revalidation du plan…", twinTitle: "Twin de scénario revalidé", twinBoundary: "Le twin n'est rendu qu'après reproduction du même fingerprint par le serveur à partir de la même recherche V5; aucune autorité d'exécution.", twinUnavailable: "Le plan choisi n'a pas pu être revalidé avec les mêmes preuves V5.", selectedFingerprint: "Fingerprint validé",
  },
  es: {
    title: "Portafolio de decisión Plan A/B/C/D", subtitle: "Compara candidatos V5 reales en una frontera de Pareto operativa. Si un layout gana varios roles, no se duplica.", previewOnly: "Vista previa · sin autoridad de ejecución", run: "Generar portafolio de escenarios", running: "Calculando portafolio V5…", basketsRequired: "Se requieren cestas de pedido anónimas para el portafolio.", permissionRequired: "Se requiere permiso de creación de Planogram para la búsqueda V5.", unavailable: "No se pudo producir un portafolio V5 comparable con estos datos.", plan: "Plan", roles: "Roles de decisión", movedModules: "Módulos movidos", p95Route: "Ruta P95", avgRoute: "Ruta media", unplacedSales: "Ventas no ubicadas ponderadas", coverageShortfall: "Brecha de cobertura", fingerprint: "Huella del layout", baseline: "Baseline / cambio mínimo", engineSelected: "Selección del motor", fastestRoute: "Ruta más rápida", qualityFirst: "Calidad y cobertura primero", frontier: "Frontera de Pareto", evaluated: "Candidatos reales evaluados", frontierCount: "Candidatos de frontera", boundary: "Esta búsqueda acotada no es un óptimo global, comparación CAPEX ni aprobación de implementación.", capexBoundary: "CAPEX no se compara aquí; los escenarios financieros se calculan por separado en la capa economics con fuentes.", openTwin: "Abrir este plan en el twin", openingTwin: "Revalidando el plan…", twinTitle: "Twin de escenario revalidado", twinBoundary: "El twin solo se muestra cuando el servidor reproduce el mismo fingerprint desde la misma búsqueda V5; no otorga autoridad de ejecución.", twinUnavailable: "El plan seleccionado no pudo revalidarse con la misma evidencia V5.", selectedFingerprint: "Fingerprint validado",
  },
  it: {
    title: "Portafoglio decisionale Plan A/B/C/D", subtitle: "Confronta candidati V5 reali su una frontiera di Pareto operativa. Un layout che vince più ruoli non viene duplicato.", previewOnly: "Anteprima scenario · nessuna autorità di esecuzione", run: "Genera portafoglio scenari", running: "Calcolo del portafoglio V5…", basketsRequired: "Per il portafoglio servono panieri ordine anonimizzati.", permissionRequired: "Per la ricerca V5 serve il permesso di creazione Planogram.", unavailable: "Non è stato possibile produrre un portafoglio V5 confrontabile con questi dati.", plan: "Plan", roles: "Ruoli decisionali", movedModules: "Moduli spostati", p95Route: "Percorso P95", avgRoute: "Percorso medio", unplacedSales: "Vendite non collocate ponderate", coverageShortfall: "Gap di copertura", fingerprint: "Fingerprint layout", baseline: "Baseline / minimo cambiamento", engineSelected: "Scelta motore", fastestRoute: "Percorso più rapido", qualityFirst: "Qualità e copertura prima", frontier: "Frontiera di Pareto", evaluated: "Candidati reali valutati", frontierCount: "Candidati di frontiera", boundary: "Questa ricerca limitata non è un ottimo globale, un confronto CAPEX o un'approvazione esecutiva.", capexBoundary: "Il CAPEX non è confrontato qui; gli scenari finanziari sono calcolati separatamente nel livello economics con fonti.", openTwin: "Apri questo piano nel twin", openingTwin: "Rivalidazione del piano…", twinTitle: "Twin dello scenario rivalidato", twinBoundary: "Il twin viene mostrato solo se il server riproduce lo stesso fingerprint dalla stessa ricerca V5; nessuna autorità esecutiva.", twinUnavailable: "Il piano selezionato non è stato rivalidato con la stessa evidenza V5.", selectedFingerprint: "Fingerprint validato",
  },
  nl: {
    title: "Plan A/B/C/D-beslisportfolio", subtitle: "Vergelijk echte V5-kandidaten op een operationeel Pareto-front. Eén layout met meerdere winnende rollen wordt niet gedupliceerd.", previewOnly: "Scenariopreview · geen uitvoeringsbevoegdheid", run: "Scenariportfolio genereren", running: "V5-kandidatenportfolio wordt berekend…", basketsRequired: "Geanonimiseerde ordermandjes zijn vereist voor het portfolio.", permissionRequired: "Planogram-aanmaakrecht is vereist voor V5-scenariozoekwerk.", unavailable: "Met deze data kon geen vergelijkbaar V5-scenarioportfolio worden gemaakt.", plan: "Plan", roles: "Beslisrollen", movedModules: "Verplaatste modules", p95Route: "P95-route", avgRoute: "Gem. route", unplacedSales: "Gewogen niet-geplaatste verkoop", coverageShortfall: "Dekkingstekort", fingerprint: "Layout-fingerprint", baseline: "Baseline / minimale wijziging", engineSelected: "Engine-selectie", fastestRoute: "Snelste route", qualityFirst: "Kwaliteit en dekking eerst", frontier: "Pareto-front", evaluated: "Beoordeelde echte kandidaten", frontierCount: "Frontier-kandidaten", boundary: "Deze begrensde zoekactie is geen globaal optimum, CAPEX-vergelijking of uitvoeringsgoedkeuring.", capexBoundary: "CAPEX wordt hier niet vergeleken; financiële scenario's worden apart berekend in de brongebonden economics-laag.", openTwin: "Open dit plan in de twin", openingTwin: "Plan wordt opnieuw gevalideerd…", twinTitle: "Opnieuw gevalideerde scenario-twin", twinBoundary: "De twin wordt alleen getoond nadat de server dezelfde fingerprint uit dezelfde V5-zoekopdracht reproduceert; geen uitvoeringsbevoegdheid.", twinUnavailable: "Het gekozen plan kon niet met hetzelfde V5-bewijs opnieuw worden gevalideerd.", selectedFingerprint: "Gevalideerde fingerprint",
  },
  pl: {
    title: "Portfel decyzji Plan A/B/C/D", subtitle: "Porównuje rzeczywistych kandydatów V5 na operacyjnym froncie Pareto. Jeden layout wygrywający kilka ról nie jest duplikowany.", previewOnly: "Podgląd scenariusza · bez uprawnień wykonawczych", run: "Utwórz portfel scenariuszy", running: "Obliczanie portfela V5…", basketsRequired: "Do portfela wymagane są anonimowe koszyki zamówień.", permissionRequired: "Wyszukiwanie V5 wymaga uprawnienia tworzenia Planogram.", unavailable: "Nie udało się utworzyć porównywalnego portfela V5 z tych danych.", plan: "Plan", roles: "Role decyzyjne", movedModules: "Przeniesione moduły", p95Route: "Trasa P95", avgRoute: "Śr. trasa", unplacedSales: "Ważona sprzedaż nieumieszczona", coverageShortfall: "Luka pokrycia", fingerprint: "Fingerprint layoutu", baseline: "Baseline / minimalna zmiana", engineSelected: "Wybór silnika", fastestRoute: "Najszybsza trasa", qualityFirst: "Jakość i pokrycie najpierw", frontier: "Front Pareto", evaluated: "Ocenieni rzeczywiści kandydaci", frontierCount: "Kandydaci frontu", boundary: "To ograniczone wyszukiwanie nie jest globalnym optimum, porównaniem CAPEX ani zgodą na wdrożenie.", capexBoundary: "CAPEX nie jest tu porównywany; scenariusze finansowe są liczone osobno w źródłowej warstwie economics.", openTwin: "Otwórz ten plan w twinie", openingTwin: "Ponowna walidacja planu…", twinTitle: "Ponownie zwalidowany twin scenariusza", twinBoundary: "Twin jest wyświetlany tylko po odtworzeniu przez serwer tego samego fingerprintu z tego samego wyszukiwania V5; bez uprawnień wykonawczych.", twinUnavailable: "Wybrany plan nie mógł zostać ponownie zwalidowany z tym samym dowodem V5.", selectedFingerprint: "Zwalidowany fingerprint",
  },
  "pt-BR": {
    title: "Portfólio de decisão Plan A/B/C/D", subtitle: "Compara candidatos V5 reais em uma fronteira de Pareto operacional. Um layout que vence vários papéis não é duplicado.", previewOnly: "Prévia de cenário · sem autoridade de execução", run: "Gerar portfólio de cenários", running: "Calculando portfólio V5…", basketsRequired: "Cestas de pedido anonimizadas são necessárias para o portfólio.", permissionRequired: "A busca V5 exige permissão de criação de Planogram.", unavailable: "Não foi possível produzir um portfólio V5 comparável com estes dados.", plan: "Plan", roles: "Papéis de decisão", movedModules: "Módulos movidos", p95Route: "Rota P95", avgRoute: "Rota média", unplacedSales: "Vendas não alocadas ponderadas", coverageShortfall: "Lacuna de cobertura", fingerprint: "Fingerprint do layout", baseline: "Baseline / mudança mínima", engineSelected: "Escolha do motor", fastestRoute: "Rota mais rápida", qualityFirst: "Qualidade e cobertura primeiro", frontier: "Fronteira de Pareto", evaluated: "Candidatos reais avaliados", frontierCount: "Candidatos da fronteira", boundary: "Esta busca limitada não é ótimo global, comparação CAPEX nem aprovação de implementação.", capexBoundary: "CAPEX não é comparado aqui; os cenários financeiros são calculados separadamente na camada economics com fontes.", openTwin: "Abrir este plano no twin", openingTwin: "Revalidando o plano…", twinTitle: "Twin de cenário revalidado", twinBoundary: "O twin só é exibido quando o servidor reproduz o mesmo fingerprint a partir da mesma busca V5; não concede autoridade de execução.", twinUnavailable: "O plano selecionado não pôde ser revalidado com a mesma evidência V5.", selectedFingerprint: "Fingerprint validado",
  },
});

export function translatePlanogramScenario(locale, key, params = {}) {
  const message = PLANOGRAM_SCENARIO_MESSAGES[locale]?.[key];
  const fallback = PLANOGRAM_SCENARIO_MESSAGES.en[key];
  const template = typeof message === "string" ? message : fallback || key;
  return template.replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}
