const en = { eyebrow: "OPEN SHIFT MARKETPLACE", title: "Publish governed capacity", detail: "Create capacity that employees can claim only after eligibility is rechecked.", warehouse: "Warehouse", date: "Date", start: "Start", end: "End", breakMinutes: "Break (min)", role: "Role", capacity: "Capacity", note: "Manager note", publish: "Publish open shift", publishing: "Publishing…", published: "Open shift published.", permission: "Open-shift publishing requires create-shift authority.", loadError: "Workforce locations could not be loaded.", created: "Published offer", remaining: "{count} place(s)", rule: "The canonical shift engine rechecks employment, leave, daily maximum and minimum rest again when an employee claims this offer." };
const tr = { ...en, eyebrow: "AÇIK VARDİYA PAZARI", title: "Yönetişimli kapasite yayınla", detail: "Çalışanın ancak uygunluk kuralları yeniden doğrulandıktan sonra alabileceği vardiya kontenjanı oluştur.", warehouse: "Depo", date: "Tarih", start: "Başlangıç", end: "Bitiş", breakMinutes: "Mola (dk)", role: "Rol", capacity: "Kontenjan", note: "Yönetici notu", publish: "Açık vardiyayı yayınla", publishing: "Yayınlanıyor…", published: "Açık vardiya yayınlandı.", permission: "Açık vardiya yayınlamak için vardiya oluşturma yetkisi gerekir.", loadError: "Workforce depo verileri yüklenemedi.", created: "Yayınlanan teklif", remaining: "{count} kontenjan", rule: "Çalışan bu vardiyayı alırken Employee Master, izin, günlük azami çalışma ve minimum dinlenme kuralları canonical vardiya motorunda yeniden doğrulanır." };
const de = { ...en, eyebrow: "MARKTPLATZ FÜR OFFENE SCHICHTEN", title: "Gesteuerte Kapazität veröffentlichen", warehouse: "Lager", date: "Datum", start: "Beginn", end: "Ende", breakMinutes: "Pause (Min.)", role: "Rolle", capacity: "Kapazität", note: "Manager-Notiz", publish: "Offene Schicht veröffentlichen", publishing: "Veröffentlichen…", published: "Offene Schicht veröffentlicht.", permission: "Zum Veröffentlichen ist die Berechtigung zum Erstellen von Schichten erforderlich." };
const ar = { ...en, eyebrow: "سوق المناوبات المفتوحة", title: "نشر سعة محكومة", warehouse: "المستودع", date: "التاريخ", start: "البداية", end: "النهاية", breakMinutes: "الاستراحة (دقيقة)", role: "الدور", capacity: "السعة", note: "ملاحظة المدير", publish: "نشر المناوبة", publishing: "جارٍ النشر…", published: "تم نشر المناوبة المفتوحة.", permission: "يتطلب النشر صلاحية إنشاء المناوبات." };
const fr = { ...en, eyebrow: "MARCHÉ DES QUARTS OUVERTS", title: "Publier une capacité gouvernée", warehouse: "Dépôt", date: "Date", start: "Début", end: "Fin", breakMinutes: "Pause (min)", role: "Rôle", capacity: "Capacité", note: "Note manager", publish: "Publier le quart", publishing: "Publication…", published: "Quart ouvert publié.", permission: "La publication requiert l'autorisation de créer des quarts." };
const es = { ...en, eyebrow: "MERCADO DE TURNOS ABIERTOS", title: "Publicar capacidad gobernada", warehouse: "Almacén", date: "Fecha", start: "Inicio", end: "Fin", breakMinutes: "Pausa (min)", role: "Rol", capacity: "Capacidad", note: "Nota del responsable", publish: "Publicar turno", publishing: "Publicando…", published: "Turno abierto publicado.", permission: "Publicar requiere permiso para crear turnos." };
const it = { ...en, eyebrow: "MERCATO TURNI APERTI", title: "Pubblica capacità governata", warehouse: "Deposito", date: "Data", start: "Inizio", end: "Fine", breakMinutes: "Pausa (min)", role: "Ruolo", capacity: "Capacità", note: "Nota manager", publish: "Pubblica turno", publishing: "Pubblicazione…", published: "Turno aperto pubblicato.", permission: "La pubblicazione richiede l'autorizzazione a creare turni." };
const nl = { ...en, eyebrow: "MARKTPLAATS OPEN DIENSTEN", title: "Beheerde capaciteit publiceren", warehouse: "Depot", date: "Datum", start: "Start", end: "Einde", breakMinutes: "Pauze (min)", role: "Rol", capacity: "Capaciteit", note: "Manager-notitie", publish: "Open dienst publiceren", publishing: "Publiceren…", published: "Open dienst gepubliceerd.", permission: "Publiceren vereist toestemming om diensten te maken." };
const pl = { ...en, eyebrow: "RYNEK OTWARTYCH ZMIAN", title: "Opublikuj zarządzaną pojemność", warehouse: "Magazyn", date: "Data", start: "Start", end: "Koniec", breakMinutes: "Przerwa (min)", role: "Rola", capacity: "Pojemność", note: "Notatka managera", publish: "Opublikuj zmianę", publishing: "Publikowanie…", published: "Otwarta zmiana opublikowana.", permission: "Publikowanie wymaga uprawnienia do tworzenia zmian." };
const ptBR = { ...en, eyebrow: "MERCADO DE TURNOS ABERTOS", title: "Publicar capacidade governada", warehouse: "Depósito", date: "Data", start: "Início", end: "Fim", breakMinutes: "Intervalo (min)", role: "Função", capacity: "Capacidade", note: "Nota do gestor", publish: "Publicar turno aberto", publishing: "Publicando…", published: "Turno aberto publicado.", permission: "Publicar exige permissão para criar turnos." };
const MESSAGES = { tr, en, de, ar, fr, es, it, nl, pl, "pt-BR": ptBR };
export function workforceFlexibilityAdminMessage(locale, key, params = {}) {
  const dictionary = MESSAGES[locale] || MESSAGES.en;
  const template = dictionary[key] || MESSAGES.en[key] || key;
  return String(template).replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}
