const en = {
  eyebrow: "INTRADAY WORKFORCE COMMAND",
  title: "Workforce Command Center",
  detail: "One governed view of demand, capacity, schedule, attendance, pressure and approved what-if evidence.",
  worksite: "Worksite", refresh: "Refresh", loading: "Loading governed interval…", error: "Command Center authority is unavailable.", noLocations: "No authorized worksite is available.",
  current: "Current interval", past: "Past governed interval", future: "Future governed interval", intervalWidth: "{minutes}-minute authority", observedAt: "Observed {time}",
  liveTruth: "Current interval — live label permitted", staleTruth: "Not current — live label blocked", truthBoundary: "Repository evidence is not field or production proof.",
  demand: "Demand", scheduled: "Scheduled", effective: "Effective capacity", gap: "Capacity gap", scheduledPeople: "Scheduled people", present: "Present now", attendanceStarted: "Attendance started", noShow: "No-show", breaks: "Active breaks", skillDeficit: "Skill deficit", dpi: "Demand pressure index", rootCause: "Root cause", kpiPressure: "KPI pressure",
  operations: "Intraday operations", authority: "Authority lineage", actions: "Manager action queue", noActions: "No governed action is required for this interval.", humanApproval: "Human approval required", automaticOff: "Automatic schedule apply is off", replan: "Latest coherent replan", replanNone: "No replan scenario is bound to this DPI baseline.", recommendation: "Recommendation", costDelta: "Estimated cost delta", modelEvidence: "Model evidence", people: "people", manHours: "MH", count: "{count}",
  AUTHORITY_INTERVAL_NOT_CURRENT_TITLE: "Governed interval is not current", AUTHORITY_INTERVAL_NOT_CURRENT_DETAIL: "Refresh demand/capacity/DPI evidence before treating this screen as live operations.",
  SCHEDULE_SNAPSHOT_DRIFT_TITLE: "Schedule and capacity snapshot differ", SCHEDULE_SNAPSHOT_DRIFT_DETAIL: "Canonical schedule projection changed after the capacity snapshot; refresh capacity authority.",
  CAPACITY_SHORTAGE_TITLE: "Capacity shortage detected", CAPACITY_SHORTAGE_DETAIL: "Governed demand exceeds effective capacity. Review staffing options without bypassing hard rules.",
  SKILL_DEFICIT_TITLE: "Skill coverage gap", SKILL_DEFICIT_DETAIL: "The capacity authority reports skill-feasible hours below required coverage.",
  NO_SHOW_TITLE: "Scheduled attendance missing", NO_SHOW_DETAIL: "{count} scheduled shift(s) passed start time without a matching attendance start.",
  DAILY_LIMIT_BREACH_TITLE: "Daily work limit breach", DAILY_LIMIT_BREACH_DETAIL: "{count} employee schedule(s) exceed the effective canonical daily work limit.",
  REST_RULE_BREACH_TITLE: "Minimum rest breach", REST_RULE_BREACH_DETAIL: "{count} employee schedule(s) violate the effective between-shift rest rule.",
  KPI_PRESSURE_TITLE: "Operational KPI pressure", KPI_PRESSURE_DETAIL: "{count} governed KPI observation(s) are outside their approved target direction.",
  PENDING_REPLAN_TITLE: "Replan review required", PENDING_REPLAN_DETAIL: "A coherent what-if proposal exists and remains human-approved only.",
  PENDING_SHIFT_TRADE_TITLE: "Shift trade decisions waiting", PENDING_SHIFT_TRADE_DETAIL: "{count} employee-accepted trade(s) are waiting for manager approval.",
};

const tr = {
  ...en,
  eyebrow: "GÜN İÇİ WORKFORCE KOMUTA", title: "Workforce Komuta Merkezi", detail: "Talep, kapasite, vardiya, puantaj, baskı ve onaylı what-if kanıtını tek yönetişimli görünümde birleştirir.",
  worksite: "Çalışma noktası", refresh: "Yenile", loading: "Yönetişimli interval yükleniyor…", error: "Komuta Merkezi authority verisi kullanılamıyor.", noLocations: "Yetkili çalışma noktası bulunamadı.",
  current: "Güncel interval", past: "Geçmiş yönetişimli interval", future: "Gelecek yönetişimli interval", intervalWidth: "{minutes} dakikalık authority", observedAt: "Gözlem {time}",
  liveTruth: "Güncel interval — canlı etiketi kullanılabilir", staleTruth: "Güncel değil — canlı etiketi kapalı", truthBoundary: "Repository kanıtı saha veya production kanıtı değildir.",
  demand: "Talep", scheduled: "Planlanan", effective: "Efektif kapasite", gap: "Kapasite açığı", scheduledPeople: "Planlı çalışan", present: "Şu an mevcut", attendanceStarted: "Puantaj başlatan", noShow: "Gelmedi", breaks: "Aktif mola", skillDeficit: "Yetkinlik açığı", dpi: "Talep baskı endeksi", rootCause: "Kök neden", kpiPressure: "KPI baskısı",
  operations: "Gün içi operasyon", authority: "Authority lineage", actions: "Yönetici aksiyon kuyruğu", noActions: "Bu interval için yönetişimli aksiyon gerekmiyor.", humanApproval: "İnsan onayı zorunlu", automaticOff: "Otomatik vardiya uygulama kapalı", replan: "Aynı baseline'a bağlı replan", replanNone: "Bu DPI baseline'ına bağlı replan senaryosu yok.", recommendation: "Öneri", costDelta: "Tahmini maliyet farkı", modelEvidence: "Model kanıtı", people: "kişi", manHours: "KS", count: "{count}",
  AUTHORITY_INTERVAL_NOT_CURRENT_TITLE: "Yönetişimli interval güncel değil", AUTHORITY_INTERVAL_NOT_CURRENT_DETAIL: "Bu ekran canlı operasyon olarak kullanılmadan önce demand/capacity/DPI kanıtı yenilenmeli.",
  SCHEDULE_SNAPSHOT_DRIFT_TITLE: "Vardiya ile kapasite snapshot'ı farklı", SCHEDULE_SNAPSHOT_DRIFT_DETAIL: "Canonical vardiya projeksiyonu kapasite snapshot'ından sonra değişti; kapasite authority yenilenmeli.",
  CAPACITY_SHORTAGE_TITLE: "Kapasite açığı tespit edildi", CAPACITY_SHORTAGE_DETAIL: "Yönetişimli talep efektif kapasitenin üzerinde. Sert kuralları aşmadan personel seçeneklerini incele.",
  SKILL_DEFICIT_TITLE: "Yetkinlik kapsama açığı", SKILL_DEFICIT_DETAIL: "Kapasite authority, yetkinlikle karşılanabilen saatlerin gerekli kapsamın altında olduğunu gösteriyor.",
  NO_SHOW_TITLE: "Planlı çalışan puantaj başlatmadı", NO_SHOW_DETAIL: "{count} vardiyanın başlangıç saati geçti ve eşleşen puantaj başlangıcı yok.",
  DAILY_LIMIT_BREACH_TITLE: "Günlük çalışma limiti ihlali", DAILY_LIMIT_BREACH_DETAIL: "{count} çalışan planı yürürlükteki canonical günlük çalışma limitini aşıyor.",
  REST_RULE_BREACH_TITLE: "Minimum dinlenme ihlali", REST_RULE_BREACH_DETAIL: "{count} çalışan planı vardiyalar arası yürürlükteki dinlenme kuralını ihlal ediyor.",
  KPI_PRESSURE_TITLE: "Operasyon KPI baskısı", KPI_PRESSURE_DETAIL: "{count} yönetişimli KPI gözlemi onaylı hedef yönünün dışında.",
  PENDING_REPLAN_TITLE: "Replan incelemesi gerekli", PENDING_REPLAN_DETAIL: "Aynı baseline'a bağlı what-if önerisi mevcut ve yalnız insan onayıyla ilerleyebilir.",
  PENDING_SHIFT_TRADE_TITLE: "Vardiya takası kararı bekliyor", PENDING_SHIFT_TRADE_DETAIL: "{count} çalışan-kabul edilmiş takas yönetici kararını bekliyor.",
};

const de = { ...en, eyebrow: "INTRADAY WORKFORCE COMMAND", title: "Workforce-Kommandozentrale", detail: "Eine gesteuerte Sicht auf Bedarf, Kapazität, Schichten, Anwesenheit und Druck.", worksite: "Standort", refresh: "Aktualisieren", loading: "Gesteuertes Intervall wird geladen…", error: "Die Command-Center-Autorität ist nicht verfügbar.", noLocations: "Kein berechtigter Standort verfügbar.", current: "Aktuelles Intervall", past: "Vergangenes Intervall", future: "Zukünftiges Intervall", liveTruth: "Aktuelles Intervall — Live-Kennzeichnung zulässig", staleTruth: "Nicht aktuell — Live-Kennzeichnung gesperrt", truthBoundary: "Repository-Nachweise sind kein Feld- oder Produktionsnachweis.", actions: "Aktionsliste für Führungskräfte", humanApproval: "Menschliche Freigabe erforderlich", automaticOff: "Automatische Schichtanwendung ist aus", noActions: "Für dieses Intervall ist keine gesteuerte Aktion erforderlich." };
const ar = { ...en, eyebrow: "قيادة القوى العاملة خلال اليوم", title: "مركز قيادة القوى العاملة", detail: "عرض محكوم يجمع الطلب والسعة والورديات والحضور والضغط.", worksite: "موقع العمل", refresh: "تحديث", loading: "جارٍ تحميل الفترة المحكومة…", error: "سلطة مركز القيادة غير متاحة.", noLocations: "لا يوجد موقع عمل مخول.", current: "الفترة الحالية", past: "فترة محكومة سابقة", future: "فترة محكومة مستقبلية", liveTruth: "الفترة الحالية — يمكن استخدام وصف مباشر", staleTruth: "ليست حالية — الوصف المباشر محجوب", truthBoundary: "دليل المستودع ليس دليلاً ميدانياً أو إنتاجياً.", actions: "قائمة إجراءات المدير", humanApproval: "موافقة بشرية مطلوبة", automaticOff: "التطبيق التلقائي للورديات متوقف", noActions: "لا يوجد إجراء محكوم مطلوب لهذه الفترة." };
const fr = { ...en, title: "Centre de commandement Workforce", detail: "Vue gouvernée de la demande, capacité, planning, présence et pression.", worksite: "Site", refresh: "Actualiser", loading: "Chargement de l’intervalle gouverné…", error: "L’autorité du centre de commandement est indisponible.", noLocations: "Aucun site autorisé.", current: "Intervalle actuel", past: "Intervalle gouverné passé", future: "Intervalle gouverné futur", liveTruth: "Intervalle actuel — libellé temps réel autorisé", staleTruth: "Non actuel — libellé temps réel bloqué", truthBoundary: "La preuve du dépôt n’est pas une preuve terrain ou production.", actions: "File d’actions manager", humanApproval: "Approbation humaine requise", automaticOff: "Application automatique du planning désactivée", noActions: "Aucune action gouvernée requise pour cet intervalle." };
const es = { ...en, title: "Centro de mando Workforce", detail: "Vista gobernada de demanda, capacidad, turnos, asistencia y presión.", worksite: "Centro", refresh: "Actualizar", loading: "Cargando intervalo gobernado…", error: "La autoridad del centro de mando no está disponible.", noLocations: "No hay centro autorizado.", current: "Intervalo actual", past: "Intervalo gobernado pasado", future: "Intervalo gobernado futuro", liveTruth: "Intervalo actual — etiqueta en vivo permitida", staleTruth: "No actual — etiqueta en vivo bloqueada", truthBoundary: "La evidencia del repositorio no es evidencia de campo ni de producción.", actions: "Cola de acciones del gerente", humanApproval: "Se requiere aprobación humana", automaticOff: "Aplicación automática de turnos desactivada", noActions: "No se requiere acción gobernada para este intervalo." };
const it = { ...en, title: "Centro di comando Workforce", detail: "Vista governata di domanda, capacità, turni, presenze e pressione.", worksite: "Sede", refresh: "Aggiorna", loading: "Caricamento intervallo governato…", error: "L'autorità del centro di comando non è disponibile.", noLocations: "Nessuna sede autorizzata.", current: "Intervallo corrente", past: "Intervallo governato passato", future: "Intervallo governato futuro", liveTruth: "Intervallo corrente — etichetta live consentita", staleTruth: "Non corrente — etichetta live bloccata", truthBoundary: "L'evidenza repository non è prova sul campo o di produzione.", actions: "Coda azioni manager", humanApproval: "Approvazione umana richiesta", automaticOff: "Applicazione automatica turni disattivata", noActions: "Nessuna azione governata richiesta per questo intervallo." };
const nl = { ...en, title: "Workforce Command Center", detail: "Beheerde weergave van vraag, capaciteit, diensten, aanwezigheid en druk.", worksite: "Locatie", refresh: "Vernieuwen", loading: "Beheerd interval laden…", error: "Command Center-authoriteit is niet beschikbaar.", noLocations: "Geen bevoegde locatie beschikbaar.", current: "Huidig interval", past: "Voorbij beheerd interval", future: "Toekomstig beheerd interval", liveTruth: "Huidig interval — live-label toegestaan", staleTruth: "Niet huidig — live-label geblokkeerd", truthBoundary: "Repositorybewijs is geen veld- of productiebewijs.", actions: "Actiewachtrij manager", humanApproval: "Menselijke goedkeuring vereist", automaticOff: "Automatische diensttoepassing uit", noActions: "Geen beheerde actie nodig voor dit interval." };
const pl = { ...en, title: "Centrum dowodzenia Workforce", detail: "Zarządzany widok popytu, pojemności, zmian, obecności i presji.", worksite: "Lokalizacja", refresh: "Odśwież", loading: "Ładowanie zarządzanego interwału…", error: "Authority Command Center jest niedostępne.", noLocations: "Brak autoryzowanej lokalizacji.", current: "Bieżący interwał", past: "Przeszły interwał", future: "Przyszły interwał", liveTruth: "Bieżący interwał — etykieta live dozwolona", staleTruth: "Nieaktualny — etykieta live zablokowana", truthBoundary: "Dowód repozytorium nie jest dowodem terenowym ani produkcyjnym.", actions: "Kolejka działań menedżera", humanApproval: "Wymagana akceptacja człowieka", automaticOff: "Automatyczne stosowanie zmian wyłączone", noActions: "Brak wymaganych działań dla tego interwału." };
const ptBR = { ...en, title: "Central de Comando Workforce", detail: "Visão governada de demanda, capacidade, turnos, presença e pressão.", worksite: "Local", refresh: "Atualizar", loading: "Carregando intervalo governado…", error: "A autoridade da Central de Comando está indisponível.", noLocations: "Nenhum local autorizado disponível.", current: "Intervalo atual", past: "Intervalo governado passado", future: "Intervalo governado futuro", liveTruth: "Intervalo atual — rótulo ao vivo permitido", staleTruth: "Não atual — rótulo ao vivo bloqueado", truthBoundary: "Evidência do repositório não é prova de campo ou produção.", actions: "Fila de ações do gestor", humanApproval: "Aprovação humana necessária", automaticOff: "Aplicação automática de turnos desligada", noActions: "Nenhuma ação governada necessária para este intervalo." };

const MESSAGES = { tr, en, de, ar, fr, es, it, nl, pl, "pt-BR": ptBR };

export function workforceCommandCenterMessage(locale, key, params = {}) {
  const dictionary = MESSAGES[locale] || MESSAGES.en;
  const template = dictionary[key] || MESSAGES.en[key] || key;
  return String(template).replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}
