const en = {
  title: "Availability & open shifts", detail: "Choose when you can work and claim eligible shifts", center: "Flexibility center", heading: "Your time, within governed rules.", intro: "Share availability and preferences. Only shifts that pass warehouse scope, leave, rest and working-time rules are offered.", availability: "Availability", date: "Date", available: "Available", unavailable: "Unavailable", hardWindow: "Available window", earliest: "Earliest start", latest: "Latest end", preference: "Preferred window", preferredStart: "Preferred start", preferredEnd: "Preferred end", note: "Note", save: "Save availability", saving: "Saving…", saved: "Availability saved.", openShifts: "Eligible open shifts", noOpen: "No eligible open shift right now.", capacity: "{count} place left", score: "Fit {score}", preferenceMatch: "Matches preference", claim: "Claim shift", claiming: "Claiming…", claimed: "Shift claimed and added to your schedule.", loadError: "Flexibility data could not be loaded.", identityMissing: "Employee identity is missing from the signed session.", trust: "Hard rules always win", trustDetail: "Availability, approved leave, warehouse scope, 11-hour rest and daily work limits are checked again when you claim a shift.", refresh: "Refresh",
};
const tr = { ...en, title: "Uygunluk ve açık vardiyalar", detail: "Çalışabileceğin zamanı seç, uygun vardiyayı al", center: "Esneklik merkezi", heading: "Zamanın senin, kurallar yönetişimli.", intro: "Uygunluk ve tercihlerini paylaş. Yalnız depo kapsamı, izin, dinlenme ve çalışma süresi kurallarını geçen vardiyalar gösterilir.", availability: "Uygunluk", date: "Tarih", available: "Müsaitim", unavailable: "Müsait değilim", hardWindow: "Çalışabileceğim aralık", earliest: "En erken", latest: "En geç", preference: "Tercih ettiğim aralık", preferredStart: "Tercih başlangıç", preferredEnd: "Tercih bitiş", note: "Not", save: "Uygunluğu kaydet", saving: "Kaydediliyor…", saved: "Uygunluk kaydedildi.", openShifts: "Uygun açık vardiyalar", noOpen: "Şu anda sana uygun açık vardiya yok.", capacity: "{count} kontenjan", score: "Uyum {score}", preferenceMatch: "Tercihinle eşleşiyor", claim: "Vardiyayı al", claiming: "Alınıyor…", claimed: "Vardiya alındı ve programına eklendi.", loadError: "Esneklik verileri yüklenemedi.", identityMissing: "İmzalı oturumda çalışan kimliği bulunamadı.", trust: "Sert kurallar her zaman öncelikli", trustDetail: "Vardiyayı alırken uygunluk, onaylı izin, depo kapsamı, 11 saat dinlenme ve günlük çalışma sınırı yeniden doğrulanır.", refresh: "Yenile" };
const de = { ...en, title: "Verfügbarkeit & offene Schichten", detail: "Verfügbarkeit festlegen und passende Schichten übernehmen", center: "Flexibilitätszentrum", heading: "Deine Zeit, mit klaren Regeln.", intro: "Teile Verfügbarkeit und Präferenzen. Nur regelkonforme Schichten werden angeboten.", availability: "Verfügbarkeit", date: "Datum", available: "Verfügbar", unavailable: "Nicht verfügbar", hardWindow: "Verfügbarkeitsfenster", earliest: "Frühester Beginn", latest: "Spätestes Ende", preference: "Bevorzugtes Fenster", preferredStart: "Bevorzugter Beginn", preferredEnd: "Bevorzugtes Ende", note: "Notiz", save: "Verfügbarkeit speichern", saving: "Speichern…", saved: "Verfügbarkeit gespeichert.", openShifts: "Passende offene Schichten", noOpen: "Derzeit keine passende offene Schicht.", capacity: "{count} Plätze frei", score: "Passung {score}", preferenceMatch: "Entspricht Präferenz", claim: "Schicht übernehmen", claiming: "Wird übernommen…", claimed: "Schicht wurde deinem Plan hinzugefügt.", refresh: "Aktualisieren" };
const ar = { ...en, title: "التوفر والمناوبات المفتوحة", detail: "حدد وقت توفرّك واختر المناوبات المؤهلة", center: "مركز المرونة", heading: "وقتك ضمن قواعد محكومة.", intro: "شارك التوفر والتفضيلات. تظهر فقط المناوبات التي تجتاز قواعد الموقع والإجازة والراحة وساعات العمل.", availability: "التوفر", date: "التاريخ", available: "متاح", unavailable: "غير متاح", hardWindow: "نافذة التوفر", earliest: "أبكر بداية", latest: "آخر نهاية", preference: "الوقت المفضل", preferredStart: "البداية المفضلة", preferredEnd: "النهاية المفضلة", note: "ملاحظة", save: "حفظ التوفر", saving: "جارٍ الحفظ…", saved: "تم حفظ التوفر.", openShifts: "المناوبات المفتوحة المؤهلة", noOpen: "لا توجد مناوبة مؤهلة الآن.", capacity: "{count} أماكن متبقية", score: "الملاءمة {score}", preferenceMatch: "مطابق للتفضيل", claim: "اختيار المناوبة", claiming: "جارٍ الاختيار…", claimed: "تمت إضافة المناوبة إلى جدولك.", refresh: "تحديث" };
const fr = { ...en, title: "Disponibilités et quarts ouverts", detail: "Définissez vos disponibilités et prenez un quart éligible", center: "Centre de flexibilité", heading: "Votre temps, avec des règles gouvernées.", availability: "Disponibilité", date: "Date", available: "Disponible", unavailable: "Indisponible", hardWindow: "Plage disponible", earliest: "Début au plus tôt", latest: "Fin au plus tard", preference: "Plage préférée", preferredStart: "Début préféré", preferredEnd: "Fin préférée", note: "Note", save: "Enregistrer", saving: "Enregistrement…", saved: "Disponibilité enregistrée.", openShifts: "Quarts ouverts éligibles", noOpen: "Aucun quart éligible pour le moment.", capacity: "{count} place(s)", score: "Adéquation {score}", preferenceMatch: "Correspond à votre préférence", claim: "Prendre le quart", claiming: "Attribution…", claimed: "Quart ajouté à votre planning.", refresh: "Actualiser" };
const es = { ...en, title: "Disponibilidad y turnos abiertos", detail: "Indica cuándo puedes trabajar y toma turnos elegibles", center: "Centro de flexibilidad", heading: "Tu tiempo, con reglas gobernadas.", availability: "Disponibilidad", date: "Fecha", available: "Disponible", unavailable: "No disponible", hardWindow: "Franja disponible", earliest: "Inicio más temprano", latest: "Fin más tarde", preference: "Franja preferida", preferredStart: "Inicio preferido", preferredEnd: "Fin preferido", note: "Nota", save: "Guardar disponibilidad", saving: "Guardando…", saved: "Disponibilidad guardada.", openShifts: "Turnos abiertos elegibles", noOpen: "No hay turnos elegibles ahora.", capacity: "{count} plazas", score: "Ajuste {score}", preferenceMatch: "Coincide con tu preferencia", claim: "Tomar turno", claiming: "Asignando…", claimed: "Turno añadido a tu horario.", refresh: "Actualizar" };
const it = { ...en, title: "Disponibilità e turni aperti", detail: "Indica quando puoi lavorare e scegli turni idonei", center: "Centro flessibilità", heading: "Il tuo tempo, con regole governate.", availability: "Disponibilità", date: "Data", available: "Disponibile", unavailable: "Non disponibile", hardWindow: "Finestra disponibile", earliest: "Inizio più presto", latest: "Fine più tardi", preference: "Finestra preferita", preferredStart: "Inizio preferito", preferredEnd: "Fine preferita", note: "Nota", save: "Salva disponibilità", saving: "Salvataggio…", saved: "Disponibilità salvata.", openShifts: "Turni aperti idonei", noOpen: "Nessun turno idoneo al momento.", capacity: "{count} posti", score: "Compatibilità {score}", preferenceMatch: "Corrisponde alla preferenza", claim: "Prendi turno", claiming: "Assegnazione…", claimed: "Turno aggiunto al programma.", refresh: "Aggiorna" };
const nl = { ...en, title: "Beschikbaarheid & open diensten", detail: "Geef aan wanneer je kunt werken en claim geschikte diensten", center: "Flexibiliteitscentrum", heading: "Jouw tijd, binnen beheerde regels.", availability: "Beschikbaarheid", date: "Datum", available: "Beschikbaar", unavailable: "Niet beschikbaar", hardWindow: "Beschikbaar venster", earliest: "Vroegste start", latest: "Laatste einde", preference: "Voorkeursvenster", preferredStart: "Voorkeursstart", preferredEnd: "Voorkeurseinde", note: "Notitie", save: "Beschikbaarheid opslaan", saving: "Opslaan…", saved: "Beschikbaarheid opgeslagen.", openShifts: "Geschikte open diensten", noOpen: "Nu geen geschikte open dienst.", capacity: "{count} plaatsen", score: "Match {score}", preferenceMatch: "Past bij voorkeur", claim: "Dienst claimen", claiming: "Claimen…", claimed: "Dienst toegevoegd aan je rooster.", refresh: "Vernieuwen" };
const pl = { ...en, title: "Dostępność i otwarte zmiany", detail: "Określ dostępność i wybieraj kwalifikujące się zmiany", center: "Centrum elastyczności", heading: "Twój czas w ramach zarządzanych zasad.", availability: "Dostępność", date: "Data", available: "Dostępny/a", unavailable: "Niedostępny/a", hardWindow: "Okno dostępności", earliest: "Najwcześniejszy start", latest: "Najpóźniejsze zakończenie", preference: "Preferowane okno", preferredStart: "Preferowany start", preferredEnd: "Preferowany koniec", note: "Notatka", save: "Zapisz dostępność", saving: "Zapisywanie…", saved: "Dostępność zapisana.", openShifts: "Dostępne otwarte zmiany", noOpen: "Brak kwalifikujących się zmian.", capacity: "{count} miejsc", score: "Dopasowanie {score}", preferenceMatch: "Zgodne z preferencją", claim: "Wybierz zmianę", claiming: "Przypisywanie…", claimed: "Zmiana dodana do grafiku.", refresh: "Odśwież" };
const ptBR = { ...en, title: "Disponibilidade e turnos abertos", detail: "Informe quando pode trabalhar e escolha turnos elegíveis", center: "Central de flexibilidade", heading: "Seu tempo, dentro de regras governadas.", availability: "Disponibilidade", date: "Data", available: "Disponível", unavailable: "Indisponível", hardWindow: "Janela disponível", earliest: "Início mais cedo", latest: "Fim mais tarde", preference: "Janela preferida", preferredStart: "Início preferido", preferredEnd: "Fim preferido", note: "Nota", save: "Salvar disponibilidade", saving: "Salvando…", saved: "Disponibilidade salva.", openShifts: "Turnos abertos elegíveis", noOpen: "Nenhum turno elegível agora.", capacity: "{count} vagas", score: "Aderência {score}", preferenceMatch: "Combina com sua preferência", claim: "Assumir turno", claiming: "Assumindo…", claimed: "Turno adicionado à sua escala.", refresh: "Atualizar" };

const MESSAGES = { tr, en, de, ar, fr, es, it, nl, pl, "pt-BR": ptBR };

export function workforceFlexibilityMessage(locale, key, params = {}) {
  const dictionary = MESSAGES[locale] || MESSAGES.en;
  const template = dictionary[key] || MESSAGES.en[key] || key;
  return String(template).replace(/\{(\w+)\}/g, (_, token) => String(params[token] ?? `{${token}}`));
}
