export const commandModules = [
  {
    id: "planogram",
    moduleKey: "planogram",
    title: "Planogram Studio",
    description: "Raf yerleşimi, fixture-first planlama, kategori optimizasyonu ve 3D operasyon görünümü.",
    route: "/planogram",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "Store Intelligence",
    shortcut: "P",
    icon: "layout",
    tone: "primary",
    meta: "Shelf · Fixture · Facing",
    lastUsedKey: "opex_last_planogram",
  },
  {
    id: "dockos",
    moduleKey: "dockos",
    title: "DockOS",
    description: "Sevkiyat, randevu, tedarikçi, PO ve depo kapasite kontrolü.",
    route: "/dockos",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "Inbound Control",
    shortcut: "D",
    icon: "dock",
    tone: "cyan",
    meta: "PO · ST · Dock",
    lastUsedKey: "opex_last_dockos",
  },
  {
    id: "budget",
    moduleKey: "budget",
    title: "Budget Control",
    description: "PR, PO, maliyet merkezi, fatura ve bütçe görünürlüğü.",
    route: "/budget",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "Finance Operations",
    shortcut: "B",
    icon: "budget",
    tone: "violet",
    meta: "PR · PO · Cost",
    lastUsedKey: "opex_last_budget",
  },
  {
    id: "workforce",
    moduleKey: "workforce",
    title: "Workforce",
    description: "Çalışan, vardiya, devam, dönem kapanışı ve saha iş gücü yönetimi.",
    route: "/workforce",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "People Operations",
    shortcut: "W",
    icon: "access",
    tone: "emerald",
    meta: "Shift · Attendance · Team",
    lastUsedKey: "opex_last_workforce",
  },
  {
    id: "recruitment",
    moduleKey: "recruitment",
    title: "Recruitment",
    description: "İşe alım talebi, aday süreci, değerlendirme ve işe giriş yönetimi.",
    route: "/recruitment",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "Talent Operations",
    shortcut: "R",
    icon: "cycle",
    tone: "amber",
    meta: "Request · Candidate · Hire",
    lastUsedKey: "opex_last_recruitment",
  },
  {
    id: "academy",
    moduleKey: "academy",
    title: "EAY Academy",
    description: "Öğrenme yolları, interaktif içerik, yetkinlik, sertifika ve kaynaklı Jarvis eğitmen.",
    route: "/academy",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "Knowledge",
    shortcut: "A",
    icon: "academy",
    tone: "amber",
    meta: "Learning · Studio · Jarvis",
    lastUsedKey: "opex_last_academy",
  },
  {
    id: "insight",
    moduleKey: "insight",
    title: "AI Insight Base",
    description: "Operasyon verisinden yorum, risk sinyali ve aksiyon önerisi üretir.",
    route: "#",
    enabled: false,
    health: "soon",
    healthLabel: "Yakında",
    group: "Intelligence",
    shortcut: "I",
    icon: "ai",
    tone: "emerald",
    meta: "Signal · Risk · Action",
    lastUsedKey: "opex_last_insight",
  },
  {
    id: "inventory",
    moduleKey: "inventory",
    title: "Inventory",
    description: "Terminal sayımı, kör sayım, fark mutabakatı, yeniden sayım ve resmi tutanak yönetimi.",
    route: "/inventory",
    enabled: true,
    health: "healthy",
    healthLabel: "Hazır",
    group: "Inventory Control",
    shortcut: "C",
    icon: "inventory",
    tone: "rose",
    meta: "Count · Variance · Audit",
    lastUsedKey: "opex_last_inventory",
  },
  {
    id: "audit-log",
    moduleKey: "admin_access",
    title: "Audit Log",
    description: "Platform eri\u015fimlerini, reddedilen i\u015flemleri ve hata kay\u0131tlar\u0131n\u0131 tenant baz\u0131nda izleyin.",
    route: "/audit-log",
    enabled: true,
    health: "healthy",
    healthLabel: "Admin",
    group: "Administration",
    shortcut: "L",
    icon: "access",
    tone: "slate",
    meta: "Actor \u00b7 Decision \u00b7 Request",
    lastUsedKey: "opex_last_audit_log",
  },
  {
    id: "access",
    moduleKey: "admin_access",
    title: "Access Control",
    description: "Ana admin ve modül adminleri için kullanıcı, grup ve modül yetkisi yönetimi.",
    route: "/access-control",
    enabled: true,
    health: "healthy",
    healthLabel: "Admin",
    group: "Administration",
    shortcut: "X",
    icon: "access",
    tone: "slate",
    meta: "User · Group · Role",
    lastUsedKey: "opex_last_access",
  },
];

export const commandStats = [
  {
    label: "Kontrol modu",
    value: "Live",
    detail: "Yetkili operasyon görünümü",
  },
  {
    label: "Güvenlik",
    value: "Role Based",
    detail: "Kartlar kullanıcıya göre açılır",
  },
  {
    label: "Operasyon yaklaşımı",
    value: "Lead",
    detail: "Operasyonu takip etme. Ona yön ver.",
  },
];
